### ISSUE TITLE
FileNotFoundException on .NET Core project with WPF

### ISSUE THREAD

**Issue by MortInfinite** [cefsharp/CefSharp#3031] opened 2020-01-30 19:36 UTC
- **What version of the product are you using?**
NuGet package "CefSharp.Wpf (79.1.350.0)"

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Create a new WPF project, using .NET Core 3.1 or 3.0 (Both cause this problem).
Add the NuGet package "CefSharp.Wpf (79.1.350.0)" to the project.
Add <wpf:ChromiumWebBrowser Address="www.google.com"/> to MainWindow.xaml file.
Install Visual C++ Runtime 2015 x64.
Run the created application.

- **What is the expected output? What do you see instead?**
I expect to see a MainWindow with a web browser.

Instead I receive the exception: "Could not load file or assembly 'CefSharp.Wpf, Version=79.1.350.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. The system cannot find the file specified."

All the required files, mentioned in the readme file, are present in the bin directory.

- **Please provide any additional information below.**
Exception described above.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
There is no debug.log file generated.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No other components added.

- **Does this problem also occur in the `CEF` Sample Application**
The sample application does not experience this problem.
Copying all files from the sample application's bin directory to my own directory does not resolve the problem.

After having copied and pasted every bit of code from the sample application to my own application, I finally found out what was wrong.

The sample application contains the following config section, in the project file:
```
	<ItemGroup>
		<!-- TODO: These updates are currently required because CefSharp.Wpf specifies
         <Private>false</Private>, which means these libraries will not be specified in
         the .deps.json file, and so the CoreCLR wouldn't load these. -->
		<Reference Update="CefSharp">
			<Private>true</Private>
		</Reference>
		<Reference Update="CefSharp.Core">
			<Private>true</Private>
		</Reference>
		<Reference Update="CefSharp.Wpf">
			<Private>true</Private>
		</Reference>
	</ItemGroup>

```
Copy/pasting this config section to my own project file solved the problem.

**Comment by amaitland** [comment] 2020-01-30 20:21
`.Net Core` support is not yet finished, the requirements are documented in https://github.com/cefsharp/CefSharp/issues/2796#issuecomment-524820012

Closing as duplicate of #2796

**Closed by amaitland** 2020-01-30 20:21 UTC
