### ISSUE TITLE
CefSharp version57  problem

### ISSUE THREAD

**Issue by liuyu5337** [cefsharp/CefSharp#2085] opened 2017-07-07 09:25 UTC
when i load html ,there is vidio in the page.but cefsharp can't show vedio.and there some warnings:

[0707/171736.885:ERROR:interface_registry.cc(203)] Failed to locate a binder
 interface: blink::mojom::SensitiveInputVisibilityService requested by: conte
renderer exposed by: content_browser via InterfaceProviderSpec "navigation:fr
".
[0707/171736.885:WARNING:interface_registry.cc(210)]

InterfaceRegistry(navigation:frame):
Owned by:
  content_browser@ run as: f5926dd8-43e4-4b8a-a288-e3202631ff59

  Providing:
    capability: renderer containing interfaces:
      autofill::mojom::AutofillDriver
      autofill::mojom::PasswordManagerDriver
      blink::mojom::MediaSessionService
      blink::mojom::PermissionService
      blink::mojom::PresentationService
      blink::mojom::SensitiveInputVisibilityService
      blink::mojom::WebBluetoothService
      blink::mojom::WebSocket
      content::mojom::BrowserTarget
      device::VibrationManager
      device::mojom::GeolocationService
      device::mojom::SensorProvider
      device::mojom::VRService
      device::mojom::WakeLockService
      device::nfc::mojom::NFC
      device::usb::DeviceManager
      discardable_memory::mojom::DiscardableSharedMemoryManager
      extensions::KeepAlive
      extensions::mime_handler::MimeHandlerService
      media::mojom::InterfaceFactory
      media::mojom::RemoterFactory
      media::mojom::Renderer
      mojom::MediaDevicesDispatcherHost
      payments::mojom::PaymentRequest
      shape_detection::mojom::BarcodeDetection
      shape_detection::mojom::FaceDetectionProvider
      shape_detection::mojom::TextDetection
      ui::mojom::Gpu

  Requiring:
    From: content_renderer:
      browser

Bound to:
  content_renderer@3_1 run as: f5926dd8-43e4-4b8a-a288-e3202631ff59

  Providing:
    capability: browser containing interfaces:
      blink::mojom::AppBannerController
      blink::mojom::EngagementClient
      blink::mojom::InstallationService
      content::mojom::ImageDownloader
      mojom::MediaDevicesListener

  Requiring:
    From: content_browser:
      renderer

Binders registered for:
 * blink::mojom::MediaSessionService
 * blink::mojom::PermissionService
 * blink::mojom::PresentationService
 * blink::mojom::WebBluetoothService
 * blink::mojom::WebSocket
 * device::VibrationManager
 * device::mojom::GeolocationService
 * device::mojom::VRService
 * device::mojom::WakeLockService
 * media::mojom::InterfaceFactory
 * media::mojom::RemoterFactory
 * mojom::MediaDevicesDispatcherHost

 * - denotes an interface exposed to remote per policy.

is there any body help me?

**Comment by merceyz** [comment] 2017-08-28 00:53
Duplicate of https://github.com/cefsharp/CefSharp/issues/1479

**Closed by merceyz** 2017-08-28 00:53 UTC
