### ISSUE TITLE
Dropdown list is under a browser window

### ISSUE THREAD

**Issue by ValeriiSalamatin** [cefsharp/CefSharp#2576] opened 2018-11-22 08:49 UTC
**What version of the product are you using?**
master branch (latest commit - 485297bb7), also tested on V69

**What architecture x86 or x64?**
x64

**On what operating system?**
Win10

**Are you using WinForms, WPF or OffScreen?**
WinForms

**What steps will reproduce the problem?**
Change test windows form property "TopMost" to true.
![error](https://user-images.githubusercontent.com/44665490/48890938-3ab99980-ee4b-11e8-8bd1-b7562557aabc.png)
On sites with combo boxes, dropdown lists are situated under the form.

**Please provide any additional information below.**
BTW: the fix of this behavior has already been merged to the CEF library (https://bitbucket.org/chromiumembedded/cef/issues/1468/dropdowns-are-hidden-behind-browser-window) and the current master branch of CEFSharp is using the CEF version with this fix 

Edit: added a link to the site with dropdowns: http://depts.washington.edu/osteoed/tools.php?type=score

**Comment by amaitland** [comment] 2018-11-22 09:12
A comment on #657 would have been perfectly sufficient, there was no need to create a new issue.

Have you tested with `cefclient` to confirm that it's actually fixed? Looks like a command line argument was added for testing purposes.

**Comment by amaitland** [comment] 2018-11-22 09:22
Closing as duplicate of #657

**Closed by amaitland** 2018-11-22 09:22 UTC
