### ISSUE TITLE
Every time flash is called a Command Line is displayed for some ms to 1sec

### ISSUE THREAD

**Issue by newradius** [cefsharp/CefSharp#1614] opened 2016-03-02 01:26 UTC
So while using PPAPI flash every time I open a website with flash elements I can see the command line for some MS up to 1sec. Then if I navigate to a non-flash website and from there to another flash website I see the command line flash again.

I load PPAPI flash like this:

`settings.CefCommandLineArgs.Add("ppapi-flash-path", "my path here")
settings.CefCommandLineArgs.Add("ppapi-flash-version", "20.0.0.306")`

**Comment by amaitland** [comment] 2016-03-02 01:29
@newradius A couple of things

- Search on `GitHub` post asking/posting a question.
- Did you read the issue template that said not to post here? 

Closing this as duplicate of #1259

**Closed by amaitland** 2016-03-02 01:29 UTC
