### ISSUE TITLE
Embedded modules ffmpegsumo.dll

### ISSUE THREAD

**Issue by Keybo1013** [cefsharp/CefSharp#2137] opened 2017-09-04 09:00 UTC
- **What version of the product are you using?**
 57.0.0，Nuget

- **What architecture x86 or x64?**
  Win7 x86

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **My problem?**
  Who has the cefsharp version 57 ffmpegsumo.dll, please?
  My application cannot play mp4 video.

**Comment by merceyz** [comment] 2017-09-04 09:07
Duplicate of #1479

**Closed by merceyz** 2017-09-04 09:07 UTC
