### ISSUE TITLE
context menu does not close in WPF version

### ISSUE THREAD

**Issue by Clemani** [cefsharp/CefSharp#2063] opened 2017-06-06 21:07 UTC
On mouse right-click the menu with Back/Forward/Print... appears.
It appears not very close to the current mouse position, just noticed this.
The issue is that the menu gets not closed if you click in the page outside of the popup menu.
You have to click on a menu item to close the popup. This is annoying if i accidentally right-click (can easily happen on tablets)

This can be re-produced in the official CefSharp.Wpf.Example project.

**Comment by merceyz** [comment] 2017-06-06 21:51
Duplicate of #1795

**Closed by merceyz** 2017-06-06 21:51 UTC
