### ISSUE TITLE
System.ArgumentException in CefSharp.OffScreen.ChromiumWebBrowser.ScreenshotOrNull

### ISSUE THREAD

**Issue by gfox1984** [cefsharp/CefSharp#2415] opened 2018-06-12 08:29 UTC
- **What version of the product are you using?**
    - Nuget 63.0.3 (also reproduced with Nuget 57.0.0)

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - Offscreen

- **What steps will reproduce the problem?**
    - We're using OffScreen CefSharp to take screenshots during automation. After taking a number of screenshots (around 120 screenshots, the number slightly varies), we always get a crash in the "ScreenshotOrNull" method. The scale of our automation project is too large to be able to give a complete reproduction scenario...

- **Please provide any additional information below.**

```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original)
   at CefSharp.OffScreen.ChromiumWebBrowser.ScreenshotOrNull(PopupBlending blend) in c:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 510
   at CefSharp.OffScreen.ChromiumWebBrowser.ScreenshotAsync(Boolean ignoreExistingScreenshot, PopupBlending blend) in c:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 531
   at Assima.Windows.ScreenshotGenerator.WebBrowser.TakeScreenshot() in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WebBrowser.cs:line 199
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.CaptureCurrentScreenShot(Boolean bResize) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 156
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.CaptureScreenShotForScreenie(ObjectScreenie screenie, String strTargetRect) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 190
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.InternalWebIntReady(String screenId, Int32 iCommand, Int32 objectId, String strTargetRect, String typeId, Int32 simId, String simLinkId, Int32 tutId, String tutStateId, String strMapTopLevelRects, String stMapDataObjects) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 294
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.WebIntReady(String screenId, Int32 iCommand, Int32 objectId, String strTargetRect, String typeId, Int32 simId, String simLinkId, Int32 tutId, String tutActionId, String strMapTopLevelRects, String strMapDataRects, Boolean bRestoreCamera, Int32 eRestoreType) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 727
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots_External.<>c__DisplayClass9_0.<WebIntReady>b__0() in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 874
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original)
   at CefSharp.OffScreen.ChromiumWebBrowser.ScreenshotOrNull(PopupBlending blend) in c:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 510
   at CefSharp.OffScreen.ChromiumWebBrowser.ScreenshotAsync(Boolean ignoreExistingScreenshot, PopupBlending blend) in c:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 531
   at Assima.Windows.ScreenshotGenerator.WebBrowser.TakeScreenshot() in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WebBrowser.cs:line 199
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.CaptureCurrentScreenShot(Boolean bResize) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 156
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.CaptureScreenShotForScreenie(ObjectScreenie screenie, String strTargetRect) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 190
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.InternalWebIntReady(String screenId, Int32 iCommand, Int32 objectId, String strTargetRect, String typeId, Int32 simId, String simLinkId, Int32 tutId, String tutStateId, String strMapTopLevelRects, String stMapDataObjects) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 294
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots.WebIntReady(String screenId, Int32 iCommand, Int32 objectId, String strTargetRect, String typeId, Int32 simId, String simLinkId, Int32 tutId, String tutActionId, String strMapTopLevelRects, String strMapDataRects, Boolean bRestoreCamera, Int32 eRestoreType) in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 727
   at Assima.Windows.ScreenshotGenerator.WI4_ScreenShots_External.<>c__DisplayClass9_0.<WebIntReady>b__0() in C:\Users\guill\source\tfs\Vimago\Hydra_Internal\Server\_Services\Assima.Windows.ScreenshotGenerator\WI4_ScreenShots.cs:line 874
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

    - Does the cef log provide any relevant information? 
      see https://1drv.ms/u/s!AroVes6PcimN5R9-yoMNMnBxZWQ1

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      Screenshots are initiated from JavaScript, and they are taken using the ScreenshotAsync (which is called after a Thread.Sleep to wait long enough for the page to render completely)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
      n/a

**Comment by amaitland** [comment] 2018-06-12 09:14
Duplicate of #2308

Whilst the stack trace isn't exactly the same, the line numbers match up, being a problem with `ScreenshotOrNull`

**Closed by amaitland** 2018-06-12 09:14 UTC
