### ISSUE TITLE
IgnoreCertificateErrors

### ISSUE THREAD

**Issue by SimonTheCat** [cefsharp/CefSharp#3011] opened 2020-01-12 22:03 UTC
CefSettings.IgnoreCertificateErrors = true not work with proxy and self signed cert, browser show bank page CEF v75-79 x86 Win10
in CEF 73 page load normal

**Comment by amaitland** [comment] 2020-01-12 23:45
Duplicate of #2887

The issue is also documented in the known issues section of the release notes https://github.com/cefsharp/CefSharp/releases/tag/v75.1.141

**Closed by amaitland** 2020-01-12 23:45 UTC
