### ISSUE TITLE
Url not working

### ISSUE THREAD

**Issue by samuel-munoz-diaz** [cefsharp/CefSharp#1884] opened 2016-12-07 16:12 UTC
- **What version of the product are you using?**
Nuget 53.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
In the CefSharp.MinimalExample when i try to open the follow link 'https://zeus.sii.cl/AUT2000/InicioAutenticacion/IngresoRutClave.html?https://misii.sii.cl/cgi_misii/siihome.cgi' the browser do not show nothing.

- **What is the expected output? What do you see instead?**
The browser have to show the page as in the CefSharp.WinForms 51.0.0 version. i have try with previus versions too, as 49.0.1,  49.0.0, 47.0.4. in all those versions work fine.

**Comment by Matherunner** [comment] 2016-12-08 01:38
Given that you're using v53 to open HTTPS sites, this is likely a duplicate of #1880.

**Closed** 2016-12-19 21:03 UTC
