### ISSUE TITLE
WPF - Browser screen tearing and glitches on resize.

### ISSUE THREAD

**Issue by getmetatable** [cefsharp/CefSharp#3072] opened 2020-03-01 15:39 UTC
- **What version of the product are you using?**
        - Nuget Version from VS2019: 79.1.360

- **What architecture x86 or x64?**
    Any CPU, Tested with x64 and x86 standalone (x86 had worse effects)
    
- **On what operating system?**
    Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    - Once the program opened, I resized it along the horizontal axis which caused a glitching effect 
       to the browser, where the text within the HTML would start to tear and stretch around. 
       Just to note the window uses a min height and width, and uses window.chrome

       ![cefTest](https://user-images.githubusercontent.com/61298642/75628609-9b995b00-5bd2-11ea-9e3c-668b6be2f85f.gif)

    - The problem still persists even using MinimalExample.

- **What is the expected output? What do you see instead?**
    - The program runs smoothly, the only unexpected output is the tearing on resize which would 
       be preferred to be a smooth resize.

- **Please provide any additional information below.**
    - There is no debug.log

- **Does this problem also occur in the `CEF` Sample Application**
    - On the cef client it just sort of makes a weird repeated border when resized, freezes the 
       application and causes input to disable. Which is only re-enabled when the vertical resize is 
       done. However this is nothing like my issue as mine resizes properly but the html gets warped 
       inside.

       An issue from the debug.log in cefclient though is: 
```
[0301/150312.823:ERROR:gl_utils.cc(325)] [.RendererMainThread-0000020179168070] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete
```

**Comment by amaitland** [comment] 2020-03-01 19:11
Closing as upstream. Resizing is a known problem with CEF and effects all CEF wrappers. 

https://bitbucket.org/chromiumembedded/cef/issues/2733/viz-osr-might-be-causing-some-graphic

Currently the WPF version ships with gpu-compositing disabled which will account for differences in testing cefclient. 

https://github.com/cefsharp/CefSharp/blob/cefsharp/79/CefSharp.Wpf/CefSettings.cs#L25

**Closed by amaitland** 2020-03-01 19:11 UTC
Labels: upstream

**Comment by amaitland** [comment] 2020-03-01 19:16
You can try disabling gpu acceleration, no guarantee though.

**Comment by getmetatable** [comment] 2020-03-01 19:27
Disabling gpu-composition worked a treat.
However the browser only resizes when the window has finished resizing.

**Comment by amaitland** [comment] 2020-03-01 20:25
Duplicate of #2939

https://github.com/cefsharp/CefSharp/issues/2925#issuecomment-540997131 has additional discussion on the `OSR` rendering engine.

Hosting the `WinForms` version in `WPF` until the `upstream` issues have been resolved.

**Comment by nnfan** [comment] 2020-05-15 08:58
the latest version(79.1.360) has same problem, downgrading to 75.1.143 solve the problem.
