### ISSUE TITLE
Blank screen coming up in WPF application -v57.0.0

### ISSUE THREAD

**Issue by srini1978** [cefsharp/CefSharp#2292] opened 2018-02-28 08:08 UTC
- **What version of the product are you using?** 
v57.0.0

- **What architecture x86 or x64?**
x86
- **On what operating system?**
Win 10, Win 8
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
I have a WPF application in which we are using CEFsharp for displaying web page . The web page is a angular JS application. When we try to open multiple instances of this web page or even in some situations one instance, the screen becomes blank. There is no HTML content in the view source. The web page is bringing back a lot of data and rendering it in the screen.  There is also JavaScript registration for some events that need to happen on selecting/unselecting certain events on the page .

When we use the debug tools on the blank page that came up, there is nothing in the view source. Is there a way we can delay the loading of the browser till all data is retrieved. Would the javascript registration be an issue as well

- **What is the expected output? What do you see instead?**
 Blank screen comes up. We end up closing and re-opening the browser 4-5 times and the page comes up correctly.
- **Please provide any additional information below.**
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Attaching the log here ([Logs.txt](https://github.com/cefsharp/CefSharp/files/1766168/1.txt))
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No, but the page is bringing back lot of data from SQL Azure.

**Comment by jankurianski** [comment] 2018-02-28 22:31
Can you create a reproducible example by forking https://github.com/cefsharp/CefSharp.MinimalExample?

**Comment by srini1978** [comment] 2018-03-02 09:10
Hello @jankurianski 

Did that  https://github.com/srini1978/CefSharp.MinimalExample . Also attaching the screenshot of the blank screen.
![blankscreen_error](https://user-images.githubusercontent.com/10396742/36891418-95d8fdaa-1e27-11e8-9e5c-10a8060ef8f1.jpg)

**Comment by amaitland** [comment] 2018-03-03 08:32
> Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer -pre release and test with that also).

`63.0.1` is the latest version, please update your example and test again.

**Comment by srini1978** [comment] 2018-03-05 06:18
@amaitland  - I upgraded to v63.0.1 and I am unable to reproduce the problem. now though update is on the cards for next release, we need to support the current product which was started on v57 back in july 2017 at which time v57 was the stable version.

We are looking for a way to understand if we can capture the error 
1. When page is becoming blank and probably reload 
2.  Show a error page that is more visually appealin.3
3.  When we step through the code, we find that even in V63.0.1 , the Browser_LoadError event handler is fired for the code above, is this a valid event handler to be used at all.

I have the minimal example code built using v63.0.1 but am unable to upload it to the site because of the size of solution .

**Comment by amaitland** [comment] 2018-03-05 06:38
> When we step through the code, we find that even in V63.0.1 , the Browser_LoadError event handler is fired for the code above, is this a valid event handler to be used at all.

There are many valid cases for `LoadError`, including when you have missing resources, you should look at the the arguments and determine what's actually causing the error. http://cefsharp.github.io/api/63.0.0/html/T_CefSharp_LoadErrorEventArgs.htm

I suspect your problem relates to your usage of `ResourceHandler.FromFilePath` see https://github.com/cefsharp/CefSharp/commit/13c9c9c49159e05c3648904c64ec21be733dfbb4 for details.

Closing as unable to reproduce in latest stable version.

**Closed by amaitland** 2018-03-05 06:38 UTC

**Comment by srini1978** [comment] 2018-03-07 06:02
Hello @amaitland   .  We are still trying to reproduce the issue with v63.0.1 but while doing that , am running into an issue which I have updated into the minimal example above.

The code that you have in minimal example has the CEF browser initialized through the XAML page but we need it to be initialized through the c# code. Can you please comment on any mistake that I may be doing ?  The place where I find the issue is chromiumWebBrowserInstance.WebBrowser  continues to be null and hence the codebase inside if statement is not executed. 

Any pointers would help?

**Comment by MohammedMushtaq** [comment] 2019-09-26 03:07
A static System.Windows.InteropRenderOptions.ProcessRenderMode property can be set at application startup.

This worked for me and solves the mystery.
