### ISSUE TITLE
Adding word to dictionary

### ISSUE THREAD

**Issue by myrnazhou** [cefsharp/CefSharp#727] opened 2015-01-06 08:16 UTC
Based on this issue https://github.com/cefsharp/CefSharp/issues/222, it looks like CefSharp already has ```AddWordToDictionary```. But when I implemented it, it looks like it just ignores the word, and doesn't add it as the suggested words. Is it suppose to work like that?

**Comment by amaitland** [comment] 2015-01-06 08:33
Are you running against `CEF 3.2171.1949` or an older version? If older then might be worth upgrading.

As I've not tried spell checking I can't comment personally. Perhaps @Bodekaer can shed some light on the implementation?

**Comment by Bodekaer** [comment] 2015-01-07 17:36
I haven't tested the AddWordToDictionary feature.
Does it work temporarily, until restart? E.g. I'm thinking it might just store it in memory.
@myrnazhou, I just upgraded to 2171.1949, so this might also help.

I looked at the code (https://github.com/Bodekaer/CefSharp/commit/e4ca157790e313f9efb10469b8d178308f70f03d), and it appears that we just pass in the word.
So seems to be CEF related - probably some sort of storage issue that hopefully has been fixed in the new update.

**Comment by myrnazhou** [comment] 2015-01-08 09:03
@Bodekaer 
Ok I'll check it out.

**Comment by myrnazhou** [comment] 2015-01-15 09:50
No it's still not working

**Comment by Bodekaer** [comment] 2015-01-15 22:45
It works here (also did in the old version I think).
What do you mean the difference is between "Add to Dictionary" and "Ignore word"?
Isn't it basically the same?

**Comment by myrnazhou** [comment] 2015-01-16 08:49
Ignore word is like just adding the word to whitelist, so it doesn't recognize it as misspelled. But add to dictionary should add it to "suggested words".

**Comment by Bodekaer** [comment] 2015-01-16 08:59
Ahh, yeah I don't think CEF supports this yet, so that's an upstream issue.
I don't think we need it either though.
Personally it works fine as a 'ignore word' feature.

We could perhaps just change the context menu to say "Ignore word" instead to make it clearer.

All the best,

Michael Bodekaer

**Comment by myrnazhou** [comment] 2015-01-16 10:19
Yes in Mailbird it's already say "ignore word", it's just Caro and Christin request that feature.

**Comment by amaitland** [comment] 2015-11-04 21:18
Some indication that `AddWordToDictionary` is working, not sure which version.

http://magpcss.org/ceforum/viewtopic.php?f=6&t=12647

Can someone check to see if there's still a problem in newer versions?

**Comment by amaitland** [comment] 2016-02-21 22:25
If the problem still exists in the latest release (`47` at time of writing`) then please comment.

Next steps would be to reproduce the issue using `cefclient` and report on http://magpcss.org/ceforum/index.php

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Closed by amaitland** 2016-02-21 22:25 UTC
Labels: upstream
