### ISSUE TITLE
Feature Request - cefsharp doesn't work for .net core 3.1 ReadyToRun 

### ISSUE THREAD

**Issue by LIFICN** [cefsharp/CefSharp#3052] opened 2020-02-11 15:38 UTC
my application assemblies as ReadyToRun (R2R)  on .net core.3.1，cefsharp doesn't work

**Comment by amaitland** [comment] 2020-02-11 19:07
Closing as duplicate of #2796 

You should discuss your problem there.

**Closed by amaitland** 2020-02-11 19:07 UTC
