### ISSUE TITLE
Encoding not working on larger files with custom scheme handler

### ISSUE THREAD

**Issue by FrankLeinbach** [cefsharp/CefSharp#2001] opened 2017-03-30 19:40 UTC
I am attaching a sample page that causes this problem.  If you change the CefSharp.WinForms.Example.BrowserTabControl, adding 

BrowserSettings = new BrowserSetting() {
  DefaultEncoding="UTF-8"
}

And then add this page to the CefSharp.Example Resources (such that you can navigate to custom://cefsharp/test.html) and ensure not to cut and paste this into the Visual Studio enviroment, the Japanese characters will be mangled to look like ASCII.  This works in CefSharp 53 and below and stopped working in 55.

It appears to be related to the size of the file, which is the reason for the overly spacious and large stylesheet within this html (our html files are much larger in content).  There may be some sort of buffer overrun issue going on or some variable as it appears to occur when the file exceeds 32,955 bytes.  If you fix the file to be equal or under 32,955 bytes, the characters appear as they should.

This appears to only be related to the custom scheme handler.

**Comment by amaitland** [comment] 2017-03-30 20:30
> I am attaching a sample page that causes this problem. If you change the

No binaries as per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#help-us-help-you

Somehow you seem to have skipped over the issue template, please read then fill out the bug report.
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

To reproduce your problem, best to fork the project and push your changes to `GitHub`.

**Comment by FrankLeinbach** [comment] 2017-03-31 13:03
What version of the product are you using?

57.0.0 (also applies to 55.0.0)

What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? e.g. 53.0.1
What architecture x86 or x64?

Using Nuget cef redist version 3.2987.1597 on x86

On what operating system?

Windows 10

Are you using WinForms, WPF or OffScreen?

WinForms

What steps will reproduce the problem?

Get the project from https://github.com/FrankLeinbach/CefSharp/tree/cefsharp/57

(this is my first git upload, so hopefully this worked correctly).

I changed BrowserTabUserControl to setup the BrowserSettings with a DefaultEncoding of UTF-8.

If you run the CefSharp.Winforms.Example project and navigate to custom://cefsharp/test.html, you will see garbage ASCII characters.  If you then navigate to custom://cefsharp/test2.html, you will see the actual Japanese characters.  The only difference between these two pages is the removal of one of the style blocks (note: there are no styles in the html page).  This puts the page over a certain amount of characters, close to 32768, that causes it to mangle UTF-8.  This worked in 53.0.0 and the problem started in 55.0.0.  I believe that, since your read block is 32k, there is something deeper in the code that is misinterpreting the data on the second read, if the block of characters falls over that threshold.

It is expected that the Japanese characters display correctly in both scenarios rather than as mangled ASCII in the test.html page.

Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

No

Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

No third party controls, just using the custom scheme handling mechanism.

Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

I would not be sure how to implement the custom scheme handler with this CEF Sample Application.

**Comment by amaitland** [comment] 2017-03-31 22:17
> Get the project from https://github.com/FrankLeinbach/CefSharp/tree/cefsharp/57
> 
> (this is my first git upload, so hopefully this worked correctly).


Looks fine, thanks 👍 

> This worked in 53.0.0 and the problem started in 55.0.0. I believe that, since your read block is 32k, there is something deeper in the code that is misinterpreting the data on the second read, if the block of characters falls over that threshold.

Have you debugged `ResourceHandler`? Likely an `upstream` issue that needs to be resolved in `CEF`.

As a workaround you can try including a `BOM` with the `ResourceHandler FromString` overload and setting `includePreamble:true`.
https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp/ResourceHandler.cs#L284

**Comment by FrankLeinbach** [comment] 2017-04-01 01:41
I did debug in the resource handler and even used the preamble set to true.  Unfortunately, while it rendered the Japanese, for our more complex web page, it had problems running JavaScript correctly.  This all worked in 53.0.0. 

It may be that there is an issue in the cef library.  If that's the case, I may have to roll back to 53.0.0 until it's resolved. We were hoping to take advantage of the better implementation of accessibility that the newer cef library offered.

Is this something that you will forward on to cef or will I need to go to their forums to do so?

**Comment by amaitland** [comment] 2017-04-01 02:27
> I did debug in the resource handler and even used the preamble set to true. Unfortunately, while it rendered the Japanese, for our more complex web page, it had problems running JavaScript correctly. This all worked in 53.0.0.

If you use `ResourceHandler.FromFilePath`, that should give a better understand of where the issue lies. The native `CefStreamResourceHandler` implementation will be used.

https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp/ResourceHandler.cs#L258
https://github.com/cefsharp/CefSharp/blob/cd934267c65f494ceb9ee75995cd2a1ca0954543/CefSharp.Core/SchemeHandlerFactoryWrapper.h#L52

> Is this something that you will forward on to cef or will I need to go to their forums to do so?

You will need to raise the issue.

**Comment by FrankLeinbach** [comment] 2017-04-04 15:17
ResourceHandler.FromFilePath works with the example that I sent, but ResourceHandler.FromString does not work.  Is that what you are trying to show me here?

**Comment by FrankLeinbach** [comment] 2017-04-04 16:59
Also, I loaded up the cef project on their site and replaced binding.html in cefclient with my test page and it loaded fine (their in memory resource handler).  I'm not sure how to show them this problem within cef if this is the case.

**Comment by amaitland** [comment] 2017-04-04 20:43
> ResourceHandler.FromFilePath works with the example that I sent

Probably a bug in `CefSharp` then. Grab the `CEF` source and see how `CefStreamResourceHandler` is implemented.

**Comment by FrankLeinbach** [comment] 2017-04-05 11:42
If the bug is in CefSharp and I sent you the sample where the problem happens, shouldn't someone there be looking into the issue, then?  I looked at the CEF source already and it was working with their source and in-memory custom scheme handler.

**Comment by amaitland** [comment] 2017-04-05 11:54
> If the bug is in CefSharp and I sent you the sample where the problem happens, shouldn't someone there be looking into the issue, then?

This isn't a big project backed by a large commercial corporation. What exactly is stopping you from working on fixing the problem?

**Comment by FrankLeinbach** [comment] 2017-04-05 12:00
I'm sorry, I realized that this is open source, but I thought the purpose of reporting issues here was for problems that couldn't be solved.  I can try and solve the issue, but I don't have enough knowledge of CefSharp or bandwidth to apply to it, so I brought the issue here, hoping that whomever made the changes since 53.0.0 would know where to look.  If that's not the case, I'll try to look into the issue when I have the time to do so.  

Otherwise, if someone else is able to solve the issue in that time, great :)

Thanks

**Comment by amaitland** [comment] 2017-04-05 12:28
> I realized that this is open source, but I thought the purpose of reporting issues here was for problems that couldn't be solved.

Reporting the problem is one thing, asserting that someone else should be working on fixing it is another don't you think?

> so I brought the issue here, hoping that whomever made the changes since 53.0.0 would know where to look.

You can use `GitHub` to compare the branches, see https://github.com/cefsharp/CefSharp/compare/cefsharp/53...cefsharp/55

There was exactly one change to the `ResourceHandler` class, and it's trivial. When upgrading to a new version of `CEF` there's always a chance something will break, just how it goes.

**Comment by FrankLeinbach** [comment] 2017-04-05 12:46
When I write code, and there's a bug, I fix it.  I don't give it to someone else to fix.  So, I brought a problem in the code for CefSharp to these forums.  Yes, I do think that the person/people who write the code should look into the problem as they are the most familiar with it.

That being said, I'll look into it when/if I have time and just roll back to cefsharp/53 for now.

**Comment by amaitland** [comment] 2017-04-05 22:17
> When I write code, and there's a bug, I fix it. I don't give it to someone else to fix. So, I brought a problem in the code for CefSharp to these forums. Yes, I do think that the person/people who write the code should look into the problem as they are the most familiar with it.

Like you I don't have the `bandwidth` at this point in time, maybe in a few months.

**Comment by amaitland** [comment] 2017-04-10 01:28
My original conclusion was correct, it's a bug in `CEF`. Re-tagging this as `upstream`.

**Comment by FrankLeinbach** [comment] 2017-04-10 12:07
So, how do I report this to CEF?  I can't reproduce it in their example app.

**Comment by amaitland** [comment] 2017-04-11 00:58
I'm busy at the moment, I will note that this project uses [BountySource](https://www.bountysource.com/issues/43630826-encoding-not-working-on-larger-files-with-custom-scheme-handler)

You can provide a financial incentive for someone else to look into this for you.

**Comment by merceyz** [comment] 2017-04-15 03:31
A solution to your problem is to go to
https://github.com/FrankLeinbach/CefSharp/blob/cefsharp/57/CefSharp.Example/CefSharpSchemeHandlerFactory.cs#L93 
and replace the line with:
`return ResourceHandler.FromString(resource, Encoding.UTF8, true, ResourceHandler.GetMimeType(fileExtension));`

**Comment by FrankLeinbach** [comment] 2017-04-21 18:46
This does not work.  It works for textual issues, but the page behaves strangely when larger and containing javascript.  There is a tabular interface with our actual product which works on the older versions of CefSharp, but not on the newer.  The text that should disappear for each tab remains on the screen when using this version.  It behaves as it should, moving the focus to the appropriate tab area, but the javascript that hides the other tabs no longer works.

**Comment by amaitland** [comment] 2017-05-04 03:30
> Get the project from https://github.com/FrankLeinbach/CefSharp/tree/cefsharp/57

The original problem reported above is an `upstream` one, following @merceyz's suggestion above which includes a `BOM` at the beginning of the `Stream` resolves the problem. The issue is also reproducible in reverse, save your files without a `BOM` and load using the native `CefStreamResourceHandler` and the `UTF-8` encoding is ignored. 

Problem needs to be reported on https://bitbucket.org/chromiumembedded/cef/issues

**Closed by amaitland** 2017-05-04 03:30 UTC
Labels: upstream

**Comment by amaitland** [comment] 2017-05-04 03:45
As for any other display related issues, you should try upgrading to `57.0.0`

**Comment by FrankLeinbach** [comment] 2017-05-04 12:17
This only works for files without JavaScript interaction.  As I explained previously, I have a page that presents with a tabbed interface, showing and hiding the appropriate DIV elements based on the tab that was selected.  Even with what @merceyz said, this does not work.  It presents without hiding any of the DIV elements.  It will still focus appropriately on the DIV element when the tab is selected, but it no longer shows and hides them.  This same exact code works in 53.0.0.  

If this is an upstream issue, I'm not aware of how to present it to them, because I cannot replicate the issue within their example.

**Comment by merceyz** [comment] 2017-05-04 12:37
Could you present me with an example that demonstrates this?

**Comment by FrankLeinbach** [comment] 2017-05-04 12:47
I will try to get as soon as possible. I would just copy the actual problem up, but it has secure content in it and it's in Japanese, so it will take me a little bit to convert it over to something else.

**Comment by KnIfER** [comment] 2021-07-25 15:28
<meta charset=utf8>
