### ISSUE TITLE
Show numeric touch keyboard (tabtip)

### ISSUE THREAD

**Issue by ArtyP** [cefsharp/CefSharp#2425] opened 2018-06-20 12:38 UTC
Hi,
I found out that Win10 has the following numeric on screen keyboard:
![Screenshot1](https://image.ibb.co/mi4GEd/Screenshot_2.png)
That's what I need, but it is not clear to me how can I pop it up. Here is the strange behaviour I have faced.
1. Tested with CefSharp.MinimalExample (v63.0.3, WinForms, x86, Win10) and pure CEF browser (cefclient 3.3396.1779) with the same result.
2. You need to activate the small keyboard on a tablet first:
![Screenshot2](https://image.ibb.co/e93hLJ/2018_06_20_1.png)
3. Start CefSharp.MinimalExample.WinForms and open any page that has `<input type="number">` on it. In my case that was [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number).
4. Click on this input and you'll see a normal (full) keyboard (Screenshot 2).
5. **Important!** Do not close the keyboard and do not lose the focus on input field.
6. You need to reactivate browser window. You can minimize browser to taskbar or switch to another window and then switch back browser.
7. Voila, you get the touch keyboard with numeric style (Screenshot 1).

Is it possible to open numeric keyboard at once? How?
Currently I'm using WinForms v47.0.4 in UI mode and it has the same behaviour as described. Google Chrome v67 does not show numeric style at all.

**Comment by amaitland** [comment] 2018-06-20 19:50
CefSharp is just a wrapper as the problem is reproducible in cefclient it will have to be fixed in CEF. 

You should post on http://magpcss.org/ceforum/index.php

Closing this as upstream.

**Closed by amaitland** 2018-06-20 19:50 UTC
Labels: upstream

**Comment by amaitland** [comment] 2018-06-21 15:35
http://magpcss.org/ceforum/viewtopic.php?f=7&t=16092

Suggestion is this is a Chromium bug.
