### ISSUE TITLE
CefSharpSubprocess memory leaks

### ISSUE THREAD

**Issue by AlexMakap** [cefsharp/CefSharp#1329] opened 2015-10-12 13:14 UTC
Hi,
Memory leaks of CefSharp.Subprocess.exe  when navigating. After navigating of 30-40 pages of one 
of the processes more than 1GB memory or relieved. After 1.3Gb - 1.4Gb rendering process crashed.
CEFClient more than 300-400 MB of none (41,43,45).

Steps to Reproduce

version 43.0.0.0.
windows7SP1 x64 , win8.1 x64
WinForms, WPF build 32 bit 
Site: www.ria.ru (Main menu and submenu)

I try 41,43,45 Releases.

Aleksey

**Comment by bjarteskogoy** [comment] 2015-10-12 14:24
.Net 4 or .Net 4.5?

**Comment by AlexMakap** [comment] 2015-10-12 15:12
.net 4.5

**Comment by amaitland** [comment] 2015-10-12 20:59
> CEFClient more than 300-400 MB of none (41,43,45).

What exactly does `of none` mean?

> Site: www.ria.ru (Main menu and submenu)

Does the problem exist only with this particular site?

**Comment by lexstark** [comment] 2015-10-13 06:07
The same problem.

version 43.0.0.0.
win8.1 x64
build x64 

cefSettings:
WindowlessRenderingEnabled = true;
SetOffScreenRenderingBestPerformanceArgs();

browserSettings:
Plugins = CefState.Disabled,
Java = CefState.Disabled,
WebGl = CefState.Disabled,
RemoteFonts = CefState.Disabled,
WindowlessFrameRate = 1,
ImageLoading = CefState.Disabled

![leak2](https://cloud.githubusercontent.com/assets/7387009/10446976/b4ece77c-7188-11e5-833a-41f2a36a17ee.PNG)

**Comment by amaitland** [comment] 2015-10-13 06:31
> The same problem.

Any particular `URL` your using?

First thing is to confirm the problem is isolated to `CefSharp` or is a problem with `CEF` in general.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment] 2015-10-13 06:34
Also try to disable `WCF`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L43

**Comment by lexstark** [comment] 2015-10-13 06:38
> Any particular URL your using?
www.drive2.ru

We have workaround - custom implementation of IRequestHandler which prevents loading images in OnBeforeResourceLoad() instead of ImageLoading = CefState.Disabled. May be it'll be usefull. 
In that case memory is ok.

**Comment by AlexMakap** [comment] 2015-10-13 07:17
www.microsoft.com - the same effect.
The same problem with regular refresh the page by clicking RELOAD.

**Comment by AlexMakap** [comment] 2015-10-13 07:58
1. In CEF ( https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef) memory periodicaly purged.
2. Disabling WCF  (https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L43) has no effect to resolve issue

**Comment by amaitland** [comment] 2015-10-13 08:38
Can you try the following version of the `MinimalExample` app, it uses the official `43.0.0` packages.
https://github.com/amaitland/CefSharp.MinimalExample/tree/demo/1329

I've disabled `WCF`, changed to `microsoft.com`, memory sites around 160-170mb

**Comment by AlexMakap** [comment] 2015-10-13 09:23
I try MinimalExample app. Memory periodically purged around 350-400mb.

**Comment by amaitland** [comment] 2015-10-13 09:30
> I try MinimalExample app. Memory periodically purged around 350-400mb.

So if you enable `WCF` does it start leaking?

**Comment by AlexMakap** [comment] 2015-10-13 09:44
I try MinimalExample app. on site ria.ru... 1.3Gb memory, CPU 10%

**Comment by amaitland** [comment] 2015-10-13 09:56
What process type is consuming the memory? Check the command line args for the process look for `--type=`

> https://github.com/amaitland/CefSharp.MinimalExample/tree/demo/1329

Using this example and the website http://www.ria.ru/ memory seemed stable at about `180-190mb`

> I try MinimalExample app. on site ria.ru... 1.3Gb memory, CPU 10%

Please be a little more verbose with your comments, it's not a lot of detail to go on, more information the better.

**Comment by AlexMakap** [comment] 2015-10-13 10:11
On site  http://www.ria.ru/  Cefsharp.Subprocess.exe used 1.3G memory and CPU use around 10%.
I also think that a memory leak occurs if the navigation is only one address. Switching to a different address clears the memory. Therefore, Microsoft site it is impossible to assess the validity, since there are constant redirects to other addresses. Site ria.ru well by the fact that nowhere forwards.

**Comment by amaitland** [comment] 2015-10-13 10:41
> On site http://www.ria.ru/ Cefsharp.Subprocess.exe used 1.3G memory and CPU use around 10%.

What are the exact steps to reproduce? I've not seen it get anywhere near that. So more information required.

> Therefore, Microsoft site it is impossible to assess the validity, since there are constant redirects to other addresses. Site ria.ru well by the fact that nowhere forwards.

`CefSharp` uses `process-per-tab`, so unlike `Chrome`, which spawns new processes, there is only the single instance per `ChromiumWebBrowser`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/CefSettings.h#L40

**Comment by AlexMakap** [comment] 2015-10-15 06:11
what can i do to resolve this issue?

**Comment by amaitland** [comment] 2015-10-15 07:24
> what can i do to resolve this issue?

Memory profile the `BrowserSubProcess`, see if there's any memory leaks.

Also might be worth taking a heap snapshot using the `DevTools`, see what memory is being allocated on the `Chromium` side of things. An excellent description of what to do can be found at 
https://github.com/canton7/SyncTrayzor/issues/37#issuecomment-85475917

**Comment by AlexMakap** [comment] 2015-10-19 14:30
Hi!
I try create memory  snapshot using the DevTools, but on second snapshot DevTools crashed.
I use .NetMemory profiler and attach to Cefsharp.Subprocess.exe. On picture show snapshot compare after 5 -7 navigations.
![image](https://cloud.githubusercontent.com/assets/15089262/10580523/832b379a-7686-11e5-9051-c929433a94f6.png)
I make video how leak memory. https://yadi.sk/i/3unJjihsjqchb  5 min- over 1 Gb

**Comment by AlexMakap** [comment] 2015-10-20 15:14
This is not enough? The problem exists in all versions of cefsharp.

**Comment by amaitland** [comment] 2015-10-20 20:09
> This is not enough?

Enough for what? This is an open source project remember. If you need to resolve this, the source is there. Feel free to submit a `PR`

**Comment by amaitland** [comment] 2015-10-20 20:12
> On picture show snapshot compare after 5 -7 navigations.

Please provide an exact set of steps to reproduce the problem.

**Comment by illfang** [comment] 2015-10-21 00:19
I think with the 43 release, it is possible that root objects including
their function and property wrappers get leaked for every additional
context created in the same browser (e.g. ads in an iframe). Looking at
your screenshot, it seems like these objects might have increased.

Besides providing a clear way to reproduce this memory profile, you should
try the 43.1 packages once released.

Alex Maitland <notifications@github.com> schrieb am Mi., 21. Okt. 2015
05:12:

**Comment by amaitland** [comment] 2015-10-21 00:29
> I think with the 43 release, it is possible that root objects including their function and property wrappers get leaked for every additional context created in the same browser (e.g. ads in an iframe). Looking at your screenshot, it seems like these objects might have increased.

Quite possibly. At no point was there any reference to `JSB` in the users bug report.

**Comment by amaitland** [comment] 2015-10-21 00:33
> The problem exists in all versions of cefsharp.

If the problem reproduces in the `41.0.1` release then it's unlikely to be a `JSB` problem.

**Comment by illfang** [comment] 2015-10-21 03:43
Some observations: (executable: unmodified CefSharp.Wpf.Example x86)

When visiting ria.ru there are multiple contexts created (debug.log):

```

Num tracked contexts: 31

```

I've quickly tried the navigation shown in the video:

> I make video how leak memory. https://yadi.sk/i/3unJjihsjqchb 5 min- over
1 Gb

- With master at 03f73b5960e5526d3d9bbc95c5e950a372c2124f the memory first
grows but then seems to stay at about 120 mb.

- For the v43 release the memory grows steadily, maybe about 20-30mb per
navigation. I've tried it until about 250mb were consumed.


> If the problem reproduces in the 41.0.1 release then it's unlikely to be
a JSB problem.

In the 41 branch it seems to be also possible that multiple root objects
are created without previously disposing existing root objects when
`OnContextCreated` is called multiple times.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L53

**Comment by amaitland** [comment] 2015-10-21 03:52
> In the 41 branch it seems to be also possible that multiple root objects are created without previously disposing existing root objects when `OnContextCreated` is called multiple times.

Fair point. I guess not many people have used `JSB` on sites with frames. It's a strange feature to use when using a public facing website, I guess you can inject `JS` to make it work.

Regardless, at no point was `JSB` mentioned in the context of this issue.

As @illfang  suggests this will likely be fixed in the `43.0.1` release.

**Comment by AlexMakap** [comment] 2015-10-21 10:39
Unfortunately I do not know all the details of the project. I have been testing the application using it and trying to figure out what is wrong. It seemed to me that suggest the presence of problemmy you as a guru of the project, it would be helpful. I will continue to search for the cause, but if you can direct me it would be good.

**Comment by AlexMakap** [comment] 2015-10-21 15:27
@illfang  @amaitland  **Excellent!** Two hours of navigation on 52c8b66 of *cefsharp/43* branch do not cause fears of further crashes. Memory holds around 400 -450 mb and cleanes periodically.Periodic bursts of memory increases occur if you open a new window, but then gradually return to average! I will start automatically clicking and in the morning see the result. If it doesn't crash - the problem is solved.

**Comment by TouchRu** [comment] 2015-10-21 17:30
@amaitland Is it possible to apply the commit 52c8b66 to a branch 41.0.1?  and if not, when do you plan to fix the version 43.0.1?

**Comment by amaitland** [comment] 2015-10-21 20:48
> @amaitland Is it possible to apply the commit 52c8b66 to a branch 41.0.1?

There are no plans for another `41.0.x` release. Do you need access to `CefDoMessageLoopWork`? or a fix for this issue? To fix this issue in `41.0.x` would take at least a couple of hours as it's not just porting between branches.

> and if not, when do you plan to fix the version 43.0.1?

Likely in the next week.

**Comment by TouchRu** [comment] 2015-10-22 06:20
No, i dont need access to CefDoMessageLoopWork. Only fixing this issue.

**Comment by AlexMakap** [comment] 2015-10-22 11:01
Now, after about 5000 navigations everything is all right.  Memory stays at about 400mb (win7). The Issue will be closed.

**Closed** 2015-10-23 07:03 UTC

**Comment by amaitland** [comment] 2015-10-29 22:19
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details
