### ISSUE TITLE
FAQ 4 & 6: "Could not load file or assembly 'CefSharp.Core.dll'.  

### ISSUE THREAD

**Issue by kevindaizj** [cefsharp/CefSharp#2464] opened 2018-07-18 10:39 UTC
**architecture**:
x64

**operating system**:
Win7

**enviroment**:
Visual Studio 2017

**tech**:
WPF

I tried to publish wpf application with clickonce, but the published app occur error: _"Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies._

Then I found description of FAQ 6: 
> Copying over to your project the contents of this folder (Only present if you have the matching version of Visual Studio installed on your computer):

and wanted to include the Visual Studio C++ redistributables on my target app, Here is the my files:
![path](https://user-images.githubusercontent.com/12622531/42876620-d4270b34-8ab9-11e8-9fd0-fc408d6eea2f.png)
![files](https://user-images.githubusercontent.com/12622531/42876628-d7d3ff26-8ab9-11e8-8273-97a4bd448e4a.png)

and Here is all my code:
```
public partial class App : Application
{
	protected override void OnStartup(StartupEventArgs e)
	{
		base.OnStartup(e);
		this.InitSettings();
	}

	private void InitSettings()
	{
		var type = typeof(CefSettings);
		MessageBox.Show(type.ToString());
	}
}
```

My question are:
1. Which files should i include to ?
2. Where should i copy to?  Release/Bin folder or published folder?

I am new on CefSharp. Any help will be appreciated.

**Comment by amaitland** [comment] 2018-07-18 11:05
Duplicate of #1314

**Closed by amaitland** 2018-07-18 11:05 UTC
