### ISSUE TITLE
[WinForms-x86] Cefsharp isn't rendering google fonts

### ISSUE THREAD

**Issue by BataBo** [cefsharp/CefSharp#3091] opened 2020-03-31 16:15 UTC
In my html file I reference one google font,I do it like this:
`<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet"> 
`
then in my style I reference it like this:
`font-family: 'Poppins', sans-serif;`
and it works fine in firefox and chrome,but cefsharp just writes it in sans-serif,when I exclude , 'sans-serif' it writes it in Times New Roman.

**Comment by amaitland** [comment] 2020-03-31 19:23
Duplicate of #3045

**Closed** 2020-03-31 19:23 UTC
