### ISSUE TITLE
Orphaned BrowserSubprocesses never go away

### ISSUE THREAD

**Issue by jamespearce2006** [cefsharp/CefSharp#1292] opened 2015-09-25 16:49 UTC
I've been doing some work to integrate v43 with our app today, and at the end of the day, I see about 20 orphaned BrowserSubprocesses in TaskManager.

I'm assuming these were orphaned when I'd stop debugging, killing the app, rather than shutting down cleanly.
I can reproduce the same problem in both the WPF and WinForms samples. Simply start the app in the debugger, open lots of tabs, then stop debugging. Frequently, one or more of the render subprocesses will be left running.

Shouldn't these be cleaning themselves up after a while?

**Comment by amaitland** [comment] 2015-09-26 03:18
> Shouldn't these be cleaning themselves up after a while?

Feel free to look into it further.

**Comment by arsher** [comment] 2015-09-26 06:15
I take it that you're running it from inside VS? The problem is the subprocesses are children of the .vshost.exe which won't be stopped wen you stop debugging hence the lingering processes. It won't happen when you're running without VS because when the main process dies for whatever reason the children will die too even if it's not a clean shutdown.

**Comment by amaitland** [comment] 2015-10-01 20:34
@jamespearce2006 Did you test out @arsher `hypothesis`?

**Comment by jamespearce2006** [comment] 2015-10-02 13:49
When you stop debugging, the vshost does go away, so I would expect the
helper processes to get cleaned up. However, even if you exit VS after you
stop debugging, these orphaned processes remain.

I'm guessing this is some sort of upstream problem, but I'm wondering
whether would should add a watchdog thread the process to check that it's
parent process is still running.

It's not a big deal, as I've only ever seen it while debugging. However, it
can quickly consume memory if you aren't aware they're being generated.

James

**Comment by amaitland** [comment] 2015-10-03 11:19
If it only happens when terminating abruptly whilst debugging then I'm inclined to close this.

It may be worth reporting `upstream`, though you'd have to reproduce the problem using `cefclient` before doing so.

**Closed** 2015-10-06 12:03 UTC
