### ISSUE TITLE
Contents not rendering properly in Cef browser

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#2213] opened 2017-12-18 12:11 UTC
Hi Team,

We are using the cefSharp browser version as 45.0.0 in our WPF application.

- We are facing the content rendering issues in the application

- If we search any id, the description not loaded and showing the empty screen
![image](https://user-images.githubusercontent.com/20086495/34105324-d0ddc194-e419-11e7-8b0d-3775afe2a1bc.png)

- After clicking the next panel and come back to the current panel only the description was loaded. If loading the description after few minutes the panel getting frozen sometimes. After goes back to the next panel only resolve this issue. 

Could you please suggest us to resolve this issue.

Please find the configuration details.

WPF .Net framework version - 4.5
Machine resolution - 1920 * 1080
CefSharp Version - 45.0.0

Regards,
Arunkumar Murugesan

**Comment by mitchcapper** [comment] 2017-12-18 16:16
@Arunkumar-Murugesan you are using a very out of date version of the control, per the https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md can you reproduce with the sample app  / fork the example to repro with the latest version with minimal changes?  Can you provide a code sample for the exact process you are doing?

**Comment by Arunkumar-Murugesan** [comment] 2017-12-19 09:09
Hi Mitchcapper,

Thanks for the update. Please find the code changes we are using the cefSharp browser.

[CefSharpBrowser.txt](https://github.com/cefsharp/CefSharp/files/1570945/CefSharpBrowser.txt)

Also please find the Debug file for the application.
[debug.txt](https://github.com/cefsharp/CefSharp/files/1570987/debug.txt)

Regards,
Arunkumar Murugesan

**Comment by Arunkumar-Murugesan** [comment] 2017-12-21 03:54
Hi Team,

Could anyone please update me on this?

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment] 2017-12-21 08:38
Duplicate of #1571

**Closed by amaitland** 2017-12-21 08:38 UTC
