### ISSUE TITLE
Please Support Fix only open I Am use x32-Bit WinForm CefSharp 65.0.0-CI2547 Support x32-Bit Perform

### ISSUE THREAD

**Issue by mohamedosama914** [cefsharp/CefSharp#2342] opened 2018-03-30 13:43 UTC
# :+1: WinForm CefSharp version 63.0.2 | x32-Bit 
# :-1:  WinForm CefSharp version 65.0.0-CI2547 | x32-Bit 
**`Please Support Fix I Am use x32-Bit WinForm CefSharp version 65.0.0-CI2547 Support x32-Bit Perform`**
![how](https://user-images.githubusercontent.com/12082147/38139500-ef592ddc-342f-11e8-8f15-00d64aa4d36c.PNG)

[0330/152048.096:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
[0330/152051.218:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
[0330/152051.234:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
[0330/152057.430:ERROR:service_manager_context.cc(252)]
Attempting to run unsupported native service:
E:\Program Files\Git\bin\Projects\ChromiumApplication\32-Bit Debug\content_renderer.service.exe

**Comment by amaitland** [comment] 2018-03-30 14:11
Duplicate of #2331

**Closed** 2018-03-30 14:10 UTC
