### ISSUE TITLE
Memory leak when using CefSharp.BindObjectAsync().

### ISSUE THREAD

**Issue by HTD** [cefsharp/CefSharp#2432] opened 2018-06-26 14:36 UTC
- **What version of the product are you using?**
65.0.0-pre02 (NuGet)

- **What architecture x86 or x64?**
Both.

- **On what operating system?**
Win10.

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen.

- **What steps will reproduce the problem?**
A huge memory leak occurs on each page reload when CefSharp.BindObjectAsync() is used.

To reproduce run the test project: https://github.com/HTD/CefSharpTest

When run in probably less than a minute memory usage of `CefSharp.BrowserSubprocess.exe` will grow exceeding 100MB, soon exceeding 1GB and more. Switch `IsFullTestEnabled` field to false and rerun the test. The described memory leak will not occur.

When `IsFullTestEnabled` field is set to false the bound class is still cached during each reload, but it is unavailable (not bound) after reloading.

It is expected, that binding the same object on each page reload should not cause a memory leak.

**Comment by HTD** [comment] 2018-06-27 06:09
I just tested it with `CefSharpSettings.LegacyJavascriptBindingEnabled = true;` option and legacy JSB, no memory leak, work as charm, so clearly new JSB is broken. Any clues? Is it possible the problem is in CefSharp, not CEF itself?

**Comment by amaitland** [comment] 2018-06-27 12:15
> To reproduce run the test project: https://github.com/HTD/CefSharpTest

Thanks for providing an example :+1:

> Any clues? Is it possible the problem is in CefSharp, not CEF itself?

No idea at this stage. The `V8 Javascript Engine` is constantly evolving,  what worked in a previous version doesn't always work in a newer ones, #2390 is a recent example of that.

**Comment by HTD** [comment] 2018-06-27 21:13
Looks like a duplicate, but in my case the leak is not present in legacy mode, only in the native one. BTW, it seems to be present since 63.x, I just haven't tested it well enough with that version.

**Comment by amaitland** [comment] 2018-06-30 08:35
Running the `WPF` example and using `BindingTest.html` as a more complete example, calling `Reload` every `10 seconds` and I'm seeing pretty much what I expect, memory usage rises, then the `GC` kicks in and reclaims it. There does appear to be a leak when you refresh the browser every second, which has me wondering if the `GC` doesn't have time to run.

Relevant commit https://github.com/cefsharp/CefSharp/commit/57d60e97cbafaaac65447bcddf8c7269e7ea3d72

**Comment by amaitland** [comment] 2018-08-27 03:09
Testing with https://github.com/cefsharp/CefSharp/commit/b0af05a6abfe07009dbb79ffd9c2859095c59881 and the `Javascript GC` appears to be working again, the memory usage goes up and after a short period of time comes back down to a manageable level. I've not seen it rise past `150mb` on my machine, this will likely vary depending on hardware/operating system.

Closing as unable to reproduce with newer versions.

**Closed by amaitland** 2018-08-27 03:09 UTC
Labels: known-issue
