### ISSUE TITLE
Drag-Drop not working new latest version

### ISSUE THREAD

**Issue by SUHASABOROLE** [cefsharp/CefSharp#4594] opened 2023-09-26 09:42 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

116.0.130

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET 4.7

### Implementation

WPF

### Reproduction Steps

I am developing a C#, WPF application for touch screens where user can search a text entered. The search results are opened in a cefsharp browser from which the user can drag and drop the searched images or videos to my canvas app where the searched images/videos can be saved offline.
With version 65, we were able to drag and drop images using touch gestures. While after updating to the latest version, the touch-based drag and drop to canvas is not working anymore. We are able to scroll the page using touch with the latest version though. In ver 65, touch scroll was not working.

Seems like touch based scroll is conflicting with touch drag function in latest versions. Is it possible to disable touch scroll so that drag and drop using touch works?

### Expected behavior

drag and drop and touch scroll both should be working in wpf application.

### Actual behavior

In cefsharp 116.0.230, touch scroll working but drag & drop does not work.

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

**Comment by amaitland** [comment] 2023-09-26 20:38
Closing as duplicate of #4592

Please don't create multiple issues for the exact same problem

**Closed by amaitland** 2023-09-26 20:38 UTC
