### ISSUE TITLE
CommunicationException when closing the application

### ISSUE THREAD

**Issue by DeltaDev1** [cefsharp/CefSharp#2220] opened 2017-12-28 10:10 UTC
- **What version of the product are you using?**
    Nuget 57.0.0.0.

- **What architecture x86 or x64?**
   x86

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  - WinForms hosted in a WPF Application.

- **What steps will reproduce the problem?**
    I just close the application calling Application.Current.Shutdown(1) and the error shows up. The application closes successfully. Cef.Shutdown doesn't help, i tried many ways of closing the application and CefSharp and nothing help, but killing the app process. Unfortunately i am unable to reproduce it in the minimal wpf example. 

- **What is the expected output? What do you see instead?**
 I expect it to close normally and i do not expect an error message. I see the error message, which is very bad in production environment.

- **Please provide any additional information below.**
    - In the windows event log i was able to look at the stack trace. 
`Application: CefSharp.BrowserSubprocess.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ServiceModel.CommunicationException Stack: at System.ServiceModel.Channels.PipeConnection.WriteHelper(Byte[], Int32, Int32, Boolean, System.TimeSpan, System.Object ByRef) at System.ServiceModel.Channels.PipeConnection.Write(Byte[], Int32, Int32, Boolean, System.TimeSpan) at System.ServiceModel.Channels.BufferedConnection.WriteNow(Byte[], Int32, Int32, System.TimeSpan, System.ServiceModel.Channels.BufferManager) at System.ServiceModel.Channels.BufferedConnection.Write(Byte[], Int32, Int32, Boolean, System.TimeSpan) at System.ServiceModel.Channels.FramingDuplexSessionChannel.CloseOutputSessionCore(System.TimeSpan) at System.ServiceModel.Channels.TransportDuplexSessionChannel.CloseOutputSession(System.TimeSpan) at System.ServiceModel.Channels.TransportDuplexSessionChannel.OnClose(System.TimeSpan) at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan) at System.ServiceModel.Channels.ServiceChannel.OnClose(System.TimeSpan) at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan) at System.ServiceModel.Channels.ServiceChannelFactory.OnClose(System.TimeSpan) at System.ServiceModel.Channels.ServiceChannelFactory+TypedServiceChannelFactory`\``1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnClose(System.TimeSpan) at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan) at System.ServiceModel.ChannelFactory.OnClose(System.TimeSpan) at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan) at CefSharp.BrowserSubprocess.WcfEnabledSubProcess.OnBrowserDestroyed(CefSharp.CefBrowserWrapper) at <Module>.CefSharp.CefAppUnmanagedWrapper.OnBrowserDestroyed(CefSharp.CefAppUnmanagedWrapper*, scoped_refptr<CefBrowser>*) at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*) at CefSharp.BrowserSubprocess.SubProcess.Run() at CefSharp.BrowserSubprocess.Program.Main(System.String[]) `

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
i do not have such a file in my bin

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
I host my application in windows forms host using a 3rd party tool VmTouchDevice for the touch events to work correctly. I use the following settings:
```
          cefSettings.MultiThreadedMessageLoop = false;
            cefSettings.CefCommandLineArgs.Add("disable-pinch", "1");
            cefSettings.CefCommandLineArgs.Add("touch-events", "1");
            cefSettings.CefCommandLineArgs.Add("allow-no-sandbox-job", "1");
            cefSettings.CefCommandLineArgs.Add("noerrdialogs", "1");
            cefSettings.LogSeverity = LogSeverity.Disable;
            Cef.EnableHighDPISupport();
            Cef.Initialize(cefSettings,);
```

            void CefMessageLoopWork(object sender, EventArgs eventArgs)
            {
                try
                {
                    Cef.DoMessageLoopWork();
                }
                catch
                {
                    ((DispatcherTimer)sender).Stop();
                }
            }
            _cefMessageLoopTimer = new DispatcherTimer
            (
                TimeSpan.FromMilliseconds(1000 / 60d),
                DispatcherPriority.ApplicationIdle,
                CefMessageLoopWork,
                Dispatcher
            );
            _cefMessageLoopTimer.Start();`

I use to register Js object and call js functions using ExecuteScriptAsync and EvaluateScriptAsync, but not at the time of the shutdown process. The error is not rised if i just use Process.Kill(); Can't think of anything else, that could be useful.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
didn't try that, since i am not even able to reproduce that in the wpf.minimal example.
Since my project is respectively big, it will take me too much time to rebuild it piece by piece to see what is likely to cause the problem.

It would be great to have an option to hide all exception messages from the CefSharp.BrowserSubprocess.exe

**Comment by amaitland** [comment] 2018-01-11 01:58
Duplicate of #2074

**Closed by amaitland** 2018-01-11 01:58 UTC

**Comment by DeltaDev1** [comment] 2018-01-11 07:54
Ty for your response. To me the problems seem a little bit different. In my case the error rises when i close the application, and the stack trace of the exception shows it occurs at the PipeConnection.WriteHelper. In the referenced issue the application crashes "randomly" and the stack trace of the exceptions shows the error occurs at PipeConnection.Read.
However i do not understand it well. May be the problem has the same source. Feel free to close the issue again if you know it for sure.

**Comment by amaitland** [comment] 2018-01-11 08:17
Doesn't matter, they're still triggered from the same call to close, focus on the bottom of the stack trace, that's the important part.

**Comment by DeltaDev1** [comment] 2018-01-11 08:22
Oh, well. As i can see from the referenced issue there's a fix to this problem, which sounds very good. Thank you!
