### ISSUE TITLE
Very high (>400MB) memory usage on some machines

### ISSUE THREAD

**Issue by canton7** [cefsharp/CefSharp#902] opened 2015-03-25 09:24 UTC
Hi,

I'm seeing an issue where a small number of users see very high memory usage (>400MB for x64, >250MB for x86). Unfortunately I'm not one of them, but thanks to a very helpful user who is experiencing the problem (@sluTTYusr) we've managed to establish the following facts:

 - The memory is in the private working set
 - The memory increase is triggered by `Cef.Initialize()`. Most of the memory is released if `Cef.Shutdown()` is called
 - The memory does not appear in Cef's heap snapshots (gathered by specifying a remote debugging port to Cef, connecting to it, and running the profiler)
 - The memory is unmanaged: the GC knows nothing about it, and it doesn't appear on .NET profilers
 - It occurs in the absence of the WPF or WinForms control
 - It's something to do with environment: the user sees the high usage on his PC, but not inside a virtual machine on that PC
 - I don't think it's to do with something being present in the GAC: [Here's the output of `gacutil -l` from his PC](http://pastebin.com/qqRRJSkR) and [from his VM](http://pastebin.com/2xxbnsZz)
 - It's present in the latest Stable and Prerelease versions of CefSharp/Cef from NuGet, and in the latest from your MyGet feed.
 - Specifying "disable-gpu-vsync" and "disable-gpu" in CefCommandLineArgs had no effect
 - Specifying `LogSeverity = LogSeverity.Verbose` produces [this debug.log](http://pastebin.com/pf1eB0qc)

I'm afraid I'm out of ideas and things to try.

If you're sure this is a Cef issue, and not a CefSharp one, please redirect me somewhere more suitable!

Thanks

**Comment by jankurianski** [comment] 2015-03-25 10:28
I would get the user to download the official Cef `Test App` from http://cefbuilds.com/ and see what its memory usage is.  There's instructions on finding the right version and command-line arguments to use here: https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment] 2015-03-25 11:09
What `OS`? What Graphics card?

> It occurs in the absence of the WPF or WinForms control

Can you clarify which version you are actually using? `OffScreen`?

Testing using `cef client` is an excellent place to start. There is also an experimental version based on `Chromium 41` available https://github.com/cefsharp/CefSharp/tree/cef/2272

**Comment by sluTTYusr** [comment] 2015-03-25 11:17
OS: Windows 7 x64
Graphics Card: Gigabyte GeForce GTX 970 Mini 4GB

**Comment by canton7** [comment] 2015-03-25 11:20
@amaitland CefSharp.Wpf and dependencies. We replicated the issue with a minimal application which literally only did `Cef.Initialize()` though - I didn't use the WPF control anywhere.

Not sure what any other users apart from @sluTTYusr are running. I'm also running win7 x64 and haven't seen it.

@sluTTYusr: Mind trying that cef test app? Go to https://cefbuilds.com/, dowload the Windows 7 64-bit Test App, and run with `cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled` (although it might be useful to see it without `--off-screen-rendering-enabled` too).

**Comment by amaitland** [comment] 2015-03-25 11:30
Latest `VC++ 2012` redist installed? What version of .Net is installed?

> We replicated the issue with a minimal application which literally only did Cef.Initialize() though - I didn't use the WPF control anywhere.

`CefSharp` is a pretty thin wrapper around `CEF`. When `Cef.Initialize()` is called, there's very little that happens in `CefSharp`.

> Go to https://cefbuilds.com/, dowload the Windows 7 64-bit Test App

@sluTTYusr Can you please try `CEF 3.2171.2039`, that roughly corresponds to `CefSharp 39`

**Comment by canton7** [comment] 2015-03-25 11:33
> Latest VC++ 2012 redist installed? What version of .Net is installed?

Latest VC++ redist 2012 was present in the same directory as the .exe. My application targets .NET 4.5.

> CefSharp is a pretty thin wrapper around CEF. When Cef.Initialize() is called, there's very little that happens in CefSharp.

Ah, so probably a Cef issue then? Let's see the result of the `cefclient` test anyway.

**Comment by sluTTYusr** [comment] 2015-03-25 11:35
Chromium build is 43.0.2344.0 in case it matters.

I ran the TestApp first with 
`cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled`
![2015-03-25_122553](https://cloud.githubusercontent.com/assets/11618119/6823699/dd215bf2-d2ea-11e4-9786-b407f87eca53.png)

Then with
`cefclient.exe --multi-threaded-message-loop`
![2015-03-25_122642](https://cloud.githubusercontent.com/assets/11618119/6823705/ecf391a8-d2ea-11e4-9eef-e23196b30f8d.png)

**Comment by sluTTYusr** [comment] 2015-03-25 11:39
OK, saw that too late...
With TestApp 3.2171.2039... firsdt with off screen rendering, second without...
![2015-03-25_123653](https://cloud.githubusercontent.com/assets/11618119/6823801/ed2ee720-d2eb-11e4-972f-97db3b60911b.png)
![2015-03-25_123732](https://cloud.githubusercontent.com/assets/11618119/6823802/f012e676-d2eb-11e4-9c29-cad74b5e39d7.png)

**Comment by canton7** [comment] 2015-03-25 11:44
This looks like a Cef issue, then? What's the best way to contact them? https://bitbucket.org/chromiumembedded/cef/issues

**Comment by amaitland** [comment] 2015-03-25 11:47
> This looks like a Cef issue, then?

Looking like it.

> What's the best way to contact them?

They prefer if you post on http://magpcss.org/ceforum/ first :+1:

**Comment by canton7** [comment] 2015-03-25 11:53
Thanks for the tip! Anything can you suggest in the meantime, based on experience?

**Comment by rwadhwa** [comment] 2015-03-25 21:21
I recently did a POC for our real time financial app . App have high charts and does lot of http polling. We have noticed that memory usage spikes upto 600+ and at time 700 + over a period. We have been using awesomium but wanted to try this since we have been having intermittent  crash issues with awesomium and also awesomium is running on chrome 18

**Comment by amaitland** [comment] 2015-03-25 22:10
There has been a lot of work done on `CefSharp` recently, and hopefully someone will profile the core code to check for memory leaks at some point. For the most part though, when seeing large numbers in the hundreds of megabytes, it's most likely linked to the `Chromium` version that `CEF` and hence `CefSharp` is based on. 

@rwadhwa Are you drawing those charts using `HTML5 canvas`? If so, then you'll likely need the latest version of `CEF` you can get your hands on. It would be also helpful if you can try isolate the issue. @canton7 has some excellent tips on how to get a snapshot of the `Chromium` heap in https://github.com/canton7/SyncTrayzor/issues/37#issuecomment-85475917

> Anything can you suggest in the meantime, based on experience?

@canton7 It's quite common to see graphics related problems, you've tried the obvious in disabling `GPU acceleration`, I'd usually recommend checking video card driver versions, see if any improvements have been made as that's a very easy thing to do. It also may be worth disabling plugins, it's a long shot. 

- `cefclient.exe --multi-threaded-message-loop --off-screen-rendering-enabled --disable-plugins-discovery`
- From the menu select, `Tests -> Plugin Info` to confirm that plugins have been disabled

**Comment by rwadhwa** [comment] 2015-03-26 02:34
@amaitland So I have two instance of cefSharp running. One has highCharts and a grid with data  and other is just a grid with data being polled continuously using lightStreamer.
here's my code
 public partial class Blotter : AweWindowBase
    {
        public Blotter ()
        {
            InitializeComponent();
            CefSharp.Cef.Initialize(new CefSettings());
            this.Name = "MyWin";
            URLAddress = NegotiationConfigurationSettings.MiniBlotterURL;
        
            this.Loaded += new System.Windows.RoutedEventHandler(this.OnWindowLoaded);
        }
        protected override void Initialize(NegotiationWindowHeader winHdr)
        {
            base.Initialize(winHdr);
            this.cbrowser = this.browser;
            winHdr.CloseBtnHandler += (o, e) =>
            {
                if (AppManager.Instance.SessionKilledFlag)
                {
                    this.Close();
                }
                else
                {
                    this.Visibility = System.Windows.Visibility.Collapsed;
                }
            };
        }
        private void OnWindowLoaded(object sender, RoutedEventArgs e)
        {
            //URLAddress = "http://la977354.dmn1.fmr.com:9000/?debug=true#/blotter";
           // URLAddress = "http://localhost:9000/?debug=true#/miniblotter";
            base.LoadBrowser();
        }
    }
}

 public abstract class AweWindowBase : Window
    {
        
        protected CefSharp.Wpf.ChromiumWebBrowser cbrowser { get; set; }
        protected string URLAddress { get; set; }
        protected AweWindowBase() 
        {
            this.ResizeMode = System.Windows.ResizeMode.CanResizeWithGrip;
        }
        protected virtual void Initialize(NegotiationWindowHeader winHdr)
        {
            
        }
 protected void LoadBrowser()
        {
            this.cbrowser.RegisterJsObject("_wpf", new WpfJSObject());
            this.cbrowser.MenuHandler = new MyMenuHandler();
            this.cbrowser.RequestHandler = new MyRequestHandler();
            this.cbrowser.Address = URLAddress;
        }
}
}

please see attached screen shot to view how high is memory usage 
![cefsharp](https://cloud.githubusercontent.com/assets/3867180/6839444/d427c596-d33e-11e4-88b9-2d860d107df7.png)

Also, I am using pre-release 39 version of cefSharp.

**Comment by rwadhwa** [comment] 2015-03-26 02:48
@amaitland 
not sure if got my previous message, by mistake I deleted it. However, I have two instance of cefSharp running one has just charts and other has grid with data. Both are polling every second to fetch data. We are using LightStreamer to do so.
Please see the task manager screenshot to view how high memory usage is.
Also here's the code snippet
public partial class Blotter : WindowBase 
 {
        public Blotter ()
        {
            InitializeComponent();
            CefSharp.Cef.Initialize(new CefSettings());
            this.Name = "MyBlotter"
            URLAddress = ConfigurationSettings.BlotterURL;
            this.Initialize(this.skrHeader);
            this.Loaded += new System.Windows.RoutedEventHandler(this.OnWindowLoaded);
        }
        protected override void Initialize(NegotiationWindowHeader winHdr)
        {
            this.cbrowser = this.browser;
        }
        private void OnWindowLoaded(object sender, RoutedEventArgs e)
        {
            base.LoadBrowser();
        }
  }

  public abstract class WindowBase : Window
    {
        protected CefSharp.Wpf.ChromiumWebBrowser cbrowser { get; set; }
        protected string URLAddress { get; set; }
        protected AweWindowBase() 
        {
            this.ResizeMode = System.Windows.ResizeMode.CanResizeWithGrip;
        }
      protected void LoadBrowser()       
      {
            this.cbrowser.RegisterJsObject("_wpf", new WpfJSObject());
            this.cbrowser.MenuHandler = new MyMenuHandler();
            this.cbrowser.RequestHandler = new MyRequestHandler();
            this.cbrowser.Address = URLAddress;
        }
   }

![cefsharp](https://cloud.githubusercontent.com/assets/3867180/6839580/fa97d8e0-d340-11e4-84c6-ba9f03d1e77b.png)

**Comment by amaitland** [comment] 2015-03-26 03:38
@codeplayer1975 Your code doesn't really divulge much unfortunately. (preferable to post anything more than a few lines as a `gist`). Do you see the same usage regardless of the hardware it's running on?

**Comment by codeplayer1975** [comment] 2015-03-26 03:54
@amaitland 
would it be an issue if I compile for x86 but run in window 7 64 bit machine.

**Comment by amaitland** [comment] 2015-03-26 04:27
> would it be an issue if I compile for x86 but run in window 7 64 bit machine.

Nope, both `x86` and `x64` will work on a `64bit` machine. The `x64` version does support more memory of course, so may be better suited to your requirements, though not required.

You could also try out the https://github.com/cefsharp/CefSharp/tree/cef/2272 branch if you wish to see how a newer version of `Chromium` performs.

Currently are you using `37` or `39`?

**Comment by codeplayer1975** [comment] 2015-03-26 04:28
I am using 39

**Comment by amaitland** [comment] 2015-03-26 04:32
`2272` is based on `Chromium 41`

**Comment by codeplayer1975** [comment] 2015-03-26 04:34
Yep, I am going to try tomorrow and let you know how it goes. Thanks

**Comment by amaitland** [comment] 2015-04-08 04:24
Any further update on this?

**Comment by codeplayer1975** [comment] 2015-04-08 11:54
I am still having same issues. Even happening when used the libraries from the branch you suggested.
My machine configuration
Windows 7 
Using 32 bit cef libraries for the application
Applications details
1- angularjs single page app
2- uses continuos http polling to update grid in the app.
3- uses highstockchart with real time update of stock prices 
4- making about 4 - 5 Ajax request per second

Same app works fine in chrome with memory spiking to about 250k in 8 hr period. Same app spikes to 700 plus and at times crash around same range of memory. 

Sorry could not spend more time on it

**Comment by codeplayer1975** [comment] 2015-04-08 13:54
got the latest from 2272 branch and getting following error 
![capture](https://cloud.githubusercontent.com/assets/3867180/7046488/201628b8-ddd4-11e4-8773-25a7c92b8f12.PNG).

**Comment by amaitland** [comment] 2015-04-09 00:37
> got the latest from 2272 branch and getting following error

I'd suggest you clean your working directory, make sure you have the latest version of the `2272` branch, which is https://github.com/cefsharp/CefSharp/commit/0f522a6f01f9fe6c9866439999ede155ea202813 as of writing.

**Comment by Sential** [comment] 2015-04-12 13:49
![przechwytywanie](https://cloud.githubusercontent.com/assets/11065386/7105795/5ef3a7e0-e12b-11e4-8078-69a98b4f748b.PNG)
I have the same problem with Subprocesses

**Comment by amaitland** [comment] 2015-04-12 22:21
> I have the same problem with Subprocesses

That's a very vague statement. You **MUST** provide more information. In general those numbers aren't that big for a web browser.

**Comment by canton7** [comment] 2015-04-13 07:35
"The same problem" is also very vague - this issue stated off with a very specific problem, then got derailed into "every CefSharp memory issue ever" :stuck_out_tongue_closed_eyes:

**Comment by bjarteskogoy** [comment] 2015-05-08 18:31
We've seen this happening on computers with .Net 4 installed. Installing .Net 4.5 has fixed this in the cases we've seen.

**Comment by amaitland** [comment] 2015-08-26 22:44
> "The same problem" is also very vague - this issue stated off with a very specific problem, then got derailed into "every CefSharp memory issue ever" :stuck_out_tongue_closed_eyes:

Closing this, for those still experiencing high memory usage, please try the latest `43.0.0-pre01` release that's now on `nuget`. If the problem is still apparently please open a new **separate** issue so we can track and diagnose things properly.

**Closed by amaitland** 2015-08-26 22:44 UTC

**Comment by andremorata** [comment] 2017-08-29 20:01
I'm experiencing something like this in version 57.0. My app is a win classic that consists in capture data from pages and auto-navigate to the next and keep collecting data. 
After 1,5 hours working the RAM allocation is about 3.7GB. 
![image](https://user-images.githubusercontent.com/1455566/29841359-853caf56-8cdb-11e7-92d4-3f38084647ea.png)

Is there anything I can do on the code to make sure it keeps at least below 1.5GB?

**Comment by merceyz** [comment] 2017-08-29 20:16
Turn off process-per-tab
