### ISSUE TITLE
Scrollbar changes size on zoom.

### ISSUE THREAD

**Issue by crystalbyte** [cefsharp/CefSharp#1341] opened 2015-10-15 20:15 UTC
Hi,

I recently updated to the latest CefSharp release.
I noticed that the scrollbar changes size when zooming in and out. 
This behavior is very unexpected, as far as I know no browser does this, nor any other application.
Is it possible to deactivate that behavior?

Alex

**Comment by amaitland** [comment] 2015-10-15 20:26
> I recently updated to the latest CefSharp release.

Please be specific, `latest` is a relative thing.

Are you using `WinForms` or `WPF`?

**Comment by crystalbyte** [comment] 2015-10-15 21:06
Sorry for not mentioning this, I am using WPF.

**Comment by amaitland** [comment] 2015-10-15 21:09
> Sorry for not mentioning this, I am using WPF.

Version?

**Comment by crystalbyte** [comment] 2015-10-15 21:09
It is 43.0.0.

**Comment by amaitland** [comment] 2015-10-15 21:31
> I noticed that the scrollbar changes size when zooming in and out.

What exactly are you seeing? Does the problem reproduce with `CefSharp.Wpf.Example`? Is it just a specific website or all websites? Quick test zooming in on `Google doodles` and I'm not seeing anything unexpected.

Relevant branch is https://github.com/cefsharp/CefSharp/tree/cefsharp/43


> This behavior is very unexpected, as far as I know no browser does this, nor any other application.

`Chrome` will resize the scroll-bars in certain scenarios, like when you zoom out a long way.

**Comment by crystalbyte** [comment] 2015-10-16 17:26
After some checking I figured out that my issue is caused by styling the scrollbar, by the CSS attributes "width" and "height" in particular. Once removed, the scrollbar no longer resizes on zoom.

**Comment by amaitland** [comment] 2015-10-16 23:55
Interesting! How does it behave in `Chrome`?

**Comment by crystalbyte** [comment] 2015-10-17 10:35
Chrome's behavior does not differ between styled and unstyled scrollbars,
The scrollbar's size remains constant.

**Comment by amaitland** [comment] 2015-10-17 12:00
> Chrome's behavior does not differ between styled and unstyled scrollbars,

Did you try a comparable version? `master` is based on `Chromium 45`, so might be worth seeing if the behavior is different.

**Comment by crystalbyte** [comment] 2015-10-17 12:14
I use Version 46.0.2490.71 m, which is on this date the latest stable release.
I checked the 45 change log, I did not found any entries regarding changes on this topic.

**Comment by amaitland** [comment] 2015-10-17 21:18
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by amaitland** [comment] 2015-11-01 10:50
@crystalbyte Any followup before closing this?

**Comment by amaitland** [comment] 2015-11-16 02:15
Closing due to lack of feedback.

**Closed by amaitland** 2015-11-16 02:15 UTC
Labels: upstream, wpf
