### ISSUE TITLE
Devtools have keypress bug when MultiThreadedMessageLoop =false

### ISSUE THREAD

**Issue by PingXD** [cefsharp/CefSharp#3751] opened 2021-08-13 07:51 UTC
when Cefsettings is `settings.MultiThreadedMessageLoop = false;` 
and ` Application.Idle += (s, e) => Cef.DoMessageLoopWork();`
in devtools Console coding ↑↓←→ and "Tab" key is Failure to press when i move  the above code  It will recover
example:
![image](https://user-images.githubusercontent.com/48038690/129323090-53ef7ea6-67e5-4dc7-acb1-054587ba2057.png)
i want will use 'Tab' key to completion the code  it's inoperble

**Comment by amaitland** [comment] 2021-08-13 07:53
Closing as duplicate of #2899

**Closed by amaitland** 2021-08-13 07:53 UTC
