### ISSUE TITLE
app crashed in CefSharp_Core!CefStreamResourceHandler::CefStreamResourceHandler+189

### ISSUE THREAD

**Issue by vincentshow** [cefsharp/CefSharp#2256] opened 2018-01-31 06:02 UTC
Same app with #2255. My app using cefsharp57, winform, installed by nuget, and the render is customized. Codes are same with CefSharp.BrowserSubprocess while the project name is myself called JJRender.  Anyway, it also could not be reproduced.

crashed with follow summary in dump file:

FAULTING_IP: 
CefSharp_Core!CefStreamResourceHandler::CefStreamResourceHandler+189
703c3119 8b01            mov     eax,dword ptr [ecx]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 703c3119 (CefSharp_Core!CefStreamResourceHandler::CefStreamResourceHandler+0x00000189)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000000
Attempt to read from address 00000000

[dump_from_crashpad.zip](https://github.com/cefsharp/CefSharp/files/1680293/dump_from_crashpad.zip)
[dump_result.txt](https://github.com/cefsharp/CefSharp/files/1680294/dump_result.txt)

**Comment by amaitland** [comment] 2018-01-31 11:33
Search the recently closed issues for CefStreamResourceHandler

**Comment by vincentshow** [comment] 2018-01-31 14:45
Sorry,  I just cannot find valuable closed issues about CefStreamResourceHandler. Can you give me a direct link or specific advice. Thank you.

**Comment by amaitland** [comment] 2018-01-31 23:28
Use the `GitHub` search.

**Comment by vincentshow** [comment] 2018-02-01 02:44
Show me which one!

![131619258308871322](https://user-images.githubusercontent.com/6469836/35658521-bb03d43a-073c-11e8-9a21-8b9cb4ad2ad2.png)

By the way, what I need is valuable advice or solution and I'm wondering if you think this is a meaningless issue. You can dispatch this to others if you are busy or have any other reason. Thank you!

**Comment by amaitland** [comment] 2018-02-01 04:50
> Show me which one!

Perhaps start with the one that says `AccessViolationException` as your seeing an `Access Violation`?

> By the way, what I need is valuable advice or solution and I'm wondering if you think this is a meaningless issue.

And I've giving you a pointer on where to start looking, see if any of the past issues match.

**Comment by amaitland** [comment] 2018-02-05 23:42
Closing as this is likely a duplicate of #2217 or #2238 (Those are the only two implementations of `CefStreamResourceHandler`.

**Closed by amaitland** 2018-02-05 23:42 UTC
