### ISSUE TITLE
unlimited-storage command doesn't work

### ISSUE THREAD

**Issue by goldengrisha** [cefsharp/CefSharp#2323] opened 2018-03-20 12:38 UTC
-  Version Nuget 63.0.2;
-  x86 and x64;
-  Win10;
-  WinForms;

 - When I try to run cefsharp with settings.CefCommandLineArgs["unlimited-storage"] = "1", it doesn't make any effects;
- Expected output is unlimited quota;

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information - NO;
    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory) - NO;
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls? - NO;

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?** NO;

**Comment by merceyz** [comment] 2018-03-20 13:10
Possible duplicate of https://github.com/cefsharp/CefSharp/issues/2317

**Closed by merceyz** 2018-03-20 13:10 UTC

**Comment by goldengrisha** [comment] 2018-03-20 15:00
Unlimited-storage it's command line arg, how can  run it ?

**Comment by amaitland** [comment] 2018-03-20 21:38
I've never heard of that command so unlikely it's supported in CEF. 

You can ask on http://magpcss.org/ceforum/index.php for a second opinion. 

CefSharp is just a wrapper around CEF
