### ISSUE TITLE
`OnAcceleratedPaint` is called very rarely so even if I've tried to use Direct3D11 to improve the rendering performance of CefSharp.Wpf things not getting better.

### ISSUE THREAD

**Issue by walterlv** [cefsharp/CefSharp#2940] opened 2019-10-23 01:48 UTC
I've tried to implemented the `OnAcceleratedPaint` method using Direct3D11 and converted it to `D3DImage`.

But unfortunately, I find that `OnAcceleratedPaint` method is called with a very low fps. So even that the rendering process is very fast, but the fps is very low.

This is my fps tested on my computer:

Method|`OnPaint`/`OnAcceleratedPaint` method called times per second
-|-
WriteableBitmap by @eh2k | 45~55
Direct3D11 by me @walterlv | 1~3

What makes me surprised is that even if I just write a `return` and do nothing in the `OnAcceleratedPaint` method, this method is still been called 1~3 times per second. So I always see a very unsmoothly website animation.

Maybe I need someone's help to tell me why the `OnAcceleratedPaint` is called rarely and how can I improve the fps of the `OnAcceleratedPaint` method. By solving this, we can improve the rendering performance of WPF ChromiumWebBrowser.

This is my code. Because it still doesn't really improve the performance so I didn't make a pull request.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using Microsoft.Wpf.Interop.DirectX;
using SharpDX.Direct2D1;
using SharpDX.Direct3D;
using SharpDX.Direct3D11;
using CreateFlags = SharpDX.Direct3D9.CreateFlags;

namespace CefSharp.Wpf.Rendering
{
    internal sealed class SharpDXRenderHandler : IRenderHandler
    {
        public void OnPaint(bool isPopup, CefSharp.Structs.Rect dirtyRect, IntPtr buffer, int width, int height, System.Windows.Controls.Image image)
        {
            // SharpDX doesn't render in software mode.
        }

        public void Dispose()
        {
        }

        private D3DImage _d3dImage;

        public void OnAcceleratedPaint(bool isPopup, CefSharp.Structs.Rect dirtyRect, IntPtr sharedHandle, System.Windows.Controls.Image image)
        {
            image.Dispatcher.InvokeAsync(() =>
            {
                if (_d3dImage is null)
                {
                    _d3dImage = new D3DImage();
                }
                if (image.Source is null)
                {
                    image.Source = _d3dImage;
                }

                var hostHandle = ((HwndSource)PresentationSource.FromVisual(image)).Handle;
                RenderToD3dImage(new Int32Rect(dirtyRect.X, dirtyRect.Y, dirtyRect.Width, dirtyRect.Height), sharedHandle, hostHandle);
            }, System.Windows.Threading.DispatcherPriority.Render);
        }

        private void RenderToD3dImage(Int32Rect dirtyRect, IntPtr sharedHandle, IntPtr hostHandle)
        {
            var texture2D = OpenSharedResource(sharedHandle);

            var d3d9Device = new SharpDX.Direct3D9.DeviceEx(
                new SharpDX.Direct3D9.Direct3DEx(),
                0,
                SharpDX.Direct3D9.DeviceType.Hardware,
                IntPtr.Zero,
                CreateFlags.HardwareVertexProcessing | CreateFlags.Multithreaded | CreateFlags.FpuPreserve,
                GetD3D9PresentParameters(hostHandle));

            var d3dTexture = new SharpDX.Direct3D9.Texture(
                d3d9Device,
                texture2D.Description.Width,
                texture2D.Description.Height,
                1,
                SharpDX.Direct3D9.Usage.RenderTarget,
                DXGIToD3D9(texture2D.Description.Format),
                SharpDX.Direct3D9.Pool.Default,
                ref sharedHandle);

            using (var surface = d3dTexture.GetSurfaceLevel(0))
            {
                _d3dImage.Lock();
                _d3dImage.SetBackBuffer(D3DResourceType.IDirect3DSurface9, surface.NativePointer);
                _d3dImage.AddDirtyRect(SafeRect(dirtyRect));
                _d3dImage.Unlock();
            }
        }

        private SharpDX.Direct3D11.Texture2D OpenSharedResource(IntPtr handle)
        {
            var device = new SharpDX.Direct3D11.Device(DriverType.Hardware, DeviceCreationFlags.BgraSupport);
            var resource = device.OpenSharedResource<SharpDX.Direct3D11.Resource>(handle);
            var texture = resource.QueryInterface<SharpDX.Direct3D11.Texture2D>();
            return texture;
        }

        private static SharpDX.Direct3D9.PresentParameters GetD3D9PresentParameters(IntPtr windowHandle)
        {
            var presentParams = new SharpDX.Direct3D9.PresentParameters
            {
                Windowed = true,
                SwapEffect = SharpDX.Direct3D9.SwapEffect.Discard,
                DeviceWindowHandle = windowHandle,
                PresentationInterval = SharpDX.Direct3D9.PresentInterval.Default
            };

            return presentParams;
        }

        private Int32Rect SafeRect(Int32Rect rect)
        {
            rect.Width = Math.Min(_d3dImage.PixelWidth, rect.Width + rect.X) - rect.X;
            rect.Height = Math.Min(_d3dImage.PixelHeight, rect.Height + rect.Y) - rect.Y;
            return rect;
        }

        private static SharpDX.Direct3D9.Format DXGIToD3D9(SharpDX.DXGI.Format format)
        {
            switch (format)
            {
                case SharpDX.DXGI.Format.R10G10B10A2_UNorm:
                    return SharpDX.Direct3D9.Format.A2B10G10R10;
                case SharpDX.DXGI.Format.R16G16B16A16_Float:
                    return SharpDX.Direct3D9.Format.A16B16G16R16F;
                case SharpDX.DXGI.Format.B8G8R8A8_UNorm:
                    return SharpDX.Direct3D9.Format.A8R8G8B8;
                default:
                    return SharpDX.Direct3D9.Format.Unknown;
            }
        }
    }
}
```

Testing machines:

- Windows 10 (1903) x64 (on 4 different devices)
- Screen resolutions: 1920×1080, 2560×1080, 3840×2160
- Cef on Chromium version 75.0

**Comment by walterlv** [comment] 2019-10-23 01:53
This is the `chrome://gpu/` results in CefSharp.Wpf and in Chrome:

![image](https://user-images.githubusercontent.com/9959623/67349584-ea771a00-f57a-11e9-9bb1-673424c8f628.png)

**Comment by amaitland** [comment] 2019-10-23 02:18
Closing as duplicate of #2675

**Closed by amaitland** 2019-10-23 02:18 UTC

**Comment by amaitland** [comment] 2019-10-23 02:21
As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report please fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an complete example. 

We can then continue the conversation over at #2675 thanks
