### ISSUE TITLE
Visual Studio crashing while using WinForms component

### ISSUE THREAD

**Issue by piotrszpruta** [cefsharp/CefSharp#4148] opened 2022-06-26 10:01 UTC
- **What version of the product are you using?**
   102.0.100

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .Net5.0
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
   1. Create new WinForms .Net5.0 project
   2. Add nuget package (CefSharp.WinForms.NETCore)
   3. Add TabPage to Form, and into tabPage2 put ChromiumWebBrowser component.
   4. Switch from tabPage1 to tabPage2
   5. Visual Studio crashes without any error.

- **What is the expected output? What do you see instead?**
   Show tabPage2 contents and allow to add more buttons etc.

- **Please provide any additional information below.**
  I don't see any logs releated with CefSharp (debug.log in bin folder), I don't quite know where to find visual studio logs.

- **Does this problem also occur in the `CEF` Sample Application**
   No, it's problem inside designer.

Minimal example: [link](https://github.com/piotrszpruta/CefSharp-Reproduction)

**Comment by amaitland** [comment] 2022-06-26 19:10
The new OOP designer is not yet supported. Adding support is being tracked with #4019

> Visual Studio crashes without any error.

What version of visual studio are you using? Usually there will be an error in the event log. 

Closing as duplicate of #4019

**Closed by amaitland** 2022-06-26 19:10 UTC

**Comment by amaitland** [comment] 2022-06-27 00:29
As you are seeing a hard crash then it's probably worth raising that with `Microsoft`, event if there is a problem with the `CefSharp` designer implementation then `VS` should handle that gracefully, specially as the designer is run out of process.

https://github.com/dotnet/winforms/discussions/6758#discussioncomment-2270412

**Comment by piotrszpruta** [comment] 2022-06-28 11:02
Okay, I collected some logs from Event Viewer. I don't know if they will be usefull but there u go :) I can't attach logs in xml format or evxt. Does any google drive or something is fine?

```
Application: devenv.exe Architecture version: v4.0.30319 Opis: proces został 
przerwany z powodu nieobsłużonego wyjątku. Information about exception: 
Microsoft.DotNet.DesignTools.Client.DesignToolsServerException Information about exception: Microsoft.DotNet.DesignTools.Client.DesignToolsServerException w 
Microsoft.DotNet.DesignTools.Client.DesignToolsClient+&lt;SendRequestAsync&gt;d__49`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b77a5c561934e089]].MoveNext() w 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() w 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) 
w Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() w 
Microsoft.VisualStudio.Threading.JoinableTask`1[[System.__Canon, mscorlib, 
Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=b77a5c561934e089]].CompleteOnCurrentThread() w 
Microsoft.DotNet.DesignTools.Protocol.Endpoints.DesignToolsEndpoints+InputImpl.InputMessage(Microsoft.DotNet.DesignTools.Protocol.SessionId, 
UInt32, UIntPtr, IntPtr, System.Drawing.Point, System.Windows.Forms.Keys, 
IntPtr, System.Nullable`1&lt;Boolean&gt;) w 
Microsoft.DotNet.DesignTools.Client.Designers.InputShield.ProcessMessage(WindowMessage, 
System.Drawing.Point, UIntPtr, IntPtr, Boolean) w 
Microsoft.DotNet.DesignTools.Client.Designers.InputShield.WndProc(System.Windows.Forms.Message 
ByRef) w System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, 
IntPtr, IntPtr)
```

**Comment by amaitland** [comment] 2022-06-28 19:19
As the error originates from the WinForms designer you'll need to report the problem to Microsoft. If you open an issue please post a link on #4019
