### ISSUE TITLE
Incorrect DownloadItem.FullPath provided by IDownloadHandler.OnDownloadUpdated

### ISSUE THREAD

**Issue by lorantamplan** [cefsharp/CefSharp#2011] opened 2017-04-07 15:17 UTC
- **What version of the product are you using?** 
Visual C# 2015 with Nuget - CefSharp 55.0 & cef 3.2883.1552 : 
    - cef.redist.x64.3.2883.1552
    - CefSharp.Common.55.0.0
    - CefSharp.WinForms.55.0.0
- **What architecture x86 or x64?** 
x64
- **On what operating system?** 
Windows 7 Pro
- **Are you using `WinForms`, `WPF` or `OffScreen`?** 
WinForms

- **What steps will reproduce the problem?**
Create a C# application with an **IDownloadHandler** implementation in order to display - for each download - its file name and download progress. 
Keep the default dialog from the OnBeforeDownload callback. 
Now when starting a download, the default dialog is displayed and asks for a file destination. Here, choose to overwrite an existing file on your computer (let's call it "**E:\MyFile.txt**").

- **What is the expected output? What do you see instead?**
The **DownloadItem.FullPath** property provided by the **OnDownloadUpdated** method should point to the chosen destination file (i.e. "**E:\MyFile.txt**").
Instead, it points to a virtual "**E:\MyFile (1).txt**" file all along the download process. It is only changed to the correct expected file path when the file download is complete.

- **Please provide any additional information below.**
This issue only happens if I chose to override an existing file. Other use cases seem to work properly.
No error message.
Nothing relevant into the debug.log file.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
I could not reproduce the issue with the Sample application, since I did not find any sample of a download progress window in this application.

**Comment by amaitland** [comment] 2017-04-07 21:03
Try the new 57.0.0-pre01 release, if you can reproduce the problem then you'll have to raise the issue on the CEF issue tracker.  CefSharp is just a wrapper.

**Comment by amaitland** [comment] 2017-04-16 09:22
> The DownloadItem.FullPath property provided by the OnDownloadUpdated method should point to the chosen destination file (i.e. "E:\MyFile.txt").
> Instead, it points to a virtual "E:\MyFile (1).txt" file all along the download process. It is only changed to the correct expected file path when the file download is complete.

Re-reading this, and I think what your seeing is likely by design. Both `Chrome` and `FireFox` download to a temp file. Perhaps the naming could be more meaning full.

Anyway, post your findings on http://magpcss.org/ceforum/index.php and ask for comment. Ideally posting a link here for others as a reference.

Closing this for now, if it turns out `CefSharp` changes are required we can reopen this later.

**Closed by amaitland** 2017-04-16 09:22 UTC
Labels: upstream
