### ISSUE TITLE
WPF - Selecting text continuing below the visible area does not scroll

### ISSUE THREAD

**Issue by mol** [cefsharp/CefSharp#2870] opened 2019-08-21 14:32 UTC
- **What version of the product are you using?**
76.1.90.0, but it's also tested to occur in 74.1.130.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Hold the left mouse button to start selecting text on the default "Getting started" page of the WPF example and move the cursor to the bottom of the screen, expecting scrolling to follow automatically, but it only scrolls a tiny bit and then stops.

- **What is the expected output? What do you see instead?**
The browser should scroll automatically to keep being able to select text without having to scroll manually.

- **Please provide any additional information below.**
Setting `settings.CefCommandLineArgs.Add("disable-threaded-scrolling", "1");` seems to initally fix the issue, but after selecting text a few more times, triggering the auto scroll, the auto scroll suddenly stops working - and any subsequent attempts will not scroll.
The debug.log file does not appear to have any relevant information.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No, the sample application works properly.

**Comment by amaitland** [comment] 2019-08-23 00:09
> * Hold the left mouse button to start selecting text on the default "Getting started" page of the WPF example and move the cursor to the bottom of the screen, expecting scrolling to follow automatically, but it only scrolls a tiny bit and then stops.

As you've discovered if the mouse leaves the bounds of the `Control` then the mouse will be released. Same as dragging the scroll bar, improving that behaviour is tracked by #2258

**Comment by amaitland** [comment] 2019-09-06 01:30
Closing as duplicate of #2258 (there are other issues that link to that one, it's really all the same thing).

**Closed by amaitland** 2019-09-06 01:30 UTC
Labels: pr-available, wpf
