### ISSUE TITLE
WPF - remote debugging js error

### ISSUE THREAD

**Issue by leonidfingergut** [cefsharp/CefSharp#4220] opened 2022-08-18 11:17 UTC
- **What version of the product are you using?**
    - v104.4.180
    - What version are you using? Nuget - CefSharp.Wpf 104.4.180 .NET Framework 4.5.2

- **What architecture x86 or x64?**
    x86
	
- **What version of .Net?**
    .NET Framework 4.5.2
    
- **On what operating system?**
    Win2012 R2

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
   I defined remote debug port (7999). I open in browser localhost:7999. I see page and click on link. After this I see white page. At console I see error:
   root.js:1 Uncaught SyntaxError: Unexpected token '?'.
Before I use 73.1.130.0 and it work good.
![PAGE](https://user-images.githubusercontent.com/39103047/185382401-46f4cf5c-d3fd-4112-93f9-b2ddbca2f49b.PNG)
![ERROR](https://user-images.githubusercontent.com/39103047/185382395-ccf67c01-85a0-406d-9a1e-b08a4f1ee45e.PNG)

**Comment by amaitland** [comment] 2022-08-19 00:18
> - **Does this problem also occur in the `CEF` Sample Application**
    - Download one of the following:
    - For x86 download   https://cef-builds.spotifycdn.com/cef_binary_104.4.18%2Bg2587cf2%2Bchromium-104.0.5112.81_windows32_client.tar.bz2
    - For x64 download   https://cef-builds.spotifycdn.com/cef_binary_104.4.18%2Bg2587cf2%2Bchromium-104.0.5112.81_windows64_client.tar.bz2
	- For arm64 download https://cef-builds.spotifycdn.com/cef_binary_104.4.18%2Bg2587cf2%2Bchromium-104.0.5112.81_windowsarm64_client.tar.bz2
	- Extract and run cefclient.exe
		- If you are using WPF/OffScreen run
		```
		cefclient.exe --multi-threaded-message-loop --no-sandbox --off-screen-rendering-enabled --enable-gpu
		```
		- If you are using WinForms run
		```
		cefclient.exe --multi-threaded-message-loop --no-sandbox
		```
	- **MAKE SURE TO TEST WITH THE COMMAND LINE ARGS LISTED ABOVE**
    - If you can reproduce the problem with `cefclient` then please report the issue on https://bitbucket.org/chromiumembedded/cef/overview (Make sure you search before opening an issue). If you open an issue here it will most likely be closed as `upstream` as the bug needs to be fixed in `CEF`.

You seem to have skipped over this section of the bug report, please test with the `CEF Sample application`. Use the `remote-debugging-port` command line arg in addition to those above.

**Comment by amaitland** [comment] 2022-08-21 01:41
Testing with `cefclient` and https://github.com/cefsharp/CefSharp.MinimalExample I don't see any remote debugging JavaScript errors loading google.com

As `remote debugging` is entirely implemented at the `CEF/Chromium` level this is unlikely a bug in `CefSharp`.

> * Before I use 73.1.130.0 and it work good.

Make sure you perform a clean checkout after upgrading, the dependencies have changed a lot.

**Comment by amaitland** [comment] 2022-08-28 19:54
Closing as unable to reproduce.

**Closed by amaitland** 2022-08-28 19:54 UTC
Labels: more-details-needed-from-op, unable-to-reproduce
