### ISSUE TITLE
BrowserSubprocess crash

### ISSUE THREAD

**Issue by MagicWang** [cefsharp/CefSharp#1348] opened 2015-10-19 11:45 UTC
#### Issue Summary
I'm using cefsharp version 43 with wpf run on win7.Sometimes i get a out of memory error,then the browsersubprocess closed,and main process crash.

[1019/135720:FATAL:memory.cc(18)] Out of memory. size=4194304

#### Technical details
* CefSharp Version: 43
* Operating System: windows 7
* x86: 
* WPF

**Comment by amaitland** [comment] 2015-10-19 22:07
What are the steps to reproduce? Do you have a code example?

**Comment by MagicWang** [comment] 2015-10-20 01:38
This appears occasionally,long after the application is running.I cannot find steps to reproduce.
My Cef Init like this

var cefPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Sdk\Cef");
            CefSharp.CefSettings settings = new CefSharp.CefSettings();
            settings.LocalesDirPath = System.IO.Path.Combine(cefPath, "locales");
            settings.Locale = "zh-CN";
            settings.CachePath = System.IO.Path.Combine(cefPath, "cache");
            settings.LogFile = System.IO.Path.Combine(cefPath, "Log.txt");
            settings.LogSeverity = CefSharp.LogSeverity.Error;
            settings.BrowserSubprocessPath = System.IO.Path.Combine(cefPath, "CefSharp.BrowserSubprocess.exe");
            CefSharp.Cef.Initialize(settings);

**Comment by amaitland** [comment] 2015-10-20 02:07
Are you using `Javascript Binding`? If you don't then you can try removing the `process-per-tab` command line option and disable `WCF`.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/CefSettings.h#L37
https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L43

> I have seen this.if v8 engine cause this,how can i handle it?

`CEF` only provides the `OnRenderProcessTerminated` handler, if that's not being called and the app is just crashing then it will likely have to be resolved in `CEF` as `CefSharp` is just a wrapper. For it to be resolved in `CEF` then you'd need to provide a detailed stack trace and potentially a way to reproduce the problem. You can download the **release** symbols from `cefbuilds.com` for the matching version your using.

**Comment by MagicWang** [comment] 2015-10-20 05:37
I have use Javascript Binding.
When i manual kill the browsersubprocess, OnRenderProcessTerminated raised.I want to refresh webbrowser in event handler,but not work.
I have try  Load and Reload method,neither work.

**Comment by amaitland** [comment] 2015-10-20 05:42
> I want to refresh webbrowser in event handler,but not work.

What event handler? What method are you calling?

**Comment by MagicWang** [comment] 2015-10-20 05:43
void IRequestHandler.OnRenderProcessTerminated(IWebBrowser browserControl, IBrowser browser, CefTerminationStatus status)
        {
            // TODO: Add your own code here for handling scenarios where the Render Process terminated for one reason or another.
            browserControl.Reload();
        }

**Comment by amaitland** [comment] 2015-10-20 06:32
I don't believe `Reload` in `OnRenderProcessTerminated` triggers spawning of a new `Render Process`. You'd likely have to load a `URL`.

**Comment by MagicWang** [comment] 2015-10-20 06:43
In fact,it does.browserControl.Load(url) perform the same as browserControl.Reload().When i reload the view,It works.
browserControl.Reload();
                var c = browserControl as CefSharp.Wpf.ChromiumWebBrowser;
                if (c != null)
                {
                    c.Visibility = System.Windows.Visibility.Hidden;
                    c.Visibility = System.Windows.Visibility.Visible;
                }

**Comment by amaitland** [comment] 2015-10-20 06:49
There were known problems, looks like it's been resolved.

https://bitbucket.org/chromiumembedded/cef/issues/1429/crash-when-calling-loadurl-or-reload-via

**Comment by MagicWang** [comment] 2015-10-21 06:24
Hi amaitland.I have find a Issues same to me.
https://bitbucket.org/xilium/xilium.cefglue/issues/122/crash-when-large-images-loaded-in-browser
Is the wrapper go wrong?

**Comment by amaitland** [comment] 2015-10-21 06:31
Possibly an issue with `CEF` it's self?

http://magpcss.org/ceforum/viewtopic.php?f=6&t=13521

Short term is switching to `x64` an option for you?

**Comment by MagicWang** [comment] 2015-10-21 06:35
No.i cannot switching to x64.But browsing to the same test.html in x86 client app for CEF itself (not Xilium) works without issues.I have test.

**Comment by amaitland** [comment] 2015-10-21 06:40
> But browsing to the same test.html in x86 client app for CEF itself (not Xilium) works without issues.

Using version `3.2357.1287`?

If you can provide a link to your test that may also be helpful.

**Comment by MagicWang** [comment] 2015-10-21 06:47
I download branch 2357 windows 32bit TestApp from https://cefbuilds.com/.
Test url is https://bitbucket.org/xilium/xilium.cefglue/issues/attachments/122/xilium/xilium.cefglue/1443103104.73/122/test.html

**Comment by amaitland** [comment] 2015-10-21 07:29
Thanks for confirming :+1: I can reproduce the problem.

Personally I don't have time to look into this any further. Fact that it reproduces in `CefGlue` is interesting. You can try memory profile the `BrowserSubProcess`, see what's happening. Downloading the `release symbols` and seeing if the callstack says anything is probably a good place to start.

**Comment by MagicWang** [comment] 2015-10-21 07:45
Ok,i will try it,thank you very much.if i have get something usefull ,i will feedback to you.

**Comment by xiangwan** [comment] 2015-12-11 07:09
( ▼-▼ ) please fix it.

**Comment by amaitland** [comment] 2016-01-11 02:35
@xiangwan Fastest way to resolve this problem is to debug it yourself and contribute a `PR`.

**Comment by amaitland** [comment] 2016-03-22 12:14
One way to resolve this is using `LARGEADDRESSAWARE` 

https://msdn.microsoft.com/en-us/library/wz223b1z%28v=vs.120%29.aspx
http://stackoverflow.com/a/3963184/4583726

Post build task
```
call "$(VS120COMNTOOLS)..\tools\vsvars32.bat"
editbin /largeaddressaware $(TargetPath)
```

**Closed** 2016-03-22 22:31 UTC

**Comment by MagicWang** [comment] 2016-03-23 08:37
:+1: Great work,it works fine now.

**Comment by rajeevshuklaciti** [comment] 2016-08-11 10:07
The error "A breakpoint has been reached" is still coming for me although i had already set largeaddressaware attribute as per given instruction described in https://github.com/cefsharp/CefSharp/commit/67e34d2fcd6a3d0e109e03c2d8dcef3f585cb6e9.

Its not a consistently reproducible issue for me but it is occurring many times in Production.

Could you please help me on this?
Many thanks in advance.
