### ISSUE TITLE
Crash when adding Facebook login button in BindingTest.html

### ISSUE THREAD

**Issue by duboi381** [cefsharp/CefSharp#1317] opened 2015-10-08 15:32 UTC
<H4>Issue Summary</H4>

What is the expected output? What do you see instead?

Expected: We should be able to use BoundObject without crash
Observation: Application crashed

<H4>Technical details</H4>

Version: Chromium: 43.0.2357.130, CEF: r3.2357.1287.g861c26e, CefSharp: 43.0.0.0
Windows 7
x86
WinForms *.Net framework :4.5

<H4>Steps to Reproduce</H4>

1- Add a facebook login button in BindingTest.html
<pre><code>&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;Binding Test&lt;/title&gt;
    &lt;/head&gt;
![step_to_reproduce](https://cloud.githubusercontent.com/assets/12235562/10370605/a9852996-6dad-11e5-8d05-ff397fad9283.gif)

    &lt;body&gt;
        &lt;div id="fb-root"&gt;&lt;/div&gt;
        &lt;script&gt;
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];

            if (!d.getElementById(id)) {
                js = d.createElement(s);
                js.id = id;
                js.src = "http://connect.facebook.net/en_US/all.js";
                fjs.parentNode.insertBefore(js, fjs);
            }
        }(document, "script", "facebook-jssdk"));
        
        window.fbAsyncInit = function () {
            FB.init({
                version: "v2.5",
                appId: "160468374291578"
            });
        };
        &lt;/script&gt;
        &lt;input id="customFbBtn" type="button" onclick='FB.login(function(response){});' value="Sign in with Facebook"&gt;&lt;/input&gt;</code></pre>
2- Run CefSharp.WinForms.Example
3- Change url to "custom://cefsharp/BindingTest.html"
4- Click the "Test Callback" button

![step_to_reproduce](https://cloud.githubusercontent.com/assets/12235562/10370624/bc6a2386-6dad-11e5-8203-3ed33ed23af1.gif)

<H4>Additional Information</H4>
If I try to reproduce with AsyncBoundObject function in a button, the application will not crash, but the "then" callback will never be called<br>
If I try to reproduce with Chromium 45 3.2454.1326, with pre-release CefSharp.Common/CefSharp.WinForm .45.0.0-CI1495, this will also crash<br>
If I try to reproduce with the cefsharp/41 branch using the same BindingTest.html, it will <b>NOT</b> crash, and you will get the result of the callback

**Comment by amaitland** [comment] 2015-10-08 21:15
Does `Debug.log` provide anything useful? (It'll be in the same directory as the executing application).

**Comment by illfang** [comment] 2015-10-09 04:12
Might be caused by the same problem as #1315 as it shows the same behaviour as this issue.

**Comment by duboi381** [comment] 2015-10-09 12:14
I was not able to attach debug.log, but I don't think there is any usefull information in this

**Comment by amaitland** [comment] 2015-10-17 02:39
Changes merged into `43` branch, hopefully release `43.0.1` shortly (just needs more testing).

**Closed by amaitland** 2015-10-17 02:39 UTC

**Comment by amaitland** [comment] 2015-10-29 22:19
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details
