### ISSUE TITLE
IJavascriptCallback.ExecuteAsync with DateTime as param produces incorrect JavaScript Date

### ISSUE THREAD

**Issue by kurtzky** [cefsharp/CefSharp#2662] opened 2019-02-25 11:01 UTC
- **What version of the product are you using?**
    - 69.0.0

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
These are just code snippets that show the overall design of the code.

**Class1.cs**
```
private ChromiumWebBrowser webBrowser;
private WebInterface webInterface;

private void CreateCef()
{
	webBrowser = new ChromiumWebBrowser();
	webInterface = new WebInterface(webBrowser);
	webBrowser.RegisterAsyncJsObject("webInterface", webInterface);	
}

//This will be called whenever we receive data from server
private void OnNotificationReceived(DateTime value)
{
	webInterface.InvokeNotification(value);
}

```

**WebInterface.cs**
```
private readonly ChromiumWebBrowser WebBrowser;
private IJavascriptCallback Callback;

public WebInterface(ChromiumWebBrowser browser) 
{
	WebBrowser = browser;
}

public void SubscribeEvent(IJavascriptCallback onCallback)
{
	Callback = onCallback;
}

public void InvokeNotification(object data)
{
	Callback?.ExecuteAsync(data); //data sent is 01/01/2018 12:00:00
}
```

**JsInterface.ts**
```
export class JsInterface {
	public OnNotify: (data: any) => void;
	
	constructor() {
	}

	public Initialize(): void {
		webInterface.SubscribeEvent((data) => {
            		if (this.OnNotify != null) {
                		this.OnNotify(data);
            		}
        	});
	}
}
```

**MainUi.ts**

```
//this is the Javascript side that receives data from server
export class MainUi {
	private _userInterfaceInstance: any;

	constructor() {
    	}

	public Initialize()
	{
		this._userInterfaceInstance = new JsInterface();
	        this._userInterfaceInstance.Initialize();
		this._userInterfaceInstance.OnNotify = OnCallback;
	}

	function OnCallback(data: any): void {
		 //data received is 01/01/2018 12:00:25
	}
}

```
- **What is the expected output? What do you see instead?**
Expected: 01/01/2018 12:00:00
Output: 01/01/2018 12:00:25

Please note that the extra seconds added is consistent at 25 seconds. For example, if my server time is 01/01/2018 12:01:59, the JavaScript receives 01/01/2018 12:02:24

**Comment by amaitland** [comment] 2019-02-25 12:05
For reference the conversion is https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/Serialization/V8Serialization.cpp#L184

One suggestion is we need to use `UTC` time to get a consistent result.

https://stackoverflow.com/questions/7227278/net-datetime-to-time-t-in-seconds/48500008#48500008

**Comment by amaitland** [comment] 2019-02-25 12:09
A `QUnit` test that reproduces the current problem will need to be added

- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/JavascriptBinding/BoundObject.cs#L56
- https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Resources/BindingTest.html#L442

**Comment by kurtzky** [comment] 2019-03-18 05:32
I tested the fix using the latest 71.0.2 release and below are the results. The outputs are the raw values received by my JavaScript callback.

**Correct**

Input: 19/6/2017 12:00:00 AM
Output: Mon Jun 19 2017 00:00:00 GMT+0800 (Singapore Standard Time)

Input: 16/1/1985 12:00:00 AM
Output: Wed Jan 16 1985 00:00:00 GMT+0800 (Singapore Standard Time)

**Wrong**

Input: 1/1/1900 12:00:00 AM
Output: Sun Dec 31 1899 22:55:25 GMT+0655 (Singapore Standard Time)

Input: 24/6/1904 12:00:00 AM
Output: Thu Jun 23 1904 22:55:25 GMT+0655 (Singapore Standard Time)

Input: 20/6/1970 12:00:00 AM
Output: Fri Jun 19 1970 23:30:00 GMT+0730 (Singapore Standard Time)

**Comment by amaitland** [comment] 2019-03-18 09:21
You will need to provide a QUnit test as outlined above.

**Comment by amaitland** [comment] 2019-04-02 11:39
@kurtzky Any further details you can provide? The `QUnit` tests pass as expected for me.

Did you try running the tests on your local machine?

**Comment by kurtzky** [comment] 2019-04-02 11:46
@amaitland Yes, I run the tests on my local machine with regional settings set to Singapore. I added those QUnit tests on the sample solution and they fail on my side.

**Comment by amaitland** [comment] 2019-04-10 22:31
@kurtzky You can try modifying `ConvertDateTimeToCefTime` to the below then rerun the tests. Basically `CEF` expects time in `UTC` which we're doing as of https://github.com/cefsharp/CefSharp/commit/72ee102bcf67c2ec293c5ab0e98044d83c3bb65f. The change below changes how the date is constructed. 

```c++
CefTime ConvertDateTimeToCefTime(DateTime dateTime)
{
	auto utc = dateTime.ToUniversalTime();
	cef_time_t time;
	time.year = utc.Year;
	time.month = utc.Month;
	time.day_of_month = utc.Day;

	time.hour = utc.Hour;
	time.minute = utc.Minute;
	time.second = utc.Second;
	time.millisecond = utc.Millisecond;

	return CefTime(time);
}
```

If that doesn't work then I have no idea.

**Comment by kurtzky** [comment] 2019-04-11 01:48
@amaitland Thanks for the help. Unfortunately, the code above yields these results:

- Debug x86 - 2 Failed Tests (1900, 1970)
- Debug x64 - 4 Failed Tests (all DateTime callbacks)
- Release x86 - 3 Failed Tests (1900, 1970, 1985)
- Release x64 - 4 Failed Tests (all DateTime callbacks)

Whereas the original code gives consistent failed tests (1900 and 1970) across all platforms. I don't know what's wrong with my local machine, but perhaps I'd consider this a machine-specific problem.

**Comment by amaitland** [comment] 2020-02-21 07:24
Closing as I'm unable to reproduce and have had no further reports. 

The date is passed in as UTC as specified by the documentation.

**Closed by amaitland** 2020-02-21 07:24 UTC
Labels: bug
