### ISSUE TITLE
Silverlight Website not working in CEFSharp

### ISSUE THREAD

**Issue by blauzon** [cefsharp/CefSharp#467] opened 2014-09-08 17:55 UTC
Hello,

We have completed the integration in our WPF application and silverlight website are not working in the broswer. 

The browser always display the "Install Microsoft Silverlight" Icon.

Microsoft Silverlight (5.1.30514.0) is already installed...

We use NuGet for the reference:
...?xml version="1.0" encoding="utf-8"?>
...packages>
  ...package id="cef.redist" version="3.1650.1562-pre3" targetFramework="net45" />
  ...package id="CefSharp.Common" version="31.0.0-pre1" targetFramework="net45" />
  ...package id="CefSharp.Wpf" version="31.0.0-pre1" targetFramework="net45" />
...packages>

I have the exact error with the CefSharp.WPF.Example

![error001](https://cloud.githubusercontent.com/assets/8699171/4189983/5b34c174-3781-11e4-882c-3f26274b4c96.png)

**Comment by perlun** [comment] 2015-05-12 12:04
I am seeing this now also. It's **extremely** frustrating, since we use the Silverlight support in our app framework to able to bridge the gap between WPF and Silverlight.

My research so far:

1. Add the `debug-plugin-loading` parameter: 

        var settings = new CefSettings();
        settings.CefCommandLineArgs.Add("debug-plugin-loading", "debug-plugin-loading");
        Cef.Initialize(settings);

2. Look at the logs. On the first page load, it says this:

```
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin C:\Users\plundberg\AppData\Roaming\Mozilla\plugins\npagee.dll
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin C:\Users\plundberg\AppData\Roaming\Mozilla\plugins\npagee64.dll
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin C:\Program Files\Citrix\Secure Access Client\npagee64.dll
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin C:\Program Files\Java\jre7\bin\dtplugin\npDeployJava1.dll
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin C:\Program Files\Java\jre7\bin\plugin2\npjp2.dll
[0512/145129:ERROR:plugin_list.cc(215)] Loading plugin c:\Program Files\Microsoft Silverlight\5.1.30514.0\npctrl.dll
[0512/145159:WARNING:webplugin_delegate_proxy.cc(377)] PluginMsg_Init returned false
````

The `PluginMsg_Init returned false` is probably the key here.

If I reload, I get a similar list but this time it doesn't give the `PluginMsg_Init` thing.

I also tried to enable the `enable-npapi` and `debug-plugin-loading`, but it hasn't helped me thus far.

**Comment by perlun** [comment] 2015-05-12 12:07
Enabling verbose logging gave one more error, but nothing more than that:

```
[0512/150645:ERROR:plugin_list.cc(215)] Loading plugin c:\Program Files\Microsoft Silverlight\5.1.30514.0\npctrl.dll
[0512/150651:VERBOSE1:webplugin_delegate_impl.cc(84)] Couldn't start plug-in instance
[0512/150651:WARNING:webplugin_delegate_proxy.cc(377)] PluginMsg_Init returned false
```

I think we almost have to dig into the CEF/Chromium source code to get this nailed down unfortunately...

**Comment by amaitland** [comment] 2015-05-12 12:30
From memory `Silverlight` was working fine with `cefclient`, so I think we're missing something, was just never able to identify exactly what that was.

**Comment by amaitland** [comment] 2015-06-09 10:15
@perlun Did you manage to find out any additional info?

**Comment by perlun** [comment] 2015-08-03 05:38
Don't remember exactly how we managed to solve this in the end. :smiley: It could be that we had to rely on an older version (based on CefSharp 1) to avoid it.

**Comment by amaitland** [comment] 2015-08-03 05:47
Fair enough :smile: As `45` removes `NPAPI` support, it's likely `Silverlight` will become a thing of the past in the not too distant future.

**Comment by perlun** [comment] 2015-08-03 06:18
Yes, for better and worse. We still have a number of existing apps using it so I'm not too happy of them pulling the plug for it already. But for the Internet at large, it's probably better if it goes away; HTML5 supersedes it to a certain extent anyway.

**Comment by MartySVK** [comment] 2015-10-12 09:51
But it would be great to resolve this problem, because many developers will have to freeze on version 43, because of NPAPI

**Comment by amaitland** [comment] 2015-10-12 09:54
> But it would be great to resolve this problem, because many developers will have to freeze on version 43, because of NPAPI

Your welcome to investigate further. I've tried without success.

**Comment by MartySVK** [comment] 2015-10-12 10:21
> Your welcome to investigate further. I've tried without success.

any idea where to start ?

**Comment by amaitland** [comment] 2015-10-12 10:37
I wasn't able to reproduce the problem using `cefclient --off-screen-rendering-enabled` as per https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

So my guess is there's something missing in our `OSR` implementation. The `OSR` rendering code is contained within `RenderClientAdapter`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/Internals/RenderClientAdapter.h

For `cefclient`, the class which holds a large portion of the `OSR` code is
https://bitbucket.org/chromiumembedded/cef/src/47e6d4bf84444eb6cb4d4509231a8c9ee878a584/tests/cefclient/browser/osr_window_win.cc?at=2357&fileviewer=file-view-default

Try enabling some of the plugin debugging command line options as above.

The fact that it works after a browser refresh suggests some piece of information isn't available when it's needed to do the initial load.

**Comment by MartySVK** [comment] 2015-10-12 11:10
Do you have this problem only with wpf ?
Because I can not run plugins like Shockwave for Director or Silverlight in winforms too.

**Comment by amaitland** [comment] 2015-10-12 11:13
> Do you have this problem only with wpf ?
> Because I can not run plugins like Shockwave for Director or Silverlight in winforms too.

Yes, only `WPF`. If your using `43.0.0` then you have to enable `NPAPI` to get `Silverlight` to load.

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Example/CefExample.cs#L54

**Comment by amaitland** [comment] 2015-10-12 11:17
Looks like the problem reproduces in `WinForms` with version `43.0.0`. From memory it worked fine in `41`.

**Comment by MartySVK** [comment] 2015-10-12 11:25
> Yes, only WPF. If your using 43.0.0 then you have to enable NPAPI to get Silverlight to load.

I did, but it does not help, another plugins (Unity, flash, VLC ) is working great, but these two not.
I also tried your minimal example with 41, but the same error.

**Comment by amaitland** [comment] 2015-10-12 11:34
> I did, but it does not help, another plugins (Unity, flash, VLC ) is working great, but these two not.
> I also tried your minimal example with 41, but the same error.

I guess something has changed.

**Comment by MartySVK** [comment] 2015-10-12 11:49
I also tried to install old version of Silverlight, but the same error

**Comment by shaunsphere** [comment] 2015-11-17 15:15
enable-npapi  -- > Silverlight works for my cefsharp.winform but need to refresh or open second page.
Anyone know how to fix ?
Thanks

**Comment by amaitland** [comment] 2015-11-17 20:05
> Anyone know how to fix ?

There is no known fix for this.

**Comment by amaitland** [comment] 2016-02-02 00:26
As there is no fix for this and `NPAPI` support has been removed effectively removing support for `Silverlight` I'm closing this.

If someone comes up with a solution then feel free to post your answer.

Please no more `How do I fix this?` or `When will this be fixed?` questions.

**Closed by amaitland** 2016-02-02 00:26 UTC
Labels: cef3
