### ISSUE TITLE
tooltip for title-attribute sometimes rendered wrong

### ISSUE THREAD

**Issue by ray007** [cefsharp/CefSharp#2569] opened 2018-11-16 09:52 UTC
- **What version of the product are you using?**
    - v67 compiled with proprietary codec support

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win10, not sure about other windows versions

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**

I'm using the title-attribute to show errors of the application:

![image](https://user-images.githubusercontent.com/126712/48613694-caaf9d00-e98c-11e8-82ad-ba485e7a2fea.png)

This is fine most of the time.
In my single-window application which contains only 1 WebView, there never is a problem.
But my view is also used as plugin to be show in a tab in another larger application, and there the initial rendering is sometimes a bit different:

![image](https://user-images.githubusercontent.com/126712/48613851-1eba8180-e98d-11e8-965e-e8919615ea9c.png)

After moving the mouse out of the window and back in, render there is also fine.

Any idea what could have gone wrong here and if there's a way to fix it on my side?

**Comment by amaitland** [comment] 2018-11-19 04:11
`CefSharp` is built using [GitLink](https://github.com/GitTools/GitLink/blob/develop/README.md), you can step into the source code to get a better understanding of what's going on. Once you've stepped into `ChromiumWebBrowser` you can add breakpoints wherever you like.

Tooltips are provided as straight text from `CEF` and rendered in an actual `WPF` tooltip, see https://github.com/cefsharp/CefSharp/blob/cefsharp/67/CefSharp.Wpf/ChromiumWebBrowser.cs#L925

I'll leave this open for a little while, will likely be closed as unable to reproduce.

**Comment by amaitland** [comment] 2018-12-01 22:30
Closing as unable to reproduce, if you can provide a code example that reproduces the problem then this can be reopened.

**Closed by amaitland** 2018-12-01 22:30 UTC
Labels: unable-to-reproduce, wpf
