### ISSUE TITLE
Bug in CefSharp.Common.NETCore.targets

### ISSUE THREAD

**Issue by augustunbear** [cefsharp/CefSharp#4245] opened 2022-09-15 12:16 UTC
https://github.com/cefsharp/CefSharp/blob/master/NuGet/PackageReference/CefSharp.Common.NETCore.targets#:~:text=%3C/Content%3E-,%3CContent%20Include%3D%22%24(MSBuildThisFileDirectory)..%5Cruntimes%5Cwin%2Dx64%5Clib%5Cnetcoreapp3.1,%3C/Content%3E,-%3CContent%20Include%3D%22%40(CefRuntimeWinArm64Locales

In this place, it should be "<Link>runtimes\win-x64\lib\%(RecursiveDir)%(FileName)%(Extension)</Link>" instead of "<Link>runtimes\win-x64\native\%(RecursiveDir)%(FileName)%(Extension)</Link>" for CefSharp.dll and Ijwhost.dll.

**Comment by amaitland** [comment] 2022-09-15 19:27
> In this place, it should be "runtimes\win-x64\lib%(RecursiveDir)%(FileName)%(Extension)" instead of "runtimes\win-x64\native%(RecursiveDir)%(FileName)%(Extension)" for CefSharp.dll and Ijwhost.dll.

Please explain the reason you think it should be changed. What problem are you seeing and how do you reproduce that problem? 

From memory those files are required in the native folder for the browsersubprocess.

**Comment by augustunbear** [comment] 2022-09-16 08:31
I have just tested in my application. It's a simple .Net 6 WinForms project with CEF webbrowser control. 

![image](https://user-images.githubusercontent.com/5863951/190593800-d68d3517-e32c-456b-9ccc-2fc8b1910cb2.png)

If I deploy this project, CefSharp.dll and Ijwhost.dll are not inside runtimes\win-x64\lib folder, the application will crash. If I copy both dlls from native to lib, then it works. Maybe they are also required in the native folder.

**Comment by amaitland** [comment] 2022-09-16 19:41
> I have just tested in my application. It's a simple .Net 6 WinForms project with CEF webbrowser control.

What does your project file look like? No images, use formatted text

Please test with the NETCore solution provided in https://github.com/cefsharp/CefSharp.MinimalExample

> If I deploy this project,

What are you doing exactly? Please provide a clear list of reproducible steps.

During development it's recommended you specify a RuntimeIdentifier as per https://github.com/cefsharp/CefSharp/blob/cefsharp/105/NuGet/PackageReference/Readme.txt#L10

If you are publishing your application then it's required. 

>  If I copy both dlls from native to lib, then it works.

What you are suggesting isn't copying the files, it's moving them.

> Maybe they are also required in the native folder.

They are also required by the browsersubprocess. The files are included in the runtimes lib folders within the Nuget package and should be copied by msbuild/vs.

https://github.com/cefsharp/CefSharp/blob/cefsharp/105/NuGet/PackageReference/CefSharp.Common.NETCore.nuspec#L37

I need a clear example and steps that exactly reproduce the problem to understand what's going on. I don't believe your proposal isn't the correct solution.

**Comment by amaitland** [comment] 2022-09-19 01:57
Testing with https://github.com/cefsharp/CefSharp.MinimalExample using the `CefSharp.MinimalExample.netcore.sln` in `VS2022 17.3.2` and the files are as I would expect. There's duplicates of `CefSharp.dll` and `Ijwhost.dll` in `lib` and `native` as required.

> https://github.com/cefsharp/CefSharp/blob/master/NuGet/PackageReference/CefSharp.Common.NETCore.targets#:~:text=%3C/Content%3E-,%3CContent%20Include%3D%22%24(MSBuildThisFileDirectory)..%5Cruntimes%5Cwin%2Dx64%5Clib%5Cnetcoreapp3.1,%3C/Content%3E,-%3CContent%20Include%3D%22%40(CefRuntimeWinArm64Locales
> 
> In this place, it should be "runtimes\win-x64\lib%(RecursiveDir)%(FileName)%(Extension)" instead of "runtimes\win-x64\native%(RecursiveDir)%(FileName)%(Extension)" for CefSharp.dll and Ijwhost.dll.

Double checking and this is incorrect, there should be a copy in both `lib` and `native`. The `lib` copy should come directly from `Visual Studio/MSBuild` from the `runtimes/lib` folder within the `nuget` package.

Closing as unable to reproduce and [Bug Report](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report) wasn't completed, so there's insufficient information to investigate this further..

**Closed by amaitland** 2022-09-19 01:57 UTC

**Comment by augustunbear** [comment] 2022-09-19 12:22
I created a demo project, with a Winforms project and a setup project. You can download it here https://my.hidrive.com/lnk/rpjSzn9d .  Then compile the setup project, after that run the setup, in the target folder "runtime\win-x64\lib" these two files are missing. Maybe it's a bug in setup project, because if I only deploy the  Winforms project, the two files are copied to target folder.

**Comment by amaitland** [comment] 2022-09-19 21:18
> - If code is required to reproduce your problem then please provide one of the following
      - Fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub` (this is the preferred option).
      - Use a code sharing service list `Gist` or `Pastebin`
      - Paste your **formatted code as part of this issue** (only do this for small amounts of code and make sure you **format the code so it's readable**)
      - Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Demos need to be viewable in a WebBrowser, thanks.

> During development it's recommended you specify a RuntimeIdentifier as per https://github.com/cefsharp/CefSharp/blob/cefsharp/105/NuGet/PackageReference/Readme.txt#L10

Are you specifying a RuntimeIdentifier? You shouldn't have runtimes folder if you did. When publishing/packaging you will need to specify one so only the arch specific assets are included. 

Read https://learn.microsoft.com/en-us/dotnet/core/rid-catalog for reference.
