### ISSUE TITLE
OffScreen - Browser fails to complete loading when CEF is initialized shortly before the browser is created

### ISSUE THREAD

**Issue by jsoldi** [cefsharp/CefSharp#3850] opened 2021-10-15 16:58 UTC
### Bug Report

- **What version of the product are you using?**
    - [94.4.20](https://github.com/cefsharp/CefSharp/releases/tag/v94.4.20)

- **What architecture x86 or x64?**
    Both x86 and x64
	
- **What version of .Net?**
  .Net 4.6.2
    
- **On what operating system?**
  Windows Server 2016 or Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    OffScreen but the error also occurs on WinForms
    
- **What steps will reproduce the problem?**
I can reliable reproduce the error in a fresh Windows Server 2016 with 4GB ram. I can't reproduce it on a larger machine, so you may only get the test to fail in a 4GB ram or less machine. The steps to reproduce are:

1.  Download [this realse](https://github.com/cefsharp/CefSharp/releases/tag/v94.4.20).
2. Add the following class to the `CefSharp.Test\OffScreen` folder:

``` C#
public class NoInitTests
{
    private readonly ITestOutputHelper output;

    public NoInitTests(ITestOutputHelper output)
    {
        this.output = output;
    }

    [Fact]
    public async Task FinishesLoading()
    {
        //Cef.Initialize(new CefSettings());
        //await Task.Delay(5000);
        var tcs = new TaskCompletionSource<bool>();
        var browser = new CefSharp.OffScreen.ChromiumWebBrowser("https://www.google.com", null, null, false);

        browser.LoadingStateChanged += (s, arg) =>
        {
            if (arg.IsLoading == false)
                tcs.TrySetResult(true);
        };

        browser.LoadError += (s, arg) =>
        {
            tcs.TrySetResult(false);
        };

        browser.CreateBrowser();
        var completedTask = await Task.WhenAny(Task.Delay(10000), tcs.Task);
        Assert.Equal(tcs.Task, completedTask);
    }
}
```
3. Run the `FinishesLoading` test.

Note that this test class doesn't use `CefSharpFixture` because `CefSharpFixture` initializes CEF before running any test, and in order for the test to fail, the delay between CEF initialization and the first browser load must be as short as possible. This test won't shutdown CEF because the thread in which it initializes it is a different one than the one at the end of the `FinishesLoading` function. 
If the two commented out lines are uncommented, the test passes.

- **What is the expected output? What do you see instead?**
The test should pass.

- **Please provide any additional information below.**
When the browser fails to complete loading, it also becomes unusable. If I open DevTools, the console cannot run any scripts. It seems to be waiting for load to complete. I also set log-severity to verbose and I don't see any errors or warning, just some component initialization log entries.

**Comment by jsoldi** [comment] 2021-10-15 20:11
I just mention WinForms because I've also randomly seen it get on this "weird" never-completed-loading state, and also confirmed it by logging `LoadingStateChanged`, but haven't came up with a quick way to replicate it.

**Comment by amaitland** [comment] 2021-10-15 21:30
> I just mention WinForms because I've also randomly seen my winforms browser get on this "weird" never-completed-loading state

Have you confirmed the root cause is the same?

**Comment by amaitland** [comment] 2021-11-02 03:02
There are changes to the `OffScreen` implementation now available for testing in version [95.7.140-pre](https://github.com/cefsharp/CefSharp/issues/3866#issuecomment-955950545)

Commit https://github.com/cefsharp/CefSharp/commit/482b4239ec6d0b07331c0aaec69b31135ba2b623 changes the behaviour to enqueue browser creation until the `Global CefRequestContext` has finished initializing.  I haven't changed `WinForms` or `WPF` at this point.

> It doesn't. I moved the initialization to the very first line of `Main` and the issue occurred less often, probably because of the delay between that and the form load event, but it still happened:

You can use the new `Cef.InitializeAsync` method that was added in #3634 

The `Task` will be resolved when the `Global CefRequestContext` has been initialized. For testing purposes you can try something like the following:

```c#
var t = CefSharp.Cef.InitializeAsync(new CefSharp.WinForms.CefSettings() { LogSeverity = CefSharp.LogSeverity.Verbose });
t.Wait();
```

**Comment by amaitland** [comment] 2021-11-02 03:05
> starting with 94.4.20 there are loading issues also in CefSharp.Wpf and Wpf.NETCore
> with 93.1.140 there are no problems.

@SchreinerK Looking at your example and I don't believe it's related to this particular issue. If I understand @jsoldi correctly then the browser will never actually be created, no amount of delay before setting the `Address` property would have any effect. If you can reproduce the problem with version [95.7.140-pre](https://github.com/cefsharp/CefSharp/issues/3866#issuecomment-955950545) then you'll need to create a new issue.

**Comment by amaitland** [comment] 2022-03-07 23:54
The changes have been in the `OffScreen` version for a number of releases now and no further reports of this issue.

I've not been able to reproduce the issue in `WinForms` or `WPF` and no other reports of the problem. Using `Cef.InitializeAsync` should be possible for anyone experiencing problems there.

Closing now. Can be reopened if further code changes are required.

**Closed by amaitland** 2022-03-07 23:54 UTC
