### ISSUE TITLE
Crash while tring to view Global section in js-debug with DevTools

### ISSUE THREAD

**Issue by tonn** [cefsharp/CefSharp#1029] opened 2015-05-17 20:00 UTC
I try to debug example project. I put breakpoint on 13 line of BindingTest.html. And when it stopped I view global variables in right panel. Nothing is showing and browser content is disappearing.

I use win7 x64 and build example in win32 mode. Sources download from github few days ago.

**Comment by jamespearce2006** [comment] 2015-05-18 18:44
Are you saying the example app is crashing?
Which example are you running? WPF or WinForms?
Are you compiling the app in debug mode or release? What happens if you run in Release mode? (sometimes debug asserts in CEF can cause the app to crash). What happens when you debug into the app, does the debugger give you any feedback as to the cause of the crash?

**Comment by tonn** [comment] 2015-05-19 09:06
> Which example are you running? WPF or WinForms?

WinForms

> Are you compiling the app in debug mode or release? 

Debug

> What happens if you run in Release mode? 

same behaviour

> What happens when you debug into the app, does the debugger give you any feedback as to the cause of the crash?

There are not any exceptions in .net-debugging (there is VS-options for exceptions http://i.imgur.com/YLg7lhc.png)

There is screenshot of problem http://i.imgur.com/kWjawdJ.png

**Comment by amaitland** [comment] 2015-05-20 00:09
It would be worth testing the relevant `cefclient` release using their binding tests to see if the problem lies `upstream`.

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by tonn** [comment] 2015-05-20 11:57
>> It would be worth testing the relevant cefclient release using their binding tests to see if the problem lies upstream.

I did some more experiments.

1. cefclient - http://google.com - works normal
2. cefsharp-winforms/cefsharp-wpf - http://google.com - works normal
3. cefsharp-winforms/cefsharp-wpf - custom://cefsharp/BindingTest.html - crash

I don't know how to test cefclient on custom://cefsharp/BindingTest.html =(

**Comment by jornh** [comment] 2015-05-20 17:56
> I don't know how to test cefclient on custom://cefsharp/BindingTest.html =(

Maybe http://tests/binding in `cefclient` ??

**Comment by tonn** [comment] 2015-05-20 18:02
>Maybe http://tests/binding in cefclient ??

Oh, thanks.
In this case Global section in JS debug is showing normally http://i.imgur.com/1bVoOiV.png

**Comment by amaitland** [comment] 2015-10-11 23:02
Please try again with latest `master`.

**Comment by tonn** [comment] 2015-10-11 23:39
Yes. Now it works.

**Comment by amaitland** [comment] 2015-10-11 23:43
> Yes. Now it works.

Great, thanks for confirming :+1: 

The relevant changes will be merged into the `cefsharp/43` branch in the near future and included in the `43.0.1` release.

**Comment by amaitland** [comment] 2015-10-17 02:38
Changes merged into `43` branch, will hopefully release `43.0.1` shortly (just needs a little more testing)

**Closed by amaitland** 2015-10-17 02:38 UTC

**Comment by amaitland** [comment] 2015-10-29 22:19
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details
