### ISSUE TITLE
CefSettings.IgnoreCertificateErrors = true no longer allows invalid certificates.

### ISSUE THREAD

**Issue by mohitemji** [cefsharp/CefSharp#2887] opened 2019-09-05 11:38 UTC
I am trying to initialize browser with Cef Settings. I am setting IgnoreCertificateErrors as True. Even after this, I am getting Load Error (which is internally related to invalid certificate). Also, I get OnCertificateError (from IRequestHandler interface which I am attaching to 
BrowserObject.RequestHandler.

Kindly let me know if I am missing something.

NOTE: If I try the same in Winforms it works as expected,

Below is my WPF Code which is not giving me expected results as follows :
 public MainWindow()
        {
            InitializeComponent();
            var settings = new CefSettings();
            **settings.IgnoreCertificateErrors = true;**
            Cef.Initialize(settings);
            **MyBrowser = new ChromiumWebBrowser("xxx.xx.xxx.xx")**
            {
                //   MyBrowser = new ChromiumWebBrowser("google.com");
                Height = 500,
                Width = 500
            };
            MyDockPanel.Children.Add(MyBrowser);
            MyBrowser.LoadError += MyBrowser_LoadError;

        }

Thanks in advance.

Regards,
Mohith Agarwal

**Comment by amaitland** [comment] 2019-09-06 00:16
Testing with `75.1.141` and I can reproduce the issue with both `WinForms` and `WPF`. Marking this as `upstream` and will likely be closed as it appears to be a bug in `CEF` and will more likely need to be reported at https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open

For now you can use the command line argument.
```c#
settings.CefCommandLineArgs.Add("ignore-certificate-errors", string.Empty);
```

> NOTE: If I try the same in Winforms it works as expected,

I tried in `WinForms` using https://github.com/cefsharp/CefSharp.MinimalExample commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/9336e6b9d65ba1c953f449bb1bdc888be48f234a and `WinForms` and `WPF` behave exactly the same. There's no reason they would be different as the `Cef.Initialize/CefSettings` code is common to both. I'm wondering if you are testing with two different versions, seems the most likely cause.

In future if you open another issue please use the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report). You haven't even included the version you are using.

**Comment by amaitland** [comment] 2019-09-20 00:28
Closing as `upstream`. If you do open an issue on https://bitbucket.org/chromiumembedded/cef/issues?status=new&status=open then please post a link back here as a reference to others.

**Closed by amaitland** 2019-09-20 00:28 UTC
Labels: upstream

**Comment by amaitland** [comment] 2020-03-07 00:57
Upstream issue https://bitbucket.org/chromiumembedded/cef/issues/2899/cefsettingsignore_certificate_errors-true

**Comment by amaitland** [comment] 2020-03-09 04:57
https://stackoverflow.com/questions/35555754/how-to-bypass-ssl-error-cefsharp-winforms/35564187#35564187 has an example of using `IRequestHandler.OnCertificateError` to accept invalid certificates, you can adapt this method to display a dialog to your users, this is generally the preferred approach of handling invalid certificates.

**Comment by trivalik** [comment] 2020-12-01 12:36
> ```cs
> settings.CefCommandLineArgs.Add("ignore-certificate-errors", string.Empty);
> ```

This seems not working since CefSharp 85.

**Comment by willleework** [comment] 2023-11-15 14:42
I also encountered this problem. I set to ignore SSL certificate errors, but it didn’t work on one computer. Was this problem eventually resolved?

**Comment by amaitland** [comment] 2023-11-15 20:59
https://github.com/cefsharp/CefSharp/wiki/General-Usage#ssltls-certificate-errors

Further questions please use discussions
