### ISSUE TITLE
Crash application if u selected text on a touchscreen

### ISSUE THREAD

**Issue by walterfranssen** [cefsharp/CefSharp#2253] opened 2018-01-26 14:02 UTC
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 57.0.0
    - Please only create an issue if you can reproduce the problem with the latest version.

- **What architecture x86 or x64?**
x64 and x86

- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
 - WinForms

- **What steps will reproduce the problem?**
    - Load a website and selected some test

- **What is the expected output? What do you see instead?**
 - just working :)

- **Please provide any additional information below.**
[0126/134850.183:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0126/134947.669:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0126/135558.135:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0126/140103.514:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0126/141342.686:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0126/142219.339:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

**Comment by jankurianski** [comment] 2018-01-28 22:08
Does this happen with the 63.0.0-pre2 NuGet package?

Download the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html? and run `cefclient --multi-threaded-message-loop`.  Does the problem occur there?

**Comment by amaitland** [comment] 2018-01-29 00:39
Duplicate of #2117?

**Comment by jankurianski** [comment] 2018-01-29 22:28
@walterfranssen thanks for confirming it is fixed.  There is no expected date or deadline for the 63 release.  @amaitland is making good progress on 63, you can follow along in #2234.

**Closed by jankurianski** 2018-01-29 22:28 UTC
