### ISSUE TITLE
DevTools JavaScript Debugger lacks syntax colorization and full debug support

### ISSUE THREAD

**Issue by puresimmer** [cefsharp/CefSharp#3062] opened 2020-02-25 20:33 UTC
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
	79.1.360

- **What architecture x86 or x64?**
    x64
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   WinForms
    
- **What steps will reproduce the problem?**
invoke the browser.ShowDevTools and visit sources tab and view any JS file - no colorization

- **What is the expected output? What do you see instead?**
Should see colorized code the way it appears in desktop chromium

**Comment by amaitland** [comment] 2020-02-25 21:23
`CefSharp` is just one of many wrappers around the [Chromium Embedded Framework (CEF)](https://bitbucket.org/chromiumembedded/cef/)

The `CEF` project has it's own [Issue Tracker](https://bitbucket.org/chromiumembedded/cef/issues). It is recommended you ask on the [CEF Forum](https://magpcss.org/ceforum/index.php) before opening an issue.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` sample application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

Closing this as `upstream` and as changes/fixes need to be made in `CEF`.

**Closed by amaitland** 2020-02-25 21:23 UTC

**Comment by amaitland** [comment] 2020-02-25 21:28
Syntax highlighting was reported at https://bitbucket.org/chromiumembedded/cef/issues/2870/debugger-sources-tab-is-missing-code this is also a duplicate of #3029

Is there a reason you skipped the Does this problem also occur in the CEF Sample Application section of the bug report?

**Comment by amaitland** [comment] 2020-02-25 21:30
Make sure you read https://github.com/cefsharp/CefSharp/wiki/General-Usage

**Comment by puresimmer** [comment] 2020-02-25 22:04
I understand what CEF is, and have used it since 2012 :)

Sorry, I have the flu and searched long and hard.  This is a great project and its why I am happy to be signed up to donate every month and have been for a long time.  

My mistake of the CEF repro - I realize what happened.  I had grabbed 80 today and it looked fine there.  My bad.

Shaun
www.electricplum.com
