### ISSUE TITLE
Undisposed instances of BrowserProcessServiceHost

### ISSUE THREAD

**Issue by deepthireddyb** [cefsharp/CefSharp#984] opened 2015-04-28 11:34 UTC
We are in the process of memory profiling our application once integration is completed with Cefsharp projects. Our application performance is getting poor when it ran for 2 or 3 hours continuously. So we used .Net memory profiler tool to understand the situation where memory leaks are happening. 

This tool found few issues with BrowserProcessServiceHost which is not getting disposed and left lot of instances in memory. 

![browserprocessservicehost_undisposed](https://cloud.githubusercontent.com/assets/12151827/7368273/0c955a5c-edc4-11e4-97de-26ac4b839168.jpg)

Seems like ManagedCefBrowserAdapter.h implemented dispose just for closing browser process service host instance created but did not dispose the host instance. Hence I thought of implementing a possible fix which is adding IDisposable for BrowserProcessServiceHost and a dispose for host instance. 

After running profiler again, warning was gone in results but the value Delta (HeapMemory: 624) is increased which means there is still leak in memory. 

I am looking for fixes in v39 version especially if there are any memory leaks and also I may need few suggestions on fixing memory leaks in cefsharp projects. 

CefSharp version downloaded: v39 CEF 3.2
Integrated with WPF project.

Thanks in advance!!

**Comment by amaitland** [comment] 2015-04-28 11:44
> Seems like ManagedCefBrowserAdapter.h implemented dispose just for closing browser process service host instance created but did not dispose the host instance. Hence I though of implementing a possible fix which is IDisposable for BrowserProcessServiceHost and added a dispose for closing the host instance.

The `BrowserProcessServiceHost` instance should remain open for the lifespan of the `ChromiumWebBrowser` instance.

Can you provide more details on how your using `CefSharp`? How many instances of `ChromiumWebBrowser` are you creating?

**Comment by amaitland** [comment] 2015-04-28 11:51
Ideally if you can fork https://github.com/cefsharp/CefSharp.MinimalExample and provide a workable demonstration of the leak that would go a long way to getting it fixed.

**Comment by deepthireddyb** [comment] 2015-04-28 12:48
My scenario is bit different. The control would be created whenever content type is set as HTML. We are having different controls loaded every time content type changed. content type would come from xml which is based on time slot provided. Hence whenever we load HTML content, there is new Chromium Browser instance, this we add to canvas and after usage we are disposing everything from canvas. Before disposing the content from canvas, we are tying to dispose all the dependencies present with Chromium browser.

**Comment by deepthireddyb** [comment] 2015-04-28 13:56
Here is a simple sample how we are trying to render Chromium browser:

    public partial class MainWindow : Window
    {
        private BackgroundWorker worker;
        private Dispatcher dispatcher;
        private bool flag;

        public MainWindow()
        {
            InitializeComponent();

            this.dispatcher = Dispatcher.CurrentDispatcher;

            this.worker = new BackgroundWorker();
            this.worker.DoWork += worker_DoWork;
            this.worker.RunWorkerAsync();
        }

        void worker_DoWork(object sender, DoWorkEventArgs e)
        {          
            while (true)
            {
                this.dispatcher.Invoke(new Action(() => this.ShowContent()));
                this.dispatcher.Invoke(new Action(() => this.StageContent()));
                Thread.Sleep(7000);
                flag = !flag;
            }
        }

        private void ShowContent()
        {
            if (this.PlayerCanvas.Children.Count > 1)
            {
                var browserToDispose = this.PlayerCanvas.Children[1];
                this.PlayerCanvas.Children.RemoveAt(1);
                ((IDisposable)browserToDispose).Dispose();
            }
        }
        private void StageContent()
        {
            var browserToStage = this.CreateBrowser(flag ? "http://screen.brandalizzer.com/dad068049d7d437ba33a27b2f6730c0e" : "http://c.guud.tv/clearchannelfuencarral/u2/");
            this.PlayerCanvas.Children.Insert(0, browserToStage);
        }

        private ChromiumWebBrowser CreateBrowser(string url)
        {
            var browser = new ChromiumWebBrowser();
            browser.Width = 540;
            browser.Height = 960;
            browser.Address = url;
            return browser;
        }
    }

**Comment by rassilon** [comment] 2015-04-28 14:05
Oh, ick. Regardless of BrowserServiceHost instances not being disposed, you should cache created browser instances, given that any HTML browser is the opposite of small and lightweight. 

If 137 instances haven't been disposed, are you sure your .Net Finalization Queue is still making forward progress? (i.e. could it have blocked permanently on something else you didn't end up disposing)

Example: I needed to play MP3 files with CefSharp. I used NAudio (.Net audio library) to do so. 
I accidentally created the audio objects on a Chromium thread. During shutdown my application would hang because my .Net finalization thread was blocked waiting for the Chromium thread to pump COM messages to the audio object. (which never happened because Chromium doesn't pump COM messages on that thread)

Bill

**Comment by amaitland** [comment] 2015-04-28 20:47
> Oh, ick. Regardless of BrowserServiceHost instances not being disposed, you should cache created browser instances, given that any HTML browser is the opposite of small and lightweight.

Indeed! There's a massive overhead for spawning even a single instance. Better just to keep reference and hide the instance. When the `ChromiumWebBrowser` is hidden it'll stop rendering to save resources.

@deepthireddyb If the example you provided is enough to reproduce the problem, then I'd suggest modifying the `CefSharp.WPF.Example` project so you can debug, step through the dispose methods, make sure they're being called.

**Comment by wpleary** [comment] 2015-04-29 00:43
There does indeed appear to be some serious leakage if you run the scenario @deepthireddyb  described. I downloaded a memory profiler to try it out and am observing the same thing. The Dispose method of ChromiumWebBrowser class stays alive, post-dispose, with many DelegateCommand instances referencing it. I am very new to CefSharp, so will post more as I learn more. Whether or not it is good or bad to cache the instances, the Dispose implementation doesn't seem to be cleaning up after itself.

**Comment by amaitland** [comment] 2015-04-29 01:00
Whilst it's quite possible that there is a memory leak, it should be noted that the sample provided is far from `Best Practice`.

- Spawn one `ChromiumWebBrowser` instance
- Call `Load(url)` passing in your given url.

**Comment by wpleary** [comment] 2015-04-29 01:58
@amaitland I agree it doesn't seem to be ideal. I myself am extremely new to CefSharp. Been playing with it intermittently for several weeks now. Is CefSharp appropriate for scenarios where what you describe is not viable? From what I understand about CEF's goals (https://bitbucket.org/chromiumembedded/cef) it is intended to be used in non-standard ways. (Offscreen, test host, etc...) Wouldn't that imply use-cases where one intentionally is spawning and then destroying a CEF web browser within a process? So, is CefSharp intended for those cases as well, or just for one where you are displaying/using a browser you intend to have a long lifetime within the application? Curious for thoughts from someone more experienced in the project.

**Comment by amaitland** [comment] 2015-04-29 02:36
> Is CefSharp appropriate for scenarios where what you describe is not viable?

What is not viable exactly? 

> Wouldn't that imply use-cases where one intentionally is spawning and then destroying a CEF web browser within a process?

You can spawn many instances if you should choose to, just remembering that a single instance has relatively speaking a very large overhead. When it's practical to reuse an instance you should. Calling `Load` within a browser instance is very cheap compared to creating a new instance.

If you wish to see `CefSharp` in action then give `MailBird` a go, it spawns many instances for viewing/editing.

http://getmailbird.com/

**Comment by amaitland** [comment] 2015-04-29 02:39
The biggest problem `CefSharp` has currently is it's reliance on `WCF` for `IPC` between browser and render processes.

**Comment by amaitland** [comment] 2015-04-29 05:02
I've taken the code provided, forked the current `master`, added a new `LeakyWindow` class. I've simplified the code down to it's bare bones. It creates a new browser every seven seconds.

https://github.com/amaitland/CefSharp/commit/4f639a2f4b42ff4c97b2d501d52b9da5ca51aa5a

I'm not seeing any memory leaks. Can you try profiling again using `master` and provide the details. Assuming you can save the profiler output, can you also provide a copy and the exact profiler you were using if the problem still exists.

**Comment by wpleary** [comment] 2015-04-29 15:56
I have been using the last official stable release, 37.0.1, not the current master release. I will pull from master and retry.

I am currently using trial versions of the memory profilers from RedGate, JetBrains, and SciTech. I can see the issue using all three of them. I believe the cause of the leak is related to the CleanupElement implementation within the ChromiumWebBrowser class. If I comment out the assignment on to CleanupElement within the OnLoaded event, I don't see any leaks. I'm not too familiar with the code, but is there an assumption that the control hosting the browser will always be a Window? I see that CleanupElement is a public property. If you don't explicitly set this property, and it defaults to being the application's main Window, that is probably the cause of the issue.

Will do a little more testing, both with what I just stated, and then using current master branch. Thanks @amaitland .

**Comment by rassilon** [comment] 2015-04-29 17:38
Since you're seeing "leaks" what objects are retaining references to the objects you want to disappear?
Are you sure the only reference isn't just the .Net finalization queue?

**Comment by wpleary** [comment] 2015-04-29 18:00
If you do not explicitly set the CleanupElement, and place the ChromiumWebBrowser into a different location within the Visual Tree, it will result in RoutedEventHandler references, ultimately owned by the main window, to keep the ChromiumWebBrowser alive, even if you explicitly remove it from the visual tree and dispose it. The references keeping it alive will be Window -> EffectiveValueEntry[] -> EventHandlersStore -> SixObjectMap -> FrugalObjectList<RoutedEventHandlerInfo> -> ArrayItemList<RoutedEventHandlerInfo> -> RoutedEventHandlerInfo[] -> RoutedEventHandler -> ChromiumWebBrowser. I believe this is completely due to the reference from the Window to ChromiumWebBrowser created by the Loaded event handler assignment.

This design makes the ChromiumWebBrowser less flexible, as if you want to dynamically add/remove it over the life of your application, you need to create an extra wrapper element that will also be removed from the visual tree as well. Since the class implements IDisposable I would think that it would either a) remove the event handler within Dispose(bool) if CleanupElement is not null, or b) not automatically wire-up to the Window or any other element...make the cleanup-via-element logic more opt-in as opposed to default.

**Comment by amaitland** [comment] 2015-04-29 21:39
> I have been using the last official stable release, 37.0.1, not the current master release. I will pull from master and retry.

The latest official stable release is `39.0.0`

**Comment by amaitland** [comment] 2015-04-29 21:43
Soon to be `39.0.1`

**Comment by wpleary** [comment] 2015-04-29 22:53
Thanks @amaitland . I had pulled the code last month and didn't realize the newer stable drop was made available this month. Will definitely start using that.

**Comment by amaitland** [comment] 2015-04-29 23:06
> I had pulled the code last month and didn't realize the newer stable drop was made available this month. Will definitely start using that.

:+1: There are quite a lot of `Dispose()` related improvements in `39` starting with #786. Overall it's a big step forward.

**Comment by amaitland** [comment] 2015-05-06 02:08
Is the leak reproducible with `39.0.0`?

**Comment by deepthireddyb** [comment] 2015-05-07 14:35
Thank you everyone for the responses. I have been fixing for the issues within ChromiumWebBrowser for cleaning the unnecessary commands and events which I don't need them in my application. This fixed most of the leaks. 
Good that you gave another drop 39.0.1. Let me try with it and update you.

Thanks again!!

**Comment by amaitland** [comment] 2015-05-15 03:58
Is there anything else required before we close this? Is there a reproducible memory leak?

**Comment by amaitland** [comment] 2015-06-01 02:14
Closing this due to lack of response.

**Closed by amaitland** 2015-06-01 02:14 UTC
Labels: wpf
