### ISSUE TITLE
long touch input content the cefsharp crash

### ISSUE THREAD

**Issue by 734209936** [cefsharp/CefSharp#2117] opened 2017-08-21 02:49 UTC
when I touch the page input content on a touch screen computer，the Cefsharp crash!

**Comment by jankurianski** [comment] 2017-08-21 02:57
If you are submitting a bug report, please add a new comment with the answers to all of these questions:
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Also please use the CEF Sample Application on the same touch screen computer.  Does the problem also occur in the CEF Sample Application?

**Comment by adamhewitt627** [comment] 2017-08-21 15:04
I get the same crash, or at least a similar one. Mine occurs when using long-press to select text.
```
Faulting module name: libcef.dll, version: 3.2987.1601.0, time stamp: 0x58e72b22
Exception code: 0xc0000005
Fault offset: 0x02ea0017
```

It does *not* happen in the sample application. My environment:
- VS 2017, Windows 10 Anniversary Update. (Builds also crash on Creator's Update)
- .NET 4.6.2, WPF app
- Running the WinForms browser with WPF interop (I don't mind the airspace issue, but I do need touch scrolling)

**Comment by adamhewitt627** [comment] 2017-08-21 15:56
Enabling error logging and I get this: (possibly the cause, or just the only output)
```
[0821/085015.224:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
```

With verbose logging, this is the full output of an app run:
```
[0821/085015.086:VERBOSE1:pref_proxy_config_tracker_impl.cc(151)] 16935A60: set chrome proxy config service to 10E87C20
[0821/085015.086:VERBOSE1:pref_proxy_config_tracker_impl.cc(278)] 16935A60: Done pushing proxy to UpdateProxyConfig
[0821/085015.089:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Pilot' log
[0821/085015.089:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Aviator' log
[0821/085015.090:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: DigiCert Log Server
[0821/085015.090:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Rocketeer' log
[0821/085015.091:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Symantec log
[0821/085015.091:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Venafi log
[0821/085015.091:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Symantec 'Vega' log
[0821/085015.091:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: CNNIC CT log
[0821/085015.091:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: WoSign log
[0821/085015.111:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: StartCom CT log
[0821/085015.111:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Skydiver' log
[0821/085015.111:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Icarus' log
[0821/085015.111:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Izenpe log
[0821/085015.112:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Certly.IO log
[0821/085015.224:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0821/085015.586:VERBOSE1:webrtc_internals.cc(99)] Could not get the download directory.
[0821/085015.696:VERBOSE1:gles2_cmd_decoder.cc(3297)] GL_OES_packed_depth_stencil supported.
[0821/085015.774:INFO:cpu_info.cc(50)] Available number of cores: 8
[0821/085015.844:VERBOSE1:gles2_cmd_decoder.cc(3297)] GL_OES_packed_depth_stencil supported.
[0821/085015.849:VERBOSE1:gles2_cmd_decoder.cc(3297)] GL_OES_packed_depth_stencil supported.
[0821/085015.879:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           (none)
  frame:                  498A19EC
  URL:                    
  context_type:           WEB_PAGE
  effective extension id: (none)
  effective context type: WEB_PAGE
[0821/085015.879:VERBOSE1:script_context.cc(111)] Created context:
  extension id:           (none)
  frame:                  00000000
  URL:                    
  context_type:           UNSPECIFIED
  effective extension id: (none)
  effective context type: UNSPECIFIED
[0821/085015.880:VERBOSE1:dispatcher.cc(396)] Num tracked contexts: 1
[0821/085015.881:VERBOSE1:mime_sniffing_resource_handler.cc(355)] To buffer: file:///....myfile.js
[0821/085037.299:VERBOSE1:statistics_recorder.cc(498)] Collections of all histograms
Histogram: GPU.ANGLE.D3D11CreateDeviceMS recorded 1 samples, mean = 18.0 (flags = 0x1)
0   ... 
17  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
20  ... 

Histogram: GPU.ANGLE.D3D11FeatureLevel recorded 1 samples, mean = 5.0 (flags = 0x1)
0  ... 
5  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
6  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.ANGLE.D3D11InitializeResult recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.ANGLE.D3DCompileMS recorded 8 samples, mean = 6.9 (flags = 0x1)
0   ... 
3   ------------------------------------O                                     (1 = 12.5%) {0.0%}
4   ------------------------------------------------------------------------O (2 = 25.0%) {12.5%}
5   ------------------------------------O                                     (1 = 12.5%) {37.5%}
6   ... 
8   ------------------------------------------------------O                   (3 = 37.5%) {50.0%}
10  ... 
14  ------------O                                                             (1 = 12.5%) {87.5%}
17  ... 

Histogram: GPU.ANGLE.DisplayInitializeMS recorded 1 samples, mean = 22.0 (flags = 0x1)
0   ... 
20  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
24  ... 

Histogram: GPU.ANGLE.Renderer11InitializeDLLsMS recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: GPU.ANGLE.Renderer11InitializeDeviceMS recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: GPU.ANGLE.SupportsDXGI1_2 recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.CollectContextGraphicsInfo recorded 1 samples, mean = 6.0 (flags = 0x1)
0  ... 
6  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
7  ... 

Histogram: GPU.ContextMemory.GLES.Shutdown recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 

Histogram: GPU.DoLinkProgramTime recorded 4 samples, mean = 13.5 (flags = 0x1)
0   ... 
7   ------------------------------------------------------------------------O (1 = 25.0%) {0.0%}
8   O                                                                         (0 = 0.0%) {25.0%}
10  ------------------------------------O                                     (1 = 25.0%) {25.0%}
12  O                                                                         (0 = 0.0%) {50.0%}
14  ------------------------O                                                 (1 = 25.0%) {50.0%}
17  O                                                                         (0 = 0.0%) {75.0%}
20  ------------------O                                                       (1 = 25.0%) {75.0%}
24  ... 

Histogram: GPU.EGLDisplayType recorded 1 samples, mean = 4.0 (flags = 0x1)
0  ... 
4  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5  ... 

Histogram: GPU.FenceSupport recorded 2 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (2 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.InitializeOneOffMediumTime recorded 1 samples, mean = 34.0 (flags = 0x1)
0   ... 
33  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
41  ... 

Histogram: GPU.MaxMSAASampleCount recorded 1 samples (flags = 0x1)
8  ------------------------------------------------------------------------O (1 = 100.0%)

Histogram: GPU.ProgramCache.BinaryCacheMissTime recorded 4 samples, mean = 10719.8 (flags = 0x1)
0      ... 
5362   ------------------------------------------------------------------------O (1 = 25.0%) {0.0%}
7439   ------------------------------------------------------------------------O (1 = 25.0%) {25.0%}
10321  ------------------------------------------------------------------------O (1 = 25.0%) {50.0%}
14319  ------------------------------------------------------------------------O (1 = 25.0%) {75.0%}
19866  ... 

Histogram: GPU.ProgramCache.CacheHit recorded 4 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (4 = 100.0%)
1  ... 

Histogram: GPU.ProgramCache.MemorySizeAfterKb recorded 4 samples, mean = 17.5 (flags = 0x1)
0   ... 
5   ------------------------------------------------------------------------O (1 = 25.0%) {0.0%}
7   ... 
12  ------------------------------------O                                     (1 = 25.0%) {25.0%}
16  O                                                                         (0 = 0.0%) {50.0%}
21  -----------------------------O                                            (1 = 25.0%) {50.0%}
28  -----------------------------O                                            (1 = 25.0%) {75.0%}
37  ... 

Histogram: GPU.ProgramCache.MemorySizeBeforeKb recorded 4 samples, mean = 10.0 (flags = 0x1)
0   ------------------------------------------------------------------------O (1 = 25.0%)
1   ... 
5   ------------------------------------O                                     (1 = 25.0%) {25.0%}
7   ... 
12  ------------------O                                                       (1 = 25.0%) {50.0%}
16  O                                                                         (0 = 0.0%) {75.0%}
21  --------------O                                                           (1 = 25.0%) {75.0%}
28  ... 

Histogram: GPU.ProgramCache.ProgramBinarySizeBytes recorded 4 samples, mean = 7874.8 (flags = 0x1)
0     ... 
5338  ------------------------------------O                                     (1 = 25.0%) {0.0%}
7031  ------------------------------------------------------------------------O (2 = 50.0%) {25.0%}
9260  ------------------------------------O                                     (1 = 25.0%) {75.0%}
12196 ... 

Histogram: GPU.TextureRG recorded 2 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (2 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: Mojo.System.GetParentPlatformHandleSyncTime recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Mojo.System.MessagesAcceptedPerEvent recorded 619 samples, mean = 0.2 (flags = 0x1)
0  ------------------------------------------------------------------------O (554 = 89.5%)
1  ----O                                                                     (34 = 5.5%) {89.5%}
2  ---O                                                                      (21 = 3.4%) {95.0%}
3  -O                                                                        (4 = 0.6%) {98.4%}
4  -O                                                                        (4 = 0.6%) {99.0%}
5  ... 
7  O                                                                         (1 = 0.2%) {99.7%}
8  O                                                                         (1 = 0.2%) {99.8%}
9  ... 

Histogram: Mojo.System.Node.ConnectedPeers recorded 3 samples, mean = 1.3 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (2 = 66.7%) {0.0%}
2  ------------------------------------O                                     (1 = 33.3%) {66.7%}
3  ... 

Histogram: Mojo.System.Node.PendingChildren recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: TaskScheduler.DetachDuration.SimplePool recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.NumTasksBeforeDetach.SimplePool recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.NumTasksBetweenWaits.SimplePool recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.BackgroundTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.BackgroundTaskPriority.MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.UserBlockingTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.UserBlockingTaskPriority.MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.UserVisibleTaskPriority recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TaskScheduler.TaskLatency.UserVisibleTaskPriority.MayBlock recorded 0 samples (flags = 0x1)
0 ... 

Histogram: TrackedObjects.GetRetiredOrCreateThreadData recorded 7 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (7 = 100.0%)
1  ... 

Histogram: UMA.Histograms.Activity.gpu-process recorded 116 samples, mean = 4.0 (flags = 0x1)
0  --O                                                                       (1 = 0.9%)
1  ------------------------------------------------------------------------O (36 = 31.0%) {0.9%}
2  --------------O                                                           (7 = 6.0%) {31.9%}
3  --------------------------------------------------------O                 (28 = 24.1%) {37.9%}
4  --------O                                                                 (4 = 3.4%) {62.1%}
5  ------O                                                                   (3 = 2.6%) {65.5%}
6  O                                                                         (0 = 0.0%) {68.1%}
7  --O                                                                       (1 = 0.9%) {68.1%}
8  ------------------------------------------------------------------------O (36 = 31.0%) {69.0%}
9  ... 

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 



```

**Comment by adamhewitt627** [comment] 2017-08-21 16:28
While the Chromium sample doesn't crash, the Cefsharp.MinimalExample does. (WinForms does - WPF doesn't even select text via touch) https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by adamhewitt627** [comment] 2017-08-21 16:34
I deleted my big long log message for clarity after finding this: https://bitbucket.org/chromiumembedded/cef/issues/2149/libcefdll-crashes-when-a-text-is-selected. Looks like CEF has fixed the issue, but it needs pulled in to CefSharp.

**Comment by jankurianski** [comment] 2017-08-21 23:38
@adamhewitt627 thanks, great detective work.  The bug fix has not been ported to the 2987 CEF branch, so that means that CefSharp 55 will always have this bug.

So the only solution to this bug is to use CefSharp 55 or CefSharp `master` (which is currently using CEF `3.3071.1649` which, just based on comparing the fix and build dates, shouldn't have this bug).

I'll close this issue as there's nothing left for us to do.  Thanks guys.

**Closed by jankurianski** 2017-08-21 23:38 UTC

**Comment by AMartens181** [comment] 2017-10-26 23:38
CefSharp: 57 uses CEF 2987. This happens in this CEF version.
