### ISSUE TITLE
Crash when show/hide tray icon

### ISSUE THREAD

**Issue by Timka654** [cefsharp/CefSharp#2150] opened 2017-09-26 15:48 UTC
Sorry but i cannot not found info for this problem
Windows Form Application, Net Framework 4.5.2, CEFSharp v57.0.0, Windows 10 (build 15063.608), crashing when execute this code
                     `  if (this.WindowState == FormWindowState.Normal)
                        {
                            this.ShowInTaskbar = false;
                            this.WindowState = FormWindowState.Minimized;
                            //this.Hide();
                        }
                        else
                        {
                            //this.Show();
                            this.WindowState = FormWindowState.Normal;
                            this.ShowInTaskbar = true;
                        }`

and returns -536870904 (0xe0000008) exit code, first time is working, 2-4 time, crash, and ChromiumWebBrowser control all time open page again, and function "Hide()" cannot hide tray icon, i'm try in other form, without ChromiumWebBrowser control, work fine

**Comment by Timka654** [comment] 2017-09-26 15:58
if this helpful, expcept ChromiumWebBrowser control, form contains 4 panel for resizing, 1 panel for ChromiumWebBrowser, and notifyicon
initialize control code
`CefSettings cs = new CefSettings()
            {
                CachePath = $"{Core.Global.AppPath}\\WebCache",
                RemoteDebuggingPort = 8088,
            };
            cs.CefCommandLineArgs.Add("--disable-web-security", "");
            cs.CefCommandLineArgs.Add("--allow-file-access-from-files", "");
            cs.CefCommandLineArgs.Add("--allow-file-access", "");

            Cef.Initialize(cs);
            wb = new ChromiumWebBrowser("file:///D:\\LC\\LCClient\\LCClient\\bin\\x86\\Debug/data/web/StartPage.html");

            wb.BrowserSettings.WebGl = CefState.Disabled;
            wb.BrowserSettings.FileAccessFromFileUrls = CefState.Enabled;
            wb.FrameLoadEnd += Wb_FrameLoadEnd;
            wb.FrameLoadStart += Wb_FrameLoadStart;
            wb.IsBrowserInitializedChanged += Wb_IsBrowserInitializedChanged;
            wb.AddressChanged += Wb_AddressChanged;
            wb.LoadingStateChanged += Wb_LoadingStateChanged;
            wb.StatusMessage += Wb_StatusMessage;
            //jquery = new JQueryExecutor(wb.Window);
            wb.Dock = DockStyle.Fill;
            this.panel1.Controls.Add(wb);`

**Comment by amaitland** [comment] 2017-10-06 00:05
Duplicate of #2042

**Closed by amaitland** 2017-10-06 00:05 UTC
