### ISSUE TITLE
The HTML tooltip does not follow cursor

### ISSUE THREAD

**Issue by heyanctil** [cefsharp/CefSharp#1849] opened 2016-10-28 17:46 UTC
I've reported this bug at first to the Chromium team but they refer me to the CefSharp team instead.

During the integration of CefSharp (WPF), we noticed some different behavior of Chrome. For example, in the screenshot below (you can't see the cursor but it is on the black circle), with CefSharp, if I move the cursor on the toolbar, the tooltip does not follow the cursor like the Chrome version.

![60898728-chromium](https://cloud.githubusercontent.com/assets/7291291/19816148/28af11b4-9d14-11e6-916e-68f8bc2947b6.png)

This sample is running on Windows Server 2012.

- **What version of the product are you using?**
    - Nuget 53.0.0 (the screenshot shows 51, but we've updated the version and see the same behavior).

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win Server 2012 / Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF

- **What steps will reproduce the problem?**
    - Move the cursors on multiple buttons with tooltip (title attribute).

- **What is the expected output? What do you see instead?**
    - The tooltip does not follow the cursor.

- **Please provide any additional information below.**
    - No additional information. Take a look at the screenshot below.

- **Does this problem also occur in the `Cef` TestApp from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
    - I've tried to build it without success, problem with CMake...

**Comment by cztomczak** [comment] 2016-10-29 10:36
For the bug report to be valid it needs to be reproducible in the project you're reporting it to.

**Comment by rlmcneary2** [comment] 2016-10-30 01:08
Would be nice to know if this is reproducible in the cef client app (seems to me this is unlikely to be a CefSharp bug). Please provide the information requested in the template, CefSharp version, etc.

**Comment by heyanctil** [comment] 2016-10-31 18:12
@rlmcneary2 I've updated the issue using the template.

**Comment by amaitland** [comment] 2016-12-01 01:55
If they're custom cursors then this is a duplicate of #606

**Comment by amaitland** [comment] 2016-12-21 03:10
Test with latest `master`, reopen if you can reproduce the issue (and provide an example/means of reproducing the issue).

**Comment by amaitland** [comment] 2018-01-08 23:17
> I also reproduced it in the CefSharp Minimal Example with this CodePen:
> https://codepen.io/anon/pen/xppPyV

Can you provide a better example please, it's a bit too basic, cannot tell where one div starts and another ends.

Also if you have time please test again using https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/63 and report back. That branch references the latest `-pre` release packages.

**Comment by DanielBretzigheimer** [comment] 2018-01-09 06:59
It does also occur in the 63 version. I updated the codepen but what you described is exactly the problem. If the div's are directly connected to each other it does not work. If a margin is applied its working like expected (see the youtube video below). In Chrome it is working in both cases.

Video:
https://youtu.be/a9DAkiMwZl8
CodePen:
https://codepen.io/anon/pen/xppPyV

**Comment by amaitland** [comment] 2018-01-09 09:04
Can you make the divs have a different background color so the separation is visible.

To start debugging this yourself download the source and start with https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Internals/ClientAdapter.cpp#L344

Tooltips could likely use a total rewrite, so by all means submit a PR if you have time.

**Comment by amaitland** [comment] 2018-01-12 00:24
My suggestion to anyone planing on tacking this would be

- Remove the tooltip timer (not really sure why that approach was chosen, seems clunky to me).
- Directly open and close the `ToolTip` based on `IWebBrowserInternal.SetTooltipText(tooltipText)`, if `tooltipText` is `null`, close the tooltip, otherwise open it and set content.
- In `MouseMove` update tooltip horizontal/vertical offset based on position (only if tooltip is open of course).

**Comment by DanielBretzigheimer** [comment] 2018-01-12 08:27
I have updated the CodePen to better see the different div's.
https://codepen.io/anon/pen/xppPyV

I will have a look at the code over the weekend but I have no experience with C++.

**Comment by DanielBretzigheimer** [comment] 2018-01-12 09:45
Easier than I thought. I created a pull request here:
https://github.com/cefsharp/CefSharp/pull/2232

2 Lines of Code which should fix it.

**Comment by amaitland** [comment] 2018-01-22 01:07
Changes merged.

**Closed by amaitland** 2018-01-22 01:07 UTC
Labels: wpf

**Comment by dhpanteon** [comment] 2018-10-22 10:41
Is there any setting is available that remove too-tip for cefsharp application ?

**Comment by amaitland** [comment] 2018-10-22 21:44
@dhpanteon If you have a question ask it on https://gitter.im/cefsharp/CefSharp
