### ISSUE TITLE
System.Reflection.TargetInvocationException when trying to delete cookies before shutdown

### ISSUE THREAD

**Issue by singhprab** [cefsharp/CefSharp#2240] opened 2018-01-18 06:02 UTC
Issue : Before closing the application, we are deleting the CEFSharp browser cookies. In some of the scenarios deleting cookies is throwing System.Reflection.TargetInvocationException. This does not happen every time.

Code : 
```
if (Cef.IsInitialized)
            {
                Cef.GetGlobalCookieManager().DeleteCookies(String.Empty, String.Empty);
                Cef.Shutdown();
            }
```

The initialisation of Cef and the deletion of cookies are happening on the same thread (Managed Thread id is 1).

![image](https://user-images.githubusercontent.com/35488267/35082918-4542113a-fc42-11e7-80af-0831b018514d.png)

![image](https://user-images.githubusercontent.com/35488267/35082941-67c2d6cc-fc42-11e7-9191-a7122886416d.png)

**Comment by amaitland** [comment] 2018-01-18 06:44
When filling out a bug report please use the template provided https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report (You can view the raw version at https://raw.githubusercontent.com/cefsharp/CefSharp/master/ISSUE_TEMPLATE.md to copy and paste)

**Comment by amaitland** [comment] 2018-01-18 06:52
https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#loading-native-symbols-for-easier-diagnosis

**Comment by singhprab** [comment] 2018-01-18 07:55
@amaitland But as per the documentation of the method; if we don't use callback (since default parameter is null), the method should get executed synchronously.
[https://github.com/cefsharp/CefSharp/blob/464dd14b6f88ebe1614cca61c2092d9d67c8efbb/CefSharp/ICookieManager.cs#L20](url)

**Comment by amaitland** [comment] 2018-01-18 10:59
The doc should say asynchronously see http://magpcss.org/ceforum/apidocs3/projects/(default)/CefCookieManager.html#DeleteCookies(constCefString&,constCefString&,CefRefPtr<CefDeleteCookiesCallback>)

**Comment by singhprab** [comment] 2018-01-22 07:00
@amaitland I am still confused if we need a callback. 
Help me to understand this. So the DeleteCookies method ICookieManager.cs has default value for callback as null; which means that this callback value(null) would be passed to the CEF engine.
If we pass null to DeleteCookies of Class CefCookieManager (in the documentation you provided), the deletion of cookies should happen synchronously.
So what is wrong with the code which we are using?

**Comment by amaitland** [comment] 2018-01-22 09:53
Where exactly does it say that? The CefSharp documentation is incorrect, needs to be updated. 

Will also need a proper stack trace and an example that reproduces the problem, you can fork the MinimumExample as a starting point.

**Comment by amaitland** [comment] 2018-01-23 11:33
For reference https://bitbucket.org/chromiumembedded/cef/src/c8368c8b130d1cd0b8e66fe752e0b9272676c486/libcef/browser/cookie_manager_impl.cc?at=3282&fileviewer=file-view-default#cookie_manager_impl.cc-261

**Comment by amaitland** [comment] 2018-01-29 00:41
Please provide a `stacktrace` for exception, it may be possible to handle the exception your seeing more gracefully, though I expect to actually delete cookies before `Shutdown` then you'll need to wait for the `DeleteCookies` to complete.

**Comment by amaitland** [comment] 2018-02-05 04:02
If waiting for `DeleteCookies` to complete doesn't resolve your problem then calling `FlushStore` and waiting for it to complete should resolve the issue.

http://cefsharp.github.io/api/57.0.0/html/M_CefSharp_ICookieManager_FlushStore.htm

**Comment by merceyz** [comment] 2018-02-05 15:23
I'm not able to reproduce this issue (Latest commit https://github.com/cefsharp/CefSharp/commit/7802653fb161e9238c19f829435f575d78d33832 )

`Cef.GetGlobalCookieManager().DeleteCookies(string.Empty, string.Empty);`
The call to this function is synchronous,

If you add a callback the call is still synchronous but:
`If |callback| is non-NULL it will be executed asnychronously on the IO thread after the cookies have been deleted`

`it` is your callback

**Comment by amaitland** [comment] 2018-02-05 23:27
> If you add a callback the call is still synchronous but:

Do you mean `asynchronous`? Looking at the code and cookies are always deleted in an `async` fashion. Maybe there's some documentation that needs to be updated?

**Comment by merceyz** [comment] 2018-02-06 08:00
No, I don't.
http://magpcss.org/ceforum/apidocs3/projects/(default)/CefCookieManager.html#DeleteCookies(constCefString&,constCefString&,CefRefPtr<CefDeleteCookiesCallback>)
Doesn't specify that it is `asynchronous`, only that the callback is.

Looking at the source I agree, in which case @singhprab you can wait on
https://github.com/cefsharp/CefSharp/blob/9407ba1828b473b7186e33c139bf776701460f1b/CefSharp/AsyncExtensions.cs#L21-L41

Also the existance of `DeleteCookiesAsync` makes it seem like `DeleteCookies` is sync

**Comment by amaitland** [comment] 2018-02-07 14:55
Fair point, I'll look at updating the xml doc to make it clearer that it's async and the call back is used for notification of completion.

**Comment by amaitland** [comment] 2018-02-08 01:06
I've updated the `xml doc`, hopefully it's clearer that these methods are executed in a `async` fashion, https://github.com/cefsharp/CefSharp/commit/4d4607f24ae1bc8fa355c5af55514da17c573b21

I would recommend calling `FlushStore` before exit and waiting for it to complete, that should hopefully ensure cookies are persisted.

**Comment by amaitland** [comment] 2018-02-13 03:05
Closing this, if you can provide a `symbolised stack trace` that shows a problem with `CefSharp` it's self then we can reopen.

**Closed by amaitland** 2018-02-13 03:05 UTC
Labels: more-details-needed-from-op
