### ISSUE TITLE
Crash with many tabs by WPF sample in Win 10 x64

### ISSUE THREAD

**Issue by xjfhnsd** [cefsharp/CefSharp#2800] opened 2019-06-03 18:39 UTC
I'm using the latest stable verion 73, WPF sample

Reproduce :
1. open 10 tabs
2. visit www.qq.com in every tab
3. it will crash or some tabs content turn to white/empty

**Comment by amaitland** [comment] 2019-06-03 20:26
Duplicate of https://github.com/cefsharp/CefSharp/issues/2779

**Closed by amaitland** 2019-06-03 20:26 UTC
