### ISSUE TITLE
No way to put cefsharp files in subdirectory anymore

### ISSUE THREAD

**Issue by Xan-Kun** [cefsharp/CefSharp#4831] opened 2024-06-10 22:28 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

125.0.210

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET 8

### Implementation

WinForms

### Reproduction Steps

In a `SelfContained` `WinForms` `x64` project, use any method mentioned anywhere (docs, github, SO)  with the current cefsharp version and it will be impossible to put the cefsharp spedific files into a subdirectory.
Not even moving them in an AfterBuild target will work.
Various crashes, from "Breakpint has been reached" to not finding DLLs that are there.
And locales are copied twice, one extra time from the example project in a AfterBuild target. (?)

I'm pretty sure this is a bug (since it destroyed 3 of my projects and I have to migrate to WebView2 real quick now), but if it's not, I would be really interested in why 🤔 

### Expected behavior

ANY way (no matter how cumbersome) to put the cefsharp files into a dedicated subdirectory.

### Actual behavior

It is impossible, atm.

### Regression?

Worked perfectly with `CefSharpTargetDir`.

### Known Workarounds

None. (Some of the older forum entries had a workaround, but none of them are functioning anymore)

### Does this problem also occur in the CEF Sample Application

Yes using WinForms command line args

### Other information

Funnily, `libcef.dll` has to be in at least two places now, to make `LocalesDirPath` work at all. 😄

**Comment by amaitland** [comment] 2024-06-11 02:32
Closing as duplicate of #4813

**Closed by amaitland** 2024-06-11 02:32 UTC

**Comment by HaukHuang** [comment] 2024-06-29 13:38
> [关闭#4813](https://github.com/cefsharp/CefSharp/issues/4813)的重复内容[](https://github.com/cefsharp/CefSharp/issues/4813)

If you close this question, please provide an answer。
I also searched for a long time but couldn't find the correct answer.
