### ISSUE TITLE
js cross domain error

### ISSUE THREAD

**Issue by gitlsl** [cefsharp/CefSharp#1225] opened 2015-08-27 08:05 UTC
i open an url like    "http://www.aaaaa.com"    and it has a iframe "http://cc.cc.com"

i can not use javascript control   the ifame's dom    it say  cross domain error,

in ie  it has same problem, i find the solution already
is there has any idea work it fine in cefsharp
sorry for my english  wish your help

**Comment by jankurianski** [comment] 2015-08-27 08:18
* Are you using WinForms, WPF or OffScreen control?
* What version of CefSharp are you using?
* Please provide complete steps to reproduce the problem in one of the CefSharp example projects

**Comment by amaitland** [comment] 2015-08-27 08:55
Try `Cef.AddCrossOriginWhitelistEntry`, I've never used it personally, so I don't have a sample. The documentation is fairly extensive.

https://github.com/cefsharp/CefSharp/blob/cefsharp/41/CefSharp.Core/Cef.h#L230

**Comment by amaitland** [comment] 2015-08-27 08:58
@gitlsl As a general rule please provide the information @jankurianski has requested, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#what-should-i-include-when-creating-an-issue for a complete rundown

**Comment by gitlsl** [comment] 2015-08-28 00:54
@jankurianski 
  <package id="cef.redist.x64" version="3.2272.32" targetFramework="net40" />
  <package id="cef.redist.x86" version="3.2272.32" targetFramework="net40" />
  <package id="CefSharp.Common" version="41.0.1" targetFramework="net40" />
  <package id="CefSharp.WinForms" version="41.0.1" targetFramework="net40" />

my steps:
1.webBrowser = new ChromiumWebBrowser("http://110.alibaba.com/policeHall/hallIndex.htm")
2.when it open compelete, click the "login" at   top right, then an iframe will be show and it's src is "https://passport.alibaba.com/mini_login.htm", it's ID is 'alibaba-login-box'     i want to input my account by js  
3.i run     var result =  webBrowser.EvaluateScriptAsync("document.getElementById('alibaba-login-box').contentWindow.window.document");
but the result.Result.Message is "Uncaught SecurityError: Blocked a frame with origin "http://110.alibaba.com" from accessing a cross-origin frame."

@amaitland 
            Cef.Initialize(new CefSettings() { Locale = "zh-CN" });
            Cef.AddCrossOriginWhitelistEntry("https://passport.alibaba.com", "https", string.Empty, true);
            Cef.AddCrossOriginWhitelistEntry("https://passport.alibaba.com", "http", string.Empty, true);
            Cef.AddCrossOriginWhitelistEntry("http://110.alibaba.com", "http", string.Empty, true);
            Cef.AddCrossOriginWhitelistEntry("http://110.alibaba.com", "https", string.Empty, true);
i try AddCrossOriginWhitelistEntry   but it is error 3q

**Comment by amaitland** [comment] 2015-08-28 01:02
Did you check the result of `Cef.AddCrossOriginWhitelistEntry`? Did it return `true`?

**Comment by gitlsl** [comment] 2015-08-28 01:05
@amaitland  yes  i get AddCrossOriginWhitelistEntry's result  is true

**Comment by amaitland** [comment] 2015-08-28 01:07
@gitlsl You can also try disabling web security using `BrowserSettings.WebSecurityDisabled` or use the `--disable-web-security` command line argument.

Those are my only two suggestions. You should also try searching on http://magpcss.org/ceforum/

**Comment by gitlsl** [comment] 2015-08-28 01:12
@amaitland  thank you i see

**Comment by amaitland** [comment] 2015-09-16 02:11
@gitlsl Anything else before closing?

**Comment by amaitland** [comment] 2015-09-21 00:48
Closing due to lack of feedback.

**Closed by amaitland** 2015-09-21 00:48 UTC
