### ISSUE TITLE
Support for D3D texture/surface provided by the client

### ISSUE THREAD

**Issue by ekalchev** [cefsharp/CefSharp#2548] opened 2018-10-22 16:15 UTC
CEF now support D3D texture/surface provided by the client. https://bitbucket.org/chromiumembedded/cef/issues/1006/cef3-support-rendering-to-a-hardware-gl

It seems it is already part of CEF branch 3497. 

It took 5 years this to be added to CEF. If this works correctly it will be huge for any modern application on windows using WPF. Any plans this to be supported by CefSharp WPF control soon?

**Comment by ekalchev** [comment] 2018-10-22 16:28
Here the details of actuall PR which added support for this feature. https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/diff

I wonder if this line if only needed to activate this feature?

info.shared_texture_enabled = true;

**Comment by amaitland** [comment] 2018-10-22 19:52
Closing as duplicate of #2527

**Closed by amaitland** 2018-10-22 19:52 UTC
