### ISSUE TITLE
App slow to close when using RegisterJsObject in version >=43

### ISSUE THREAD

**Issue by MartySVK** [cefsharp/CefSharp#1304] opened 2015-09-29 15:58 UTC
Hi,
after upgrade cefsharp to 43 (winforms) and I have a problem with closing my program. It takes about 10 seconds.
The problem is with RegisterJsObject. I have no idea, why it is happening, but when I delete the line with RegisterJsObject, everything is fine.
It does not matter, if website contain function or not. After first load of website, the program has problem with closing.

But I can not reproduce this fault on your minimal example.
Any idea where could be the problem?

```
chromeBrowser = new ChromiumWebBrowser(String.Empty);
chromeBrowser.RegisterJsObject("jscall", this, false);
```

**Comment by amaitland** [comment] 2015-09-29 22:11
Likely relates to the `WCF` channel timing out rather than closing properly.

Can you provide an example to reproduce the problem? Are you using popups?

**Comment by MartySVK** [comment] 2015-09-30 10:23
No, I am not using popups. I will try to provide example asap, but probably tomorrow.

**Comment by amaitland** [comment] 2015-09-30 11:29
The line that blocks is likely https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/ManagedCefBrowserAdapter.h#L104

Basically the `WCF` service has a `10 second` time out before it closes. Under normal circumstances it will close without issue, obviously in this case something is keeping it open. The last time this problem occurred was because of popups not being closed. If your not using popups then there will be something else causing the problem.

**Comment by expertsonline** [comment] 2015-09-30 12:22
The below simple example shows the 10 second close issue.
Winforms App with CefSharp 43.0.0.0 from Nuget.

```C#
    public partial class Form1 : Form
    {
        private ChromiumWebBrowser browser;
        public Form1()
        {
            InitializeComponent();
            browser = new ChromiumWebBrowser("about:blank")
            {
                Dock = DockStyle.Fill,
            };
            browser.RegisterJsObject("jsBind", new JSBinding());
            browserPanel.Controls.Add(browser);
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            Cef.Shutdown();
            Application.Exit();
        }
    }

    public class JSBinding
    {
        public string temp = "";

        public string getTemp()
        {
            return temp;
        }

        public void setTemp(string value)
        {
            this.temp = value;
        }
    }
```

**Comment by amaitland** [comment] 2015-10-01 00:38
Try disposing of the browser instance before you exit. 

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/BrowserForm.cs#L115

Also if you can work the `MinimalExample` project to demo the problem that would make things easier to debug.

**Comment by expertsonline** [comment] 2015-10-01 01:04
Disposing also has the same issue.

Amended code.

```C#
private void btnExit_Click(object sender, EventArgs e)
        {
            var sw = Stopwatch.StartNew();
            if(browser != null)
                browser.Dispose();
            var time = sw.ElapsedMilliseconds;
            Cef.Shutdown();
            Console.WriteLine(String.Format("Dispose: {0}, Shutdown: {1}",time,sw.ElapsedMilliseconds - time));
            Application.Exit();
        }
```

Output
```
Dispose: 11052, Shutdown: 21
```

**Comment by amaitland** [comment] 2015-10-01 01:27
> Is there a way to manually terminate/unbind the JS object before disposing?

No, it's not that simple, the object isn't the relevant part, it's the underlying `WCF` channel that's not closing.

If you can fork the `MinimalExample` I'll have at look further.

**Comment by expertsonline** [comment] 2015-10-01 13:49
Sure - Have forked it here : https://github.com/expertsonline/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/BrowserForm.cs#L27

Simply adding a binding allows the issue to be reproduced.

**Comment by amaitland** [comment] 2015-10-01 20:25
> Simply adding a binding allows the issue to be reproduced.

Steps to reproduce? I'm not seeing a problem, I pulled in your changes, recompiled, ran `CefSharp.MinimalExample.WinForms`, I'm using `VS2013u4 Community)

**Comment by MartySVK** [comment] 2015-10-02 07:18
Did you try to close the program with file->exit ?

**Comment by amaitland** [comment] 2015-10-02 12:11
Are you both calling `Dispose` and `Cef.Shutdown()` as per the example?

For now it's probably worth letting `CefSharp` dispose/shutdown for you if possible (there are a few cases where this isn't going to work)

https://github.com/cefsharp/CefSharp.MinimalExample/commit/aab09ca804e44729f403ac70317dd8229c223c8e

**Comment by MartySVK** [comment] 2015-10-02 12:32
Yes, I do.
```
        {
            chromeBrowser.Dispose();
            Cef.Shutdown();
            Application.Exit();
        }
```

**Comment by amaitland** [comment] 2015-10-03 08:52
> Yes, I do.

Try calling `Close()` on your form, if your lucky the rest should just happen for you (and by the rest I mean disposing of the browser and shutting down `CEF`)

**Comment by MartySVK** [comment] 2015-10-05 07:39
Sorry, but it didn't help.

**Comment by amaitland** [comment] 2015-10-05 09:49
So your code now looks like?

```c#
{
  //chromeBrowser.Dispose();
  //Cef.Shutdown();
  //Application.Exit();
  Close();
}
```

**Comment by mattjhammond** [comment] 2015-10-05 23:10
I see this issue in 43 and by simply running the SimpleBrowserForm in the WinForms.Example from https://github.com/cefsharp/CefSharp/commit/ac4df2e7c59a791c8628f88ccb2c35a9343144fa.

**Comment by amaitland** [comment] 2015-10-05 23:30
> I see this issue in 43 and by simply running the SimpleBrowserForm in the WinForms.Example from ac4df2e

For clarity that commit references the `master` branch, the `43` branch is https://github.com/cefsharp/CefSharp/tree/cefsharp/43

Any fix will need to be targeted against `43` (there is no release based on `master` yet).

> The browser.Dispose() call is what is hanging for about 10 seconds.

It should be exactly `10 seconds` as that's the default `WCF` timeout for closing the host.

Using the example below works fine for me, it might not work in all scenarios (it works in the standard `CefSharp.WinForms.Example` app as it doesn't dispose the browser explicitly.

https://github.com/cefsharp/CefSharp.MinimalExample/commit/aab09ca804e44729f403ac70317dd8229c223c8e

**Comment by mattjhammond** [comment] 2015-10-05 23:39
My intention was to indicate that the issue existed in 43 with my application and in the example in the master.  I commented the dispose and shutdown calls and it appears to work.

**Comment by amaitland** [comment] 2015-10-06 01:13
Looks like the problem only appears in the `WinForms` version. Likely a timing issue.

Possible workarounds
- Change `Close()` to `Abort()` for the `WCF` channel, not sure about this option, it may have some side effects
- Change `Close` to use a smaller `Timeout` which will still have the problem
- Make timeout configurable, using `CefSharpSettings` class, could call `Abort` if timeout is `0`

Someone will need to investigate the problem further, doesn't look like the `BrowserSubProcess` is calling `OnBrowserDestroyed`

https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.BrowserSubprocess/CefRenderProcess.cs#L101

**Comment by amaitland** [comment] 2015-10-06 01:17
Relevant code that blocks is https://github.com/cefsharp/CefSharp/blob/cefsharp/43/CefSharp.Core/ManagedCefBrowserAdapter.h#L104

**Comment by MartySVK** [comment] 2015-10-06 09:22
Hi,
can you please check my simple application ?
https://github.com/MartySVK/TestCefSharpJS

**Comment by amaitland** [comment] 2015-10-06 11:57
The sample I provided was for a close button handler, try removing your closing handler altogether. You may need to move your Initialize code into program main.

https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L15

I'm not near Visual Studio at the moment, so will test it later :+1:

**Comment by amaitland** [comment] 2015-10-08 09:11
Removing the `Dispose/Shutdown` calls and letting the framework handle them seems to be working in your very simple demo.

https://github.com/amaitland/TestCefSharpJS/commit/e6adb8dddc2921fc121fbf2449ff52c927ff4db4

**Comment by MartySVK** [comment] 2015-10-08 12:11
Hi, when I remove Dispose/Shutdown, it is working, but is it safe to calling Initialize and not Shutdown ?

**Comment by amaitland** [comment] 2015-10-08 12:26
> it is working, but is it safe to calling Initialize and not Shutdown ?

`CEF` requires that you call `Shutdown`, and for that reason `CefSharp` will by default call `Shutdown` for you.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/ChromiumWebBrowser.cs#L76
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L208

**Comment by amaitland** [comment] 2015-10-08 12:30
For most cases this is hopefully a functional workaround. At some stage someone will need to investigate the problem further.

**Comment by amaitland** [comment] 2015-10-08 12:44
I've added the option to specify the Timeout to `master`

https://github.com/cefsharp/CefSharp/commit/d1ba723bd51c01a926a5fa6209de9358734f795e

Still just a workaround for the underlying problem.

**Comment by culmencasa** [comment] 2016-03-31 08:54
i add this works
                form.Controls.Remove(browser);

**Comment by kpko** [comment] 2016-06-01 21:42
I've just experienced the same problem with v49.0.1. @culmencasa 's Workaround with removing the control in my Form_Close handler fixes this issue.

**Comment by dandotevans** [comment] 2016-07-26 12:43
I've seen this issue appear in our project since release v49. 

am able to workaround using below code in the formclose handler. 

```
                CefSharpSettings.WcfTimeout = new TimeSpan(0);
                Browser.Dispose();
                Application.DoEvents();
                CefSharpSettings.WcfTimeout = new TimeSpan(0,0,0,10);
```

not sure if that is how the timeout what intended to be used.. 
What is Wcf used for, Communication with JS?

**Comment by amaitland** [comment] 2016-08-02 23:07
@dandotevans Simple set `WcfTimeout` to `Zero` early on in your app would be sufficient. No need to reset.

> What is Wcf used for, Communication with JS?

`Javascript Binding` uses `WCF` for communication. Switch to the `async` version and it will only use the `native IPC` (and is faster).

**Comment by merceyz** [comment] 2016-12-14 01:29
Using OffScreen 55.0.0-CI2071 I started getting issues after using RegisterJsObject.
However instead of taking a long time to close, it just crashes.
It might be somewhat relevant to this issue.

```
OS: Windows 7, 64bit
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ServiceModel.CommunicationObjectFaultedException
   at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan)
   at System.ServiceModel.Channels.ServiceChannelFactory.OnClose(System.TimeSpan)
   at System.ServiceModel.Channels.ServiceChannelFactory+TypedServiceChannelFactory`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnClose(System.TimeSpan)
   at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan)
   at System.ServiceModel.ChannelFactory.OnClose(System.TimeSpan)
   at System.ServiceModel.Channels.CommunicationObject.Close(System.TimeSpan)
   at CefSharp.BrowserSubprocess.WcfEnabledSubProcess.OnBrowserDestroyed(CefSharp.CefBrowserWrapper)
   at <Module>.CefSharp.CefAppUnmanagedWrapper.OnBrowserDestroyed(CefSharp.CefAppUnmanagedWrapper*, CefRefPtr<CefBrowser>*)
   at <Module>.CefExecuteProcess(CefMainArgs*, CefRefPtr<CefApp>*, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])


```

**Comment by vovanre** [comment] 2016-12-16 18:36
Small hack:

```
Browser.Parent.Dispose();
Cef.Shutdown();
```

**Comment by ccnucheng** [comment] 2017-01-03 02:12
`CefSharpSettings.WcfEnabled = false;`
`Cef.Shutdown();`

**Comment by amaitland** [comment] 2017-01-03 05:47
> CefSharpSettings.WcfEnabled = false;

Setting `WcfEnabled` to `false` before calling `Shutdown` may lead to an undesired result so beware. https://github.com/cefsharp/CefSharp/blob/11dee93bf331f012dd6416fb2f2162549d9137a3/CefSharp.Core/ManagedCefBrowserAdapter.h#L90

**Comment by amaitland** [comment] 2018-05-02 04:47
Closing as I've not seen reports of this in quite some time. Anyone experiencing this problem should set 

```c#
CefSharpSettings.WcfTimeout = new TimeSpan(0);
```

Before you create the first `ChromiumWebBrowser` instance. The` WCF` channel will be aborted and won't wait for close.

**Closed by amaitland** 2018-05-02 04:47 UTC
Labels: winforms
