### ISSUE TITLE
WPF application crashes when closing a PDF containing XFA form

### ISSUE THREAD

**Issue by abid76** [cefsharp/CefSharp#4701] opened 2024-02-02 09:39 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

120.2.70

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.Net 4.8

### Implementation

WPF

### Reproduction Steps

The application CefSharp.Wpf.Example crashes when closing a tab which contains some kind of XFA form. Until now this only occurs when the XFA form triggers a JsDialogHandler (at least I had no issues with forms without a JS-Dialog). Maybe it's also related to PDF version 1.7 (with version 1.6 I had no issues).

I have exactly the same problem in my own application when closing a tab.

Steps to reproduce:
1. Start CefSharp.Wpf.Example
2. Open the attached file. [Grusi Weiterbewilligungsantrag.pdf](https://github.com/cefsharp/CefSharp/files/14137524/Grusi.Weiterbewilligungsantrag.pdf) (**You have to open it from local filesystem**, otherwise the file isn't displayed at all, just a file dialog is opened)
3. Close the tab -> the application crashes. The VS output says: `Das Programm "[36100] CefSharp.Wpf.Example.exe" wurde mit Code 3221225477 (0xc0000005) 'Access violation' beendet.`

### Expected behavior

The tab can be closed without any issues.

### Actual behavior

Application crashes.
`Das Programm "[36100] CefSharp.Wpf.Example.exe" wurde mit Code 3221225477 (0xc0000005) 'Access violation' beendet.`

Log file: 
[debug.log](https://github.com/cefsharp/CefSharp/files/14137748/debug.log)

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

When using the CEF Sample Application(cefclient) application it already crashes when opening the PDF file.

**Comment by amaitland** [comment] 2024-02-03 01:15
> Does this problem also occur in the CEF Sample Application
> Yes using WPF/OffScreen command line args
> 
> Other information
> When using the CEF Sample Application(cefclient) application it already crashes when opening the PDF file.

As the problem is within CEF, not directly in `CefSharp`. You'll need to raise an issue at https://github.com/chromiumembedded/cef/issues  (Post a link back here for reference). Closing as `upstream`

**Closed by amaitland** 2024-02-03 01:15 UTC
Labels: upstream

**Comment by amaitland** [comment] 2024-02-09 19:59
Upstream issue https://github.com/chromiumembedded/cef/issues/3644

I'd suggest you add any additional relevant information there.

**Comment by abid76** [comment] 2024-03-01 09:56
In reference to your answer https://github.com/cefsharp/CefSharp/issues/4701#issuecomment-1924994199

The issue of crashing cef when **opening** the PDF form [is fixed now](https://github.com/chromiumembedded/cef/issues/3644).

But my problem still persists: the _CefSharp.Wpf.Example_ application crashes when it's **closed** or when the tab containing the PDF form is **closed**. It's still the same like in the issue description above.

This problem **does not occur** when opening and closing the PDF form in the _CefSharp.MinimalExample.Wpf_ application. The application closes normally without any `Access violation` message.

As this only seems to occur in a WPF tabbed application I am not sure how to report it in [cef issue tracker](https://github.com/chromiumembedded/cef/issues).

Can you give me any advice? Do you need some additional information?

**Output CefSharp.Wpf.Example (starting directly before the PDF form is opened).** ([debug.log](https://github.com/cefsharp/CefSharp/files/14459398/debug.log))

```
"CefSharp.Wpf.Example.exe" (CLR v4.0.30319: CefSharp.Wpf.Example.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.ServiceModel.resources.dll" geladen. Das Modul wurde ohne Symbole erstellt.
Der Thread 0x402c hat mit Code 0 (0x0) geendet.
Der Thread 0x1554 hat mit Code 0 (0x0) geendet.
Der Thread 0x3c58 hat mit Code 0 (0x0) geendet.
Der Thread 0x2fc0 hat mit Code 0 (0x0) geendet.
"CefSharp.Wpf.Example.exe" (CLR v4.0.30319: CefSharp.Wpf.Example.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll" geladen. 
Der Thread 0x8620 hat mit Code 0 (0x0) geendet.
Der Thread 0x46fc hat mit Code 0 (0x0) geendet.
Das Programm "[15912] CefSharp.Wpf.Example.exe" wurde mit Code 3221225477 (0xc0000005) 'Access violation' beendet.
```

**Output CefSharp.MinimalExample.Wpf (starting directly before the PDF form is opened).** ([debug.log](https://github.com/cefsharp/CefSharp/files/14459394/debug.log))

```
"CefSharp.MinimalExample.Wpf.exe" (CLR v4.0.30319: CefSharp.MinimalExample.Wpf.exe): "C:\Windows\system32\WinMetadata\Windows.UI.winmd" geladen. Das Modul wurde ohne Symbole erstellt.
"CefSharp.MinimalExample.Wpf.exe" (CLR v4.0.30319: CefSharp.MinimalExample.Wpf.exe): "C:\Windows\system32\WinMetadata\Windows.Foundation.winmd" geladen. Das Modul wurde ohne Symbole erstellt.
"CefSharp.MinimalExample.Wpf.exe" (CLR v4.0.30319: CefSharp.MinimalExample.Wpf.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.WindowsRuntime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.WindowsRuntime.dll" geladen. Das Modul wurde ohne Symbole erstellt.
"CefSharp.MinimalExample.Wpf.exe" (CLR v4.0.30319: CefSharp.MinimalExample.Wpf.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.WindowsRuntime\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.WindowsRuntime.dll" geladen. Das Laden von Symbolen wurde übersprungen. Das Modul ist optimiert, und die Debugoption "Nur eigenen Code" ist aktiviert.
[0301/104045.677:ERROR:browser_info_manager.cc(629)] Timeout of new browser info response for frame 30064771076 [7,4]
[0301/104045.840:INFO:CONSOLE(0)] "Unchecked runtime.lastError: Not implemented", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (0)
Der Thread 0x18e4 hat mit Code 0 (0x0) geendet.
"CefSharp.MinimalExample.Wpf.exe" (CLR v4.0.30319: CefSharp.MinimalExample.Wpf.exe): "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll" geladen. 
Der Thread 0x6974 hat mit Code 0 (0x0) geendet.
Der Thread 0x4c0c hat mit Code 0 (0x0) geendet.
Der Thread 0x8b44 hat mit Code 0 (0x0) geendet.
Das Programm "[10656] CefSharp.MinimalExample.Wpf.exe" wurde mit Code 0 (0x0) beendet.
```

**Comment by amaitland** [comment] 2024-03-04 20:40
https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#unmanaged-crashes-when-the-process-dies

**Comment by abid76** [comment] 2024-03-09 11:39
After upgrading to recent version 121.3.130 the problem disappeared :-) 
Now, in CefSharp.Wpf.Example a tab containing the file https://github.com/cefsharp/CefSharp/files/14137524/Grusi.Weiterbewilligungsantrag.pdf can be closed without crashing the application.
