### ISSUE TITLE
WinForms/WPF does not work when packaged as WAP (Desktop Bridge) project.

### ISSUE THREAD

**Issue by srdjanjovcic** [cefsharp/CefSharp#2642] opened 2019-02-04 23:20 UTC
- *What version of the product are you using?* **Latest NuGet package.**
- *What architecture x86 or x64?* **AnyCPU**
- *On what operating system?* **Win10**
- *Are you using `WinForms`, `WPF` or `OffScreen`?* **WinForms, packaged as WAP (see [Package a desktop application by using Visual Studio](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net)).**

- *What steps will reproduce the problem?* **Attempt to create a WAPPROJ to package WinForms app which uses CefSharp, and also uses AnyCPU architecture, as described in #1714.**

I think that issue comes from the fact that *.targets and *.props files which ship with NuGet package add a backslash after  $(CefSharpTargetDir), as seen here:

```
	<None Include="@(CefSharpCommonBinaries64)">
          <Link>$(CefSharpTargetDir)\%(RecursiveDir)%(FileName)%(Extension)</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
```
When `$(CefSharpTargetDir)` is not set (as it is a default), `<Link>` metadata ends up starting with `\`, which causes those files to be included into root folder of APPX package, and application cannot find them.

I didn't test this further, but I believe that fix would be to 

a) Remove backslash between `$(CefSharpTargetDir)` and `%(RecursiveDir)` in all `<Link>` attributes.
b) Add MSBuild code to ensure that `$(CefSharpTargetDir)` is always terminated with a backslash (if specified).

**Comment by amaitland** [comment] 2019-02-07 03:27
> What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like Latest from Nuget) e.g. 57.0.0 or 63.0.0-pre01

As per https://github.com/cefsharp/CefSharp/blob/cefsharp/71/ISSUE_TEMPLATE.md#bug-report please specify the exact version you are using, **Latest NuGet package** is relative and will be inaccurate as soon as the next version is released.

> * and also uses AnyCPU architecture, as described in #1714.

There are three options listed for `AnyCPU`, please specify which one you are using.

> I think that issue comes from the fact that *.targets and *.props files which ship with NuGet package add a backslash after $(CefSharpTargetDir), as seen here:

The `<None/>` entries in `CefSharp.Common.props` shouldn't actually be there, thanks for highlighting that. They have been removed in https://github.com/cefsharp/CefSharp/commit/3c650a012164438f30c6ec71a548b5c918db079c

> I didn't test this further, but I believe that fix would be to
> 
> a) Remove backslash between `$(CefSharpTargetDir)` and `%(RecursiveDir)` in all `<Link>` attributes.
> b) Add MSBuild code to ensure that `$(CefSharpTargetDir)` is always terminated with a backslash (if specified).

You can easily test this

- Actually specify a value for `$(CefSharpTargetDir)` and modify the `AnyCPU` option you have chosen (I have no idea which one you chose, so I cannot provide any specifics). This is pretty trivial.
- Manually edit your local cached copy of `.targets` files (unload/reload the solution in `VS` of course).

**Comment by Snorvarg** [comment] 2019-05-19 20:57
jeffxpx, I can confirm your solution/hack is working. I had exactly the same problem as srdjanjovcic, but I use the "Windows Application Packaging Project" for creating an appxbundle.

**Comment by johot** [comment] 2019-08-27 18:15
I can also confirm I got a desktop bridge sample working using the info found here, thank you!

Before doing the following I got an error saying, when running the desktop bridge project (running the regular WinForms project would work):
```
Could not load file or assembly 'CefSharp.WinForms, Version=75.1.141.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.
```

But I have also seen the error referring to `cef.pak` above. Not sure what the reason for that was, but it had the same solution, setting `$(CefSharpTargetDir)`.

## What I did then (using the instructions here) was:
* Cloned out: `https://github.com/cefsharp/CefSharp.MinimalExample.git`
* Removed the WPF and OffScreen projects (I wanted to use WinForms for best performance)
* Used `x64` (the default for the Minimal example)
* Edited the `CefSharp.MinimalExample.WinForms.csproj` file by adding (to the bottom of the first `<PropertyGroup>`:
```xml
<CefSharpTargetDir Condition=" '$(CefSharpTargetDir)' == '' ">.</CefSharpTargetDir>
```

Not sure what the best solution regarding x86 vs x64 would be when submitting to the store, maybe you can submit multiple versions?

Many thanks @jeffxpx @srdjanjovcic @amaitland !

**Comment by Snorvarg** [comment] 2019-08-27 21:34
@johot, we are a bit off of the original question, but you can submit multiple versions. The installer detects which processor user has and install the correct version.

**Comment by johot** [comment] 2019-08-27 22:46
> @johot, we are a bit off of the original question, but you can submit multiple versions. The installer detects which processor user has and install the correct version.

You are correct sorry about that :) I'm just very happy a solution has been found. Will there be a way to fix this for all users you think? I would have been pretty lost without finding this issue :)

**Closed** 2019-10-01 10:54 UTC
Labels: winforms

**Comment by amaitland** [comment] 2019-10-01 10:56
Defaulting `CefSharpTargetDir ` to `.` seems like the easiest option, so we'll go with that for now.
