### ISSUE TITLE
CefSharp.BrowserSubprocess.exe . Restart and Reload the loaded page.

### ISSUE THREAD

**Issue by bicossampalis** [cefsharp/CefSharp#2201] opened 2017-11-24 08:34 UTC
We are using cefsharp and we have produced a User Control which is hosted inside our application. The parent form is a MDI Form (DevExpress).
Everything works fine until we drag the Parent Form outside the MDI Container.
Process of ChromeBrowser instance (which is embedded inside the MDI Form) (CefSharp.BrowserSubprocess.exe) is killed and a new one starts which causes an effect to reload the projects content inside the WebView.
This is not good for our application's flow.
Any idea why this is happening and how we will prevent it?

**Comment by perlun** [comment] 2017-11-30 19:41
@bicossampalis Do you use CefSharp Windows Forms or WPF?

**Comment by merceyz** [comment] 2017-12-01 08:04
This seems related to #2042

**Comment by amaitland** [comment] 2017-12-18 23:46
Closing as duplicate of https://github.com/cefsharp/CefSharp/issues/2042

**Closed by amaitland** 2017-12-18 23:46 UTC
Labels: more-details-needed-from-op
