### ISSUE TITLE
CefSharp.BrowserSubprocess has stopped working

### ISSUE THREAD

**Issue by dem219** [cefsharp/CefSharp#1393] opened 2015-10-30 15:58 UTC
I am using WinForms version 41.0.1

Occassionally when our application is shutdown, and error dialog gets displayed with the following messge, 

"CefSharp.BrowserSubprocess has stopped working
A problem caused the progam to stop working correctly. Please close the program.'

There is no other impact to users.  The application continues to run correctly the next time.  There is nothing of relevance in the debug.log file when this happens.

When shutting down, the following is always called:
CefSharp.Cef.Shutdown();

Any known reason for this?  Any other info I can gather?  Or any way I can suppress these dialogs, even if it requires modifying the source code?

Thanks

**Comment by amaitland** [comment] 2015-10-31 00:26
> I am using WinForms version 41.0.1

Does the problem reproduce using the latest release? (`43.0.1`). See https://github.com/cefsharp/CefSharp/wiki/CefSharp-43 for information on upgrading.

> Any known reason for this?

Not enough information to provided.

> Any other info I can gather?

If it's reproducible then you can attach the debugger to the running sub process with the corresponding source.

> Or any way I can suppress these dialogs, even if it requires modifying the source code?

Unlikely, the process has crashed for some reason.

**Comment by amaitland** [comment] 2015-11-04 07:50
@dem219 Are you able to provide more information?

**Comment by dem219** [comment] 2015-11-06 16:34
I have not been able to reproduce the issue, it only happens sporadically.

**Comment by dem219** [comment] 2015-11-06 17:04
I was just able to finally get an exception snapshot - 

System.ServiceModel.CommunicationObjectFaultedException was unhandled
  HResult=-2146233087
  Message=The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
  Source=System.ServiceModel
  StackTrace:
       at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
       at System.ServiceModel.Channels.ServiceChannelFactory.OnClose(TimeSpan timeout)
       at System.ServiceModel.Channels.ServiceChannelFactory.TypedServiceChannelFactory`1.OnClose(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
       at System.ServiceModel.ChannelFactory.OnClose(TimeSpan timeout)
       at System.ServiceModel.Channels.CommunicationObject.Close(TimeSpan timeout)
       at CefSharp.BrowserSubprocess.CefRenderProcess.OnBrowserDestroyed(CefBrowserWrapper browser)
       at CefSharp.CefAppUnmanagedWrapper.OnBrowserDestroyed(CefAppUnmanagedWrapper* , CefRefPtr<CefBrowser>* browser)
       at CefExecuteProcess(CefMainArgs* , CefRefPtr<CefApp>* , Void* )
       at CefSharp.CefAppWrapper.Run()
       at CefSharp.BrowserSubprocess.Program.Main(String[] args)
  InnerException:

**Comment by amaitland** [comment] 2015-11-06 20:06
You'll need to upgrade to `43.0.1` to resolve this. (The `41.0.x` branch is no longer supported).

**Comment by dem219** [comment] 2015-11-06 20:32
Handling the breaking changes btw the versions is a moderate amount of work for us.  

I am willing to upgrade, if there is a reason to believe this issue is fixed in 43.0.1.  But if I should upgade just because that is latest release, then I'll need to wait until we have more time.

**Comment by amaitland** [comment] 2015-11-06 20:53
> Handling the breaking changes btw the versions is a moderate amount of work for us.

Whilst it looks like a daunting task, it's mostly trivial stuff from the end users point of view. If there is something you can't find then searching the code should locate things quite quickly. 

Also read https://github.com/cefsharp/CefSharp/wiki/CefSharp-43 (If you find something missing from the wiki entry, feel free to contribute, anyone with a `GitHub` account can contribute).

> I am willing to upgrade, if there is a reason to believe this issue is fixed in 43.0.1. But if I should upgade just because that is latest release, then I'll need to wait until we have more time.

A large portion of the `IPC` was ported over to the native implementation provided by `CEF`, whilst the `WCF` service still exists, it's not nearly as heavily used.

I make no guarantees, at the end of the day it's your call. Does it annoy your users enough to justify the time spent? 

There will likely be another `43.0.x` release in a few weeks, and an upcoming `45.0.0` release, so keeping up to date does have it's advantages in terms of new features and bug fixes.

**Comment by dem219** [comment] 2015-11-06 21:11
Thanks, I will try to update next week.

**Comment by amaitland** [comment] 2015-12-15 01:16
@dem219 Any update?

**Comment by dem219** [comment] 2015-12-15 02:28
Not yet. Upgrade has been on hold behind other work.  But I plan on doing
it later this week or next week.

**Comment by amaitland** [comment] 2016-01-11 02:26
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask follow up questions there. If there is a reproducible bug then we can reopen this issue.

**Closed by amaitland** 2016-01-11 02:26 UTC
Labels: winforms
