### ISSUE TITLE
High CPU usage (>30%) with Facebook Gameroom even at idle

### ISSUE THREAD

**Issue by sydbarrett74** [cefsharp/CefSharp#2116] opened 2017-08-18 19:49 UTC
- **What version of the product are you using?**
57.0.0.0 (bundled with Facebook Gameroom)

- **What architecture x86 or x64?**
x64 Ivy Bridge Core i7 (3630QM); 12GB RAM

- **On what operating system?**
Windows 10 Creators Update 1703

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
unknown

- **What steps will reproduce the problem?**
Playing any game through Facebook Gameroom

- **Please provide any additional information below.**
N/A

**Comment by Spiderpig86** [comment] 2017-08-19 02:55
Also facing the same issue. I suspected it was caused by glyphs like Font-Awesome not every site that uses it has high CPU usage.

**Comment by jankurianski** [comment] 2017-08-20 23:56
CefSharp is a wrapper around CEF.  Please identify whether the issue is unique to CefSharp or is actually a CEF issue by following the steps at the bottom of the issue template ("Does this problem also occur in the CEF Sample Application from ..."):
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

I will close this issue for now as it is probably a CEF issue.

**Closed by jankurianski** 2017-08-20 23:56 UTC

**Comment by heigouxiaobai** [comment] 2018-01-19 08:50
cpu是因为页面渲染图片导致的，如果有动态的图片切换特效，可以尝试吧特效屏蔽看看效果
