### ISSUE TITLE
Hang when opening and closing a File select dialog 

### ISSUE THREAD

**Issue by breagol37** [cefsharp/CefSharp#4879] opened 2024-07-12 15:29 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.70

### Operating System

Windows 11

### Architecture

x64

### .Net Version

.Net 8.0

### Implementation

WPF

### Reproduction Steps

Using CefSharp version 126.2.70.

In a WPF application either display a page (or navigate to a page) that contains an input of type File. 
Select the chose file (Explorer opens as normal)
Either select a file or close explorer. 

Saw this issue in our application so created a very basic application pointing to a test site such as 

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file

Issue was also seen when testing it against the CefSharp.Wpf.Example in this repository and navigating the page to a site that has an input type file. 

### Expected behavior

Selected file is displayed (or Explorer closes) as normal. You can then re select a file or use app as normal. 

### Actual behavior

Application hangs then eventually crashes with CefSharp.Wpf.Example.exe' has exited with code 2147483651 (0x80000003).

### Regression?

Yes works as expected on version 125.0.210

### Known Workarounds

Use version 125.0.210

### Does this problem also occur in the CEF Sample Application

No

### Other information

Can not reproduce in the CEF sample application as that appears to be version 122.1.20 this only seems to appear in 126.2.70

**Comment by amaitland** [comment] 2024-07-12 19:57
Closing as duplicate of #4857

**Closed by amaitland** 2024-07-12 19:57 UTC
