### ISSUE TITLE
Blank Bitmap using LoadHTML - OffScreen

### ISSUE THREAD

**Issue by Robula** [cefsharp/CefSharp#1713] opened 2016-06-16 14:44 UTC
My packages.config:
```
<packages>
  <package id="cef.redist.x64" version="3.2623.1401" targetFramework="net461" />
  <package id="cef.redist.x86" version="3.2623.1401" targetFramework="net461" />
  <package id="CefSharp.Common" version="49.0.1" targetFramework="net461" />
  <package id="CefSharp.OffScreen" version="49.0.1" targetFramework="net461" />
</packages>
```

Attempting to use CefSharp.OffScreen to render a HTML string to a bitmap. The resulting image is just a pure white/blank and I'm not sure why. `LoadHTML()` seems to fire the FrameLoadEnd event, but it just does not render. Using `browser.Load("http://google.co.uk");` successfully generates a Bitmap of the Google homepage. Either I am using `LoadHTML` incorrectly, or there seems to be an issue with it on my environment. My debug.log in /bin/ is empty.

My program is x64 targetting .NET 4.6.1.
My console output:

> Browser Initialized
Loaded: (200) - http://blank/
`<html><head></head><body style="background-color:#ff0000"><h1>Test</h1></body></html>`

```
using CefSharp;
using CefSharp.OffScreen;
using System;
using System.Diagnostics;
using System.Drawing;

namespace CefSharp_POC {
    class Program {
        private static ChromiumWebBrowser browser;

        static void Main(string[] args) {
            bool CefInitialised = Cef.Initialize();
            if (CefInitialised) {
                browser = new ChromiumWebBrowser(string.Empty, automaticallyCreateBrowser: true);
                browser.BrowserInitialized += Browser_BrowserInitialized;
                browser.FrameLoadEnd += Browser_FrameLoadEnd;
            }
            Console.ReadLine();
        }

        private static void Browser_BrowserInitialized(object sender, EventArgs e) {
            Console.WriteLine("Browser Initialized");
            browser.LoadHtml("<html><body style=\"background-color:#ff0000\"><h1>Test</h1></body></html>", "http://blank/");
        }

        private async static void Browser_FrameLoadEnd(object sender, FrameLoadEndEventArgs e) {
            Console.WriteLine("Loaded: (" + e.HttpStatusCode + ") - " + e.Url);
            string savePath = "D:\\chrome_image.bmp";

            Console.WriteLine(await e.Browser.MainFrame.GetSourceAsync());
            Bitmap image = await browser.ScreenshotAsync();
            if (image != null) {
                image.Save(savePath);
                image.Dispose();
                //Cef.Shutdown();
            } else {
                Console.WriteLine("image is null");
            }
        }
    }
}
```
I'd appreciate any help I can get, thank you.

**Comment by amaitland** [comment] 2016-06-16 15:29
I don't have time to look into this. If `browser.Load` works then just use a `Data Uri` instead.

https://github.com/cefsharp/CefSharp/blob/a94bbdd593fb72a2edc92fcfe4987c505802e768/CefSharp.WinForms.Example/BrowserForm.cs#L475

https://developer.mozilla.org/en-US/docs/Web/HTTP/data_URIs

**Comment by Robula** [comment] 2016-06-16 17:12
I attempted to create and register my own ResourceHandler and load that and again it rendered a pure white screen..
Using `browser.Load("data:text/html," + System.Web.HttpUtility.UrlPathEncode(html));` worked beautifully, thank you for that workaround! 👍

**Comment by amaitland** [comment] 2016-07-03 10:48
I tried your code with [cefsharp/51](https://github.com/cefsharp/CefSharp/tree/cefsharp/51) branch and it worked fine (I had to change the output path).

For screenshots I usually suggest lowering the frame rate and ignore the current screenshot just to make sure you've given the browser time to render. You can of course tweak the framerate, for most a number less than 10 will likely give the best result.

```c#
var browserSettings = new BrowserSettings();
browserSettings.WindowlessFrameRate = 1;

Bitmap image = await browser.ScreenshotAsync(true);
```

Closing now, if you can reproduce with the next version (`51.0.0`) then we can look at reopening this.

**Closed by amaitland** 2016-07-03 10:48 UTC
Labels: offscreen

**Comment by Robula** [comment] 2016-07-04 09:56
Thanks @amaitland, I will try your suggestions, especially in regards to setting the frame rate. I've progressed past this issue using `browser.Load()` and running into issues where `browser.Bitmap` is null, and `browser.ScreenshotAsync()` causing "Access violation"s to crash my app! I'm still trying to debug it myself and I will try and compile the 51 branch to see if that resolves it else I'll open a new issue.

Thank you for your help in this matter!

**Comment by amaitland** [comment] 2016-07-04 12:43
> EDIT: Using the NuGet 51-pre package of CefSharp and setting the WindowlessFrameRate property to <=5 has solved all my issues! Big thumbs up @amaitland! :+1: :+1:

If you were using `await` then it's likely that #1672 was the cause of your problem.
