### ISSUE TITLE
Input Korean Text in cefSharp:ChromiumWebBrowser

### ISSUE THREAD

**Issue by chieubkhn** [cefsharp/CefSharp#2004] opened 2017-04-04 09:40 UTC
Hi CefSharp Team,
-I just new member in cefSharp:ChromiumWebBrowser Framewwork and i have a big issue. I create new Wpf project and use a simple cefSharp:ChromiumWebBrowser but when app is running I can't type Korean text in every input text in browser (I can do that if use english text). my issue sinimar this issue: https://github.com/cefsharp/CefSharp/issues/1978
-I have checked few projects and have result like that:
-1.project wpf use WebBrowser : I can type korean text in input text on web.
-2.project wpf use cefSharp:ChromiumWebBrowser : I can't type korean text in input text on web.
-3.project WinForms use WebBrowser : I can type korean text in input text on web.
-4.project WinForms use cefSharp:ChromiumWebBrowser: I can type korean text in input text on web.
-So I think this issue belong cefSharp:ChromiumWebBrowser for wpf version. please help me about this issue. Thanks!

**Comment by merceyz** [comment] 2017-04-04 10:22
Please follow the issue template, most likely a duplicate of #1262

**Closed** 2017-04-04 11:58 UTC
Labels: duplicate
