### ISSUE TITLE
PIPELINE_ERROR  + HW video decode not available for profile 11

### ISSUE THREAD

**Issue by novasdream** [cefsharp/CefSharp#1665] opened 2016-04-19 19:04 UTC
- **What steps will reproduce the problem?**
```
I can reproduce that error accessing whatsapp web ( https://web.whatsapp.com ) and sending a video ( WebM without proprietary codec ) 
```

- **What is the expected output? What do you see instead?**
```
I expect that video will be send without problems.
```

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
```
WinForms.
```

- **What version of the product are you using? On what operating system? x86 or x64?**
```
x64
```

- **What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?**
```

CefSharp.Common.49.0.0-pre02
```

- **Win7, Win 8, Win10, etc?**
```
Win10
```

- **Please provide any additional information below.**
A stack trace if available, any Exception information.
In Console window 
```
[0420/000131:ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
```

- **Does the cef log provide any relevant information?**
(By default there should be a debug.log file in your bin directory)
```

[0419/174450:INFO:CONSOLE(0)] "Creating Application Cache with manifest https://web.whatsapp.com/404.appcache", source: https://web.whatsapp.com/ (0)
[0419/174450:INFO:CONSOLE(0)] "Application Cache Checking event", source: https://web.whatsapp.com/ (0)
[0419/174450:WARNING:browser_accessibility_manager_win.cc(87)] Not firing AX event because of no delegate
[0419/174450:WARNING:browser_accessibility_manager_win.cc(178)] Not firing AX event because of no root_delegate or hwnd
[0419/174451:INFO:CONSOLE(0)] "Application Cache Error event: Manifest fetch failed (404) https://web.whatsapp.com/404.appcache", source: https://web.whatsapp.com/ (0)
[0419/174509:ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
[0419/174527:ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
[0419/175341:ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
```

- **Any other background information that's relevant?** Are you doing something out of the ordinary? 3rd party controls?
```
I see a error in console.
Cache.match() does not support 'ignoreVary' option yet.
```

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
```
Yes Chromium 48.0.2556.0 g304f01a1
```
---
have that issue.

When i upload a WebM file in WPP web.
```
[0419/154802:ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
[0419/154832:ERROR:gpu_video_decode_accelerator.cc(281)] HW video decode not available for profile 11
```

**Comment by amaitland** [comment] 2016-04-19 20:56
@novasdream Please fill out the issue report above and post when your finished.

https://github.com/cefsharp/CefSharp/wiki/Trouble-Shooting#troubleshooting-graphics-video-or-performance-problems

**Comment by amaitland** [comment] 2016-04-19 21:21
Also have you tried googling your error?

**Comment by novasdream** [comment] 2016-04-20 00:19
```
CEF	3.2623.1396.g0451528
Chromium	49.0.2623.110
OS	Windows
WebKit	537.36
JavaScript	4.9.385.33
Flash	
User Agent	Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Command Line	"C:\Importante\Swell--WPP\Swell--WPP-Forms\Swell--WPP-Forms\bin\x64\Release\Swell--WPP-Forms.vshost.exe" --browser-subprocess-path=CefSharp.BrowserSubprocess.exe --no-sandbox --lang=en-US --log-file="C:\Importante\Swell--WPP\Swell--WPP-Forms\Swell--WPP-Forms\bin\x64\Release\debug.log" --enable-system-flash=1 --process-per-tab=1 --disable-surfaces=1 --enable-media-stream=1 --disable-accelerated-video-decode=1 --enable-gpl=0 --allow-running-insecure-content=1 --enable-logging=1 --disable-gpu-vsync=1 --disable-gpu=1
Module Path	C:\Importante\Swell--WPP\Swell--WPP-Forms\Swell--WPP-Forms\bin\x64\Release\libcef.dll
Cache Path	C:\tmp\Swell--WPP-Forms\
```


i will fix my main post in few hours.

**Comment by amaitland** [comment] 2016-04-20 00:52
> [0420/105007:ERROR:gpu_video_decode_accelerator.cc(281)] HW video decode not available for profile 11

I get this when playing the `html5` video from http://www.webmfiles.org/demo-files/ the media plays fine (both video and sound), so maybe a warning more than an error.

**Comment by amaitland** [comment] 2016-04-20 01:16
When I disable the `GPU` the error goes away, so I think it's safe to ignore.

**Comment by novasdream** [comment] 2016-04-20 03:22
biggest problem is 
```
ERROR:render_media_log.cc(20)] MediaEvent: PIPELINE_ERROR demuxer: could not open
```

i really dont understand why that happen to try fix.

**Comment by amaitland** [comment] 2016-04-20 03:46
> i really dont understand why that happen to try fix. |

Marking this as `upstream`, will need to be resolved in `CEF` as it reproduces with `cefclient`.

> Updated main post

Thanks :+1:

**Comment by amaitland** [comment] 2016-04-25 03:33
https://bugs.chromium.org/p/chromium/issues/detail?id=605083#c4

> You need to build with ffmpeg_branding=Chrome proprietary_codecs=1 or their gn equivalents to make this work.

Looks like the solution is to compile with `Proprietary Codecs` enabled.

**Closed by amaitland** 2016-04-25 03:33 UTC
Labels: upstream, wontfix
