### ISSUE TITLE
Context Menu doesn't go away when clicking on anything else

### ISSUE THREAD

**Issue by 7H3LaughingMan** [cefsharp/CefSharp#1892] opened 2016-12-18 15:27 UTC
- **What version of the product are you using?**
Nuget 53.0.0

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Windows 7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Open up any website and than right-click to display the Context Menu. Try clicking on anything else on the page or in another program and note that the Context Menu doesn't go away.

- **What is the expected output? What do you see instead?**
For the Context Menu to disappear when clicking on anything else.

- **Please provide any additional information below.**

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
Does not occur on the `12/14/2016 - CEF 3.2883.1540.gedbfb20 / Chromium 55.0.2883.59` build of the CEF Sample Application.

**Comment by jankurianski** [comment] 2016-12-18 22:07
Looks like dupe of #1795

**Closed by jankurianski** 2016-12-18 22:07 UTC
Labels: duplicate
