### ISSUE TITLE
AccessViolationException when wpf transitioning between browser to different UI item quickly

### ISSUE THREAD

**Issue by bondib** [cefsharp/CefSharp#2013] opened 2017-04-09 11:02 UTC
- **What version of the product are you using?**
CefSharp.WPF v55.0.0 - via nuget
.net 4.5.2

- **What architecture x86 or x64?**
both x86 and x64
- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
Switch wpf browser control using animation or other quickly - on or off and an access violation exception will be thrown.

- **What is the expected output? What do you see instead?**
For it to work without crashing...

- **Please provide any additional information below.**

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Windows.Media.MILUtilities.MILCopyPixelBuffer(Byte* pOutputBuffer, UInt32 outputBufferSize, UInt32 outputBufferStride, UInt32 outputBufferOffsetInBits, Byte* pInputBuffer, UInt32 inputBufferSize, UInt32 inputBufferStride, UInt32 inputBufferOffsetInBits, UInt32 height, UInt32 copyWidthInBits)
   at System.Windows.Media.Imaging.WriteableBitmap.WritePixelsImpl(Int32Rect sourceRect, IntPtr sourceBuffer, Int32 sourceBufferSize, Int32 sourceBufferStride, Int32 destinationX, Int32 destinationY, Boolean backwardsCompat)
   at CefSharp.Wpf.Rendering.WritableBitmapInfo.Invalidate() in c:\projects\cefsharp\CefSharp.Wpf\Rendering\WritableBitmapInfo.cs:line 94
   at CefSharp.Wpf.ChromiumWebBrowser.<>c__DisplayClass13.<CefSharp.Internals.IRenderWebBrowser.InvokeRenderAsync>b__12() in c:\projects\cefsharp\CefSharp.Wpf\ChromiumWebBrowser.cs:line 629
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Shell.App.Main()
```
- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

No - the file is empty.

- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

The application is a power point like application - where switching slides - pefromns transition between different ui items.
In case the UI item is a cef sharp wpf browser - and you switch quickly enough (the browser content did load already) - the issue will occur and crash the appliacrion.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Can't reproduce it there as it doesn't animate between 2 browser components...

**Comment by amaitland** [comment] 2017-04-11 00:02
@bondib Can you provide a demo that reproduces your problem? 

If you have time, download the source and debugging this for yourself will be the quickest way to a solution 👍

**Comment by amaitland** [comment] 2017-05-09 00:39
This issue will be closed in 14 days if there is no further feedback.

**Comment by bondib** [comment] 2017-05-09 07:24
The issue exists. Closing it will not solve it...

________________________________

**Comment by amaitland** [comment] 2017-05-09 08:52
Then provide a sample that reproduces the problem other wise the issue will be closed.

**Comment by amaitland** [comment] 2017-05-23 00:47
Closing due to lack of feedback. Happy to reopen if someone can provide an example and detailed steps to reproduce. 

You can always implement your own `WritableBitmapInfo` using a custom `IBitmapFactory`

https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Wpf/Rendering/WritableBitmapInfo.cs
https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Wpf/Rendering/BitmapFactory.cs
https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp.Wpf/ChromiumWebBrowser.cs#L174

**Closed by amaitland** 2017-05-23 00:47 UTC
Labels: more-details-needed-from-op, wpf

**Comment by sneltyn** [comment] 2017-12-08 14:24
I have this problem. 

Log trace from event viewer windows:

```
System.AccessViolationException
   в System.Windows.Media.MILUtilities.MILCopyPixelBuffer(Byte*, UInt32, UInt32, UInt32, Byte*, UInt32, UInt32, UInt32, UInt32, UInt32)
   в System.Windows.Media.Imaging.WriteableBitmap.WritePixelsImpl(System.Windows.Int32Rect, IntPtr, Int32, Int32, Int32, Int32, Boolean)
   в CefSharp.Wpf.Rendering.WritableBitmapInfo.Invalidate()
   в CefSharp.Wpf.ChromiumWebBrowser+<>c__DisplayClass10.<CefSharp.Internals.IRenderWebBrowser.InvokeRenderAsync>b__f()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   в MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   в System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   в System.Windows.Application.RunDispatcher(System.Object)
   в System.Windows.Application.RunInternal(System.Windows.Window)
   в System.Windows.Application.Run(System.Windows.Window)
   в TestApp.App.Main(System.String[])
```

Basically, the problem is seen on the Intel Stick / operation system win10 x64.

Provide a demo?

**Comment by mitchcapper** [comment] 2017-12-08 19:25
@sneltyn if you can fork the sample app and make as minimal of a change as possible that would be great.
