### ISSUE TITLE
PDFs in WPF do not scroll properly/at all (does work in WinForm and cef spotify sample app)

### ISSUE THREAD

**Issue by mitchcapper** [cefsharp/CefSharp#1868] opened 2016-11-18 21:12 UTC
Go to a single page PDF or a multi-page pdf like: https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

In the CefSharp3.WPF.Sample doesn't load pdfs well at all, after visiting a PDF I have to switch to another tab and then back to see it.  Then you cannot interact with it at all.

Using my own app it loads the PDF fine however scrolling just doesn't function correctly.  Neither mouse wheel scrolling, or using the scrollbar work well.  If you try to drag the scroll grabber the page just jumps around.  

This issue does not happen in the WinForms sample (works fine).
It also does not cause an issue on the Spotify sample app at all with:
cefclient --multi-threaded-message-loop
however running with:
cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
made mouse scrolling stop working (but normal scrolling works ok).

Using master (2016-11-18 / 77413cf2a7c66e69ffbfcae89bfbd377b300aacf).
x64
Windows 10

**Comment by amaitland** [comment] 2016-11-19 00:43
Duplicate of #1799

**Closed by amaitland** 2016-11-19 00:43 UTC

**Comment by mitchcapper** [comment] 2016-11-19 01:05
@amaitland this is not a duplicate.  It may be why the sample app does not load the pdf right away but not the issue.  As mentioned I have pdf rendering working in my app (as I disable gpu acceleration), in addition in the actual app even switching back does not still scroll properly.  This is about the scrolling problem with gpu accel disabled, unless you are saying that should also be fixed.

**Comment by mitchcapper** [comment] 2016-11-19 01:33
(And for what it is worth calling .InvalidateVisual(); 60 @ fps does not solve either.)

**Comment by amaitland** [comment] 2016-11-19 08:44
InvalidateVisual is not the method referenced. You'll need a much newer branch of CEF than any currently available in CefSharp.

**Comment by mitchcapper** [comment] 2016-11-19 08:46
Ah cheers, sorry to bother.
