### ISSUE TITLE
Npr.org not formatted correctly in v53.0 Winforms

### ISSUE THREAD

**Issue by jeoware** [cefsharp/CefSharp#1890] opened 2016-12-18 02:19 UTC
Using Minimal example, the web sites www.npr.org and www.nytimes.com are incorrectly formatted. Seems to ignore Java on the site.
 **What version of the product are you using?**
Cef Winforms 53.0.0 --- 51.0 works fine.
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 47.0.3

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms.
- **What steps will reproduce the problem?**
Use the minimal example. The two sites will be incorrectly formatted.
 
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html (http://cefbuilds.com for older version)?**
Yes, absolutely.

I've tested 51 & 53 with hundreds of websites and thousands of links on those sites. These are the only examples of formatting failures I've found. No memory leaks, unlike IE.

**Comment by amaitland** [comment] 2016-12-19 21:03
Duplicate of #1880 

The resources fail to load due to the certificate error.

**Closed by amaitland** 2016-12-19 21:03 UTC
Labels: duplicate
