### ISSUE TITLE
WPF - text cursor displayed at the left side of currently writing character

### ISSUE THREAD

**Issue by EmilyPaek** [cefsharp/CefSharp#3911] opened 2021-11-27 05:50 UTC
- **What version of the product are you using?**
    - 81.3.100 and 95.7.141. (I have tested only two version)

- **What architecture x86 or x64?**
    - x86
	
- **What version of .Net?**
    - .Net 4.7.1
    
- **On what operating system?**
    - Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WPF
    
- **What steps will reproduce the problem?**
    - Writing words with only Korean.
    - Text cursor location is wrong when typing Korean.
    It seems like a minimal issue, but is a big issue for Korean speaker.
    the cursor at the left side of writing word is irritating.
    It needs to be get fixed.
    
    I attached a video of the issue in my application.
    Here is the video:
https://user-images.githubusercontent.com/37920379/143552266-a3775709-17d9-4f76-9853-75ab5fc5e6c5.mp4

    - Does the problem reproduce using the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)?
    I can't reproduce my problem with MinimalExample.
    Because a strange box appeared at the left upper corner.
    Here is the box image:
![스크린샷 2021-11-27 오후 2 55 53](https://user-images.githubusercontent.com/37920379/143669931-70598f9b-5f31-46b4-8fdb-a299456a3102.png)
    
- **What is the expected output? What do you see instead?**
A text cursor shown right of the word.
Here is expected result:
https://user-images.githubusercontent.com/37920379/143553277-c1fe40a3-19bc-459a-9bb6-227c97c3d3d1.mp4

- **Please provide any additional information below.**
    - I think it is MS IME issue

- **Does this problem also occur in the `CEF` Sample Application**
    no

**Comment by amaitland** [comment] 2021-11-27 08:18
Closing as duplicate of #1262 

Make sure you have enabled experimental IME support as per https://github.com/cefsharp/CefSharp/issues/1262#issuecomment-659294710

If you are still experiencing problems please comment on #1262

**Closed by amaitland** 2021-11-27 08:18 UTC
