### ISSUE TITLE
c# - Changes in cefsharp 79.1.35 (from 75.1.143) creates: 'The calling thread cannot access this object because a different thread owns it.'

### ISSUE THREAD

**Issue by Dyr-Fenrir** [cefsharp/CefSharp#3034] opened 2020-01-31 05:34 UTC
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
e.g. 57.0.0 or 63.0.0-pre01
    - Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer `-pre` release and test with that also).
I am using 79.1.35 from NuGet in Visual Studio 2019.

- **What architecture x86 or x64?**
x64

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10 Build 1909 (x64 EN-US)

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).
I recently update the NuGet package of cefsharp.wpf from 75.1.143 to 79.1.35 and now the following code no longer works:

```c#
public class Handle
{
    string source = null;
        int loaded = 0;
        private RequestHandler _requestHandler;
        public IWebBrowser _browser;
        public int previousRequestNrWhereLoadingFinished = -1;

        public Handle()
        {
            var settings = new CefSharp.Wpf.CefSettings()
            {
                CachePath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CefSharp\\Cache")
            };

            settings.CefCommandLineArgs.Add("enable-media-stream", "1");

            Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);
            _browser = new CefSharp.Wpf.ChromiumWebBrowser();
            _requestHandler = new RequestHandler();
            _browser.RequestHandler = _requestHandler;
        }

        public void OnIsBrowserInitializedChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (_browser.IsBrowserInitialized)
            {
                status = 1;
            }
            //status = 0;
        }

        public async void _browser_LoadingStateChanged(object sender, LoadingStateChangedEventArgs e)
        {
            if (!e.IsLoading)
            {
                if (previousRequestNrWhereLoadingFinished < _requestHandler.NrOfCalls)
                {
                    previousRequestNrWhereLoadingFinished = _requestHandler.NrOfCalls;
                    source = await _browser.GetBrowser().MainFrame.GetSourceAsync();
                    ...
                }
            }
        }
...
}
```

The error I get is: "System.InvalidOperationException: 'The calling thread cannot access this object because a different thread owns it.'"

On the following line:

```c#
source = await _browser.GetBrowser().MainFrame.GetSourceAsync();
```

I cannot figure out why this happens so far, may you help me out with this issue please?

This is probably related to the changes in the new version, I read them but I could find what exactly broke this.

Thank you for your time and help, it is greatly appreciated.

Here is the stack call:

```c#
This exception was originally thrown at this call stack:
System.Windows.Threading.Dispatcher.VerifyAccess()
System.Windows.DependencyObject.GetValue(System.Windows.DependencyProperty)
CefSharp.Wpf.ChromiumWebBrowser.IsBrowserInitialized.get()
CefSharp.WebBrowserExtensions.ThrowExceptionIfBrowserNotInitialized(CefSharp.IWebBrowser)
CefSharp.Wpf.ChromiumWebBrowser.GetBrowser()
First_4_Figures.MainWindow.Handle._browser_LoadingStateChanged(object, CefSharp.LoadingStateChangedEventArgs) in MainWindow.xaml.cs
```

I will gladly provide additional information if requested.

- **What is the expected output? What do you see instead?**
With version 75.1.143 I did not receive the error 'The calling thread cannot access this object because a different thread owns it.' on the following line: 
source = await _browser.GetBrowser().MainFrame.GetSourceAsync();

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.
Exception thrown: 'System.InvalidOperationException' in WindowsBase.dll
An exception of type 'System.InvalidOperationException' occurred in WindowsBase.dll but was not handled in user code
The calling thread cannot access this object because a different thread owns it.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Not that I could find.

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Not that I think of.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No.

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

**Comment by amaitland** [comment] 2020-01-31 05:53
Closing as duplicate of #3032 

In future please respond on stackoverflow and wait for a reply before opening an issue.

https://stackoverflow.com/questions/59993520/c-sharp-changes-in-cefsharp-79-1-35-from-75-1-143-creates-the-calling-thre#comment106100771_59993520

**Closed by amaitland** 2020-01-31 05:53 UTC
