### ISSUE TITLE
WPF - Dropdown popup doesnt overflow the window like normal applications

### ISSUE THREAD

**Issue by EricPRHC** [cefsharp/CefSharp#4382] opened 2023-01-30 14:37 UTC
In our production environment an external integrated party has a website with a native dropdown at the bottom of their page. Unfortunately the dropdown popup doesnt render completely as it typically pops up below the dropdown.
Though we use WPF, for testing purposes I've compared the minimal example in WinForms as well, which does work.

- **What version of the product are you using?**
    - Issue verified on v109.0.5414.87 minimal example downloaded from ZIP, but we are experiencing this issue in production v103 using nugets.

- **What architecture x86 or x64?**
  AnyCPU but I think I should say x64
	
- **What version of .Net?**
   .Net 4.8
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF. I also tested WinForms but that seems to work fine.
    
- **What steps will reproduce the problem?**
    - See also attached screenshots below.
    - Visit https://www.globalsqa.com/demo-site/select-dropdown-menu/ or create an html file with a SELECT with 20 OPTION elements.
    - Resize your application/browser window so that the dropdown wouldnt fit
    - The problem does reproduce with the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample).

- **What is the expected output? What do you see instead?**
    - The dropdown popup options list is being clipped at the edge of the browser, whilst it should exceed the application window's boundaries.

- **Does this problem also occur in the `CEF` Sample Application**
    - The problem does NOT occur in this version: [x64 download] https://cef-builds.spotifycdn.com/cef_binary_108.4.13%2Bga98cd4c%2Bchromium-108.0.5359.125_windows64_client.tar.bz2 But to be honest I'm not sure what to get from that or where to go from there, I believe this is actually the winForms variant.

CefSharp WPF:
![image](https://user-images.githubusercontent.com/123941308/215506982-f91633c4-7a57-4b64-852d-653ca593ce83.png)

CefSharp WinForms:
![image](https://user-images.githubusercontent.com/123941308/215506702-aec914fe-8c24-426f-9e14-938b9e7185b1.png)

Chrome webbrowser:
![image](https://user-images.githubusercontent.com/123941308/215506086-24208e41-d316-4709-b5a6-ddaf942966cf.png)

**Comment by amaitland** [comment] 2023-01-30 19:35
Closing as duplicate of #2820

**Closed by amaitland** 2023-01-30 19:35 UTC
