### ISSUE TITLE
Unable to customise path for the crash dump process (crashpad)

### ISSUE THREAD

**Issue by merceyz** [cefsharp/CefSharp#1876] opened 2016-12-01 21:43 UTC
- **What version of the product are you using?**
    - 55.0.0-CI2067

- **What architecture x86 or x64?**
    - x64

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - OffScreen

- **What steps will reproduce the problem?**
    - Enumerate through the string[] "args" in Program.Main and write them out to the console then call Cef.Initialize();

- **What is the expected output? What do you see instead?**
    - The expected output is the first three lines, the rest is the unexpected part.
![f6f1601dd47acd4f7d10825d4601629d](https://cloud.githubusercontent.com/assets/3842800/20813451/ed343e76-b815-11e6-8bfc-84f6d735047b.png)

- **Please provide any additional information below.**
    - I updated from CI2055 to CI2067, the issue was not present before the update.
    - Seems like CefSharp or Cef is calling Program.Main instead of whatever it's supposed to call
    - debug.log:
```
[1201/221400:ERROR:file_io.cc(30)] read: expected 4, observed 0
[1201/221400:ERROR:registration_protocol_win.cc(53)] CreateFile: The system cannot find the path specified. (0x3)
```

**Comment by merceyz** [comment] 2016-12-02 12:27
Update: I went through each MyGet package starting at CI2055. The issue first happens in CI2065

**Comment by amaitland** [comment] 2016-12-21 03:07
The relevant `upstream` issue is https://bitbucket.org/chromiumembedded/cef/issues/1995/migrate-from-breakpad-to-crashpad

As yet there is no way to customise the new `crashpad` process. Short term workaround is to use your main process to host `crashpad`, an example was added see https://github.com/cefsharp/CefSharp/commit/8970196740d5337a47b246518815ee8849cba90f

**Comment by amaitland** [comment] 2016-12-21 03:09
The `CEF` issue needs to be resolved before `55.0.0` can be released.

**Comment by amaitland** [comment] 2017-01-11 01:59
Issue has been resolved `upstream`, hopefully the changes will be merged into the `2883` branch shortly.

https://bitbucket.org/chromiumembedded/cef/issues/1995/migrate-from-breakpad-to-crashpad#comment-33539720

**Comment by amaitland** [comment] 2017-01-11 02:09
> If "AppName" is set on Windows then crash report information (metrics,
> database and dumps) will be stored locally on disk under the
> "C:\Users\[CurrentUser]\AppData\Local\[AppName]\User Data" folder. On other
> platforms the CefSettings.user_data_path value will be used.

I'm guessing `crashpad` will be disabled unless a `crash_reporter.cfg` is present. The examples will be updated to enable crashpad, if no server url is specified the crash reports will be generated on disk. We'll go with this option for testing purposes.

**Comment by amaitland** [comment] 2017-01-16 02:03
Crashpad is now disabled by default. I have been unable to get it working with the examples, that's a different problem.

**Closed by amaitland** 2017-01-16 02:03 UTC
Labels: known-issue, upstream

**Comment by amaitland** [comment] 2017-01-16 03:42
`crashpad` process spawns successfully when running outside of `Visual Studio`, likely a problem caused by the `vshost` process.

**Comment by merceyz** [comment] 2017-01-16 04:36
I did a nuget restore and built the projects but now my program crashes instantly.
It crashes before any of the code in Main.cs is called, I attached the debugger but it was useless.

From console window:

> Unhandled Exception: System.IO.FileLoadException: A procedure imported by 'CefSharp.Core.dll' could not be loaded

**Comment by amaitland** [comment] 2017-01-16 04:43
You can use https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/55 for testing. Likely you just need to perform a full cleanup (exit out of `VS` and do a `git clean -fx`). `VS` gets confused from time to time.

**Comment by merceyz** [comment] 2017-01-16 04:49
I removed the comment because I thought I found the issue, didn't want to waste your time, wasn't fast enough.

The issue is that the cef.redist.x64 files aren't getting copied over to the folder where my project builds itself, too late for me now. I'll give you an update later
