### ISSUE TITLE
Context menu position on the mouse right button click is wrong

### ISSUE THREAD

**Issue by Vladimir35** [cefsharp/CefSharp#2093] opened 2017-07-17 13:02 UTC
The context menu, available on the right mouse click, is shown in a wrong position. Somehow the offset is calculated to the main window and not to the control itself.

- Version 57.0.0
- x64
- Win10
- WPF
- This problem also occur in the `CEF` WPF Sample Application form.

It looks like an older bug:
https://stackoverflow.com/questions/39824245/cefsharp-context-menu-spawns-in-the-wrong-position

**Comment by merceyz** [comment] 2017-07-17 20:19
Duplicate of #1795

**Closed by merceyz** 2017-07-17 20:19 UTC
