### ISSUE TITLE
WPF application using CEF Pages sometimes die

### ISSUE THREAD

**Issue by netstart188** [cefsharp/CefSharp#2175] opened 2017-10-26 04:43 UTC
- What version of the product are you using?
Chromium: 57.0.2987.133. CEF: r3.2987.1601.gf035232, CefSharp: 57.0.0.0
Branch 57

- What architecture x86 or x64?
x64

- On what operating system?
Win10

- Are you using WinForms, WPF or OffScreen?
WPF

WPF application using CEF Pages sometimes die，Page Jump window. location. href is already the address of the new page, but the display interface still shows the old page。

----

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? Please include the exact version number you are using (no ambiguous statements like `Latest from Nuget`)
e.g. 57.0.0 or 63.0.0-pre01
    - Please only create an issue if you can reproduce the problem with the latest version. (If you are using the latest stable release please check to see if there is a newer `-pre` release and test with that also).

- **What architecture x86 or x64?**

- **On what operating system?**
    - Win7, Win 8, Win10, etc?

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
    - Please no binary (zip, etc) links, fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to `GitHub`. (Alternatively use a code sharing service list `Gist` or `Pastebin`).

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

**Comment by jankurianski** [comment] 2017-10-26 07:06
Unfortunately not enough detail to investigate.  Could you reproduce with `cefclient`?

**Comment by netstart188** [comment] 2017-10-27 02:47
![image](https://user-images.githubusercontent.com/14831279/32085887-40a1b8a8-bb04-11e7-8657-cc1910e255f1.png)

**Comment by jankurianski** [comment] 2017-10-27 04:16
Please read section "Does this problem also occur in the CEF Sample Application from  ..." in the [issue template](https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md).  Can you reproduce it with `cefclient`?  Please use the same version of CEF that CefSharp uses - `2987`.

**Comment by netstart188** [comment] 2017-10-27 05:50
Does the cef log provide any relevant information?

[debug.log](https://github.com/cefsharp/CefSharp/files/1420909/debug.log)

**Comment by netstart188** [comment] 2017-11-02 02:55
Do not refresh the page or local refresh phenomenon, what methods to force it to redraw.

**Comment by amaitland** [comment] 2017-12-21 23:44
What `DPI` are you using?

**Comment by netstart188** [comment] 2018-01-09 14:35
96

**Comment by amaitland** [comment] 2018-01-11 03:56
Make sure you mark your process as `LargeAddressAware` see https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses

If that doesn't solve your problem then you will need to provide steps to reproduce and/or an example (no `binary` files, uploading to a code sharing service like `GitHub` thank you)

**Comment by netstart188** [comment] 2018-01-16 03:04
How C # or WPF adds a largeaddressaware identity

**Comment by amaitland** [comment] 2018-01-18 03:45
The `Examples` are `LargeAddressAware`, you can use them for reference see https://github.com/cefsharp/CefSharp/search?q=LargeAddressAware&type=Commits&utf8=%E2%9C%93

If you require further assistance setting `LargeAddressAware` then I'd suggest you ask on `Stackoverflow` (search there first, as it's very likely the question has been answered before).

**Comment by netstart188** [comment] 2018-01-31 10:00
After the test,it's not the point on LargeAddressAware, the page design still can't be draw again.

**Comment by amaitland** [comment] 2018-01-31 11:10
Try the latest -pre release. 

If that doesn't solve your problem you will need to provide an example that reproduces the problem.

**Comment by netstart188** [comment] 2018-02-02 02:36
I have tried to update -pre release,but it didn't solve my problem,and it started DisableGpuAcceleration and SetOffScreenRenderingBestPerformanceArgs.Otherwise,invoking Invalidate(PaintElementType.View) in the MainFrame_FrameLoadEnd will reduce the problems,but it can't eliminate  the problems.

**Comment by amaitland** [comment] 2018-02-05 23:54
Without a sample that reproduces the problem or a list of steps to reproduce the problem with one of the `examples` I'm not sure what else we can do here. I'm not seeing any reports of others with the same problem.

**Comment by amaitland** [comment] 2018-02-13 03:19
`63.0.0` is out, if you can reliably reproduce the problem then you should test with the `CEF Sample Application`, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details.

If you are unable to reproduce the problem with the `CEF Sample Application` then update your original post completing the bug report that I've included. It's critical you include adequate steps to **reproduce** the problem.

If no further feedback this issue will be closed in 14 days.

**Comment by netstart188** [comment] 2018-02-26 03:37
I have tried to 63.0.0 release,but it didn't solve my problem。
Normal：
![nomal](https://user-images.githubusercontent.com/14831279/36652366-569fc54c-1ae9-11e8-826d-120a767a349e.png)
Exception：
![error](https://user-images.githubusercontent.com/14831279/36652385-739125d8-1ae9-11e8-83fd-fe57c17ae62c.png)

**Comment by amaitland** [comment] 2018-02-26 03:43
Without a proper bug report that includes a way to reproduce the problem there isn't anything further we can do.

**Closed** 2018-03-06 02:27 UTC
Labels: more-details-needed-from-op
