### ISSUE TITLE
IME in chinese status position

### ISSUE THREAD

**Issue by GaoJones** [cefsharp/CefSharp#3160] opened 2020-06-28 09:19 UTC
Hi, i am using the CefSharp 81.3.100.0,  when i input  chinese  the input box position always to the top left corner of the screen, is fix it in new version,  as far as i know previous versions have had this problem all the time.

**Comment by amaitland** [comment] 2020-06-28 10:04
Duplicate of #1262

Please report the problem you are having there.

**Closed by amaitland** 2020-06-28 10:04 UTC

**Comment by amaitland** [comment] 2020-07-02 00:25
Possibly fixed by #3163

**Comment by amaitland** [comment] 2020-07-02 00:31
Try upgrading to `83.4.20`

**Comment by Pursue00** [comment] 2021-08-02 06:42
However, this problem still exists

**Comment by Pursue00** [comment] 2021-08-02 06:46
> Try upgrading to `83.4.20`

However, this problem still exists

**Comment by amaitland** [comment] 2021-08-02 07:07
If you can reproduce the problem with version 91 then you should add detailed steps to reproduce the problem at https://github.com/cefsharp/CefSharp/issues/1262

**Comment by Pursue00** [comment] 2021-08-02 07:37
> If you can reproduce the problem with version 91 then you should add detailed steps to reproduce the problem at #1262

Do you mean that this problem has been resolved in the latest version?
