### ISSUE TITLE
Memory leak when playing mjpeg

### ISSUE THREAD

**Issue by martijn189** [cefsharp/CefSharp#1177] opened 2015-08-07 14:31 UTC
Using CEFsharp version 41.0.1 (NuGet), there is a large memory leak that uses more RAM every second the proces is open. When the used RAM reaches 4GB (on 32 bit) the proces crashes and the CEFsharp control is white (images disappers).

HTML used (URL wa taken from google, i take no responsability for the content of the image):

`<img src="http://141.89.114.98/cgi-bin/video640x480.mjpg?dummy=garb">`

I have tried to load a image (single image from mjpeg) with a javascript loop that refreshes the image each 2 seconds, the memory still increases every x seconds... altough a bit slower

I can see 2 sub processes, when loading a normal webpage it uses arround 20 MB of RAM, issue only appears to be with refreshing an image verry often.

**Comment by amaitland** [comment] 2015-08-08 08:01
Can you reproduce the problem using the `upstream` example application? (`cefclient`)

https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

Also `master` is based on a newer version of `CEF`, might be worth checking out if you have time?

**Comment by martijn189** [comment] 2015-08-10 07:59
Thank you for the reply. I downloaded the test application of the 2357branch, i cannot reproduce the memory leak. Is the NuGet version older then the latest branch?

**Comment by amaitland** [comment] 2015-08-10 10:46
> Then i downloaded the CefSharp.MinimalExample and tried the winforms example, the problem came back.

The `MinimalExample` currently targets the `2272` branch, so it's not really a fair comparison. 

> CEFSharp and CEF have other ways of using the subproces, coudl it be that there is a problem with the sub proces exe?

Entirely possible. What type of sub process is it that's leaking? `Renderer`? `GPU`?

**Comment by martijn189** [comment] 2015-08-11 09:15
Owh, i do not know sorry, how could i check? Steps to reproduce:

1) create html file with mjpeg stream from post #1
2) Load page into cefsharp application
3) Open windows Task Manager and look for the "CefSharp.BrowserSubprocess.exe" proces, every second it consumes more RAM memory... until the PC has no more left, or it reaches the 32 bit limit.

**Comment by amaitland** [comment] 2015-08-11 09:32
In `Task Manager` you can look at the command line arguments for a process, the `--type` argument is the important part there.

See http://www.winhelponline.com/blog/configure-task-manager-to-display-full-path-of-running-processes/ if your not familiar with the extra columns in `Task Manager`.

**Comment by amaitland** [comment] 2015-08-11 10:40
Looks like your problem is an `upstream` one.

I've created a `43` branch which is a minimal upgrade, feel free to take it for a spin.

https://github.com/cefsharp/CefSharp/tree/cefsharp/43

**Comment by martijn189** [comment] 2015-08-17 08:22
It took me a day to correct al the compile errors, but it works. I believe the leak is still there, but now it consumes 1 MB per 2-3 minutes and not 1MB per second.

**Comment by amaitland** [comment] 2015-08-17 08:30
> I believe the leak is still there, but now it consumes 1 MB per 2-3 minutes and not 1MB per second.

You'll likely need to report that upstream.

**Comment by amaitland** [comment] 2015-08-17 08:39
> It took me a day to correct al the compile errors, but it works.

Have created a `wiki` entry, it's not really very helpful at this point. If you have some time, please contribute to make the process easier for others. Thanks :+1: 

https://github.com/cefsharp/CefSharp/wiki/CefSharp-43-%28Alpha%29

**Comment by amaitland** [comment] 2015-08-26 21:29
> It took me a day to correct al the compile errors, but it works. I believe the leak is still there, but now it consumes 1 MB per 2-3 minutes and not 1MB per second.

If you do report the problem `upstream` please post a link to the issue here.

It's probably worth trying `2454` at some point. Closing this now as it's `mostly resolved` and it's not something `CefSharp` has control over.

**Closed by amaitland** 2015-08-26 21:29 UTC
Labels: upstream, winforms
