### ISSUE TITLE
Win10 system input method, the position of the Chinese standby box is not close to the input window.

### ISSUE THREAD

**Issue by JackChen1866** [cefsharp/CefSharp#2269] opened 2018-02-07 12:06 UTC
What version of the product are you using?
CefSharp version 57.0.0 or master

What architecture x86 or x64?
x86

On what operating system?
Win 10

Are you using WinForms, WPF or OffScreen?
wpf

What steps will reproduce the problem?
Win10 system input method, the position of the Chinese standby box is not close to the input window.

**Comment by merceyz** [comment] 2018-02-07 12:10
Please use the `Bug Report` template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Fork the https://github.com/cefsharp/CefSharp.MinimalExample project and provide an example that reproduces your problem.

**Comment by CJXHZY** [comment] 2018-02-07 12:22
What version of the product are you using?
 CefSharp version 57.0.0  or master

What architecture x86 or x64?
x86 

On what operating system?
Win 10

Are you using WinForms, WPF or OffScreen?
wpf 

What steps will reproduce the problem?
     Win10 system input method, the position of the Chinese standby box is not close to the input window.

**Comment by amaitland** [comment] 2018-02-07 12:41
IME is not currently supported in WPF

Closing as duplicate of #1262

**Closed by amaitland** 2018-02-07 12:41 UTC
