### ISSUE TITLE
form file choice broken

### ISSUE THREAD

**Issue by crucifyer** [cefsharp/CefSharp#4858] opened 2024-07-01 10:25 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

126.2.70

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.net 4.6.2

### Implementation

WPF

### Reproduction Steps

input type=file file choice

### Expected behavior

then broken.

### Actual behavior

choice file

### Does this problem also occur in the CEF Sample Application

Yes using WPF/OffScreen command line args

### Other information

test code : https://github.com/crucifyer/cefsharp-formfilebug/tree/master/FormFileBug
error message
```
[46440:21192:0701/191934.157:FATAL:partition_alloc_support.cc(807)] Detected dangling raw_ptr in unretained with id=0x00006ecc009f493c:

Task trace:
	sqlite3_dbdata_init [0x00007FFB4B38F3AB+960843]
	GetHandleVerifier [0x00007FFB455DAC6E+2056062]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFB4A9CFD2F+35730895]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFB4A9CF853+35729651]
	GetHandleVerifier [0x00007FFB46F75694+28903844]
Task trace buffer limit hit, update PendingTask::kTaskBacktraceLength to increase.

Stack trace:
	GetHandleVerifier [0x00007FFB453EBB92+28322]
	cef_time_from_basetime [0x00007FFB44ED6729+16701849]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFB4A2B32D9+28273529]
	cef_zip_reader_create [0x00007FFB43E3347C+301356]
	cef_zip_reader_create [0x00007FFB43E335DE+301710]
	sqlite3_dbdata_init [0x00007FFB4B38EA03+958371]
	sqlite3_dbdata_init [0x00007FFB4B38F1CE+960366]
	CrashForExceptionInNonABICompliantCodeRange [0x00007FFB490672E2+9087874]
	GetHandleVerifier [0x00007FFB46F227BD+28564173]
	GetHandleVerifier [0x00007FFB47045AC3+29756883]
	GetHandleVerifier [0x00007FFB46F155B3+28510403]
	cef_time_from_basetime [0x00007FFB44EC721E+16639118]
	GetHandleVerifier [0x00007FFB453F3FC6+62166]
	cef_time_from_basetime [0x00007FFB44EF1D5F+16814031]
	cef_zip_reader_create [0x00007FFB43E4158D+358973]
	cef_time_from_basetime [0x00007FFB44EC107F+16614127]
	BaseThreadInitThunk [0x00007FFCC6577344+20]
	RtlUserThreadStart [0x00007FFCC69026B1+33]


Please check for more information on:
https://chromium.googlesource.com/chromium/src/+/main/docs/unretained_dangling_ptr_guide.md
```

**Comment by amaitland** [comment] 2024-07-01 19:51
Closing a s duplicate of #4857

**Closed by amaitland** 2024-07-01 19:51 UTC
Labels: upstream
