### ISSUE TITLE
vimeo video play failed

### ISSUE THREAD

**Issue by Guawazii** [cefsharp/CefSharp#3222] opened 2020-08-26 05:24 UTC
vimeo video does not support . example: https://vimeo.com/210599507

**Comment by amaitland** [comment] 2020-08-26 05:30
> Due to licensing issues default builds do not support proprietary codecs like H264/AAC, sites like Netflix/Twitter/Instagram/Facebook won't play video/audio.

As per the release notes only free and open video/audio codecs are supported.

https://github.com/cefsharp/CefSharp/wiki/General-Usage#multimedia-audiovideo

Closing as duplicate of #2631

**Closed by amaitland** 2020-08-26 05:30 UTC
Labels: invalid
