### ISSUE TITLE
Load fails with some audio stream uris.

### ISSUE THREAD

**Issue by TEDSON007** [cefsharp/CefSharp#2344] opened 2018-03-31 22:13 UTC
- **What version of the product are you using?**
CEF	3.3239.1723.g071d1c1
Chromium	63.0.3239.132

- **What architecture x86 or x64?**
x64

- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
chromiumWebBrowserInstance.Load("https://r6---sn-uigxx03-auol.googlevideo.com/videoplayback?pl=17&mn=sn-uigxx03-auol%2Csn-aigllnzd&ip=188.28.102.168&mm=31%2C29&id=o-AN2_S5EeTPRDIBfkvbU2PaKN1o-oMZeXljv8N6Qz1kl5&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&itag=140&ms=au%2Crdu&initcwndbps=343750&mv=m&dur=4389.244&mt=1522522283&ipbits=0&key=yt6&c=WEB&ei=C9m_WoqYF4SrW-uUm_gJ&clen=69712377&gcr=gb&source=youtube&gir=yes&mime=audio%2Fmp4&requiressl=yes&keepalive=yes&fvip=13&expire=1522543979&lmt=1508517609957431&signature=D9F570EA8BD797E57519FBBB8372C647B9E87337.3061F8CAD528540E5E6073A6ECED145057D31762&ratebypass=yes");

- **What is the expected output? What do you see instead?**
Browser navigation to the web page and subsequent playing of the audio stream it contains.
What I actually see is nothing happening at all.

- **Please provide any additional information below.**
 There are no indications of an error of any kind, or exception or any reference to an issue in debug.log file.
The browser simply does not navigate to the url, there is no server error, it simply stays on its current page. There are plenty more urls similar pointing to different streams which produce the same undesirable result, and plenty that it happily navigates to

Only third party control is cef.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Yes and no.
The test app appears to leave its current page, but there is still no navigation to the stream.
Further more, the test app does not navigate to any of the many url streams which my app does.

cef_binary_3.3325.1756.g6d8faa4_windows64_client.tar

(edit) Additionally, the page does not load when the url is passed into ChromiumWebBrowser constructor.
It will also not navigate to the problem link above, if I navigate to this page and click it in browser.

**Comment by amaitland** [comment] 2018-03-31 22:54
Only free and open audio/video codecs are supported. See #1479 for some background. Version 65 will support MP3 as it's no longer proprietary. 

Closing as the files don't play in cefclient, so not a bug in CefSharp.

**Closed by amaitland** 2018-03-31 22:54 UTC

**Comment by TEDSON007** [comment] 2018-03-31 23:59
Fair enough. Just a shame I cannot detect this design issue, to deal with it.

**Comment by amaitland** [comment] 2018-04-01 00:31
Detect a design issue? That doesn't make sense.

**Comment by TEDSON007** [comment] 2018-04-01 07:07
You're right, it doesn't when I read it back.
I meant there is no navigation by design, but there is no indication of that fact which would allow me to deal with it easily.

**Comment by amaitland** [comment] 2018-04-01 08:57
We're limited by the API CEF provides. If the LoadError event isn't being called then you'd probably have to use HTML/JavaScript to load the media and use the events exposed there. 

CEF has it's own forum, you might find an alternate solution there http://magpcss.org/ceforum/index.php

**Comment by TEDSON007** [comment] 2018-04-01 13:29
Thanks for your time, I've performed a http request on page headers before navigation to determine if it's Mp3 as a workaround, until a later CefSharp release.
