### ISSUE TITLE
Broadcast web site not works

### ISSUE THREAD

**Issue by ChrisChi0922** [cefsharp/CefSharp#1682] opened 2016-05-09 08:44 UTC
###Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - 49.0.0, 47.0.3 NuGet

- **What architecture x86 or x64?**
    - x86

- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    - Run CefSharp.MinimalExample.WinForms.exe then browse http://tunein.com/radio/FM-Chao-792-s164698/

- **What is the expected output? What do you see instead?**
    - Sound of Internet Radio should works but not works (works in Google Chrome)

- **Please provide any additional information below.**
    - no stack trace.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
      NO

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
      NO

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
      UNKNOWN

**Comment by amaitland** [comment] 2016-05-09 09:00
> Run CefSharp.MinimalExample.WinForms.exe then browse http://tunein.com/radio/FM-Chao-792-s164698/

Requires Flash to be installed. You'll need to install `Pepper Flash`

Marking this as duplicate of #1505

**Closed by amaitland** 2016-05-09 09:00 UTC
