### ISSUE TITLE
Error displaying Panorama GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM

### ISSUE THREAD

**Issue by NitinIIRS** [cefsharp/CefSharp#1679] opened 2016-05-03 10:01 UTC
What steps will reproduce the problem?
I have created a window form and WPF application using CEFsharp and tried to incorporate WEBGL for displaying panorama.

What is the expected output? What do you see instead?
Sometimes it works normally and sometime on loading of same image or different images the screen goes black and the following errors are recorded on the debug file.

[0503/125112:ERROR:gles2_cmd_decoder.cc(14033)] [.Compositor-00614AA0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name [0503/125112:ERROR:gles2_cmd_decoder.cc(7430)]

Are you using WinForms, WPF or OffScreen?
I have tried using WinForms and WPF.

What version of the product are you using? On what operating system? x86 or x64?
X86.

What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Nuget

Win7, Win 8, Win10, etc?
Win7

Please provide any additional information below.Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

[.Compositor-00614AA0]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name [0503/125112:ERROR:gles2_cmd_decoder.cc(7430)]

[.Compositor-00614AA0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering. [0503/140519:WARNING:dns_config_service_win.cc(673)]

Failed to read DnsConfig. [0503/140832:ERROR:ipc_channel_win.cc(465)] pipe error: 995

Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

The application is running normally with x64.

Does this problem also occur in the Cef TestApp from http://cefbuilds.com?
Yes

**Comment by amaitland** [comment] 2016-05-03 10:05
@NitinIIRS Please stop opening issues, there's 4 in total now that you've opened for the same thing.

Closing as duplicate of #1678

**Closed by amaitland** 2016-05-03 10:05 UTC
