### ISSUE TITLE
The program '[29180] App.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

### ISSUE THREAD

**Issue by jlVidal** [cefsharp/CefSharp#2101] opened 2017-07-25 23:34 UTC
- **What version of the product are you using?**
CefSharp.Common and CefSharp.OffScreen v57.0.0 from nuget 
cef.redist.x86 3.2987.1601

- **What architecture x86 or x64?**
x86

- **On what operating system?**
win10 x64

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **What steps will reproduce the problem?**
Implement/Use a custom IRequestHandler to stop http redirection
After a few seconds of browser usage/dispose resources, the app crashes
https://pastebin.com/RkahKPFF

- **What is the expected output? What do you see instead?**
No crash

- **Please provide any additional information below.**
`The program '[29180] App.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.`  

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
```
[0725/161307.953:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0725/161358.718:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
```
- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Not verified

**Comment by jankurianski** [comment] 2017-07-25 23:41
If you modify your callback disposal to be more defensive such as in...
https://github.com/cefsharp/CefSharp/blob/64b63b3dce4226cc7824b9aa0319c158590dd384/CefSharp.Example/RequestEventHandler/RequestEventHandler.cs#L152
... does the problem occur?

**Comment by jlVidal** [comment] 2017-07-25 23:49
@jankurianski yes. Yes, it doesn't change the crash, or behavior

**Comment by amaitland** [comment] 2018-01-02 06:53
Unable to reproduce the problem with `62.0.0-pre01`, closing this as `upstream` as it's a bug in `CEF` that has been resolved by the looks of it.

**Closed by amaitland** 2018-01-02 06:53 UTC
Labels: upstream
