### ISSUE TITLE
WebRTC not working with CefSharp

### ISSUE THREAD

**Issue by thwchou** [cefsharp/CefSharp#2441] opened 2018-07-05 19:01 UTC
- **What version of the product are you using?**

63.0.3 Nuget

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

I wrote a small WinForms application to test our CefSharp WebRTC support the display of video from an IP Camera. Unfortunately, it doesn't look like seem to work. The source code is attached

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using CefSharp;
using CefSharp.WinForms;

namespace CameraChromTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            this.FormClosing += Form1_FormClosing1;
            InitializeComponent();
            InitializeChromium();
        }

        private void Form1_FormClosing1(object sender, FormClosingEventArgs e)
        {
            Cef.Shutdown();
        }

        public ChromiumWebBrowser chromeBrowser;

        public void InitializeChromium()
        {
            CefSettings settings = new CefSettings();
            settings.BrowserSubprocessPath = @"x86\CefSharp.BrowserSubprocess.exe";
            // Enable WebRTC                            
            settings.CefCommandLineArgs.Add("enable-media-stream", "1");

            Cef.Initialize(settings, true, null);

            var chromeBrowser = new ChromiumWebBrowser("http://umediaserver.net/umediaserver/demohtml5WebRTCplayer.html");

            this.Controls.Add(chromeBrowser);
            chromeBrowser.Dock = DockStyle.Fill;
        }
    }
}
```

The error that I get is

"Error: Initialization of peer connection failed"

**Comment by amaitland** [comment] 2018-07-06 01:00
You should test with the `CEF Sample Application`.

- Firstly identity which version of `CEF` your actually using, easiest way is to check your `packages.config` file, look for the `cef.redist.x86` package, it's version will be something like `3.2526.1362`, that's the exact version of `CEF` you'll need to download for comparison. You can also open `chrome://version` in the browser to determine the version.
- Open http://opensource.spotify.com/cefbuilds/index.html in a web browser
- Locate the exact `Branch` you require, for the example above the branch is `2526`, all the versions follow a similar pattern
- Locate the `Windows 32bit` or `Windows 64bit` item, if you don't see the exact version, then click `more revisions`
- Download **Test App**
- Are you using `WPF/Offscreen` or `WinForms`? 

**This next part is key**
- To compare with WPF/OffScreen run `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`
- To compare with WinForms `cefclient --multi-threaded-message-loop`

**Comment by amaitland** [comment] 2018-07-06 01:18
Run https://test.webrtc.org/ and see what you get.

`WebRTC` works fine for me using the `Web Cam`. So this is unlikely a bug in `CefSharp`.

**Comment by amaitland** [comment] 2018-07-13 00:56
Using https://github.com/cefsharp/CefSharp.MinimalExample I'm able to open http://umediaserver.net/umediaserver/demohtml5WebRTCplayer.html

It's possible you need to specify a `CachePath`, see https://github.com/cefsharp/CefSharp.MinimalExample/blob/726c328f6a268f5eb13a28d758ed183a853f05bb/CefSharp.MinimalExample.WinForms/Program.cs#L19

Closing as unable to reproduce the problem with the `MinimalExample.`

**Closed by amaitland** 2018-07-13 00:56 UTC
