### ISSUE TITLE
Media Stream Issue On Orientation Change In Tablet

### ISSUE THREAD

**Issue by mismaiel62** [cefsharp/CefSharp#2207] opened 2017-12-08 14:21 UTC
Hi, 

I am using Cefsharp 58.0.0-C12289 (pre-release version) and using Media Stream (for camera) in one of the page.

Stream works perfectly fine but when I change the orientation of my tablet (landscape to portrait or vice verse) then the orientation of stream gets disturbed and it doesn't show the video in proper orientation.

But the same page with same functionality works well on any other browser like Microsoft Edge etc. I am just getting the stream and showing it in Html5 video player.

Is there any solution for this? Or am i missing something in Cef settings?

P.S. One can test chromium with this link: https://webrtc.github.io/samples/src/content/getusermedia/gum/

Thanks,
M.Ismaiel

**Comment by mitchcapper** [comment] 2017-12-08 21:30
Are you able to test with the CEF example to narrow it to being a CEFSharp issue?

**Comment by mismaiel62** [comment] 2017-12-08 21:33
I tried it with CEF and got that issue. But that's not the case with any other browser.

**Comment by mitchcapper** [comment] 2017-12-08 21:34
@mismaiel62 if it happens with CEF you would want to file the bug upstream with cef: https://bitbucket.org/chromiumembedded/cef/issues  as CefSharp is based on it.

**Comment by jankurianski** [comment] 2017-12-10 22:37
@mitchcapper thanks for helping diagnose

@mismaiel62 I will close this issue as there is nothing that can be done in CefSharp, we will have to wait until the problem is fixed in CEF and then incorporate the new version when it is released.  Please report back if you decide to post an issue in the CEF issue tracker or seek help on the [CEF forum](http://magpcss.org/ceforum/) for future reference.

**Closed by jankurianski** 2017-12-10 22:37 UTC
Labels: upstream

**Comment by merceyz** [comment] 2017-12-11 00:09
Upstream issue: https://bitbucket.org/chromiumembedded/cef/issues/2318/media-stream-issue-on-orientation-change
