### ISSUE TITLE
WPF User Interface block/stuck while loading of any web URL

### ISSUE THREAD

**Issue by Sandeep-Prajapat** [cefsharp/CefSharp#2511] opened 2018-09-12 16:27 UTC
Hello, 
We are using the CefSharp WPF version ( https://github.com/cefsharp/CefSharp ) in our WPF window/desktop app. We are using .net framework 4.5 along with the 64 bit version of the CefSharp version 6.3.0.3.0
Whenever any web URL loading in the CefSharp browser the other user interface and animation in the app gets block/stuck during loading. After loading gets finished in the browser, user interface and animations in the app works well.
Any way we can avoid this stuck/block issue while loading of any web URL in the CefSharp browser?

Thanks,
Sandeep Prajapat

**Comment by amaitland** [comment] 2018-09-13 00:58
> Any way we can avoid this stuck/block issue while loading of any web URL in the CefSharp browser?

Never seen this before nor have I had any other reports. 

Please fill out the bug report https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Make sure the issue reproduces with version `67.0.0`, you will need to provide an example that reproduces your problem. See the bug report for fill details.

If no response this will be closed in 7 days.

**Comment by amaitland** [comment] 2018-09-19 23:17
Closing due to lack for feedback. To be reopened you will need to fill out the bug report.

**Closed by amaitland** 2018-09-19 23:17 UTC
