### ISSUE TITLE
Ebay 'I Agree' button is rendering very small

### ISSUE THREAD

**Issue by booktrakker** [cefsharp/CefSharp#3015] opened 2020-01-20 13:56 UTC
I have looked around for an explanation, but I cannot find anything that addresses this, and it worked fine the V71 version I had installed previously.  Since I installed V75.1.143 the 'I Agree' button that is critical to my workflow now renders very small, so tiny that it is nearly invisible.  This is a critical issue for me, and I am hoping it can be resolved quickly.

I attached two images, one from my Cefsharp browser, the other from a Chrome browser.  You can clearly see the problem.  I cannot find any cause, or any solution.  I need to resolve this ASAP as we are due to ship, and this was caught after a late update of the Cefsharp from V71 to V75.

I reach the registration page via this URL which requires an Ebay Account to get to the page in question:

https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&RuName=F-FILEEXL51P1EHH6L899Q9B969GE134DK-FileUpload

I hope you can identify a fix quickly.  I really need to get this resolved.  Thanks!

![ProperEbayButton](https://user-images.githubusercontent.com/57117693/72731779-366d3700-3b49-11ea-94c6-94e90dabc579.jpg)
![SmallEbayButton](https://user-images.githubusercontent.com/57117693/72731781-366d3700-3b49-11ea-99f4-fd36f6418652.jpg)

**Comment by jankurianski** [comment] 2020-01-20 22:04
Remember CefSharp is just a wrapper around CEF.  Please fill out the bug report template provided here: https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

In particular follow the steps in "Does this problem also occur in the CEF Sample Application from ...", ensuring you match the correct CEF version and launch parameters.

Often by following the bug report template, users end up answering their own question as the issue stems from a CEF issue or an issue unique to their application (in which case, you will need to create a fork of the MinimalExample project to demonstrate the issue).

**Comment by booktrakker** [comment] 2020-01-21 13:44
Hi Jan,

 

Thanks for the response.  I took a look at what is involved, and when I unzipped the sample client using a BZ tool I ended up with a large file with no further indication of how to extract the client or do anything with it.  

 

I am under a severe deadline so I am going to uninstall the V75 CefSharp library and revert to what works.  I wish I had time to submit a bug report, but the process is far too involved for the time available to me now.

 

Much appreciated, at least it pointed me in a direction I was wondering if might be best path.

 

Jim Gutterman

Director of Development

BookTrakker.com

 <mailto:jim@booktrakker.com> jim@booktrakker.com

**Comment by booktrakker** [comment] 2020-01-22 17:24
Hi Jan,

 

Just to confirm my experience, I reverted to V71..0.2.0  and the issue went away.  I do not have the time or resources to file a bug report given what is involved, so I am providing this screen shot should you wish to pursue.  I will gladly provide any information needed, but since I could not unzip the Test Environment I cannot proceed with a bug report as you wish.

 

As you can see in the image below, the Agree button renders properly in v71.0.2.0 yet in the next image, shot with the V75.1.143.0 build.  I made no other changes of any kind, I just removed the newer version and replaced it with the older version.  

 

I am sorry if my inability to file a bug report causes any issues, but the workflow you require prohibits me from doing so.  Hopefully this provides sufficient evidence for you to investigate.  Since v71 works for me I am going to proceed with my work on my product.

 

Regards,

Jim

 



 



 

Jim Gutterman

Director of Development

BookTrakker.com

 <mailto:jim@booktrakker.com> jim@booktrakker.com

**Comment by jankurianski** [comment] 2020-01-22 21:32
Hi Jim, I personally don't pursue bug reports - I just try to ease the load on the sole project maintainer that CefSharp has.  Most bugs can be self-solved or redirected if the bug report template is followed and with enough pointers.  I understand you have found a work around by going back to an old version and you don't have the time to pursue your bug further, so I will close the issue.

If in future you have time to file the bug report template, and you discover the problem is solely in the CefSharp project (i.e. rather than within CEF, which has its own support forum and issue tracker, and not within your own code) feel free to re-open this issue.

**Comment by booktrakker** [comment] 2020-01-22 21:37
Understood.  Thanks for the response!

 

Jim Gutterman

Director of Development

BookTrakker.com

 <mailto:jim@booktrakker.com> jim@booktrakker.com

**Closed** 2020-01-22 21:40 UTC
