### ISSUE TITLE
win10 The input method does not support Chinese

### ISSUE THREAD

**Issue by tkggusraqk** [cefsharp/CefSharp#1709] opened 2016-06-14 09:31 UTC
- **What version of the product are you using?**
    - nuget  "49.0.1
```
  <package id="CefSharp.Common" version="49.0.1" targetFramework="net45" />
  <package id="CefSharp.Wpf" version="49.0.1" targetFramework="net45" />
```

- **What architecture x86 or x64?**
x86
- **On what operating system?**
    - win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF
- **What steps will reproduce the problem?**
open http://www.baidu.com ，Chinese input method is used to search, input methods not on screen
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
     http://v1.freep.cn/3tb_16061417304492xk512293.jpg

**Comment by amaitland** [comment] 2016-06-14 09:36
Duplicate of #1262

**Closed by amaitland** 2016-06-14 09:36 UTC

**Comment by fjch1997** [comment] 2016-06-14 09:39
I have the same issue with input methods. They are not working on any website. And on my end, IME crashes the whole application when typing in address bar with IME enabled (No need to actually commit the character. It crashes when any key is pressed with IME enabled). 

There is, however, a workaround avaliable. Steam is using CEF too and it uses a dialog to accept IME input and push the result to the web control programmatically when user press enter. So I guess this is an upstream issue since Steam is not using CefSharp but CEF itself.

**Comment by fjch1997** [comment] 2016-06-14 09:40
OK.... I was writing my comment when you closed it

**Comment by amaitland** [comment] 2016-06-14 09:43
> So I guess this is an upstream issue since Steam is not using CefSharp but CEF itself.

It is an issue with `CEF` for which is there a workaround already listed in #1262 the relevant commit is https://github.com/cefsharp/CefSharp/commit/7eafe6211c5d152915df28224b1925e4d2c01d02

**Comment by amaitland** [comment] 2016-06-14 09:52
@tkggusraqk @fjch1997 In future please take the time to research before posting, a simple search for `IME` would have found you an open issue. The `GitHub` search above is pretty amazing, will search through code and issues.

https://github.com/cefsharp/CefSharp/search?q=ime&type=Issues&utf8=%E2%9C%93

**Comment by tkggusraqk** [comment] 2016-06-16 12:53
@amaitland #1262  Did not solve the problem, the latest version of this problem still exists

**Comment by amaitland** [comment] 2016-06-16 15:22
> @amaitland #1262 Did not solve the problem, the latest version of this problem still exists

@tkggusraqk There is a workaround listed in #1262, if you've used the workaround and it didn't work then there is nothing I can do, the problem needs to be resolved in the `CEF` framework.

**Comment by tkggusraqk** [comment] 2016-06-18 07:10
@amaitland Thank you  very much，use winfrom dll no problem ,but I was wpf
