### ISSUE TITLE
Content not rendering in WPF with CefSharp version 57.0.0

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#2260] opened 2018-02-02 11:50 UTC
Hi Team,

I have upgraded the CefSharp version from 45.0.0 to 57.0.0 to avoid the High DPI rendering issue into WPF project. After upgraded, the content was not rendering in the browser. It showing as empty.

Please find the codes we are using to load the HTML.

` if (Application.Current != null)
                {
                    System.Windows.Application.Current.Dispatcher.Invoke(
                                                               DispatcherPriority.Normal,
                                                               (System.Action)delegate()
                                                               {
                                                                   ChromiumWebBrowser cefSharpBrowser = new ChromiumWebBrowser();
                                                                   MainWindow _mainwindow = Application.Current.MainWindow as MainWindow;
                                                                   cefSharpBrowser = new CefSharp.Wpf.ChromiumWebBrowser();
                                                                   cefSharpBrowser = _mainwindow.MainApplicationWindow.supportModuleView.SupportView.IncidentView.updatesView.IncidentUpdateWithRTE as CefSharp.Wpf.ChromiumWebBrowser;
                                                                   var supportModuleViewDataContext = _mainwindow.MainApplicationWindow.supportModuleView.DataContext as SupportModuleVM;
                                                                   cefSharpBrowser.LoadHtml(UpdateHistory, "http://example/");
                                                                   Keyboard.Focus(cefSharpBrowser);
                                                               });
                }`

Please find the configuration details,

WPF .Net framework version | 4.5.2
-- | --
Machine resolution | 1920 * 1080
CefSharp Version | 57.0.0
Package | Nuget
Platform Architecture | X86
Operating System | Win 10

We are using the customization CS file for CefSharp browser. I had attached the files here.
[CefSharpBrowserExtension.txt](https://github.com/cefsharp/CefSharp/files/1689200/CefSharpBrowserExtension.txt)

Could you please provide us the solution to resolve this problem?

Please let me know the concerns if any.

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment] 2018-02-05 00:51
Please format your code, really hard to read, see https://guides.github.com/features/mastering-markdown/ click the `Code` tab for some examples.

Likely you are calling `LoadHtml` before the browser has been initialized. Subscribe to `browser.IsBrowserInitializedChanged` event to be notified when the browser has been initialized.

**Comment by Arunkumar-Murugesan** [comment] 2018-02-05 07:22
@amaitland : Thanks for the update.

Here I have added the formatted code.

**CefSharpBrowserExtensions**

```
namespace Syncfusion.DirectTrac.WPF.CommonUtils
{
    /// <summary>
    /// Implemetation of Doenload Handler
    /// </summary>
    public class DownloadHandler : IDownloadHandler
    {
        public void OnBeforeDownload(IBrowser browser, DownloadItem downloadItem, IBeforeDownloadCallback callback)
        {
            string downloadPath;
            downloadPath = downloadItem.SuggestedFileName;
        }

        public void OnDownloadUpdated(IBrowser browser, DownloadItem downloadItem, IDownloadItemCallback callback)
        {
            // DO NOTHING
        }
    }

    /// <summary>
    /// Implementation of Context menu for CefSharp Browser
    /// </summary>
    public class LifeSpanHandler : ILifeSpanHandler
    {
        public bool DoClose(IWebBrowser browserControl, IBrowser browser)
        {
            return false;
        }

        public void OnAfterCreated(IWebBrowser browserControl, IBrowser browser)
        {
            // DO NOTHING
        }

        public void OnBeforeClose(IWebBrowser browserControl, IBrowser browser)
        {
            // DO NOTHING
        }

        public bool OnBeforePopup(IWebBrowser browserControl, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IPopupFeatures popupFeatures, IWindowInfo windowInfo, IBrowserSettings browserSettings, ref bool noJavascriptAccess, out IWebBrowser newBrowser)
        {
            try
            {
                System.Diagnostics.Process.Start(targetUrl);
            }
            catch (Exception ex)
            {
                new ErrorLog().LogExceptionMessageToFile("CefSharpBrowserExtensions.cs - LifeSpanHandler()" + ex.StackTrace);
            }
            newBrowser = null;
            return true;
        }
    }

    /// <summary>
    /// Dependency Property for Binding content
    /// </summary>
    public class CefSharpBrowserContent
    {
        public static readonly DependencyProperty HtmlProperty = DependencyProperty.RegisterAttached(
                "Html",
                typeof(string),
                typeof(CefSharpBrowserContent),
                new FrameworkPropertyMetadata(OnHtmlChanged));

        /// <summary>
        /// Property To Get Dependency Property
        /// </summary>
        /// <param name="d"></param>
        /// <param name="value"></param>
        [AttachedPropertyBrowsableForType(typeof(CefSharp.Wpf.ChromiumWebBrowser))]
        public static string GetHtml(CefSharp.Wpf.ChromiumWebBrowser d)
        {
            return (string)d.GetValue(HtmlProperty);

        }

        /// <summary>
        /// Property To set Dependency Property
        /// </summary>
        /// <param name="d"></param>
        /// <param name="value"></param>
        public static void SetHtml(CefSharp.Wpf.ChromiumWebBrowser d, string value)
        {
            d.SetValue(HtmlProperty, value);
        }

        /// <summary>
        /// Method is called when frameworkMetaDataChanges
        /// </summary>
        /// <param name="dependencyObject"></param>
        /// <param name="e"></param>
        static void OnHtmlChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
        {
            try
            {
                var webBrowser = dependencyObject as CefSharp.Wpf.ChromiumWebBrowser;
                if (webBrowser != null && e.NewValue != null)
                    if (string.IsNullOrEmpty(e.NewValue.ToString()))
                    {
                        webBrowser.LoadHtml(string.Empty, "http://example/");
                    }
                    else
                    {
                        webBrowser.LoadHtml(e.NewValue as string, "http://example/");

                        HideScriptErrors(webBrowser, true);
                    }
            }
            catch (Exception ex)
            {

            }
        }

        /// <summary>
        /// This method is used ignore script error for web browser control
        /// </summary>
        private static void HideScriptErrors(CefSharp.Wpf.ChromiumWebBrowser wb, bool hide)
        {
            System.Reflection.FieldInfo fieldComWebBrowser = typeof(CefSharp.Wpf.ChromiumWebBrowser).GetField("_axIWebBrowser2", BindingFlags.Instance | BindingFlags.NonPublic);
            if (fieldComWebBrowser == null) return;
            object objComWebBrowser = fieldComWebBrowser.GetValue(wb);
            if (objComWebBrowser == null) return;
            objComWebBrowser.GetType().InvokeMember("Silent", BindingFlags.SetProperty, null, objComWebBrowser, new object[] { hide });
        }
    }

    /// <summary>
    /// Extended functionality for CefSharp Browser
    /// </summary>
    public class CefSharpBrowserExtension
    {
        bool isControlKeyPressed = false;
        double maxZoomLevel = 8;
        double minZoomLevel = -8;
        ChromiumWebBrowser browser = new ChromiumWebBrowser();
        public CefSharpBrowserExtension(ChromiumWebBrowser newbrowser)
        {
            browser = newbrowser;
            browser.DownloadHandler = new DownloadHandler();
            browser.LifeSpanHandler = new LifeSpanHandler();
            browser.ContextMenu = new System.Windows.Controls.ContextMenu();
            browser.ZoomLevel = 0;
            browser.ZoomLevelIncrement = 0.5;
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "Select All", Command = browser.SelectAllCommand });
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "Copy", Command = browser.CopyCommand });
            browser.ContextMenu.Items.Add(new MenuItem() { Header = "View Source", Command = browser.ViewSourceCommand });
            //browser.ContextMenu.Items.Add(new MenuItem() { Header = "Zoom In", Command = browser.ZoomInCommand });
            //browser.ContextMenu.Items.Add(new MenuItem() { Header = "Zoom Out", Command = browser.ZoomOutCommand });
            //browser.ContextMenu.Items.Add(new MenuItem() { Header = "Reset", Command = browser.ZoomResetCommand });
            browser.MouseWheel += OnMouseWheel;
            browser.PreviewKeyDown += OnKPreviewKeyDown;
            browser.PreviewKeyUp += OnPreviewKeyUp;
        }

        private void OnPreviewKeyUp(object sender, KeyEventArgs e)
        {
            try
            {
                if (e.Key == Key.RightCtrl || e.Key == Key.LeftCtrl)
                {
                    isControlKeyPressed = false;
                }
            }
            catch (Exception ex)
            {
                new ErrorLog().LogExceptionMessageToFile("CefSharpBrowserExtensions.cs - OnPreviewKeyUp()" + ex.StackTrace);
            }
        }

        private void OnKPreviewKeyDown(object sender, KeyEventArgs e)
        {
            try
            {
                if (e.Key == Key.RightCtrl || e.Key == Key.LeftCtrl)
                {
                    isControlKeyPressed = true;
                }
            }
            catch (Exception ex)
            {
                new ErrorLog().LogExceptionMessageToFile("CefSharpBrowserExtensions.cs - OnKPreviewKeyDown()" + ex.StackTrace);
            }
        }

        private void OnMouseWheel(object sender, MouseWheelEventArgs e)
        {
            try
            {
                if (isControlKeyPressed)
                {
                    if (e.Delta > 0 && browser.ZoomLevel < maxZoomLevel)
                    {
                        browser.ZoomInCommand.Execute(null);
                    }
                    else if (e.Delta < 0 && browser.ZoomLevel > minZoomLevel)
                    {
                        browser.ZoomOutCommand.Execute(null);
                    }
                }
            }
            catch (Exception ex)
            {
                new ErrorLog().LogExceptionMessageToFile("CefSharpBrowserExtensions.cs - OnMouseWheel()" + ex.StackTrace);
            }
        }

    }
}
```

Here's is the content loading method,

```
private void LoadIncidentUpdatesHistory()
        {
            if (!string.IsNullOrEmpty(IncidentUpdateHistory))
            {
                if (Application.Current != null)
                {
                    System.Windows.Application.Current.Dispatcher.Invoke(
                                                               DispatcherPriority.Normal,
                                                               (System.Action)delegate()
                                                               {
                                                                   ChromiumWebBrowser cefSharpBrowserIncidentUpdates = new ChromiumWebBrowser();
                                                                   MainWindow _mainwindow = Application.Current.MainWindow as MainWindow;
                                                                   cefSharpBrowserIncidentUpdates = new CefSharp.Wpf.ChromiumWebBrowser();
                                                                   cefSharpBrowserIncidentUpdates = _mainwindow.MainApplicationWindow.supportModuleView.SupportView.IncidentView.updatesView.IncidentUpdateWithRTE as CefSharp.Wpf.ChromiumWebBrowser;
                                                                   var supportModuleViewDataContext = _mainwindow.MainApplicationWindow.supportModuleView.DataContext as SupportModuleVM;
                                                                   cefSharpBrowserIncidentUpdates.LoadHtml("https://www.google.co.in/", "http://example/");
                                                               });
                }
            }
        }
```
In this above code, the browser has been initialized before it could be load. Please find the screen shot for the browser initialized,

![image](https://user-images.githubusercontent.com/20086495/35792260-40edf8a4-0a72-11e8-9b3d-fdbbe3708605.png)


Previously, we are using the same codes for CefSharp version 45.0.0 and the content was rendering properly. We planned to upgrade the version for avoiding the rendering problem in High resolution DPI machines.
After upgrading into the version 57.0.0, we are getting this issue.

Please let me know if you need any further details.

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment] 2018-02-05 07:29
`CefSharp` supports `GitLink`, you can step into the code and see what's going on see https://github.com/cefsharp/CefSharp/issues/1680 for details.

**Comment by amaitland** [comment] 2018-02-05 07:44
See https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp/WebBrowserExtensions.cs#L297 to understand what's going on when you call `LoadHtml`. You might be better to use the other version that loads html as a `data:uri`. see https://github.com/cefsharp/CefSharp/blob/cefsharp/57/CefSharp/WebBrowserExtensions.cs#L270

**Comment by Arunkumar-Murugesan** [comment] 2018-02-07 09:01
@amaitland : I didn't get any exception for the browser initialization since the browser was initialized as true before it comes to load html method. Is there a way to initialize the browser manually to true? since it is an read only property.

Please find the screen short,

![image](https://user-images.githubusercontent.com/20086495/35901028-ca52fab6-0bfa-11e8-84aa-0f81aa887dbc.png)

I'm using the version 63.0.0-pre03 instead of 57.0.0 since I noticed in the release notes of 63.0.0-pre03, the High DPI https://github.com/cefsharp/CefSharp/issues/1571 has been fixed in this version only.
Is this issue https://github.com/cefsharp/CefSharp/issues/1571 has been fixed in 57.0.0 version?

As per your suggestion, I tried this Load html in my code, but still the content not rendering,

```
       ChromiumWebBrowser cefSharpBrowser = new ChromiumWebBrowser();
                                                                   MainWindow _mainwindow = Application.Current.MainWindow as MainWindow;
                                                                   cefSharpBrowser = new CefSharp.Wpf.ChromiumWebBrowser();
                                                                   cefSharpBrowser = _mainwindow.MainApplicationWindow.supportModuleView.SupportView.IncidentView.updatesView.IncidentUpdateWithRTE as CefSharp.Wpf.ChromiumWebBrowser;
                                                                   var supportModuleViewDataContext = _mainwindow.MainApplicationWindow.supportModuleView.DataContext as SupportModuleVM;
                                                                   //cefSharpBrowser.LoadHtml(IncidentUpdateHistory, "http://example/");
                                                                   //cefSharpBrowser.Address = IncidentUpdateHistory;
                                                                   cefSharpBrowser.Load("data:text/html," + IncidentUpdateHistory);
```

Also I tried to link the CefSharp source to my project using this link https://github.com/cefsharp/CefSharp/issues/1680. I have downloaded the project from the below location,

![image](https://user-images.githubusercontent.com/20086495/35907159-1b94051a-0c13-11e8-9afe-6afcde91cd45.png)

Here I couldn't find the solution of the project. Could you please suggest me how could I proceed this? 

![image](https://user-images.githubusercontent.com/20086495/35907301-84497144-0c13-11e8-83a6-6856b5ba344b.png)

Which one I have to use this?

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment] 2018-02-07 12:49
Follow the instructions on the GitLink home page, there is no need to download GitLink it's self, just configure Visual Studio as they suggest. 

If you're still having problems after you get debugging working try modifying the CefSharp MinimalExample project to reproduce your probably

**Comment by Arunkumar-Murugesan** [comment] 2018-02-08 10:35
I had tried this link for configuring the below criteria's,

Enabled source server support, Installed the Git link package and installed the chocolatey with using the link provided. But I didn't aware how could I proceed further. Also it showing it required only VS 2012. Is it only required?

Is there any document to be followed the configuration completely?

I'm new for cefSharp. Could you please guide me to resolve this problem?

**Comment by amaitland** [comment] 2018-02-08 10:48
GitLink is independent of CefSharp, once you've enabled source server support you should be able to step into the CefSharp code in the debugger.

**Comment by Arunkumar-Murugesan** [comment] 2018-02-08 13:12
Shall we do this in Visual studio 2015?

Is there any workflow document for this?

**Comment by amaitland** [comment] 2018-02-08 22:24
63.0.0 is out, try upgrading.

GitLink is incredibly easy in my experience, if you need more information then try using your preferred search engine.

**Comment by Arunkumar-Murugesan** [comment] 2018-02-09 13:18
[TestSampleProject.zip](https://github.com/cefsharp/CefSharp/files/1711103/TestSampleProject.zip)

@amaitland : I have created simple sample with upgrading 63.0.0 version. Here I had faced the reference problem in cefSharp.

Could you please meet my requirements in this sample for loading the data?

**Comment by merceyz** [comment] 2018-02-09 14:56
No binary files

**Comment by amaitland** [comment] 2018-02-11 08:37
Upload your code to GitHub or another similar service if you'd like someone to look at it.

**Comment by Arunkumar-Murugesan** [comment] 2018-02-12 05:15
@amaitland : I have uploaded my project into GitHub. Please find sample under the master branch,

https://github.com/Arunkumar-Murugesan/CefSharp/blob/master/TestSampleProject.zip

**Comment by merceyz** [comment] 2018-02-12 12:26
That's also a binary file

**Comment by Arunkumar-Murugesan** [comment] 2018-02-12 12:30
@merceyz : can you please guide, how could upload into binary files? I just upload the entire projects into the github

**Comment by amaitland** [comment] 2018-02-13 01:31
The general idea is you fork the main project or the `MinimalExample`, make your changes, push those changes to `GitHub`, then they can easily be reviewed. A zip file is useless to me on my phone, and that's where I read most of the content these days.

**Comment by amaitland** [comment] 2018-02-13 01:33
> Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).

Direct excerpt from https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

**Comment by Arunkumar-Murugesan** [comment] 2018-02-13 05:52
@amaitland : I have uploaded my files into github. Please checkout of my sample here

https://github.com/Arunkumar-Murugesan/CefSharp_SampleProject

**Comment by Arunkumar-Murugesan** [comment] 2018-02-13 13:48
@amaitland : I have added added platform as x86 and removed unwanted codes. Please find the updated source here https://github.com/Arunkumar-Murugesan/CefSharp_WpfSample_63.0.0

**Comment by Arunkumar-Murugesan** [comment] 2018-02-14 19:52
Is there any update on this?

**Comment by Arunkumar-Murugesan** [comment] 2018-02-19 05:28
could you please update me on this? or need any other details from this?

**Comment by Arunkumar-Murugesan** [comment] 2018-02-23 04:00
Hi Team,

Could you please look into my request?

**Comment by amaitland** [comment] 2018-03-06 02:19
> SupportVM doesn't appear to be assigned anywhere other than letting the designer know that type the DataContext is

Where is your view model assigned to the data context? Your example appears to be incomplete.

I'm closing this as `invalid` as I'm unable to reproduce the problem using the `MinimalExample` and version `63.0.1`. 

Your `Html AttachedProperty` didn't take into account the browser not being initialized, when it wasn't initialized `LoadHtml` would never have been called. 

Here is a [Gist](https://gist.github.com/amaitland/ddf0905072b00ebbe29e1c0e1031c4c6) that handles the browser not being initialized.

If you have further questions please ask them on `Gitter`.

**Closed by amaitland** 2018-03-06 02:19 UTC
Labels: invalid
