### ISSUE TITLE
Change preferences via CefRequestContext 

### ISSUE THREAD

**Issue by midas643** [cefsharp/CefSharp#1405] opened 2015-11-05 16:50 UTC
I would like to change preferences(proxy settings, etc.) during runtime I see this is possible with CEF
https://bitbucket.org/chromiumembedded/cef/issues/1709/allow-configuration-of-preferences-during however CefSharp still doesn't have this functionality wrapped. That would be nice to see it in the future releases.  Thank you :smile_cat:

**Comment by illfang** [comment] 2015-11-05 17:08
duplicate of #1308

**Comment by jankurianski** [comment] 2015-11-05 22:31
Good spotting @illfang, closing this issue.

@midas643 As CefSharp is an open-source project, features are only implemented when a developer needs them.  The current active contributors to CefSharp do not need to change preferences during runtime, so the feature will probably not be implemented unless someone new steps up.

**Closed by jankurianski** 2015-11-05 22:31 UTC
