### ISSUE TITLE
WPF application using CEF does not run in Debug Mode

### ISSUE THREAD

**Issue by greuterc** [cefsharp/CefSharp#2160] opened 2017-10-10 13:39 UTC
I am trying to get CEF to work in a WPF application. However it does not compile/Start in Debug. Release seems to work.

What i did:
- installed the VC++ dist for x86 and x64
- Installed the nuget package cefSharp.wpf
- Set Platform in my project to x86

Debug fails with:

Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.	ProjectNamexy	D:\Projekte\ProjectNameXy\SGEN		

Any ideas?

**Comment by ewan-derivco** [comment] 2017-12-12 16:14
Hi, Getting the same error. This seems to be triggered by "Generate serialization assembly" in the project build configuration. If you set it to on it will fail to build. If you set it to Off it will build successfully.

It is recreatable (for me) with the https://github.com/cefsharp/CefSharp.MinimalExample WPF project

I'm guessing that this is because it tries to generate serialisation assemblies for both the x86 and x64 dll using just the one version of sgen.exe

**Comment by amaitland** [comment] 2017-12-22 00:58
> It is recreatable (for me) with the https://github.com/cefsharp/CefSharp.MinimalExample WPF project

What are the steps to reproduce? Are you turning on `Generate serialization assembly`?

**Comment by ewan-derivco** [comment] 2017-12-22 08:30
Open the project, set Generate serialization assembly to on, attempt to build

**Comment by amaitland** [comment] 2018-01-03 22:45
Closing as duplicate of #2223 (it's got a better description)

**Closed by amaitland** 2018-01-03 22:45 UTC
Labels: more-details-needed-from-op
