### ISSUE TITLE
In singleton instance of ChromiumWebBrowser hang appears when dialog is reopened of wpf app

### ISSUE THREAD

**Issue by abhargav7** [cefsharp/CefSharp#2088] opened 2017-07-13 09:24 UTC
In a singleton instance of ChromiumWebBrowser hosted inside a user control of a dialog , there is a  hang when dialog is reopened of wpf app, no threading issue is there.
u can see the web page but you cannot click on web page.
There is no such issue if dialog is opened first time. issue only occurs on reopening the dialog in which ChromiumWebBrowser is there inside a user control.

Basically seems a focus issue, if i throw an exception inside a code issue is gone.

**Comment by jankurianski** [comment] 2017-07-13 22:36
Can you please fork https://github.com/cefsharp/CefSharp.MinimalExample on GitHub and push an example that reproduces the problem?

**Comment by abhargav7** [comment] 2017-07-14 09:35
Thanks for reply.
First of all purpose of making the Browser control as singleton is to retain the  previous browser state means if previous browser session has some images or content in text blocks etc, after the user reopens the WPF dialog in which this Browser control is hosted.
-----
I looked at the example and there is two difference from my project 
1.  I do not have App.xaml.cs implementation for Cef.Initialize(settings, performDependencyCheck: true, browserProcessHandler: null);;; but i did implement it where I initialize the Usercontrol that has the ChromiumWebBrowser
2 . I load ChromiumWebBrowser in usercontrol not in MainWindow->MainWindow laods the usercontrol
This issue does not come if I remake or new the instance of UserControl hosted inside the dialog, but this resets the previous browser state means if previous browser session has some images or content in text blocks etc
[GUI.zip](https://github.com/cefsharp/CefSharp/files/1147966/GUI.zip)

**Comment by merceyz** [comment] 2017-07-14 10:16
No binary files

**Comment by abhargav7** [comment] 2017-07-14 11:25
It will take some time to make a new project, will do in the weekend, In mean time do you have any clue how to retain the previous browser state(every user input/ changed address etc), any property in ChromiumWebBrowser itself so that I reassign that to a new ChromiumWebBrowser  instance when its made on reopen of dialog? 
Or clue whats been wrong in above?

**Comment by abhargav7** [comment] 2017-07-14 12:00
https://github.com/abhargav7/CefSharp/tree/abhargav7-patch-1

After downloading Mimimal Code to reproduce:-
Just open modal dialog:- do a google
reopen  modal dialog there is a hang

**Comment by Angular2Coder** [comment] 2017-07-14 13:45
I also faced same issue in a very basic senario.
WebBrowser control in wpf which is IE based resolved this issue.

**Comment by abhargav7** [comment] 2017-07-15 05:10
Team,
Is this a bug then, known issue?
I have a very common use case for it in my application. This bug is stopping me to use this browser in my application.
Can I have a fix please? 
Thanks

**Comment by abhargav7** [comment] 2017-08-31 06:05
Any update?
Let me know if you need for info on this?
Thanks!!

**Comment by perlun** [comment] 2017-12-02 20:45
> Can I have a fix please?

Unfortunately, that's not really how it works.

CefSharps works well for a lot of companies and individuals; we use at work for _numerous_ projects. It serves us well; we use the WPF component. The stability is great, we instantiate new `ChromiumWebBrowser` every time the user opens a web app, and close it whenever they close the app.

Now, you have a problem with the library because of this bug? That's fine. But really, you must be aware that just because you feel that this is a "very common use case in your application" doesn't mean that _everybody else_ feels this problem is equally important to them.

Remember: most people who devote time working on CefSharp do so on their spare time.

That basically means: you can ask questions, report bugs etc. Things which are problematic for other people also tend to be fixed sooner. Things which _only you_ happen to run into, well - they get lower priority.

The only _sure_ way to get your bug fixed is either:

1. To fix it yourself and submit a pull request. (They are highly welcome! We have 113 individual contributors at the moment), _or_
2. Pay someone to fix it.

Sad but true, this is the way it works at the moment. If we would get bought by Google (very unlikely!), things might end up being a bit different. But that's not the way right now.

Sorry if I sound a bit harsh; I just want to make sure people have the right expectations here.

**Comment by amaitland** [comment] 2017-12-19 02:39
By default when `CleanupElement` is unloaded the `ChromiumWebBrowser` will be `Disposed`. The `CleanupElement` if not specified will default to `Window.GetWindow(this)`. So when your `Dialog` is unloaded the browser will be disposed. If you manually set `CleanupElement` to `null` after `Loaded` then you could be able to reuse the instance. Look at the source if you need to know more.

You will then be responsible for disposing if your own `ChromiumWebBrowser` instances, if you fail to do so, it's possible your app fill hang on exit.

**Comment by amaitland** [comment] 2018-01-11 02:06
Closing this as I don't believe it's a bug. If setting `CleanupElement` to `null` doesn't work then report back. You should be able to debug the code easy enough.

**Closed by amaitland** 2018-01-11 02:06 UTC
Labels: wpf
