### ISSUE TITLE
Page Download not working with offscreen.

### ISSUE THREAD

**Issue by FairSite2C** [cefsharp/CefSharp#1885] opened 2016-12-09 16:36 UTC
I have an scrapping app that was working great until Monday. Has been working for about 3 months. I am gathering information off a major retail site and processing about 10,000 pages a day. 

Since Monday at 10 pm when I requested a page all I would get back is an empty html document . Nothing but html, head, body tags. This editor will not display it 

At first I thought the site had caught on and screwing with me but I don't believe that is the case since I get the same results from different computers on different networks and different sites. On different sites sometimes the page loads sometimes I get the empty doc result.

Next I thought maybe it was because of big page sizes. I created on disk a 12 meg file and it loaded just fine.

I went back and ran older versions of my project with the same result. That would seem to rule out code change causes. 

What is even stranger is nothing seems to write to debug.log which before recorded copious amounts of information.

I am using cefsharp 53, the latest available on nuget. 

Totally stumped and desperate here.

Sounds bizarre? Any clues to get me out of this mess would be appreciated.

**Comment by amaitland** [comment] 2016-12-19 21:04
Duplicate of #1880

**Closed by amaitland** 2016-12-19 21:04 UTC
Labels: duplicate
