### ISSUE TITLE
Youtube issue fullscreen

### ISSUE THREAD

**Issue by Sential** [cefsharp/CefSharp#942] opened 2015-04-12 13:43 UTC
Fullscreen in Youtube doesn't working. Please fix it ;)
Best regards, Eryk.

**Comment by javathunderman** [comment] 2015-04-12 15:22
Interesting- @AJDev77 we have the same issue, don't we?

**Comment by avspeed** [comment] 2015-04-12 17:33
I do not believe that this is a CefSharp issue.
It is a Cef issue..

https://bitbucket.org/chromiumembedded/cef/issue/562

I have just tested with the cefclient binary demo here https://cefbuilds.com/
and it does not work there either.

It appears that there is a patch attached to the cef issue. If you feel adventurous, you can apply the patch and rebuild cef ..

**Comment by AJDev77** [comment] 2015-04-12 18:29
Did anyone notice that YouTube is not loading at all, or is that just my build? I feel like it is just my build, because someone would have noticed... Anyway, YouTube is loading the page securely (https), but in the video stats, it shows it is trying to load the video from an un-secure line (http). This could be a completely different issue though.

**Comment by avspeed** [comment] 2015-04-12 18:35
@AJDev77 I cannot reproduce what you are experiencing.

**Comment by AJDev77** [comment] 2015-04-12 18:43
Ignore that... Just tried some things, and it appears to be an issue with YouTube. If I set a custom user agent, it does not load, but if I don't set a custom user agent (so it uses the default one with Chrome listed) the videos load just fine.

**Comment by avspeed** [comment] 2015-04-12 18:59
It appears that YouTube doe snot like people messing with the user agent  

http://forum.maxthon.com/thread-10828-1-1.html

**Comment by amaitland** [comment] 2015-04-12 22:24
Closing this as there is already #720

**Closed by amaitland** 2015-04-12 22:24 UTC
Labels: duplicate
