### ISSUE TITLE
ContextMenu not working v53

### ISSUE THREAD

**Issue by bsw-msc** [cefsharp/CefSharp#1865] opened 2016-11-14 12:18 UTC
Hey, 

I just updated from CefSharp v49.0.1 to CefSharp v53 (NuGet, WPF) and now my XAML context menu isn't working anymore as it isn't show up.

I ran some tests with the CefShap.MinimalExample.Wpf v49.0.1 till v53 (NuGet, too). V51s' context menu is working but v53s' not.

I edited the [CefSharp.MinimalExample.Wpf](https://github.com/cefsharp/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.Wpf) with a [new ContextMenuHandler](http://pastebin.com/Ut0MvH0z) and added a [simple FrameworkElement.ContextMenu](http://pastebin.com/eFv5gteU) to the [wpf:ChromiumWebBroser](https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.Wpf/MainWindow.xaml) element.

- Windows 10 (x64), latest updates, .NET 4.6.1
- Issue appears on both CefSharp x64 and x86
- WPF
- NuGet

Can you confirm that?

Regards

**Comment by amaitland** [comment] 2016-12-01 02:00
Duplicate of #1767

**Closed by amaitland** 2016-12-01 02:00 UTC
