### ISSUE TITLE
Object does not registred while js call to c#.

### ISSUE THREAD

**Issue by tonn** [cefsharp/CefSharp#1032] opened 2015-05-18 16:26 UTC
Some pseudo-code to show which class structure I want to use

```
--- mainform.cs ---

browser.RegisterJsObject("jsproxy", new JSProxy())

--- JSProxy.cs ---

class JSProxy
{
  CreateModel()
  {
    browser.RegisterJsObject("model", new model());
  }
}

--- view.js ---

JSProxy.CreateModel() <--- JSProxy work normally
var data = model.someprop; <---- model is undefined
```

Are there some restrictions to use browser.RegisterJsObject? 
Is it possible to create dynamicaly c#-objects from js code and get access to this object from js?
How can I UnRegisterJsObject?

**Comment by jamespearce2006** [comment] 2015-05-18 17:13
Can't you create a method on JSProxy that returns model?

    public class JsProxy
    {
        model CreateModel() 
        {
            return new model();
        }

    }

    browser.RegisterJsObject("jsproxy", new JSProxy())

    --- view.js ---

    var model = JSProxy.CreateModel();
    var data = model.someprop;

**Comment by amaitland** [comment] 2015-05-19 00:54
> Are there some restrictions to use browser.RegisterJsObject?

Yes there are, see the FAQ.

https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#3-how-do-you-expose-a-net-class-to-javascript

**Comment by amaitland** [comment] 2015-05-19 00:54
> How can I UnRegisterJsObject?

There is no feature to do that currently.

**Comment by tonn** [comment] 2015-05-19 08:51
>jamespearce2006: Can't you create a method on JSProxy that returns model?
I try this way, but as I understand - it makes copy of returned model and if model is changing in C# thread there aren't changes in JS-model

JS-model and C#-model changing synchronously If use RegisterJsObject

I try other way - get model from c# on each step when redraw chart, and it works. But I cannot predict a overhead of this method.

problem 2: in some reason returned JS-model does not have methods from C#-class only properties. 

There is code of view.js from my project with comments paste.org.ru/?jgv0td

**Comment by tonn** [comment] 2015-05-19 08:59
> amaitland: Yes there are, see the FAQ.
> from FAQ: // After your ChromiumWebBrowser has been created
There is just example where RegisterJsObject calls before browser is shown (or when it is doing binding of all RegisterJsObject-objects? ), but there is not note about necessary of this sequence call methods. It is not so obviously. Can you write remark about this case explicitly in FAQ?
Thanks.

**Comment by amaitland** [comment] 2015-05-19 09:24
> Can you write remark about this case explicitly in FAQ?

What addition are you proposing exactly? Any use with a `GitHub` account can edit the `wiki`, so your welcome to make improvements yourself.

**Comment by tonn** [comment] 2015-05-20 13:17
>so your welcome to make improvements yourself.

I've added note to FAQ as I understood RegisterJsObject behavior

**Comment by amaitland** [comment] 2015-05-20 21:09
> Need to Register objects directly after Browser is created as there's no on the fly binding as yet

This statement was intended to convey the same information, I guess maybe that doesn't mean the same to everyone. Will make a few tweaks to that `FAQ` item later, think it's time to remove the `CefSharp1` reference.

**Comment by amaitland** [comment] 2015-05-20 21:10
Unless there is something else, I'm going to close this as I believe #602 represents the feature you were after.

**Closed by amaitland** 2015-05-20 21:10 UTC
