### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by ArtyP** [cefsharp/CefSharp#1691] opened 2016-05-20 14:14 UTC
Hello,
I'm currently supporting CEFSharp app. After updating from version 39 to 49 virtual keyboard does not appear any more. I have read all issues I had found and tried all possible combinations of them . No success.
The list of workarounds I have tried:
- set FocusHandler to null;
- set MultiThreadedMessageLoop to false;
- [automatically display the touch keyboard;](http://www.windowscentral.com/auto-display-touch-keyboard-windows-10-desktop-mode)
- Set browser focus;
- Enabling touch-events;
- some other tricks, which did not help.

Then I have installed Visual Studio on tablet, build a WinForms example 49. But keyboard still does not appear. My question is, what should I do **to make keyboard appear** in this simple example.

System:
- Lenovo miix 3 1030
- CefSharp version 49.0
- x86
- Win10
- WinForms

Steps will reproduce:
Start CefSharp.WinForms.Example on tablet.

In cefclient (from http://cefbuilds.com) keyboard works properly.

**Comment by amaitland** [comment] 2016-05-20 19:35
> Then I have installed Visual Studio on tablet, build a WinForms example 49. But keyboard still does not appear. My question is, what should I do to make keyboard appear in this simple example.

Does the problem reproduce in `47.0.4`? You might be better to rollback a version.

> In cefclient (from http://cefbuilds.com) keyboard works properly.

Did you explicitly use `3.2623.1396`?

**Comment by amaitland** [comment] 2016-05-20 19:51
Also make sure you don't have a physical keyboard plugged in when testing.

**Comment by ArtyP** [comment] 2016-05-23 10:46
Thanx for your help. After rollback to **47.0.4** my project works perfectly fine for me.
In CefSharp.WinForms.Example you need to set FocusHandler to null. Otherwise virtual keyboard appears but keypress does not work.
Should we close the issue?

**Comment by amaitland** [comment] 2016-05-23 11:17
> Should we close the issue?

I will assign this to the `51.0.0` milestone, I'll let you know when a test build is available. If you have time I'd appreciate if you could re-test.

**Comment by ArtyP** [comment] 2016-05-23 11:27
Sure.

**Comment by amaitland** [comment] 2016-05-30 07:39
The `master` branch has been upgraded to `CEF 2704.1415` which is based on Chromium `51.0.2704.63`. If you have time to download the source and test this out that would be much appreciated.

A `-pre` release based on this version will likely be released in the next couple of weeks.

**Comment by amaitland** [comment] 2016-06-09 21:43
@ArtyP  `51.0.0-pre01` packages are on `Nuget.org`, appreciate if you could test them out.

**Comment by martin-k** [comment] 2016-08-26 10:15
We are developing a kiosk solution using Windows 10 and CefSharp but we have the same problem with the touch keyboard not appearing in 49 and 51. We tried downgrading to version 47 hoping that would fix it, but no luck. When using a Chrome browser, the keyboard appears.
So we are wondering: Are we even initialising CEF correctly? What are the required settings in CEF for making the onscreen keyboard appear?

**Comment by amaitland** [comment] 2016-08-26 10:21
> We are developing a kiosk solution using Windows 10 and CefSharp but we have the same problem with the touch keyboard not appearing in 49 and 51. We tried downgrading to version 47 hoping that would fix it, but no luck.

Your using `WinForms`? If your using `WPF` then that's a totally different issue.

> When using a Chrome browser, the keyboard appears.

It's not relevant to compare to `Chrome`  in this instance,  see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

> What are the required settings in CEF for making the onscreen keyboard appear?

There are none, `CefSharp` has no control, it's just a wrapper. It either works or it doesn't.

**Comment by martin-k** [comment] 2016-08-26 11:02
Its a WinForms project. 
So if I understand you correctly I should be looking for solutions on the CEF forums instead? Sorry for posting in this thread then, it just sounded exactly like our problem. You can delete these comments if you wish.

**Comment by amaitland** [comment] 2016-08-26 11:06
> So if I understand you correctly I should be looking for solutions on the CEF forums instead?

If you can reproduce the problem using `cefclient` then the bug will need to be resolved in `CEF`. I don't have a touch screen, so someone else needs to take responsibility for this issue.

**Comment by nuttaone** [comment] 2016-11-07 15:49
I have had this issue all the way back to v41 being the last known working version for my kiosks.
As I desperately needed to upgrade and move forward on to v53 to use more newly exposed APIs I created a workaround using the RegisterAsyncJsObject to inject an "addEventListener" for "touchstart" (touch only events) on common input types, to start the tabtip.exe process manually. Although it may not be the best practical solution but it works for myself and could prove useful to others using Cefsharp.
However I'm fairly new to github and if someone points me where I can provide an example I'd be more than happy to share my workaround.

**Comment by amaitland** [comment] 2017-01-10 01:09
Someone experiencing this problem should test with the examples provided in #1748 It's possible that integrating into your applications existing message loop will resolve this issue.

**Comment by mismaiel62** [comment] 2017-08-08 14:31
Hi,
I am using CefSharp 58.0.0-CI2289 in my app and Virtual Keyboard doesn't appear on clicking any editable box in my app on tablet.
Anyone have solution to this problem?

**Comment by hahrens** [comment] 2017-08-20 18:37
After a long time of looking for a solution, i finally found one that works for me and bring up the onscreen-keyboard as expected. Found it in a [Youtube-Video](https://www.youtube.com/watch?v=e4OBPpAWksw):
Add `"disable-usb-kyboard-detect=1"` as CommandLine-Argument

            CefSettings settings = new CefSettings();
            settings.CefCommandLineArgs.Add("disable-usb-keyboard-detect", "1");
            Cef.Initialize(settings);

This brings up the Windows OnScreen-Keyboard every time i touch into an input field. Tested with Cef v47.0.4 and installed Chrome v60.0.3112.101.

**Comment by mismaiel62** [comment] 2017-08-29 14:18
@hahrens Thanks mate.
worked perfectly fine for me.

Otherwise, I was launching keyboard process through JS (which is extra headache and slows degrades the performance) before your solution.

Thumps up (Y)

**Comment by amaitland** [comment] 2018-07-23 09:52
Tested with the latest `MinimalExample` which is based on version `65` and it's working correctly on my `Surface Pro 1` running `Windows 10`. Those experiencing issues should use the `disable-usb-keyboard-detect` command line argument.

https://github.com/cefsharp/CefSharp.MinimalExample

**Closed by amaitland** 2018-07-23 09:52 UTC
Labels: known-issue, up-for-grabs, winforms

**Comment by avzuylen** [comment] 2018-11-28 14:30
Hello, I'm using version 69. The onscreen keyboard correctly pops up when I touch an entry box. Problem is it ALSO pops up when I click in it with a mouse. I have tried 'disable-usb-keyboard-detect' set to '0' and '1' but no effect. Does anyone know a solution?

**Comment by avzuylen** [comment] 2018-11-30 10:50
Thanks, I have downgraded to version 65.0.1 where it works fine.
It also works ok with version 67.0.0 but there I have the problem that session cookies are not cleared on exit (is this a known problem as well?). So I just stick to 65.0.1 for the time being.

**Comment by RukaiYu** [comment] 2019-01-17 03:07
Hello @avzuylen

> Thanks, I have downgraded to version 65.0.1 where it works fine.
> It also works ok with version 67.0.0 but there I have the problem that session cookies are not cleared on exit (is this a known problem as well?). So I just stick to 65.0.1 for the time being.
I tried on CEF 68, but it seems does work....

**Comment by amaitland** [comment] 2019-01-17 05:15
`71.0.0-pre01` is out, you should try upgrading.

**Comment by akhudairy** [comment] 2020-12-28 11:17
Tried it on 84.1.1 but it is **not** working for me

**Comment by fotoguy42** [comment] 2022-03-28 20:22
Just tested with the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) on 99.2.90 and it does not work the majority of the time on a Surface Go original. I did get the keyboard to pop up once while randomly scrolling and tapping, and then the keyboard would popup regardless of if a text field had focus.

**Comment by amaitland** [comment] 2022-03-28 20:49
> Tested with the [cefclient](https://cef-builds.spotifycdn.com/index.html#windows64) and tapping text fields does work.

Did you test with the command line args listed at https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

```
cefclient.exe --multi-threaded-message-loop --no-sandbox
```

**Comment by amaitland** [comment] 2022-03-28 20:51
Please confirm you've tested the workaround listed at https://github.com/cefsharp/CefSharp/issues/1691#issuecomment-323603277

**Comment by simonbuehler** [comment] 2023-09-22 06:47
same issue with 101 in a kiosk winforms app.
i also tried the usb workaround but didn't help, any ideas?
