### ISSUE TITLE
Crashs on popup window when closed

### ISSUE THREAD

**Issue by okatip1** [cefsharp/CefSharp#1528] opened 2016-01-04 19:23 UTC
#### Issue Summary
What is the expected output? What do you see instead?

#### Steps to Reproduce
1. This is the first step

This is a bug because...
Code sample if relevant
Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?

#### Technical details
* CefSharp Version: nuget - master - latest commit:  INSERT COMMIT REF
* Operating System: 
* x86/x64: 
* WinForms/WPF/OffScreen: 

--
When I closed a popup window, I took that error many times. Both wpf and winforms..

![ekran alintisi](https://cloud.githubusercontent.com/assets/16343394/12098191/38759652-b329-11e5-9eb7-220e2df6a4d6.JPG)

**Comment by bilginkilic** [comment] 2016-01-04 19:33
I had the same error.

**Comment by okatip1** [comment] 2016-01-04 19:38
we stuck in this error, please help..

**Comment by amaitland** [comment] 2016-01-04 20:28
Fill out the bug report and post a **new** comment when your done.

**Comment by bilginkilic** [comment] 2016-01-04 20:56
@amaitland how to fix this error?

**Comment by amaitland** [comment] 2016-01-04 21:02
> @amaitland how to fix this error?

Fill out a bug report. What is your stack trace? Where's the sample code that reproduces the problem? Which version are you using?

If I provided you with a screenshot of an exception, and asked you to solve a problem, how useful do you think that would be?

**Comment by jankurianski** [comment] 2016-01-04 22:19
> we stuck in this error, please help..

At the moment we cannot help you.  You need to write instructions on how to reproduce this problem.  If your English is not good, record a video of the entire process instead - start from opening visual studio and end with the crash.  I have used `CamStudio` to record videos before and it works well.

**Comment by amaitland** [comment] 2016-01-04 22:36
> I have used CamStudio to record videos before and it works well.

Starting with `Windows 7` you can use `Problem Steps Recorder` (Handy that it comes with `Windows`).

http://blogs.msdn.com/b/patricka/archive/2010/01/04/using-the-secret-windows-7-problem-step-recorder-to-create-step-by-step-screenshot-documents.aspx

**Comment by amaitland** [comment] 2016-01-08 02:25
@okatip1 Are you still seeing a problem? If you are can you please edit the original issue and provide the required information. Thanks.

**Comment by amaitland** [comment] 2016-01-15 22:54
@okatip1 @bilginkilic Unless someone provides more information I'm going to close this issue.

**Comment by amaitland** [comment] 2016-01-21 21:20
Closing due to lack of feedback. 

We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask any follow up questions there.

**Closed by amaitland** 2016-01-21 21:20 UTC
Labels: more-details-needed-from-op

**Comment by amaitland** [comment] 2016-02-26 08:54
Duplicate of #1594
