### ISSUE TITLE
Browser.ExecuteScriptAsync can not execute script after Browser.Load is called

### ISSUE THREAD

**Issue by haoap** [cefsharp/CefSharp#3115] opened 2020-05-01 11:52 UTC
- **What version of the product are you using?**
Nuget 79.1.360
- **What architecture x86 or x64?**
 x64
- **On what operating system?**
 Win10
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms
- **What steps will reproduce the problem?**
    1. Create Browser with https://stackoverflow.com/,  Browser.ExecuteScriptAsync execute script successfully.
    2. Use _Browser.Load_("github.com") to load another url. Browser. ExecuteScriptAsync cause V8Context exception. Both url contains JavaScript.
    3. Use _Browser.Reload()_ to reload github.com. Browser.ExecuteScriptAsync can execute script then.

- **What is the expected output? What do you see instead?**
Browser.ExecuteScriptAsync can execute script when frame has JavaScript.

- **Please provide any additional information below.**
 1. I use RenderProcessMessageHandler of Browser to check the ContextCreated event, seems the event was not ok after Broswer.Load was called.
2. _I tested with Browser.GetMainFrame().ExecuteJavaScriptAsync, seems work after Browser.Load is called._

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
Yes, Exception was throw. System.Exception: Unable to execute javascript at this time, scripts can only be executed within a V8Context.

**Comment by amaitland** [comment] 2020-05-01 12:09
Closing as duplicate of #3021

**Closed by amaitland** 2020-05-01 12:09 UTC
