### ISSUE TITLE
Blurry effect

### ISSUE THREAD

**Issue by dongsiDaengsi** [cefsharp/CefSharp#4636] opened 2023-11-29 07:57 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

119.4.30

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET Framework 4.7.2

### Implementation

WPF

### Reproduction Steps

1. Open the attached index.html with Version equal or above 97.1.11 -> you can see the blurry effect
2. Open the attached index.html with Version equal or lower than 96.0.180 -> you can see no blurry effect

### Expected behavior

No blurry effect in higher and current version.

### Actual behavior

When using the CefSharp, I noticed an error in the display. Various elements (see supplied HTML page) are displayed blurred. However, this is only the case from version 97.1.11. This display error is not present in older versions. I am using a WPF project with .NET Framework 4.7.2

**Version equal or lower than 96.0.180**
![not-blurry](https://github.com/cefsharp/CefSharp/assets/62557519/f2761045-8258-4b50-9f2c-8082c2b4b014)

**Version equal or lower than 97.1.11**
![blurry](https://github.com/cefsharp/CefSharp/assets/62557519/636cf737-38f7-44c6-a4a6-e6119c506a49)

**Example file: index.html - Please convert it to .html and remove .txt**
[index.html.txt](https://github.com/cefsharp/CefSharp/files/13497642/index.html.txt)

### Regression?

The blurred effect is not present in version 96.0.180. The effect is available from version 97.1.11. However, the effect is NOT present in Chrome and Chromiomembedded. The effect does only appear in CefSharp.

### Does this problem also occur in the CEF Sample Application

No

**Comment by amaitland** [comment] 2023-12-01 20:21
> ### Does this problem also occur in the CEF Sample Application
> No

What command line args did you test with? Did you test with the `WPF` ones?

This sounds exactly like https://github.com/cefsharp/CefSharp/discussions/4565

https://github.com/cefsharp/CefSharp/discussions/4565#discussioncomment-6755159

**Comment by amaitland** [comment] 2023-12-04 21:48
> Additional context

> Yes, the error can be reproduced with the cefclient or cefsimple sample application. However, this means that the blurred display is present.

Looks like you already raised https://github.com/chromiumembedded/cef/issues/3612

> However, the effect is NOT present in Chrome and Chromiomembedded.

https://github.com/chromiumembedded/cef/issues/3612 states that the problem does reproduce in `CEF`. 

You need to provide the `WPF` command line args so the `CEF` maintainer knows how to reproduce the problem.

It's also possible the specific GPU you are using is part of the equitation. 

Closing as `upstream`.

**Closed by amaitland** 2023-12-04 21:48 UTC

**Comment by dongsiDaengsi** [comment] 2024-01-29 07:05
Good morning.
Would there be another opportunity to deal with my problem? 
Thank you very much.

**Comment by amaitland** [comment] 2024-01-30 09:31
See https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#roundingbitmapscaling

You can also try https://learn.microsoft.com/en-us/dotnet/api/system.windows.uielement.snapstodevicepixels?view=windowsdesktop-8.0

If your still having a problem then you'll need to debug the rendering implementation

- https://github.com/cefsharp/CefSharp/blob/cefsharp/120/CefSharp.Wpf/Rendering/WritableBitmapRenderHandler.cs#L54
- https://github.com/cefsharp/CefSharp/blob/cefsharp/120/CefSharp.Wpf/Themes/Generic.xaml

You can create bitmaps for each individual frame and write them to disk for diagnostic purposes, you can adapt code from https://github.com/cefsharp/CefSharp/blob/cefsharp/120/CefSharp.OffScreen/BitmapBuffer.cs and hook into the `WPF` render handler.
