### ISSUE TITLE
Screen is not rendered properly and have a glitch while rendering

### ISSUE THREAD

**Issue by soundararajans** [cefsharp/CefSharp#3642] opened 2021-06-25 07:26 UTC
What version of the product are you using?
- Nuget Version from VS2019: 86.0.24

What architecture x86 or x64?
Any CPU, Tested with x64 and x86 standalone 

On what operating system?
Windows 10 Home Single Language 20H2

Additional Configuration Details,
Huawei D15 with processor 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 2.42 GHz 
Ram 16GB
Windows Feature Experience Pack 120.2212.2020.0
Screen Resolution: 1920*1080 
Intel Iris video adapter

Are you using WinForms, WPF or OffScreen?
WPF

What steps will reproduce the problem?
Browser page is not rendered properly with above-mentioned configuration properly and have a lot glitches while rendering. Please refer the simple reproducible sample.
[CefSharpTestApp.zip](https://github.com/cefsharp/CefSharp/files/6714256/CefSharpTestApp.zip)

Also refer the video for this issue snap.

Before Resize,

![image](https://user-images.githubusercontent.com/64411747/123386439-50b80980-d5b4-11eb-9e95-a21d1b7a4877.png)

After Resize,

![image](https://user-images.githubusercontent.com/64411747/123386355-33833b00-d5b4-11eb-9cb1-cb309c466c3f.png)

Expected Output
App is working fine with other environments except above configuration.
![image](https://user-images.githubusercontent.com/64411747/123386659-865cf280-d5b4-11eb-8095-6922df439583.png)

cefTest

The problem still persists even using MinimalExample.

What is the expected output? What do you see instead?

Page should render properly without any glitches.

There is no debug.log
Does this problem also occur in the CEF Sample Application
No

**Comment by amaitland** [comment] 2021-06-25 07:32
Closing as duplicate of #3280

**Closed by amaitland** 2021-06-25 07:32 UTC
