### ISSUE TITLE
WinForms touch screen does not work with Windows 7

### ISSUE THREAD

**Issue by Developerius** [cefsharp/CefSharp#2272] opened 2018-02-09 09:07 UTC
I use WinForms version in WPF application.
Touches works in WPF(outside ChromiumWebBrowser).
Inside ChromiumWebBrowser are ignored(Windows draw touch circle but page ignore it).
CefSharp 57 - touch not work
CefSharp 63 - touch not work
Chrome 57 - touch work
Chrome 64 - touch work

Same application and same hardware and same web page with Windows 8/10 work.

**Comment by amaitland** [comment] 2018-02-09 10:44
Does the problem reproduce with the WinForms MinimalExample?

https://github.com/cefsharp/CefSharp.MinimalExample

**Comment by amaitland** [comment] 2018-02-09 10:45
Also test with the CEF sample application see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef

**Comment by Developerius** [comment] 2018-02-12 09:25
WinForms MinimalExample - touch work
CEF sample application - tuch work

In clear WPF application with CefSharp.WinForms - touch not work

Reproduce([Wpf.CefSharp.WinFormsMinimal.zip](https://github.com/cefsharp/CefSharp/files/1715824/Wpf.CefSharp.WinFormsMinimal.zip)):
- create new WPF Project
- install CefSharp.WinForms packages
- add references to WindowsFormsIntegration, System.Windows.Forms
- copy Cef initialization code(from CefSharp.MinimalExample/Program.cs: Main(), to App.cs: OnStartUp())
- copy ChromiumWebBrowser creation code(from CefSharp.MinimalExample/BrowserForm.cs: BrowserForm(), to MainWindow.cs: MainWindow())

On Windows 7 Embedded (sp1, .net 4.5.2) web page ignored touch.
Windows 8/10 all fine.

**Comment by amaitland** [comment] 2018-02-12 11:55
For future reference no binaries, this includes zip files, thank you. 

I personally don't have time to look into this any further, it's probably worth digging through old issues to see if anyone else has provided a solution already. Best of luck.

**Comment by amaitland** [comment] 2018-03-06 01:11
Closing as duplicate of #1833

**Closed by amaitland** 2018-03-06 01:11 UTC
