### ISSUE TITLE
WritableBitmapInfo - MILERR_WIN32ERROR Exception

### ISSUE THREAD

**Issue by Arunkumar-Murugesan** [cefsharp/CefSharp#2035] opened 2017-05-02 10:05 UTC
Hi Team,

As it is the same scenario, We have faced this issue often.

**Issue Details**

```
Application Error - MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003)   at System.Windows.Media.Imaging.WriteableBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette)
   at CefSharp.Wpf.Rendering.WritableBitmapInfo.CreateBitmap()
   at CefSharp.Wpf.ChromiumWebBrowser.<>c__DisplayClass13.<CefSharp.Internals.IRenderWebBrowser.InvokeRenderAsync>b__12()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

We have already faced this issue in the task https://github.com/cefsharp/CefSharp/issues/1759.

From that, the team said to use the version 51.0.0 instead of using 45.0.0.0. But we just need to know the reason for this issue. In which case this issue will be reproduced? Can't we resolve it by this version itself?

Thanks in advance,

Regards,
**Arunkumar Murugesan**

**Comment by amaitland** [comment] 2017-05-04 03:15
Quick google suggests there is a `bug` the `.Net` framework. See http://stackoverflow.com/questions/32297637/system-windows-media-imaging-writeablebitmap-leaking-memory

You'll have to do your own research, submit a `PR` if you can devise a workable solution.

It's interesting that your the only person to report this problem, so you must be doing something different.

Before posting again please read https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment] 2017-05-06 07:22
https://github.com/Microsoft/dotnet/blob/master/releases/net46/dotnet46-changes.md

Microsoft have fixed a memory leak in writable bitmap, if your not already try .Net 4.6

You can also try removing dirtyrect support as suggested in http://stackoverflow.com/questions/24960650/workaround-for-memory-leak-when-using-writeablebitmap-adddirtyrect

**Comment by amaitland** [comment] 2017-05-09 00:39
This issue will be closed in 14 days if there is no further feedback.

**Comment by Arunkumar-Murugesan** [comment] 2017-05-09 06:40
@amaitland : Thank you for update.  But we haven't used the writable bitmap in our codes.

**Comment by amaitland** [comment] 2017-05-09 06:50
> Application Error - MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003)   at System.Windows.Media.Imaging.WriteableBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat, BitmapPalette palette)

@Arunkumar-Murugesan It's `WriteableBitmap` that is throwing the exception. It's used to provide `High DPI` support for the `OSR` rendering that the `WPF` version uses.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#offscreen-rendering-osr for background.

How do you reproduce the problem? Are you using `.Net 4.6`?

**Comment by Arunkumar-Murugesan** [comment] 2017-05-09 08:59
@amaitland : Yes. The exception throwing for WriteableBitmap only. But it is not occurred all the time and it comes in rare case only. We are using,

Product  - CI Nuget
Operating System - Win 10
Machine Resolution - 1920 * 1080
Cef Sharp Version - 45.0.0
.Net Framework Version - 4.5
Application - WPF

The problem is, we couldn't get this problem in all the time. that's why we are requesting to you for knowing the reason.

Please let me know the concerns if any.

Regards,
Arunkumar Murugesan

**Comment by amaitland** [comment] 2017-05-09 09:02
As I've said looks like a memory leak in . Net. Try upgrading to .Net 4.6

Also version 45 is old and unsupported, no bugs will be fixed in old versions.

**Comment by Arunkumar-Murugesan** [comment] 2017-05-09 09:15
@amaitland : Thanks for the update.

**Comment by amaitland** [comment] 2017-05-15 20:25
> You can also try removing dirtyrect support as suggested in http://stackoverflow.com/questions/24960650/workaround-for-memory-leak-when-using-writeablebitmap-adddirtyrect

If upgrading to `.Net 4.6` doesn't solve the problem then based on the advice suggested in the above link I'd suggest anyone facing this problem simply subclass `WpfBitmapInfo` and override `Invalidate`, don't invalidate the dirty rect, invalidate the whole bitmap. Implement your own `IBitmapFactory` and return your custom `WpfBitmapInfo` implementation.

The other suggestion is to create a `WriteableBitmap` large enough to cover the whole desktop, I guess this might be possible and only have the downside of initially allocating potentially a large block of memory (which maybe more efficient in some scenarios), for a multi monitor setup you would have to create a `Bitmap` that covered the suited the largest desktop resolution.

Closing this as `wontfix` as it appears to be a bug in the `.Net` framework and not directly related to `CefSharp`. If someone can provide a reliable method to reproduce this issue then possibly it can be reopened at a later point.

**Comment by xmedeko** [comment] 2017-12-22 12:30
@amaitland we've got this exception issue rarely from our users, CefSharp 57, these users have probably .NET 4.5.2 (our app has the minimum requirements .NET 4.5.2).
The CefSharp has the minimum requirements .NET 4.5.2 in the `README.md` and the problem is clearly in the `CefSharp.Wpf.Rendering.WritableBitmapInfo` class. If you do not plan to rise the minimum .NET supported version, then I think this issue ought to be reopened.

**Comment by mitchcapper** [comment] 2017-12-22 15:37
@xmedeko I periodically ran into this issue when actually running out of addressable ram for the application (with multiple instances running at once).  If you are using x86 make sure you are flagging the app for high memory to allow addressing more than 2GB of ram with a postbuild step that flags the exe as largeaddressaware: https://msdn.microsoft.com/en-us/library/wz223b1z.aspx  if you are running x64 or process explorer doesn't show you near 2G it could be due to something else.

**Comment by xmedeko** [comment] 2017-12-22 18:40
We just allow single instance and normally the 0.5, max 1GB should be enough for the app. Yeah, it's possible the memory leak is somewhere else, do the app memory grows beyond 2GB. But one source of the leak is the `WritableBitmapInfo`, too.
I understand if the fix is too difficult or hacky, then just the doc (README.md) should mention this issue when using officially supported .NET 4.5.2.

**Comment by amaitland** [comment] 2018-01-02 03:25
@xmedeko Did you attempt any of the solutions I posted above?

- Install `.Net 4.6` on the machine experiencing the problem (just the `redist`, no need to compile your app with `.Net 4.6`)
- Implement your own `WritableBitmapInfo` that only calls `Invalidate` without the dirty rect param

> problem is clearly in the CefSharp.Wpf.Rendering.WritableBitmapInfo class.

The problem isn't directly in the `WritableBitmapInfo` implementation, it's in the `.Net` framework it's self, so whilst calling `Invalidate` without the dirty rect params is an option, it's not really a great one for those who aren't seeing this problem, their performance is affected for no reason at all.

The `minimum` requirement is `.Net 4.5.2`, and that's only for compilation, you can install newer versions of the runtime like `4.6.` or `4.7 and benefit from the bug fixes they provide.

As @mitchcapper suggests if you haven't already then make sure if your using a `32bit` app then it's marked as `largeaddressaware`, that's very important to accessing more than `2gb` of memory.

> I understand if the fix is too difficult or hacky, then just the doc (README.md) should mention this issue when using officially supported .NET 4.5.2.

By all means submit your suggestions as a `PR`, the documentation can always be improved.

**Comment by amaitland** [comment] 2018-01-02 03:27
> The other suggestion is to create a WriteableBitmap large enough to cover the whole desktop, I guess this might be possible and only have the downside of initially allocating potentially a large block of memory (which maybe more efficient in some scenarios), for a multi monitor setup you would have to create a Bitmap that covered the suited the largest desktop resolution.

@xmedeko This might also be a viable option, as I cannot reproduce the problem it's really up to users like yourself to investigate further.

**Comment by xmedeko** [comment] 2018-01-04 11:56
We have just anonymous error logs and do not know OS details of our users unless they contact us. Just recently, one user has contacted us with .NET 4.7 and I have found another WPF memory leak (`StaticResource` not frozen) in our app. So, as @mitchcapper said, this `MILERR_WIN32ERROR` may be triggered by another memory problem in an app.

However, since we have a few `MILERR_WIN32ERROR` error logs from an older version of our app, so there is still a possibility of `WriteableBitmap` causing problems with .NET 4.5.2. I will try to test it later.

Also, we recommend .NET 4.6.1 for our app, while allow minimum 4.5.2 and I guess the very most of our users have 4.6.1 or higher. So, I am not much about complicated fixes which may cause performance problems. For me is enough to know about this WPF bug and if someone contact us with `MILERR_WIN32ERROR` and .NET 4.5.2, then I would recommend him to upgrade .NET first. So, I have submitted a PR to README.md about this problem.

**Comment by amaitland** [comment] 2018-01-08 09:01
If it's confirmed that upgrading to a newer version of .Net resolves the problem we can add a check in code to use the no param invalidate method on older versions

**Comment by amaitland** [comment] 2018-02-06 01:09
With commit https://github.com/cefsharp/CefSharp/commit/e7002a78740e2abd3b5213603b4c42a93c99b030#diff-14031cd523e9232a5c99fca04b232e90R49 I've the option to create a new `WritableBitmapFactory` that invalidates the whole bitmap.

I've added a note to the `General Usage Guide`, see https://github.com/cefsharp/CefSharp/wiki/General-Usage/_compare/3afd60b984b4538cb2a6f44adcdba2f88f739abb...7754691ed020a7e864cf9337d99064b8b3c822e3

Closing this now, if someone comes up with a meaningful code improvement then by all means submit a `PR`.

**Closed by amaitland** 2018-02-06 01:09 UTC
Labels: wontfix, wpf

**Comment by koralcem** [comment] 2019-10-29 22:33
Not claiming this issue should be reopened; I just had a question.

@amaitland I've read the note added to the General Usage Guide for this issue. The part I can't get my head around is: is it sufficient for the client machine to be running .NET 4.6+ for them to avoid this problem? Or does our app also need to be built for .NET 4.6+ to actually get the updated behavior that avoids this problem?

Because we currently have an app that has this in its `app.config`:
```
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/></startup>
```

We've had a customer who hit this issue, yet they had updated to the latest version of Windows 10, and had gotten the .NET Framework version 4.8 in the process. Should we have expected that they not have this problem, since they're running with .NET 4.6+? Or do we need to update our build and put out a new version first?

**Comment by amaitland** [comment] 2019-11-19 02:00
Having a `.Net` version `>=4.6` should resolve the memory leak in [WriteableBitmap.WritePixels](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.writeablebitmap.writepixels?view=netframework-4.8#System_Windows_Media_Imaging_WriteableBitmap_WritePixels_System_Windows_Int32Rect_System_IntPtr_System_Int32_System_Int32_System_Int32_System_Int32_)

It is still possible to avoid using this method and update the whole bitmap. Specify `invalidateDirtyRect : false` when creating an instance of [WritableBitmapRenderHandler](http://cefsharp.github.io/api/75.1.x/html/M_CefSharp_Wpf_Rendering_WritableBitmapRenderHandler__ctor.htm) then assign to the [RenderHandler](http://cefsharp.github.io/api/75.1.x/html/P_CefSharp_Wpf_ChromiumWebBrowser_RenderHandler.htm) property.

---

As outlined above, it's not necessarily `CefSharp` that's leaking memory, If at anypoint `CefSharp` attempts to create a new `WriteableBitmap` and the process doesn't have enough memory the exception will be thrown. The browser only creates a new `WriteableBitmap` if one doesn't exist already or the browse size changes.

I'd suggest anyone experiencing this issue profile their application, if you find a leak in `CefSharp` then by all means create a new issue.

There are lots of common memory leaks in `WPF` that people should be aware of.
- https://blog.jetbrains.com/dotnet/2014/09/04/fighting-common-wpf-memory-leaks-with-dotmemory/
- https://www.red-gate.com/products/dotnet-development/ants-memory-profiler/learning-memory-management/WPF-silverlight-pitfalls
- Bitmaps not being frozen
