### ISSUE TITLE
Drag and Drop inside Canvas fails in WPF, works fine in WinForms

### ISSUE THREAD

**Issue by A9T9** [cefsharp/CefSharp#2467] opened 2018-07-23 08:40 UTC
I tested with the latest version V65.0.3325, "Minimal Example", Master branch on x64, Win10

The issue is very easy to recreate:

- Go to https://konvajs.github.io/docs/drag_and_drop/Drag_and_Drop.html

- Try to drag the rectangle around. This works just fine with the Winform version, but with WPF, the rectangle does not move at all:

![testcase1](https://user-images.githubusercontent.com/9657938/43066369-c387c454-8e64-11e8-9d9b-25c203c9156a.png)

**Comment by amaitland** [comment] 2018-07-23 09:06
Closing as duplicate of #1330

The `WPF` drag implementation is only partially complete.

**Closed by amaitland** 2018-07-23 09:06 UTC

**Comment by A9T9** [comment] 2018-07-23 09:48
Thanks for the quick responses. Just for my understanding: Why would this be an upstream problem if it works in WinForms?

**Comment by A9T9** [comment] 2018-07-23 09:52
To answer my own question: WPF uses off-screen rendering...

**Comment by amaitland** [comment] 2018-07-23 09:58
You must set `AllowDrop="True"` in `xaml`  (or in code behind) to enable `Drag and Drop` in the `WPF` implementation. Dragging with the mouse works partially, which is the same behaviour I'm seeing in `cefclient`.

**Comment by A9T9** [comment] 2018-07-23 10:03
Yes. From my tests so far, dragging something from outside a canvas to inside the canvas works, but dragging _within_ a canvas does not work.

**Comment by A9T9** [comment] 2018-09-25 21:13
I should add: The issue [has been reported upstream](https://bitbucket.org/chromiumembedded/cef/issues/2479/drag-drop-inside-canvas-fails-with-off) (already in July).
