### ISSUE TITLE
Blank page if browser control is not visible at startup

### ISSUE THREAD

**Issue by NeomMob** [cefsharp/CefSharp#2676] opened 2019-03-06 15:17 UTC
- **What version of the product are you using?**
v71 from Nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
 Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
- Use demo app (based on minimal example) from https://github.com/NeomMob/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.Wpf 
- Click multiple time the toggle browser visibility button. Soon or later, the browser start to freeze and has incorrect layout.
- **What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/326762/54268919-9899fa80-457c-11e9-946d-d4a5b334f4bc.png)

- **Please provide any additional information below.**
No crash, just not getting the expected behavior.
debug.log:
```
[0308/064211.851:ERROR:broker_win.cc(137)] Error sending sync broker message: The pipe is being closed. (0xE8)
[0308/064533.989:ERROR:broker_win.cc(137)] Error sending sync broker message: The pipe is being closed. (0xE8)
[0308/070902.294:ERROR:broker_win.cc(137)] Error sending sync broker message: The pipe is being closed. (0xE8)
[0308/070923.367:ERROR:broker_win.cc(137)] Error sending sync broker message: The pipe is being closed. (0xE8)
```

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
Using mahapps.metro

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled --enable-gpu
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)
    - Please include the version you tested with e.g. `cef_binary_3.3029.1611.g44e39a8_windows64_client.tar.bz2`. It's important to you test with the same version that `CefSharp` is based on. Check the release notes to determine the version (https://github.com/cefsharp/CefSharp/releases) or load `chrome://version` in the browser.

---

# Environment
- CefSharp Version 71
- WPF
- Framework 4.6.2
- HiDPI support activated through `<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True/PM</dpiAware>`

# Description
I am developing an application where the browser control is at startup inside a grid column having a 0 width.
It results to a blank browser when I resize the containing grid column.

It seems to really look like #1412 but I did not find a way to fix the issue.

**Comment by amaitland** [comment] 2019-03-06 19:44
Please use the template provided at https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

Will need an example that reproduces your problem.

**Comment by NeomMob** [comment] 2019-03-13 11:04
I updated the issue

**Comment by amaitland** [comment] 2019-03-14 02:36
> * Use demo app (based on minimal example) from https://github.com/NeomMob/CefSharp.MinimalExample/tree/master/CefSharp.MinimalExample.Wpf

Thanks 👍 

> * Click multiple time the toggle browser visibility button. Soon or later, the browser start to freeze and has incorrect layout.

This differs greatly from the issue `Title`. `Title` suggests there is only a problem at `Startup`.

**Comment by NeomMob** [comment] 2019-03-19 06:19
@amaitland actuallyt it really look like https://github.com/cefsharp/CefSharp/issues/1571

**Comment by amaitland** [comment] 2019-03-19 08:24
In that case closing as duplicate of #2547 

There are a few resize issues that will be fixed `upstream` in `73`

**Closed by amaitland** 2019-03-19 08:24 UTC
Labels: wpf
