### ISSUE TITLE
XMLHttpRequest empty responseText

### ISSUE THREAD

**Issue by dhoerner2412** [cefsharp/CefSharp#2835] opened 2019-07-12 08:09 UTC
- **What version of the product are you using?**
Nuget version 73.1.130

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Win 10

- **What steps will reproduce the problem?**
Sending a POST request to a Cross-Origin URI with empty body data with a XMLHttpRequest in javascript

- **What is the expected output? What do you see instead?**
I can see in development-console that the request successfully returned (Status Code 200, Response Header Content-Length > 0) but the Response-Tab is empty and also the property "responseText" of the XMLHttpRequest object is a empty string

- **Please provide any additional information below.**
The Webpage works as expected with Cefsharp version 67.0.0

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

No, with the sample cefclient.exe, all works as expected

**Comment by amaitland** [comment] 2019-07-12 08:23
It's important to note that `CefSharp` is just a wrapper around the `Chromium Embedded Framework (CEF)`. Closing this as `upstream` and as changes need to be made in `CEF`. 

The `CEF` project has it's own issue tracker located at https://bitbucket.org/chromiumembedded/cef it is recommended you ask on https://magpcss.org/ceforum/index.php before opening an issue on the CEF issue tracker. The behavior you are seeing may be the expected default.

Before opening a new issue you should:

- Search open/closed issues to determine if the problem you are seeing has already been reported
- Test with a newer version if available, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for details on testing with the `cefclient` reference application.

If you do find an existing issue that matches this one or create a new one then post a link here for others to follow.

**Comment by amaitland** [comment] 2019-07-12 10:07
Looks like you opened https://bitbucket.org/chromiumembedded/cef/issues/2717/xmlhttprequest-empty-responsetext

**Comment by dhoerner2412** [comment] 2019-07-15 13:45
@amaitland When will there a new cefsharp release (Nuget) with cef 3770 (chromium version 75), because in this cef version this error is fixed?

**Comment by dhoerner2412** [comment] 2019-07-15 15:55
I was able to test this issue with the cefclient.exe downloaded from http://opensource.spotify.com/cefbuilds/index.html

I was not able to reproduce the issue with the cefclient.exe in version 67, 69, 73 and 74. All works as expected. It seems that this issue only occurs in combination with the cefsharp framework, so please reopen this issue!

**Comment by amaitland** [comment] 2019-07-16 07:40
I will reopen this for now though I'm very skeptical that this is an issue with CefSharp. More likely a settings that's different. 

An example that actually reproduces the problem is required.  Please fork the minimum example,  details are in the bug report template see https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#bug-report

Having read your follow up comments on bitbucket I'd suggest you look into http://cefsharp.github.io/api/73.1.x/html/M_CefSharp_Cef_AddCrossOriginWhitelistEntry.htm instead of disabling websecurity. Best to avoid disabling web security.

**Comment by dhoerner2412** [comment] 2019-07-17 11:16
I have pushed the minimal example to reproduce to https://github.com/dhoerner2412/CefSharp.MinimalExample.git

please read the Readme.txt in the repositoty for further details

**Comment by amaitland** [comment] 2019-07-18 12:19
A quick check and if I disable web security using the below command line arg then it works as expected. Which is the equivalent of what you tested with. Testing with commit https://github.com/cefsharp/CefSharp/commit/6233925efd926e163c1f0fb9ea3c20c57b05cfc4

```
settings.CefCommandLineArgs.Add("disable-web-security", "1");
```

Looking at the `BrowserSettings` source and I don't see any obvious errors, debugging it appears the value is passed correctly. Seems likely this is a bug in `CEF`.

---

Using https://jsfiddle.net/t29fp47m/ for simplicity of testing.

**Comment by amaitland** [comment] 2019-08-02 00:36
Closing as this appears to be a bug in `CEF`. I'd suggest modifying `cefclient` and disabling `web security` via `browser settings`, once you've confirmed that the issue reproduces there it should be possible to get the `upstream` issue reopened.

**Closed by amaitland** 2019-08-02 00:36 UTC
Labels: upstream
