### ISSUE TITLE
Dispose Browser (or WCF in fact) in Event Invoked by KeyboardHandle with js object registered cause process hanging up

### ISSUE THREAD

**Issue by Yangff** [cefsharp/CefSharp#1879] opened 2016-12-03 10:58 UTC
- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. Nuget v53

- **What architecture x86 or x64?**
x64

- **On what operating system?**
    - Win7, Win 8, Win10, etc?
Win18

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
In WinForms Example, add a shortcut (e.g. Ctrl+W) to Close Tab. Compile&Run, **_focus on browser_ (important!!)**, trigger Ctrl+W, and it Processes will not exit. Pause it and watch stack, we can found it stucked in Closing WCF. 

- **What is the expected output? What do you see instead?**
It should terminal all processes and exit, but turns out not. 

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

And, currently, I've a workaround on it, use the following code replace `CloseTabToolStripMenuItemClick`

```cs
        private void CloseTabToolStripMenuItemClick(object sender, EventArgs e)
        {
            Task.Factory.StartNew(() => this.BeginInvoke((MethodInvoker)delegate
            {
                if (browserTabControl.Controls.Count == 1)
                {
                    ExitApplication();
                    return;
                }

                var currentIndex = browserTabControl.SelectedIndex;

                var tabPage = browserTabControl.Controls[currentIndex];

                var control = GetCurrentTabControl();

                if (control != null)
                {
                    control.Dispose();
                }

                browserTabControl.Controls.Remove(tabPage);

                tabPage.Dispose();

                browserTabControl.SelectedIndex = currentIndex - 1;
            }));
        }

```

Plus, I tend to add this trick `deal with it in next tick` in `KeyboardHandler` and found these comments on `KeyboardHandler`.

```cs
            // We can't use BeginInvoke here, because we need the results for the return value
            // and isKeyboardShortcut. In theory this shouldn't deadlock, because
            // atm this is the only synchronous operation between the two threads.
```

 I assume here do cause a deadlock, maybe some other components is waiting this function to return before it can be disposed. So maybe it have something to do with cef3, but it's mainly about C#'s event processing, I guess.

**Comment by amaitland** [comment] 2016-12-20 22:31
Your threading code is questionable in the example provided. What happens if you just add the shortcut?

Keyboard handler is just an example, modify it as you like. Submit a PR with improvements if you like. You could easily handle special cases in your own custom keyboard handler and execute close in an asynchronous fashion.

**Comment by Yangff** [comment] 2016-12-21 04:57
@amaitland I'm adding a shortcut to close tab (like `Ctrl+W` in chrome). I'm trying to improve the Keyboard handler itself, but found that is almost impossible.

If I remove `Task.Factory.StartNew(() => this.BeginInvoke((MethodInvoker)delegate`, the program will lose respond and wait for `control.Dispose()` to return.

I guess, what caused these is, assume there are two threads, tCef and tWinform.

In keyboard handler, it's running on tCef or invoked some other thread by tCef, anyway, tCef is waiting for the handler to return.

And, I invoked to tWinform to Dispose something. When disposing the Browser, it need to dispose some object host by tCef (WCF or something, anyway, it need to invoke to thread tCef). 

But now, tCef is waiting tWinform to return and vice versa.

So, here is a dead lock.

Adding  `Task.Factory.StartNew(() => this.BeginInvoke((MethodInvoker)delegate`, the program will lose respond and wait for `control.Dispose()`  will make `CloseTabToolStripMenuItemClick` to return immidately. It is a Lasy Dispose.

**Comment by amaitland** [comment] 2016-12-21 05:45
@Yangff I understood your problem perfectly from the beginning. And I'm well aware of the threading considerations. I also know there are many other options available. I did a quick test with `master` before responding and it closed perfectly. Regardless you have other options to resolve the problem your seeing.

- Firstly change from using `MultiThreadedMessageLoop`, and integrate `CEF` into your main application by calling `Cef.DoMessageLoopWork()`. This resolves the disconnect and renders requiring a forwarding keyboard handler redundant. 

- Secondly you can also handle the `Ctrl+W` key combination as a special situation in `KeyBoardHandler`, simply close the form yourself in an `async` fashion, resolving any deadlock.

> In keyboard handler, it's running on tCef or invoked some other thread by tCef, anyway, tCef is waiting for the handler to return.

The `KeyboardHandler` events are running on the `CEF UI` thread (which in this case is not that same thread as your main application `UI` thread). See https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-threads for details on the different threads `CEF` uses.

> When disposing the Browser, it need to dispose some object host by tCef (WCF or something, anyway

There is a `10 second` timeout for the `WCF` connection to close, you can reduce that using `WcfTimeout` setting (make it `Zero` to terminate instantly). 

https://github.com/cefsharp/CefSharp/blob/1c0fb619327c014b92aece84ce1a659450b9c1fa/CefSharp/CefSharpSettings.cs#L35

In General I'd advise that people stop using `RegisterJsObject` and switch to `RegisterAsyncJsObject` which uses the native `IPC`. (The `FAQ` will be updated at some point in the new year).

> Adding Task.Factory.StartNew(() => this.BeginInvoke((MethodInvoker)delegate will make CloseTabToolStripMenuItemClick to return immidately. It is a Lasy Dispose.

The scenario  of `UI Thread -> Thread Pool -> UI Thread`, is crazieness.

**Comment by Yangff** [comment] 2016-12-21 06:01
@amaitland 

I noticed the 10s timeout, but I'm not sure why it doesn't killed that thread in my program, I'll upload a simplified version of my code which trigger this problem later. 

I've tried `RegisterAsyncJsObject` and it works out with some other problems.. But I'm not sure..

**Comment by amaitland** [comment] 2016-12-21 06:04
You should switch to using `Cef.DoMessageLoopWork` then, more info is in #1748

**Closed by amaitland** 2016-12-21 06:04 UTC

**Comment by amaitland** [comment] 2016-12-21 06:10
I've added https://github.com/cefsharp/CefSharp/commit/b3ae966a5424b43445a922eb123f17bcdf222343 and see no problems closing the form.

**Comment by Yangff** [comment] 2016-12-21 08:46
https://www.youtube.com/watch?v=YhVHb6a6480&feature=youtu.be

Yes, but another issue comes up... you can see, in the end of this clip, the whole program crashes, based on `master` branch. 

And it happens only when browser is focused.

**Comment by amaitland** [comment] 2016-12-21 09:19
`master` is far from being production ready. 

I am aware of the focus requirement, I read your issue and am unable to reproduce. Your screenshot is not helpful, you should check the stack trace.  I cannot help you further. Do some more research. Good luck!

**Comment by Yangff** [comment] 2016-12-21 10:23
OK.. anyway, thank you.

**Comment by amaitland** [comment] 2016-12-21 10:38
I'll reiterate you should switch to DoMessageLoopWork, you may need to run it 10 additional times before shutdown, search ceforum for details.

**Comment by amaitland** [comment] 2016-12-22 00:40
> I'll reiterate you should switch to DoMessageLoopWork, you may need to run it 10 additional times before shutdown, search ceforum for details.

The `WinForms` example already contains a working example, see  https://github.com/cefsharp/CefSharp/blob/cefsharp/53/CefSharp.WinForms.Example/Program.cs#L62
