### ISSUE TITLE
Context menu stays open untill user clicks one of the menu items (WPF)

### ISSUE THREAD

**Issue by KubilayKara** [cefsharp/CefSharp#2933] opened 2019-10-17 10:37 UTC
Hi,

When the user opens the context menu, it stays open until one of the menu items clicked.
However, clicking anywhere should close the menu.
Furthermore, the menu stays on top of every other window which is very disturbing for the user experience.

I'm using the latest available **CefSharp.Wpf** library which's version is 75.1.142.
You can reproduce this problem simply by putting a ChromiumWebBrowser to a WPF window and right-clicking on it.

I've found a similar issue that was closed due to a fix (https://github.com/cefsharp/CefSharp/issues/1795).
But it seems like the problem was reappeared.

**Comment by amaitland** [comment] 2019-10-22 02:01
Closing as duplicate of #1795

> I've found a similar issue that was closed due to a fix (#1795).

As per https://github.com/cefsharp/CefSharp/issues/1795#issuecomment-271454758 you need to use a custom menu or integrate `CEF` into your applications message loop.

The project source contains an example of a custom menu handler https://github.com/cefsharp/CefSharp/blob/cefsharp/75/CefSharp.Wpf.Example/Handlers/MenuHandler.cs

**Closed by amaitland** 2019-10-22 02:01 UTC
Labels: wpf
