### ISSUE TITLE
Drag/drop not working in WPF

### ISSUE THREAD

**Issue by EricFerro** [cefsharp/CefSharp#2350] opened 2018-04-10 09:08 UTC
Hi 

We are using ChromiumWebBrowser v63.0.3 inside a WPF application .

All standard pure drag/drop native javascript operation are not working.
For example we test the embbeded web browser with https://html5demos.com/drag/ and drag/drop does not work as it does in Chrome for example.

Any help is welcome;

Thanks

**Comment by amaitland** [comment] 2018-04-11 03:31
The drag/drop implementation in the WPF version is somewhat incomplete. Pull requests welcome.

**Comment by EricFerro** [comment] 2018-04-11 08:09
Hi
Just to be sure there is no misunderstanding here.

We are speaking here about pure javascript drag'n'drop inside the browser.
And nothing about drag'ndrop between WPF components and the javascript browser.

Agree ?

**Comment by amaitland** [comment] 2018-04-11 09:17
Follow the instructions at https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef and test with cefclient. It is possible that CEF does not support the scenario you are trying. 

The CefSharp drag/drop implementation was contributed by someone many years ago, I've never had a need for it myself. If cefclient works correctly then it's a problem with the CefSharp implementation, which is quite likely as there is at least one open issue related to drag and drop. 

If this is a feature you require then by all means get involved and improved the implementation.

**Comment by amaitland** [comment] 2018-04-11 10:53
For reference https://github.com/cefsharp/CefSharp/issues/1332

**Comment by amaitland** [comment] 2018-04-13 03:40
Quick test with `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled` and it behaves the same a the `WPF` version.

Making this as `upstream` as someone will have to investigate if it's possible.

**Comment by EricFerro** [comment] 2018-04-13 07:27
Hi
I do not have the same result on my side.

If you test the site https://html5demos.com/drag/.

On standard browser like chrome, dragging an element make the cursor to take element shape and you can drop it in the list.

With cefclient without argument line, all is working the same as in chrome, perfectly.

With cefclient (with argument line --off-screen-rendering-enabled) cursor DOES NOT change but drop works correctly

With WPF version cursor DOES NOT change and drop DOES NOT work.

Hope this helps

**Comment by amaitland** [comment] 2018-04-13 07:41
> With cefclient without argument line, all is working the same as in chrome, perfectly.

That's not relevant in the context of `WPF`. That's more like comparing the `WinForms` version.

> With WPF version cursor DOES NOT change and drop DOES NOT work.

Ok thanks for confirming. Someone will have to analyze the `cefclient` source code and submit a `PR`.

**Comment by amaitland** [comment] 2018-04-26 00:08
If you can reproduce the problem with `AllowDrop="True"` then this can be reopened. Closing as unable to reproduce.

**Closed by amaitland** 2018-04-26 00:08 UTC
Labels: up-for-grabs, wpf

**Comment by Bjaris** [comment] 2018-09-17 12:06
Hi, 
I have exactly  same issue. 
I checked &  have AllowDrop="True".
To reproduce : 

- use this Angular app https://github.com/ngrx/platform/tree/master/projects/example-app 
  and host it in an WPF view with a WPF CefSharrp webcontrol.

- Log in using test/test, go to browse books on the left and try to drag&drop some text on Find a Text  from an external source like notepad.

Result : It was not possible  (interdiction sign)
Expected : drag & drop is accepted

**Comment by amaitland** [comment] 2018-09-17 12:50
Dragging from an external source is a completely different issue. Your welcome to create a new issue, please make sure you use the bug report template see https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md#bug-report

The WPF drag/drop implementation is incomplete, Pull requests welcome.
