### ISSUE TITLE
EvaluateScriptAsync Frame Is No Longer Available

### ISSUE THREAD

**Issue by bjarteskogoy** [cefsharp/CefSharp#1354] opened 2015-10-22 07:58 UTC
I'm testing upgrading our software to use the master branch instead of 43.
In one particular browser (WPF), I always end up with this error when evaluating javascript: https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L184

Any hints on what might lead to this?

**Comment by amaitland** [comment] 2015-10-22 08:22
The `frameId` may be incorrectly passed into that message. Not really a lot of information to go on.

Can you provide a working example?

**Comment by LeMoussel** [comment] 2015-10-23 07:12
@amaitland : Some idea when fix this?

**Comment by bjarteskogoy** [comment] 2015-10-23 07:16
I'll try to see if I can reproduce it. It's kind of inside something, inside something in a corner of the application. The two relevant differences from other places where we do exactly the same thing, as I can see now, is that the browser is not visible when the script is executed and that it happens in the FrameLoadEnd event.

**Comment by amaitland** [comment] 2015-10-23 07:18
> Some idea when fix this?

I can now reproduce the issue using the `URL` provided by @LeMoussel 

https://github.com/amaitland/CefSharp/commit/bdd922f8a7f34863d0fc146fa45e5835e77b6432

So hopefully it's not too hard to fix.

**Comment by amaitland** [comment] 2015-10-26 01:20
So it appears at least in the context of http://crawlbin.com/ `CefAppUnmanagedWrapper::OnContextCreated` is never called. From what I can tell the page has no javascript, so I guess `CEF` never creates a `CefV8Context` as it doesn't believe one is required.

If I add a call to `ExecuteScriptAsync`, a context is created. e.g.

```c#
browser.ExecuteScriptAsync("1 + 1");
```

The correct approach to fix this is yet unclear.

**Comment by amaitland** [comment] 2015-10-26 01:43
First attempt at a solution can be found at https://github.com/amaitland/CefSharp/commit/7d300d1c97c38f5bafb3e72796301fea47e615f9

**Comment by amaitland** [comment] 2015-10-27 06:12
Change merged into `master` and `cefsharp/43`, will wait for a little bit more feedback before releasing the upcoming `43.0.1`.

@bjarteskogoy If you get a change would you mind trying the change out?

**Comment by bjarteskogoy** [comment] 2015-10-27 07:33
I never experienced this on 43. I've built from master and the problem is gone for our case at least. (y)

**Comment by amaitland** [comment] 2015-10-27 22:05
> I never experienced this on 43.

Restructure to the code since the `43.0.0` release to allow full support for frames and popups.

**Closed** 2015-10-28 12:04 UTC

**Comment by amaitland** [comment] 2015-10-29 22:20
`43.0.1` has been released to `Nuget.org` See https://github.com/cefsharp/CefSharp/releases/tag/v43.0.1 for more details

**Comment by Ashley-Upson** [comment] 2019-07-31 17:06
Hi there

I'm running into this exact issue 4 years down the line, using version 73.1.130

My case is essentially I've got a wrapper being started from a plugin for a program we need to use.
The wrapper consists of a CefSharp Window and some logic.

What I'm trying to achieve is to use ```this.browser.GetMainFrame().EvaluateScriptAsync()``` to inject some data into the local storage of the window, if it doesn't already have said data.

I'm just running into ```Frame -4 is no longer available, most likely the Frame has been Disposed or Removed.```

Please be aware I have pretty much 0 experience with C#, but have been a developer for years (so I have an idea of what I'm doing). I'm tasked with fixing a pre-existing app that can't really be updated or killed off

I'd appreciate any help you could possibly provide, and I can provide more snippets if need be
