### ISSUE TITLE
CefSharp v45 : EvaluateScriptAsync, Error "Frame is no longer available."

### ISSUE THREAD

**Issue by LeMoussel** [cefsharp/CefSharp#1364] opened 2015-10-23 06:04 UTC
I'm testing CefSharp V45.

Chromium: 45.0.2454.101
CEF: r3.2454.1342.g4e94f47
CefSharp: 45.0.0.0
OS: Windows 7

I got error '`Frame 1 is no longer available, most likely the Frame has been Disposed` when evaluating javascript (https://github.com/cefsharp/CefSharp/blob/master/CefSharp.BrowserSubprocess.Core/CefAppUnmanagedWrapper.cpp#L184)

```C#
BrowserSettings browserSettings = new BrowserSettings { };
using (ChromiumWebBrowser browser = new ChromiumWebBrowser("http://crawlbin.com/", browserSettings))
{
   await Task.Delay(1000);

   // OK, Get HTML source code
   string html = await browser.GetSourceAsync();

   // KO, Message error 'Frame 1 is no longer available, most likely the Frame has been Disposed.'
   JavascriptResponse task = await browser.EvaluateScriptAsync(@"(function() { return 1; })();");
   task.Wait();
   var response = task.Result;
   result = response.Success ? (response.Result ?? "null") : response.Message;
}
```

**Comment by amaitland** [comment] 2015-10-23 06:15
Duplicate of  #1354

**Closed by amaitland** 2015-10-23 06:15 UTC

**Comment by amaitland** [comment] 2015-10-23 06:40
Appreciate the detailed description :+1:

**Comment by amaitland** [comment] 2015-10-23 06:47
Just an `FYI` your code doesn't compile, you already awaited on `EvaluateScriptAsync`, so you cann't call `Wait` as their is never a `Task` returned.
