### ISSUE TITLE
WinForms - Enter/Arrow keys not working in new windows with MultiThreadedMessageLoop = false

### ISSUE THREAD

**Issue by Kandel-at-Tromb** [cefsharp/CefSharp#3289] opened 2020-11-21 17:48 UTC
- **What version of the product are you using?**
   Problem confirmed with both v73.1.130 and v85.3.130

- **What architecture x86 or x64?**
    Problem confirmed when compiling to both
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**
    - Problem can be reproduces with the Cefsharp.Winform.Example-project
        - Confirmed problem with commit fe48a51d1c27d1885a16ee812026e9e5e7a759c6
    - Change `const bool multiThreadedMessageLoop` in `CefSharp.WinForms.Example.Program` to `false`
    - Build and run
    - Go to any page with a `target="_blank"` link that will open in a new window and click on it
    - If the new window has any text-input field use that for testing else navigate to a page that has one
    - Enter any text-field and confirm that Enter, Arrow-keys, Tab or Esc does nor work

    - Example
        - Go to https://github.com/cefsharp/CefSharp/issues/new?assignees=&labels=&template=bug_report.md&title= and click on the link "Styling with Markdown is supported".
        - Click on "GitHub.com"-link on the markdown-page
        - Use the "Search or jump to…"-field for testing

- **What is the expected output? What do you see instead?**
    The keys: Enter, Up, Down, Left, Right, Tab and Esc does not work on webpages opened in new windows while running WinForms with `MultiThreadedMessageLoop = false`

- **Please provide any additional information below.**
    - Probably the same problem as this: https://github.com/cefsharp/CefSharp/issues/2899
    - When binding a KeyboardHandler the key-events reaches both `OnPreKeyEvent` and `OnKeyEvent`

**Comment by amaitland** [comment] 2020-11-22 23:50
Thanks for the detailed bug report 👍 This is at it's core the same issue as #2899 

`DevTools` is opened as a popup the same as other popups. (The default behaviour for popups is to open a new window).

It's not clear that this is something we can actually `fix` as it's `WinForms` that's processes the `Enter/Arrow` keys. The `ChromiumWebBrowser` classes overrides [Control.IsInputKey](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.isinputkey?view=netframework-4.5.2) to influence this behaviour.

https://github.com/cefsharp/CefSharp/blob/cefsharp/86/CefSharp.WinForms/ChromiumWebBrowser.cs#L810

Digging through the `.Net Reference Source` I have yet to find anything means of changing this behaviour.

I've edited the title of #2899 to make it a little more generic, I'm going to close this as duplicate of #2899 as it's fundamentally the same problem. By all means join in the discussion there 👍

**Closed by amaitland** 2020-11-22 23:50 UTC
