### ISSUE TITLE
WPF - blank screen when GPU acceleration disabled 

### ISSUE THREAD

**Issue by EMJagadeesh** [cefsharp/CefSharp#3337] opened 2020-12-31 11:53 UTC
Hi,

I've found a possible inconsistency in cef sharp 86.0.241 in our application. when DisableGpuAcceleration in CefSettings and launch the application, it open with blank html UI when I minimize it and restore it, html UI will load in the application.

- **What version of the product are you using?**
   86.0.241

- **What architecture x86 or x64?**
x64

- **On what operating system?**
     Win10 Enterprise

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
 WPF

- **What steps will reproduce the problem?**
    - When DisableGpuAcceleration in CefSettings and i launch the cefsharp application, html UI is loaded with blank white page while minimize and restore the app UI will load. I am not able to perform any UI action until when i minimize and restore the app. It create a major problem in our application

- **What is the expected output? What do you see instead?**
**Expected Output:**
When DisableGpuAcceleration in CefSettings and launch the application, html page load properly without any blank page

   **Actual Output:**
When DisableGpuAcceleration in CefSettings and launch the application, html page load properly with blank page

- **Please provide any additional information below.**

   Please find the faced blank page while launching the application

    ![image](https://user-images.githubusercontent.com/64392941/103407314-44fb0580-4b84-11eb-82d7-c2cdc905de5a.png)

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
Yes

Thanks,
Jagadeesh

**Comment by amaitland** [comment] 2020-12-31 19:29
> If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview

As per https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Any problem that reproduces with cefclient needs to be fixed in CEF. 

Is there a reason you need to disable GPU acceleration?

**Comment by stevenwei** [comment] 2021-01-03 23:35
Could this be related to the Intel Xe graphics issue described in #3330 and #3280? We are getting users reporting similar issues in our app and the common thread between them all seems to be having new computers with this Intel Xe graphics card.

**Comment by amaitland** [comment] 2021-01-10 03:47
> Could this be related to the Intel Xe graphics issue

The `Intel Xe Graphics` issue sounds a little different in that it works when `GPU Acceleration` is disabled. 

@EMJagadeesh What `Graphics` card are you experiencing this issue with?

As this problem is likely `Hardware` specific and unlikely we can do anything directly as it stands this will be closed as `upstream`. 

At this point my only suggestion would be to also disable `GPU Compositing` as well.

```c#
settings.CefCommandLineArgs.Add("disable-gpu");
settings.CefCommandLineArgs.Add("disable-gpu-compositing");
```

**Comment by EMJagadeesh** [comment] 2021-01-10 03:54
@amaitland - Issue resolve after disable GPU

**Closed** 2021-01-10 04:08 UTC
Labels: upstream, wpf

**Comment by amaitland** [comment] 2021-01-10 04:12
@EMJagadeesh Thanks for confirming.
