### ISSUE TITLE
Proxy auto config failed both in MinimalExample and CefSharp.WinForms.Example demos

### ISSUE THREAD

**Issue by nob2b** [cefsharp/CefSharp#1972] opened 2017-03-02 03:57 UTC
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
e.g. 53.0.1
 
   I downloaded it from here:  https://github.com/cefsharp/CefSharp.MinimalExample
- **What architecture x86 or x64?**
      x86 
- **On what operating system?**
    Win7 

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WinForm*
- **What steps will reproduce the problem?**
    - I have installed **shadowsocks** and uses proxy auto config (pac) to visit google from china (google is banned in china).
   - google can be reached by all browsers : IE, CHROME.... .but failed in cefsharp!!!

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)
      [0302/102805:ERROR:interface_registry.cc(99)] Capability spec prevented service service:content_browser from binding interface: net::interfaces::ProxyResolverFactory 

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
     NO
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    - To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
    - To compare with WinForms run cefclient --multi-threaded-message-loop
    - If you can reproduce the problem with `cefclient` then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

**Comment by jankurianski** [comment] 2017-03-02 04:34
CefSharp is a wrapper around CEF.  Please try your steps using the CEF Sample Application and see if the same problem occurs.

**Comment by amaitland** [comment] 2017-03-05 22:47
Duplicate of #1948

**Closed by amaitland** 2017-03-05 22:47 UTC
