### ISSUE TITLE
CefSharp.Internals.BrowserProcessServiceHost Exception

### ISSUE THREAD

**Issue by tbowers** [cefsharp/CefSharp#862] opened 2015-03-04 20:24 UTC
I have a WinForms app that hosts a `ChromiumWebBrowser` control. After extended use (1+ hour of heavy navigation), the memory footprint of the browser appears to rise up and never go down. 

Being unsure if this is was a leak, I added the ability to reset the browser (disposing and reseting the instance and creating a new one). This is invoked automatically every few minutes or so.

This worked fine in an automated test for a couple hours (and the memory foot print seemed to be at bay), however it finally crashed w/ the following.

```
System.InvalidOperationException: The communication object, CefSharp.Internals.BrowserProcessServiceHost, cannot be modified while it is in the Closing state.
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfClosedOrOpened()
   at System.ServiceModel.Description.ServiceMetadataExtension.System.ServiceModel.IExtension<System.ServiceModel.ServiceHostBase>.Attach(ServiceHostBase owner)
   at System.ServiceModel.ExtensionCollection`1.InsertItem(Int32 index, IExtension`1 item)
   at System.Collections.Generic.SynchronizedCollection`1.Add(T item)
   at System.ServiceModel.Description.ServiceMetadataExtension.EnsureServiceMetadataExtension(ServiceDescription description, ServiceHostBase host)
   at System.ServiceModel.Description.ServiceDebugBehavior.System.ServiceModel.Description.IServiceBehavior.ApplyDispatchBehavior(ServiceDescription description, ServiceHostBase serviceHostBase)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnBeginOpen()
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(Int32 browserId)
   at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
```

Could this be because I am destroying and creating the browser too quickly? Is it correct that we should only call `Initialize` and Shutdown` once for the lifetime of the application?

**Comment by amaitland** [comment] 2015-03-04 23:18
> Is it correct that we should only call Initialize and Shutdown` once for the lifetime of the application?

Effectively you can only call `Cef.Initialize()` once, see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/Cef.h#L153

As for `Cef.Shutdown()` you should only call that when you've completely finished with `CEF` as there's no way to reinitialize (I did try to get that working at one point and `CEF` just wouldn't play nice).

Do you have access to a memory profiler, see what's causing the leak? Probably something we should fix.

Also it would be great that if in every issue you include the basic info, i.e. version, long term it's easier if each issue is self contained :+1:

**Comment by tbowers** [comment] 2015-03-05 18:46
Sounds good, I apologize for the confusion. I will make to include the pertinent info in my future posts. I'm working now to reproduce the issues in the sample apps so it can easily seen on your end. Thanks again for the help.

**Comment by tbowers** [comment] 2015-03-06 18:26
Any other indicators from this stack trace what led to the crash?

**Comment by amaitland** [comment] 2015-03-19 05:30
Are you able to reproduce this? Modify one of the examples?

Pretty much the exact same error as reported https://github.com/cefsharp/CefSharp/issues/804#issuecomment-74082296

Are you using `-pre03` or later?

**Comment by amaitland** [comment] 2015-03-19 05:38
It looks like a timing issue, the `_browserProcessServiceHost->Open();` call throws the exception. 

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/ManagedCefBrowserAdapter.h#L112

**Comment by amaitland** [comment] 2015-03-19 05:46
Hopefully this helps https://github.com/cefsharp/CefSharp/commit/387101ee79b730d593d701b88e5fc521381fd964

**Comment by amaitland** [comment] 2015-04-02 00:24
Any further update on this one?

**Comment by tbowers** [comment] 2015-04-02 00:25
Fortunately we haven't seen it again.

**Comment by amaitland** [comment] 2015-04-02 01:31
Was it just the one time? Did you upgrade to the latest version and test again or still running the same version?

**Comment by tbowers** [comment] 2015-04-02 13:35
Yea it was just the one time and I'm still on `-pre03` tag.

**Comment by amaitland** [comment] 2015-04-02 21:38
Closing this as we have two issues representing the same exception. (#804)

**Closed by amaitland** 2015-04-02 21:38 UTC
Labels: bug, winforms
