### ISSUE TITLE
Cant input Chinese

### ISSUE THREAD

**Issue by Ms-Kelly-Yu** [cefsharp/CefSharp#3883] opened 2021-11-17 10:27 UTC
cef version
<PackageReference Include="CefSharp.Wpf.NETCore" Version="93.1.111" />
win10   *64  WPF
sometimes can input chinese, sometimes cant.
when I pressed a outter button then came back to the browser,  the browser will cant intput chinese.

**Comment by amaitland** [comment] 2021-11-17 11:08
Closing as duplicate of #1262

**Closed by amaitland** 2021-11-17 11:08 UTC

**Comment by ChanceLai** [comment] 2022-04-11 06:49
It is still present in the new version（v94.4.110）

**Comment by amaitland** [comment] 2022-04-11 07:34
> It is still present in the new version（v94.4.110）

This is an old unsupported version. 

IME is not enabled by default see https://github.com/cefsharp/CefSharp/issues/1262#issuecomment-659294710

**Comment by ChanceLai** [comment] 2022-04-11 08:01
`            _browser.WpfKeyboardHandler = new CefSharp.Wpf.Experimental.WpfImeKeyboardHandler(_browser);
`
 I've added this code.

**Comment by ChanceLai** [comment] 2022-04-11 08:06
> > It is still present in the new version（v94.4.110）
> 
> This is an old unsupported version.
> 
> IME is not enabled by default see [#1262 (comment)](https://github.com/cefsharp/CefSharp/issues/1262#issuecomment-659294710)

_browser.WpfKeyboardHandler = new CefSharp.Wpf.Experimental.WpfImeKeyboardHandler(_browser);
I've added this code.

**Comment by amaitland** [comment] 2022-04-11 08:36
You also need to upgrade to a newer version .

**Comment by ChanceLai** [comment] 2022-04-18 07:00
> You also need to upgrade to a newer version .

upgrade to v100.0.140.
In  one week's use, there is still the problem of being unable to input Chinese

**Comment by amaitland** [comment] 2022-04-18 07:04
All problems with IME should be reported on https://github.com/cefsharp/CefSharp/issues/1262 providing sufficient detail so someone else can reproduce the problem.
