### ISSUE TITLE
InvokeOnUiThreadIfRequired now internal

### ISSUE THREAD

**Issue by daphonk** [cefsharp/CefSharp#3042] opened 2020-02-05 15:21 UTC
Hi, I read in the new release InvokeOnUiThreadIfRequired is now internal.

How to I now realise this code:

this.InvokeOnUiThreadIfRequired(() => outputLabel.Text = output);

**Comment by amaitland** [comment] 2020-02-05 19:14
Duplicate of #2983 

Implement your own version,  the code is in the source.

**Closed by amaitland** 2020-02-05 19:14 UTC

**Comment by amaitland** [comment] 2020-02-05 19:19
See also #2980 which contains background information and an example
