### ISSUE TITLE
Win 10, WinForms,  Alt key hangs application

### ISSUE THREAD

**Issue by hfirst** [cefsharp/CefSharp#1855] opened 2016-11-06 16:11 UTC
I've duplicated this on multiple Windows 10 machines and also other developer and client pcs. The problem does not happen on the one Windows 7 machine I have.  It happens in both cef 39.0.02 and the current 53.0.0.  I even created a brand new empty C# winform .net 4.6.1 app so it's not any of our other code.  All I did in the empty winform app was declare a form1 class level private variable

`private ChromiumWebBrowser _browser;`

and in the form load event, new the browser and open a site

```
_browser = new ChromiumWebBrowser("www.amazon.com");
_browser.Dock = DockStyle.Fill;
this.Controls.Add(_browser);
_browser.Focus();

```
App starts, everything works, but if I just press the alt key all by itself, the whole app freezes and can even be hard to kill.

Updated ticket with template

What version of the product are you using?
 - 53.0.0

What architecture x86 or x64?
 - Machine is x64 but app is compiled in VS for x86

On what operating system?
 - Windows 10

Are you using WinForms, WPF or OffScreen?
 - WinForms

What steps will reproduce the problem?
 - Reference ：CefSharp.dll CefSharp.Core.dll CefSharp.Winform.dll
 - Create ChromiumWebBrowser and add it to mainform Controls.
 - Run app, page loads
 - Press JUST the alt key by itself.  App freezes and can only be killled via TaskManager

What is the expected output? What do you see instead?
 - App should not freeze

Does this problem also occur in the Cef TestApp from http://cefbuilds.com?
 - NO - but in your TestApp you have a top level menu (external to browser) that is being activated by the alt key, but our app does not have any external menu, just a fully dock filled browser and the app's menu is in the browser.  

Are you doing something special internally to connect the alt key with an external menu?

**Comment by amaitland** [comment] 2016-11-19 00:54
Duplicate of #1822

**Closed by amaitland** 2016-11-19 00:54 UTC
