### ISSUE TITLE
Upgrade projects to VS2015 (at least)

### ISSUE THREAD

**Issue by tdjastrzebski** [cefsharp/CefSharp#2723] opened 2019-04-15 12:33 UTC
It seems that **CefSharp.BrowserSubprocess.Core** and **CefSharp.Core projects** rely on VS2013 Build Tools (Platform Toolset = 'v120'). Those tools, unlike 2015 and 2107 versions, are not available in VS2019 installer and do not seem to be supported in VS2019. I tried installing them separately but no luck compiling.

**Comment by amaitland** [comment] 2019-04-15 19:44
Closing this as duplicate of #2628 

Currently you can use `VS2015` or `VS2017` to compile the project (official builds use `VS2015`). It only defaults to `VS2013` as there are no entries for `VS2019` in https://github.com/cefsharp/CefSharp/blob/master/CefSharp.props they will be added in #2628

Short term it's possible to add support for compiling in `VS2019` using the `VS2017` build tools.

**Closed by amaitland** 2019-04-15 19:44 UTC

**Comment by tdjastrzebski** [comment] 2019-04-15 20:12
I do not know if it is a problem but `<Project DefaultTargets="Build" ToolsVersion="12.0"...` in
[https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSharp.Core.vcxproj](https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSharp.Core.vcxproj) (e.g.)
indicats VS 2013 tools version. VS 2015 uses version 14.0, if I am not mistaken.

**Comment by amaitland** [comment] 2019-04-15 20:41
> I do not know if it is a problem but `<Project DefaultTargets="Build" ToolsVersion="12.0"...` in
> https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Core/CefSharp.Core.vcxproj (e.g.)
> indicates VS 2013 tools version

From memory this makes no difference in terms of compiler, makes no difference to me opening in `VS2015` or `VS2017`. By all means submit a `PR` upgrading to version `14`. I don't believe this will allow you to compile with `VS2019` until `CefSharp.props` has been updated.

> In VS 2019 both "Core" projects are marked as VS 2013.

The default will be `VS2013` as there are no `VS2019` entries in `CefSharp.props`.

**Comment by tdjastrzebski** [comment] 2019-04-16 19:02
My only intent was to point out the build process probably uses VS 2013 tools, which are unsupported in VS 2019. Changing the defeult to 2015 may solve the issue - the need for another, older VS.

**Comment by amaitland** [comment] 2019-04-16 20:23
> My only intent was to point out the build process probably uses VS 2013 tools

Currently a version of `Visual Studio` must be explicitly supported, otherwise it defaults to `VS2013`. `VS2013`, `VS2015` and `VS2017` are the current supported versions. 

> Changing the defeult to 2015 may solve the issue - the need for another, older VS.

Will be rewritten as part of #2628
