### ISSUE TITLE
Sticky scroll bar annoying users

### ISSUE THREAD

**Issue by arvindlloyds** [cefsharp/CefSharp#2484] opened 2018-08-14 10:56 UTC
What steps will reproduce the problem?

- **What version of the product are you using?**
v65.0.0 NuGet
- **What architecture x86 or x64?**
x64
- **On what operating system?**
    - Win7

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What steps will reproduce the problem?**
1-Just open any web url.
2-Press mouse left button on scroll bar, keep pressed and move the mouse outside.
3-Leave the mouse button
4-Come back to browser and move mouse up or down
- **What is the expected output? What do you see instead?**
Expected - Scroll bar must not move
Actual - Scroll bar is sticky and moves with mouse move

- **Please provide any additional information below.**

- **Does this problem also occur in the `CEF` Sample Application from 
Problem also occurs in - CefSharp.MinimalExample.Wpf

Please Note: I searched for few days, could not find any flag etc to resolve this.

-**Its possible that this not a bug but usual functionality. But I need to switch this off. So need help from experts**

**Comment by amaitland** [comment] 2018-08-16 02:04
Closing as duplicate of https://github.com/cefsharp/CefSharp/issues/2458

Please open a new issue for your other tooltip problem.

**Closed by amaitland** 2018-08-16 02:04 UTC

**Comment by amaitland** [comment] 2018-08-18 22:52
`65.0.1` has been released which reverts to the old behaviour.
