### ISSUE TITLE
PDF scrolling with mouse wheel not working

### ISSUE THREAD

**Issue by shenhavba** [cefsharp/CefSharp#1916] opened 2017-01-17 16:42 UTC
Bug Report

**What version of the product are you using?**

CefSharp.Common, CefSharp.Wpf all version 55

**What version are you using? Nuget? CI Nuget? build from a branch? If so which branch? e.g. 53.0.1
What architecture x86 or x64?**

build from branch 55.0.0-pre01 - x86

**On what operating system?**

windows 10

**Are you using WinForms, WPF or OffScreen?**

wpf

**What steps will reproduce the problem?**

     1. open pdf with a lot of pages.
     2.try to scroll with the mouse, nothing happens for few seconds and then, the pages jump to the last page           

**Please provide detailed information here, enough for someone else to reprodce your problem.
Please no binary (zip, etc) links, fork the MinimalExample and push your changes to GitHub. (Alternatively use a code sharing service list Gist or Pastebin).
What is the expected output? What do you see instead?**

The expected behavior is good scrolling, page by page but the scrolling causing the pages to jump to the last one.
Its working fine in version 47.

**Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

No.

**Comment by merceyz** [comment] 2017-01-17 18:14
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md

**Comment by amaitland** [comment] 2017-01-17 20:38
It's interesting to note that scrolling with the `scrollbar` is working fine. 

> Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?
> 
> No.

Please verify the command line args you used when tested with `cefclient`, it's very important they're the ones listed for `WPF`. If this reproduces with the command line args specified for comparing to `WPF`, then someone will need to dig into this further, I guess starting with comparing the mouse wheel code.

If you have time, please investigate this further. The `cefclient` code is available at https://bitbucket.org/chromiumembedded/cef/src/9d48a4f80e2ba30bb3ddaf97f9e7c34e670c22a7/tests/cefclient/?at=master

**Comment by amaitland** [comment] 2017-01-17 21:43
@shenhavba Did you actually test with `cefclient --multi-threaded-message-loop --off-screen-rendering-enabled`???? I'm seeing the same problem reproduce....

**Comment by amaitland** [comment] 2017-01-17 22:06
https://bitbucket.org/chromiumembedded/cef/issues/2078/osr-pdf-scrolling-with-mousewheel-keyboard

**Comment by shenhavba** [comment] 2017-01-18 04:09
I did not know that i should run it with command line parameters unril you said so.

Can i remove those parameters?

Thank you for checking this issue!

**Comment by amaitland** [comment] 2017-01-18 04:15
> Does this problem also occur in the CEF Sample Application from http://opensource.spotify.com/cefbuilds/index.html?

>    To compare with WPF run cefclient --multi-threaded-message-loop --off-screen-rendering-enabled
>    To compare with WinForms run cefclient --multi-threaded-message-loop
>    If you can reproduce the problem with cefclient then you'll need to report the bug on https://bitbucket.org/chromiumembedded/cef/overview there is no point opening an issue here. (Make sure you search before opening an issue)

@shenhavba The parameters to use were clearly outlined in the issue template.

> Can i remove those parameters?

No. You can use the `WinForms` version until this has been resolved.

**Comment by AndrewBragdon** [comment] 2017-06-18 18:37
This repros for me as well.  Would be great if we could fix this, since it appears to affect all PDF files in the WPF version of cefsharp.

**Comment by perlun** [comment] 2017-12-02 20:50
Seemingly fixed in CEF62 - those of you seeing this, please try the latest MyGet builds to see if you can also verify this is indeed fixed in our latest bits.

**Comment by angshuman-agarwal** [comment] 2017-12-13 11:43
Yes - PDF scrolling works fine. Thank you.

I did check - 
**Install-Package CefSharp.Wpf -Version 62.0.0-pre01**

**Comment by amaitland** [comment] 2017-12-19 01:55
Resolved in `62.0.0-pre01`

**Closed by amaitland** 2017-12-19 01:55 UTC
Labels: known-issue, upstream, wpf
