### ISSUE TITLE
Cef.wpf can't enable flashplayer.

### ISSUE THREAD

**Issue by FrankieGao** [cefsharp/CefSharp#1653] opened 2016-04-07 11:13 UTC
when I used Cef.wpf in the wpf project,when I visited the website which needed flasherplayer,it notices that i need to install the player,when I installed on my machine ,it's still not ok. when I tried in this way below ,it's also not well.
   CefSharp.Wpf.ChromiumWebBrowser webbrower = new CefSharp.Wpf.ChromiumWebBrowser();
            webbrower.BrowserSettings.Plugins = CefSharp.CefState.Enabled;

**Comment by amaitland** [comment] 2016-04-07 12:09
> So you have a question to ask, where can you look for answers?

> - Check out the FAQ, lots of useful information there, specially if your having trouble deploying to a different machine : https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions
> - GitHub proves a fantastic search feature, it'll search through past issues and code. So check that out (Search box at the top of this page) : https://github.com/cefsharp/CefSharp
> - You can see all the `CefSharp` tagged issues on `Stackoverflow`, some useful stuff there : http://stackoverflow.com/questions/tagged/cefsharp
> - You can search the `Gitter Chat Channel` for past questions/conversations, you can search through every discussion from the beginning : https://gitter.im/cefsharp/CefSharp

Please take the time to read the issue template, if you have a question, ask it on `Gitter` first. 
https://github.com/cefsharp/CefSharp/blob/master/ISSUE_TEMPLATE.md


Closing this as duplicate of #1505

**Closed by amaitland** 2016-04-07 12:09 UTC
