### ISSUE TITLE
Wpf.Example Has Constant Refresh On google.com - When google Has A Doodle

### ISSUE THREAD

**Issue by scottcg** [cefsharp/CefSharp#1637] opened 2016-03-20 15:02 UTC
- **What steps will reproduce the problem?**
  Run Wpf.Example in debug|release, x64, and open a tab to google.com. Today has a doodle instead of usual google logo. This the doodle for today:
  http://www.google.com/doodles/first-day-of-spring-2016-northern-hemisphere 

- **What is the expected output? What do you see instead?**
  Expected to see google home page without repeated refresh.

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
  WPF, the WinForms demo works great.

- **What version of the product are you using? On what operating system? x86 or x64?**?
  Win10, latest pull from github. x64 both release|debug has the same problem.

- **Please provide any additional information below.**
  No errors, and log file is empty. I don't see this problem with my own custom app -- not built from latest on github.

- **Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?**
  Not that I can tell, I'm just running the WPF demo.

- **Does this problem also occur in the `Cef` TestApp from http://cefbuilds.com?**
  I didn't try these, just did a package restore, in VS2013.

**Comment by amaitland** [comment] 2016-03-20 20:37
Duplicate of #1634

**Closed by amaitland** 2016-03-20 20:37 UTC

**Comment by amaitland** [comment] 2016-03-20 20:42
Switch to using the current release branch if you wish to test out the `WPF` control, `master` is unstable.

https://github.com/cefsharp/CefSharp/tree/cefsharp/47
