### ISSUE TITLE
v41 flash/html5 issue

### ISSUE THREAD

**Issue by EvilMindsGFX** [cefsharp/CefSharp#1103] opened 2015-07-02 09:57 UTC
Currently on the recently released v41 pre-release & apparently the stable reported by nuget seem to have a problem with flash or something. Upon sites like Twitch, videos never load. It doesn't even begin to initialize the video player. Everything all goes fine on YouTube, but it's a no go on twitch. Had to revert back to v39 to get it working again.

I'm using CefSharp Winforms.

**Comment by amaitland** [comment] 2015-07-02 10:08
What plugins does it report being loaded? `Cef.GetPlugins()` for full info. If you load `chrome://version/` it should show the flash version if it found one. What version does it show? I'm using `18.0.0.194` successfully.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L109

**Comment by EvilMindsGFX** [comment] 2015-07-02 17:37
Show's it is loading the current up-to-date flash player.

"CEF: 3.2272.32.gbda8dc7
Chromium: 41.0.2272.104
OS: Windows
WebKit: 537.36
JavaScript: 4.1.0.21
Flash: 18,0,0,194"

**Comment by amaitland** [comment] 2015-07-03 01:34
If you download the matching `Test App` from https://cefbuilds.com/#branch_2272 does the problem reproduce? 

Flash is somewhat in a state of flux as `NPAPI` is phased out in favor of `PPAPI`.
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12820
http://magpcss.org/ceforum/viewtopic.php?f=6&t=12888&p=25508

> In short you need to pass the `--enable-npapi` command-line flag to use NPAPI Flash or use a master branch build (until M43 branch is created) to use PPAPI Flash.

**Comment by EvilMindsGFX** [comment] 2015-07-03 05:01
Yes. Under that test app the same issue occurred & it dumped a log for javascript.

`Message: JQMIGRATE: Logging is active

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 17

-----------------------

Message: JQMIGRATE: jQuery.browser is deprecated

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 17

-----------------------

Message: XMLHttpRequest cannot load chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js. Cross origin requests are only supported for protocol schemes: http, data, chrome-devtools, chrome, client, https.

Source: http://www.twitch.tv/

Line: 0

-----------------------

Message: XMLHttpRequest cannot load chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js. Cross origin requests are only supported for protocol schemes: http, data, chrome-devtools, chrome, client, https.

Source: http://www.twitch.tv/

Line: 0

-----------------------

Message: XMLHttpRequest cannot load chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js. Cross origin requests are only supported for protocol schemes: http, data, chrome-devtools, chrome, client, https.

Source: http://www.twitch.tv/

Line: 0

-----------------------

Message: XMLHttpRequest cannot load chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js. Cross origin requests are only supported for protocol schemes: http, data, chrome-devtools, chrome, client, https.

Source: http://www.twitch.tv/

Line: 0

-----------------------

Message: XMLHttpRequest cannot load chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js. Cross origin requests are only supported for protocol schemes: http, data, chrome-devtools, chrome, client, https.

Source: http://www.twitch.tv/

Line: 0

-----------------------

Message: No cast extension found

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 29

-----------------------

Message: Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js'.

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 30

-----------------------

Message: Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js'.

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 30

-----------------------

Message: Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js'.

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 30

-----------------------

Message: Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js'.

Source: http://www-cdn.jtvnw.net/assets/global-4a23cd388b0c76ad8bda5c98823ecc16.js

Line: 30

-----------------------

Message: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

Source: 

Line: 0

-----------------------
`

**Comment by amaitland** [comment] 2015-07-03 05:39
Does a basic site like https://www.adobe.com/au/software/flash/about/ work?

Do you know if twitch tries to use some sort of `chrome extension`? If that's the case then it won't work in `CEF` and subsequently `CefSharp` as there is no plugin support.

**Comment by amaitland** [comment] 2015-07-03 10:30
Quickly tried in `39` and `41`, for now you'll have to stick with `41` by the looks of it.

`43` will bring support for `ppapi` which is the way of the future.

**Comment by EvilMindsGFX** [comment] 2015-07-03 18:41
It does not attempt to use any extensions. Currently I'm just sticking with `39` until `43` as it's the only one currently working for my app as it's primarily targeted for Twitch.

**Comment by amaitland** [comment] 2015-07-03 21:33
Looks like its attempting to use the Chromecast extension http://stackoverflow.com/questions/25814914/chrome-youtube-cast-sender-js-console-error

Anyways, can you force twitch to use html5?

**Comment by EvilMindsGFX** [comment] 2015-07-04 02:24
It does use `HTML5` for the chat now, but the video consist to use Flash Player.
I'm wondering how it's attempting to load Chromecaster. Chromecaster is only added to extensions if you choose to install it from the Chrome web store.

**Comment by amaitland** [comment] 2015-07-05 23:35
https://bitbucket.org/chromiumembedded/cef/issue/1624/support-playback-of-pepper-flash-video

**Comment by EvilMindsGFX** [comment] 2015-07-07 23:52
Even under '39' using DevTools it shows the same thing about not being able to load 'cast_sender.js', but it still loads videos from twitch.

**Comment by jornh** [comment] 2015-07-08 18:16
Well according to your feedback in https://github.com/cefsharp/CefSharp/issues/1103#issuecomment-118233730 behavior is the same for the upstream CEF official test app. So as it reproduce with CEF alone it's not really something that can be fixed in The CefSharp codebase. Marking as `upstream`.

As @amaitland already mentioned CEF is naturally 1/2 a step ahead of CefSharp and in a state of flux with moving to pepper flash. Only thing I think CefSharp can do is keep an eye on that moving to pepper flash in `43` will resolve.

**Comment by amaitland** [comment] 2015-08-11 03:28
`master` has been updated with the latest `2357` build.

**Comment by amaitland** [comment] 2015-08-19 20:47
> Upon sites like Twitch, videos never load.

https://github.com/cefsharp/CefSharp/issues/799#issuecomment-124034087

**Closed by amaitland** 2015-08-19 20:47 UTC
Labels: upstream

**Comment by EvilMindsGFX** [comment] 2015-08-20 19:07
Attempting to update my solution with the `43 pre-release` completely breaks my browser being initialized. `Cef.Initialize();` a single sub-process, but it does not move forward from there. It leaves my application blank.

**Comment by amaitland** [comment] 2015-08-20 20:39
> Some different method needed to load a browser window or some ish?

Nope, the core is the same in that sense. What does the `debug.log` file say?

What features are you using specifically?

**Comment by jankurianski** [comment] 2015-08-21 01:00
If you attach a handler to the `BrowserInitialized` event, does it fire?

Are you trying to use the browser before `IsBrowserInitialized` is true?

**Comment by EvilMindsGFX** [comment] 2015-08-22 12:34
`debug.log` came out blank but attempting to reload a page causes my crash reporter to catch `Browser Is Not yet initialized. Use the IsBrowserInitializedChanged event and checkthe IsBrowserInitialized property to determine when the browser has been intialized.`
I've never had to do anything but include `Cef.Intialize();` and
`browser = new ChromiumWebBrowser("www.google.com")
            {
                Dock = DockStyle.Fill,
            };
`

**Comment by EvilMindsGFX** [comment] 2015-08-23 03:09
If the minimal example works, but my own doesn't, what must it be?

**Comment by amaitland** [comment] 2015-08-23 08:05
How are you calling Shutdown?

**Comment by EvilMindsGFX** [comment] 2015-08-23 08:20
Currently using `Form_Closing` event with `Cef.Shutdown();`.

**Comment by amaitland** [comment] 2015-08-23 12:07
Do you use any callbacks or javascript binding?

**Comment by EvilMindsGFX** [comment] 2015-08-23 13:45
Nope. Absolutely nothing but the browser itself.

**Comment by amaitland** [comment] 2015-08-23 20:01
You can try disabling `WCF` then, see if that improves things.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/CefExample.cs#L41

**Comment by EvilMindsGFX** [comment] 2015-08-25 04:53
Yup. That fixed the problem with it taking a very long time to shutdown.

**Comment by EvilMindsGFX** [comment] 2015-08-26 06:49
Anything useful on removing the `--no-sandbox` flag to avoid the flash pop-up window?

**Comment by amaitland** [comment] 2015-08-26 07:05
> Anything useful on removing the --no-sandbox flag to avoid the flash pop-up window?

You'd have to actually implement `sandboxing` for that to be of use. You can look at the `cefclient` for an example if your interested.
