### ISSUE TITLE
WPF - Value cannot be null ToolTipService.GetBetweenShowDelay

### ISSUE THREAD

**Issue by 537mfb** [cefsharp/CefSharp#4229] opened 2022-08-30 13:43 UTC
- **What version of the product are you using?**
    - v. 104.4.240 from nuget.

- **What architecture x86 or x64?**
    AnyCpu on x64 machine
	
- **What version of .Net?**
    .Net 6.0
    
- **On what operating system?**
    Windowns 11

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    - I was testing several sites in my app and ended up on an article on yahoo.com (specific address: https://www.yahoo.com/news/sen-marco-rubio-called-student-010640825.html) - I decided to look through the comments on said article. Throught the comments there will be links like '1 reply' or 'n replies' that load more replies and the 'see more' links that expand long comments. I was clicking theses links and after several that worked fine, the app crashed with a Symbol loading skipped exception. (StackTrace at the bottom of these report)

- **What is the expected output? What do you see instead?**
   - I expected more replies to be loaded, as it had happene with previous links

- **Please provide any additional information below.**
    - Message: Value cannot be null. (Parameter 'element')
    - Source: PresentationFramework
    - StackTrace:
 ```
  at System.Windows.Controls.ToolTipService.GetBetweenShowDelay(DependencyObject element)
   at System.Windows.Controls.PopupControlService.CloseToolTip(ToolTip tooltip)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(Tuple`2 postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.ChangeMouseCapture(IInputElement mouseCapture, IMouseInputProvider providerCapture, CaptureMode captureMode, Int32 timestamp)
   at System.Windows.Input.MouseDevice.Capture(IInputElement element, CaptureMode captureMode)
   at CefSharp.Wpf.ChromiumWebBrowser.OnMouseDown(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MyBrowserApp.App.Main()
```

- **Does this problem also occur in the `CEF` Sample Application**
    - Couldn't replicate it in the CEF Sample Application so far - maybe it's a problem only on AnyCPU? Or just haven't figured out how to replicated it exactly? Will look into this and report back if I find anything new
    - **EDIT:** actually with the CEF Sample Application sometimes the page reloads itself, removing all comments I had previously loaded by clicking those links - I'm assuming it's the same error, only the Sample Application is recovering itself while my app crashes for some reason
    - **EDIT2:** Found the following in debug.log of the CEF Sample Application (not sure if related): `[0830/152616.803:WARNING:spdy_session.cc(3502)] Received HEADERS for invalid stream 189`

**Comment by amaitland** [comment] 2022-08-30 19:12
Closing as duplicate of #4048

This is a bug in WPF https://github.com/dotnet/wpf/issues/6319

**Closed by amaitland** 2022-08-30 19:12 UTC
