### ISSUE TITLE
CSS cursor property not working in WPF version

### ISSUE THREAD

**Issue by Jadecity** [cefsharp/CefSharp#1826] opened 2016-10-10 15:43 UTC
As mentioned in #606 , I didn't got a custom cursor image when I visited http://html5advent2011.digitpaint.nl/3/index.html and hover over _Custom Cursor_ box. I just changed the address of ChromiumWebBrowser control in Cefsharp mini-example. 
I am using WIN 10, VS 2013 and .Net 42. Cefsharp version is 51.  Cef test app can show that custom cursor, but Cefsharp mini-example can not. How could I fix this problem ?

**Comment by amaitland** [comment] 2016-10-10 21:13
Closing this as duplicate of #606 

> How could I fix this problem ?

You'd need to submit a `PR` that implements #606

**Closed by amaitland** 2016-10-10 21:13 UTC
