### ISSUE TITLE
Provide debugging symbols online

### ISSUE THREAD

**Issue by ralphmayr** [cefsharp/CefSharp#1013] opened 2015-05-07 12:11 UTC
It would be good if the CefSharp project could provide a symbol server where the PDBs of the releases can be downloaded.
If the symbols are available somewhere already it would be nice if anyone could point me to them :)

**Comment by amaitland** [comment] 2015-05-07 12:18
Duplicate of #880

**Closed by amaitland** 2015-05-07 12:18 UTC
