### ISSUE TITLE
WebGL performance issues

### ISSUE THREAD

**Issue by sxhatrix** [cefsharp/CefSharp#2430] opened 2018-06-25 20:00 UTC
- **What version of the product are you using?**

63.0.3 through nuget. Issue also occurs with all 63.0.x versions and 65.0.0-pre02 through nuget

- **What architecture x86 or x64?**

x64, issue also occurs with x86

- **On what operating system?**

Win7 and Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WPF and WinForms

- **What steps will reproduce the problem?**

Launch MinimalExample with any version 63 or higher and go to http://webglsamples.org/aquarium/aquarium.html, the framerate will be very low
Launch MinimalExample again with any version before 63 and the framerate will be normal

- **What is the expected output? What do you see instead?**

Expecting similar framerate to previous version, it is maybe 1/6th the framerate of previous version.

Tried with hardware acceleration on and off and I upgraded GPU drivers before testing

- **Please provide any additional information below.**

Only one warning in log, WARNING:client_shared_bitmap_manager.cc(98)] Browser failed to allocate shared memory

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

Does not occur in sample Cef application.

**Comment by amaitland** [comment] 2018-06-25 21:35
What version of cefclient did you test with and what command line arguments did you test with?

Have you tested on different hardware? What gpu are you using? What frame rate are you actually seeing?

I'm not experiencing any problems nor have I received any other reports and 63 has been out for quite some time. 

Your bug report could use an edit, please don't put your answers as bold and remove the placeholder text.

**Comment by amaitland** [comment] 2018-06-26 00:00
You should open chrome://gpu in the browser and confirm that gpu acceleration is actually enabled. 

Open chrome://version to determine which CEF version you need to compare to

**Comment by sxhatrix** [comment] 2018-07-02 16:49
I've been researching this some more and it's only happening with lower end GPUs. I tested it on some PCs with Intel HD Graphics using the minimal CefSharp build and going to chrome://gpu shows gpu acceleration ON for WebGL / WebGL2 in CefSharp versions 57 and below. After upgrading to CefSharp 63 or later with no other changes the GPU acceleration now shows as OFF.

Running the Windows Cef client Version 3.3396.1779.g36f9eab / Chromium Version: 67.0.3396.79 and going to chrome://gpu it always shows hardware acceleration for WebGL/WebGL2 as ON.

Is there something that may be causing the WebGL hardware acceleration to be turned off?

**Comment by amaitland** [comment] 2018-07-06 01:04
> Is there something that may be causing the WebGL hardware acceleration to be turned off in CefSharp versions 63+?

Not that I'm aware of. It works for me with an `Intel HD 4000` graphics card running `Windows 10 1709` using commit https://github.com/cefsharp/CefSharp/commit/41a6b837a0e419d2154fdb7f824b0cd2d036f707

**Comment by amaitland** [comment] 2018-08-02 00:16
I've not seen any other reports of this problem and are unable to reproduce myself.

`master` has been upgraded to `CEF 3.3440.1803.gde363ee / Chromium 68.0.3440.75`, and `GPU Acceleration` is working for my `Intel HD 4000` Graphics card.

Will leave this open for a little bit longer incase someone else wants to chime in. Will in all likelihood be closed as `Unable to reproduce`.

**Comment by amaitland** [comment] 2018-08-12 10:54
Closing as `unable to reproduce`. The `67.0.0-pre01` packages are now out, if others can reproduce the same problem (where `GPU Acceleration works in `cefclient` and not in `CefSharp`) then this can be reopened.

Make sure you test with `cefclient` before commenting, see https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-chromium-embedded-frameworkcef for instructions.

**Closed by amaitland** 2018-08-12 10:54 UTC

**Comment by Styn** [comment] 2019-03-29 08:03
Had a similar issue, but it was limited to CefSharp.Wpf. Probably related to it using off screen rendering.
(It was more or less reproducable with CefClient.)
Turning off gpu compositing in the command line args of CefSettings dramatically increased performance for us.

**Comment by AliFlux** [comment] 2019-04-06 10:29
Hi. I've run mapbox webgl example using CefSharp latest version on WPF, it runs considerably slow compared to Firefox and Chrome, any idea what could the reason be?

```cs
var settings = new CefSettings();
settings.CefCommandLineArgs.Add("enable-gpu", "1");
settings.CefCommandLineArgs.Add("enable-webgl", "1");
settings.CefCommandLineArgs.Add("enable-begin-frame-scheduling", "1");
settings.CefCommandLineArgs.Add("--off-screen-frame-rate", "60");

Cef.Initialize(settings);

var browser = new ChromiumWebBrowser();
MainGrid.Children.Add(browser);
browser.Address = "https://docs.mapbox.com/mapbox-gl-js/example/add-image/";
```
