### ISSUE TITLE
File not found exception when used from within office application

### ISSUE THREAD

**Issue by OOTTMM** [cefsharp/CefSharp#2228] opened 2018-01-08 13:58 UTC
Hi guys,
I am trying to get CefSharp to work from within an C# MSO COM add-in.
When I try to build the WinForm example in my add-in code everything compiles without errors but when I load the form and the first call to CefSharp is made  => CefSettings settings = new CefSettings();
I get the below error.

System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Additional information: Could not load file or assembly 'CefSharp, Version=57.0.0.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.

The same code works in a normal Win form app without any error. I double checked the created x86 folder and all files are there. Any idea how to proceed?

My configuration
Nuget 57.0
Excel2013
Win 8.1
WinForms
x86

Kind regards
Oliver

**Comment by mitchcapper** [comment] 2018-01-08 18:38
Hi Oliver gitter is best for questions, try using procmon to make sure the dll's are where expected and search ticket history for some of the other issues.

**Comment by amaitland** [comment] 2018-01-08 22:59
Duplicate of #2109 and #1191

I'd suggest you look at a different `CEF` wrapper as `CefSharp` is not going to work out of the box in that scenario.

**Closed by amaitland** 2018-01-08 22:59 UTC
