### ISSUE TITLE
Mouse pointer disappears if to close window using touch

### ISSUE THREAD

**Issue by helen-dwa** [cefsharp/CefSharp#2759] opened 2019-05-07 02:14 UTC
It is same as issue #1886 but solution didn't work for me.

-What version of the product are you using?
    63.0.3
-What architecture x86 or x64?
    x86
-On what operating system?
   Win10, Tablet Surface Pro with touch screen and connected keyboard with a touchpad
-Are you using WinForms, WPF or OffScreen?
   WinForms, WPF
-Additional information
   A library WmTouchDevice is used. CefSharp.WinForms in CefWindowsFormsHost.

**What steps will reproduce the problem?**
- Create a main window and a button "Open child window"
- Create a child window with Browser and Close button
- Run the app, press "Open child window"
- Touch somewhere in browser
- Touch "Close" button

Result: mouse cursor is invisible in the main window.

Source code files are attached.
[src.zip](https://github.com/cefsharp/CefSharp/files/3150515/src.zip)

**Comment by amaitland** [comment] 2019-05-07 02:21
Closing as duplicate of #1886

You can ask for help in #1886

**Closed by amaitland** 2019-05-07 02:21 UTC
