### ISSUE TITLE
OffScreen - PrintToPdfAsync: set_MarginBottom(Int32) method not found

### ISSUE THREAD

**Issue by scegg** [cefsharp/CefSharp#4347] opened 2022-12-22 01:45 UTC
- **What version of the product are you using?**
 Nuget 108.4.130

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
   .Net 6
    
- **On what operating system?**
Win11

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms OffScreen (UI is not for cef)
    
- **What steps will reproduce the problem?**
```
await browser.PrintToPdfAsync(fileName, new PdfPrintSettings
                    {
                        MarginType = CefPdfPrintMarginType.Custom,
                        MarginBottom = 0,
                        MarginTop = 0,
                        MarginLeft = 0,
                        MarginRight = 0,
                        PageWidth = 500,
                        PageHeight = 500
                    });
```

- **What is the expected output? What do you see instead?**
Print to pdf as usual.

- **Please provide any additional information below.**
Exception: Method not found: 'Void CefSharp.PdfPrintSettings.set_MarginBtoom(Int32)'

**Comment by amaitland** [comment] 2022-12-22 02:09
Print to PDF support was refactored as there was upstream changes see #4311 

Have you tried to reproduce the issue with the MinimalExample as requested in the bug report? 

> * WinForms OffScreen (UI is not for cef)

Are you using `WinForms` or `OffSceen`?

> Exception: Method not found: 'Void CefSharp.PdfPrintSettings.set_MarginBtoom(Int32)'

Is this the exact error your seeing? There's a typo here.

> PageWidth = 500,
> PageHeight = 500

Your code shouldn't even compile, these properties were renamed to `PaperWidth` and `PaperHeight`.

This looks more like a problem with your project than it does a `CefSharp` bug as your code shouldn't even compile.

**Comment by amaitland** [comment] 2022-12-22 02:18
> Compiling finished with no error.

Sounds like one of the projects in your solution wasn't updated correctly.

It should be impossible for that code to compile with `M108`.

**Comment by amaitland** [comment] 2022-12-22 02:19
> set_MarginBottom(Int32) method not found

Your issue title has a different spelling. What is the exact error?

**Comment by amaitland** [comment] 2022-12-22 02:29
> I think I should open an issue to visual studio instead, right?

No. 

Have you created an isolated example that reproduces the problem? More likely it's a transient issue. 

The following works as expected using the `MinimalExample`. Tested with `.Net 6.0`

```c#
await browser.PrintToPdfAsync("test.pdf", new PdfPrintSettings
{
	MarginType = CefPdfPrintMarginType.Custom,
	MarginBottom = 0,
	MarginTop = 0,
	MarginLeft = 0,
	MarginRight = 0,
	PaperWidth = 4,
	PaperHeight = 6
});
```

I'm going to close this issue as unable to reproduce. Your code shouldn't even compile. Start with a clean checkout from your source control.

**Closed by amaitland** 2022-12-22 02:29 UTC
Labels: unable-to-reproduce

**Comment by amaitland** [comment] 2022-12-22 02:37
You can review the source see https://github.com/cefsharp/CefSharp/blob/cefsharp/108/CefSharp/PdfPrintSettings.cs

Those properties simply don't exist anymore.

For the issue to be reopened you need to provide an example that reproduces the problem (no zip files, push code to github).

**Comment by amaitland** [comment] 2022-12-22 02:56
You should also check the version of the `CefSharp.dll` in your `bin` folder. My guess is it's still `M107`.
