### ISSUE TITLE
Win10 system input method bug  ,CefSharp version 57.0.0 or master

### ISSUE THREAD

**Issue by JackChen1866** [cefsharp/CefSharp#2270] opened 2018-02-07 12:34 UTC
What version of the product are you using?
CefSharp version 57.0.0 or master

What architecture x86 or x64?
x86

On what operating system?
Win 10

Are you using WinForms, WPF or OffScreen?
wpf

What steps will reproduce the problem?
      Win10 system input method, the position of the Chinese standby box is not close to the input window.

**Comment by amaitland** [comment] 2018-02-07 12:40
IME is not currently supported in WPF

Closing as duplicate of #1262

**Closed by amaitland** 2018-02-07 12:40 UTC
