### ISSUE TITLE
Calling method on Bound C# object throws NullReferenceException in unmanaged code

### ISSUE THREAD

**Issue by maynardflies** [cefsharp/CefSharp#1611] opened 2016-02-26 16:56 UTC
- **What steps will reproduce the problem?**

1. Create browser in code
2. Bind object using browser.RegisterJsObject
3. add browser to a WPF control and let it render
4. Attempt to call a method on the object

- **What is the expected output? What do you see instead?**
Expected output would be nothing, as the method in question is a void type.  I get the following error instead
```

salesbookBridge.invokeBloombergCommand("","","") < -- Invocation call, in DevTools (same thing happens when using JSFiddle)

VM187:2 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at CefSharp.JavascriptMethodWrapper.Execute(Object[] parameters)
   at CefSharp.JavascriptMethodHandler.Execute(JavascriptMethodHandler* , CefStringBase<CefStringTraitsUTF16>* name, CefRefPtr<CefV8Value>* object, vector<CefRefPtr<CefV8Value>\,std::allocator<CefRefPtr<CefV8Value> > >* arguments, CefRefPtr<CefV8Value>* retval, CefStringBase<CefStringTraitsUTF16>* exception)

   at CefSharp.JavascriptMethodWrapper.Execute(Object[] parameters)
   at CefSharp.JavascriptMethodHandler.Execute(JavascriptMethodHandler* , CefStringBase<CefStringTraitsUTF16>* name, CefRefPtr<CefV8Value>* object, vector<CefRefPtr<CefV8Value>\,std::allocator<CefRefPtr<CefV8Value> > >* arguments, CefRefPtr<CefV8Value>* retval, CefStringBase<CefStringTraitsUTF16>* exception)
    at Error (native)
    at <anonymous>:2:17
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)

```
- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WPF

- **What version of the product are you using? On what operating system? x86 or x64?**
x86 v47.0.3

    - What version are you using? Nuget? CI Nuget? build from a branch? If so which branch?
Nuget 47.0.3

    - Win7, Win 8, Win10, etc?
Win7

Execution doesn't come into my managed code at all.  I'm using VS2012 so I can't compile from source or debug into CefSharp.WPF as compilation is not supported in 2012 anymore

There is nothing in the debug.log file at all related to this, attempting to execute the method writes nothing to the file

It's worth noting that it does appear to find the method, as changing the call to use a non-existent method name gives a different error ("not a function").  My C# code is fairly simple

````
var browser = new ChromiumWebBrowser();
            if (BoundObject != null)
                browser.RegisterJsObject("salesbookBridge", BoundObject);
            AppDomain.CurrentDomain.ProcessExit += CurrentDomain_ProcessExit;
            browser.FrameLoadEnd += FrameLoaded;
             BindingOperations.SetBinding(browser, ChromiumWebBrowser.AddressProperty,
                new Binding("ContainerElement.URL"));
            this.AssociatedObject.Child = browser; <- adding the browser to a Border for rendering`
```

**Comment by maynardflies** [comment] 2016-02-26 17:02
using RegisterAsyncJsObject appears to work, the method on the .NET side gets called correctly.

**Comment by amaitland** [comment] 2016-02-26 21:08
@maynardflies Please provide a working example of your problem. You can use the `MinimalExample`, it only targets `.Net 4.0`, so you can use `VS2012`.

https://github.com/cefsharp/CefSharp.MinimalExample

If your happy with your alternate solution the go ahead and close this.

**Comment by amaitland** [comment] 2016-02-26 21:09
Also remember `Visual Studio 2013 Community Edition` is free for small business and **open source** projects, same goes for the `2015` edition.

**Comment by maynardflies** [comment] 2016-02-26 21:10
Understood, I am asking my corporate helpdesk to allow me to install VS2015CE, at the moment I’m blocked

**Comment by amaitland** [comment] 2016-02-26 21:52
> Understood, I am asking my corporate helpdesk to allow me to install VS2015CE, at the moment I’m blocked

Great :+1: 

For completeness can you post the code for your bound object.

**Comment by maynardflies** [comment] 2016-02-26 21:56
I'm not entirely able to do so as there is business specific code interspersed in that object.  Right now, however, the object consists of one method with the signature posted, as well as a default constructor and a serialization constructor

**Comment by amaitland** [comment] 2016-02-26 21:58
> I'm not entirely able to do so as there is business specific code interspersed in that object. Right now, however, the object consists of one method with the signature posted, as well as a default constructor and a serialization constructor

That's not enough for me to look into this further. Report back when you have something :+1: 

See https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Resources/BindingTest.html for examples you can use for testing when compiling from source.

**Comment by RichardGrundy** [comment] 2016-02-29 11:49
I just want to add a note here. We have been having the same problem but only on a machine with McAfee Anti-virus installed. When we removed McAfee the problem ceased. Can anyone shed light on how we sort this problem out and run CEF with managed C# object and avoid McAfee messing with this?

**Comment by amaitland** [comment] 2016-02-29 21:45
> using RegisterAsyncJsObject appears to work, the method on the .NET side gets called correctly.

@RichardGrundy Switching to `RegisterAsyncJsObject` means only the native `IPC` is used, for the standard version `WCF` is used for communication. Also set `CefSharpSettings.WcfEnabled = false` to make sure that `WCF` is never started.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp/CefSharpSettings.cs#L25

**Comment by maynardflies** [comment] 2016-03-03 17:09
@RichardGrundy That's an interesting point.  We also use McAfee here as a corporate antivirus, and we are obviously not able to disable it.  Are there known issues with WCF and McAfee having interaction issues?

**Comment by codeinternals** [comment] 2016-03-05 11:56
I'm having the same issue and if i try to access the bound object via the dev tools console i get this error

    
```
Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.

(anonymous function)	@	VM146:2
InjectedScript._evaluateOn	@	VM56:875
InjectedScript._evaluateAndWrap	@	VM56:808
InjectedScript.evaluate	@	VM56:664
```

it works fine when i use `RegisterAsyncJsObject` reproducing the problem is pretty simple 

```
using System.Windows.Forms;
using CefSharp;
using CefSharp.WinForms;


namespace TestApplication
{
    public class CallbackObjectForJs
    {
        public void Test(string msg)
        {
            MessageBox.Show(msg);
        }
    }

    public partial class MainForm : Form
    {
        public ChromiumWebBrowser browser;
        public CallbackObjectForJs callback = new CallbackObjectForJs();

        public MainForm()
        {
            InitializeBrowser();
            InitializeComponent();
        }

        public void InitializeBrowser()
        {
           Cef.Initialize(new CefSettings());

           browser = new ChromiumWebBrowser("http://dev.local/remote_test");
           browser.RegisterJsObject("TestObject", callback);
            
           this.Controls.Add(browser);
           browser.Dock = DockStyle.Fill;
           browser.IsBrowserInitializedChanged += Browser_IsBrowserInitializedChanged;
        }

        private void Browser_IsBrowserInitializedChanged(object sender, IsBrowserInitializedChangedEventArgs e)
        {
            if (e.IsBrowserInitialized)
            {
                browser.ShowDevTools();
            }
        }
    }
}
```

I'm using **Windows 10**

**Comment by amaitland** [comment] 2016-04-07 07:30
As this is outside of the control of `CefSharp`, I'm closing this. If anyone happens to contact the `AV` developer to find out more information then be all means comment. The workaround for now is to use `async` version (It's faster than the regular version, so it's probably preferably as the default regardless).

**Closed by amaitland** 2016-04-07 07:30 UTC

**Comment by kaido42** [comment] 2016-04-07 19:15
We have found a similar problem. Actually, it looks like exactly the same issue. Out of several thousand installations in the wild we've seen one before, and now I'm trying to debug another one.

The problem does not happen in my development box, despite having McAfee installed. And the latest case I looked at, is Windows 10 build 10240 box, *without* any McAfee products installed. So I'm not sure this has something to do with McAfee .. 

For us the RegisterAsyncJsObject() is not a solution (at least in short run), as we have quite a lot of JS code depending on current implementation ..

**Comment by amaitland** [comment] 2016-04-07 21:35
> The problem does not happen in my development box, despite having McAfee installed. And the latest case I looked at, is Windows 10 build 10240 box, without any McAfee products installed. So I'm not sure this has something to do with McAfee ..

It would appear they're still factors outside the control of `CefSharp`, possibly environmental, possibly a `.Net` framework issue. There have been other issues in the past #915. Personally I'd like to upgrade to `.Net 4.5` which **may** improve the situation, though there is some objection #1572

> For us the RegisterAsyncJsObject() is not a solution (at least in short run), as we have quite a lot of JS code depending on current implementation ..

The `WCF` implementation is one of those that I look back at and wish I'd never finished. If it wasn't the incumbent implementation then I'd be removing it. I'm hoping that `ES6` will bring a fancy new feature that will allow for a simpler migration path, if it's possible, the `RegisterJsObject` function will be deprecated.
