### ISSUE TITLE
User Defined Breakpoint issue in BrowserSubProcess

### ISSUE THREAD

**Issue by RadicalLinux** [cefsharp/CefSharp#745] opened 2015-01-15 17:43 UTC
When drawing on a html 5 canvas I receive the following at a certain point.  Not sure what is being called as it doesn't give any more information than that currently.  This is most likely an upstream issue.  Just documenting here for future info

http://prntscr.com/5stty4

**Comment by amaitland** [comment] 2015-01-16 00:20
`CEF` version?

**Comment by RadicalLinux** [comment] 2015-01-16 01:20
Sorry about that, Cef/2171 branch

**Comment by amaitland** [comment] 2015-01-16 02:25
I'm planning on upgrading `cef/2171` to `CEF 3.2171.1972` sometime over the next week, so might be worth testing again after that.

**Comment by jankurianski** [comment] 2015-01-16 02:30
User-defined breakpoint sounds like an assertion failure in CEF, so I think you are right about it being an upstream problem.

Can you reproduce this with the `Test App` from http://cefbuilds.com/ (they have one for CEF 3.2171.1949, under `More Revisions`)?  Run `cefclient.exe` with the following parameters to match CefSharp `WinForms` or 'WPF' behaviour (you haven't said which you are using):
https://github.com/cefsharp/CefSharp/blob/master/CONTRIBUTING.md#cefsharp-vs-cef

**Comment by RadicalLinux** [comment] 2015-01-16 02:32
I am using winforms, but it really shouldn't matter since this is the browsersubprocess which is separate.  I've not tried with cefclient.exe yet. I believe it may be a memory issue as the canvas has approximately 60,000 rect objects drawn.

**Comment by amaitland** [comment] 2015-01-16 04:45
> but it really shouldn't matter since this is the browsersubprocess which is separate

Just for clarity the browser sub process does the rendering, and `WinForms` uses different rendering to `WPF`.

**Comment by RadicalLinux** [comment] 2015-01-16 04:50
But isn't the BrowserSubProcess the stand alone (exe) that runs separate to the actual control?  Since it's what is processing what the server returns before displaying wouldn't that not be dependent on wpf or winforms?  I would expect the actual control to throw the error if it was an issue displaying.

**Comment by amaitland** [comment] 2015-01-16 05:11
> But isn't the BrowserSubProcess the stand alone (exe) that runs separate to the actual control? Since it's what is processing what the server returns before displaying wouldn't that not be dependent on wpf or winforms? I would expect the actual control to throw the error if it was an issue displaying.

The browser sub process does the rendering, and that rendering can happen in one of two different ways, `Standard` and `OSR`. If you were using `WPF` and needed to compare using `cefclient`, you'd need to tell it that you were using `OSR` mode for an accurate comparison. Since your using `WinForms`, you can just ran `cefclient` as per normal.

**Comment by RadicalLinux** [comment] 2015-01-16 05:13
Okay, so in my case it was doing Standard Rendering when the issue was encountered.

**Comment by amaitland** [comment] 2015-01-16 05:17
Correct :+1: 

If the problem occurs in the `Test App(cefclient.exe)` it would be worth trying the `Test App` for a newer version like `3.2171.1972` in the hopes that it's been resolved.

**Comment by amaitland** [comment] 2015-01-23 01:05
@RadicalLinux  New version based on `cef 3.2171.1972` is out if your interested.

**Comment by RadicalLinux** [comment] 2015-01-23 01:12
I've grabbed it and will be taking a look.  I've worked around it by creating a png with php and then displaying.  But I'll test with HTML5 canvas.  Thanks!

**Comment by amaitland** [comment] 2015-01-30 05:12
@RadicalLinux Newer version resolve the issue?

**Comment by RadicalLinux** [comment] 2015-01-30 12:41
I'm on vacation so haven't got to try yet, will this next week

**Comment by amaitland** [comment] 2015-01-31 06:40
No prob, enjoy the vacation!

**Comment by amaitland** [comment] 2015-03-18 11:56
@RadicalLinux Any feedback on this one?

**Comment by amaitland** [comment] 2015-04-08 04:15
Unsure if this has been resolved. Closing for now. Reopen if required.

**Closed by amaitland** 2015-04-08 04:15 UTC
Labels: more-details-needed-from-op
