### ISSUE TITLE
Hide artifacts from VS Solution Explorer in new CsProj format

### ISSUE THREAD

**Issue by mscrivo** [cefsharp/CefSharp#2456] opened 2018-07-13 14:33 UTC
- **What version of the product are you using?**
CefSharp.OffScreen 65.0.0 from nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **What steps will reproduce the problem?**
Create a new .net core console app, or even a .net framework app but using the new CsProj format

- **What is the expected output? What do you see instead?**
Solution explorer in VS 2017 15.7.5 is showing all the CefSharp artifacts (see below)

- **Please provide any additional information below.**
![image](https://user-images.githubusercontent.com/275524/42697070-1749a092-8688-11e8-982a-31c74b639f52.png)

I've been trying various versions of the hacks listed here: https://github.com/NuGet/Home/issues/4856#issuecomment-404716672 to no avail.  Any idea how to hide these artifacts from view?

**Comment by amaitland** [comment] 2018-07-13 21:13
That's my only suggestion, if that didn't work then you'll have to continue following up with Microsoft.

For reference the Nuget package files are https://github.com/cefsharp/CefSharp/tree/cefsharp/65/NuGet

**Comment by mscrivo** [comment] 2018-07-13 21:41
ah @amaitland, didn't realize you were on the CefSharp team when you posted in that other thread.  Thanks for your help.

**Comment by amaitland** [comment] 2018-07-17 10:59
Restructuring the packages to use `<Content/>` instead of `<None/>` would resolve this, there are some advantages and disadvantages of doing this.

- `None` doesn't seem to work for `ClickOnce` like I had hoped (Haven't tested, just basing this on user report)
- 'None' supports copying files to referenced projects (Adding `CefSharp` to a class library will copy to a referencing project as well).
- `Content` appears to support the newer project format.
- `Content` doesn't allow for setting `CopyToOutputDirectory`

https://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory/30316946#30316946

Either way `MS` should probably fix the newer project format to exclude `None` items or honour a `Visible` attribute.

**Comment by DaZiYuan** [comment] 2019-09-26 03:22
I have deal with similar problem in other project. resolved by ContentWithTargetPath.

for example
```
<ContentWithTargetPath Include="$(MSBuildThisFileDirectory)CEFSharpDLL\**"
                           TargetPath="\%(Filename)%(Extension)"
                           CopyToOutputDirectory="PreserveNewest" />
```

**Comment by phdjonov** [comment] 2019-10-08 22:47
Hacking the `.target` files to include a `<Visible>false</Visible>` property in the `<None/>` elements seems to work well in recent versions of VS2019 (seems to leave behind "empty" `locales` and `swiftshader` folders, but that's minor compared to the clutter we otherwise get).

**Comment by Telavian** [comment] 2019-10-13 03:45
This issue is horrendous. Makes a clean solution hideous to look at.

**Comment by amaitland** [comment] 2019-10-14 09:50
Firstly this issue isn't `CefSharp` specific, it's been over a year since anyone followed up with `Microsoft` at https://github.com/NuGet/Home/issues/4856 If `Microsoft` confirm they aren't ever going to fix the issue then we'll look at restructuring. The older style `project format` still works as expected, so historically this worked fine.

---
Secondly you can specify a subfolder to copy the libraries to, an example would look something like:

Add `<CefSharpTargetDir>WhateverFolderYouLike</CefSharpTargetDir>` to the first `<PropertyGroup>` in your project (e.g. .csproj file). In the below example we'll use the `cefsharp` folder.
```
<PropertyGroup>
  <CefSharpTargetDir>cefsharp</CefSharpTargetDir>
</PropertyGroup>
```

Add `<probing privatePath="cefsharp"/>` to your app.config as outlined in https://msdn.microsoft.com/en-us/library/4191fzwb.aspx

```
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <probing privatePath="cefsharp"/>
    </assemblyBinding>
</runtime>
```

---

**Comment by amaitland** [comment] 2019-10-14 09:53
In the short term if someone would like to submit a `PR` that sets `<Visible>false</Visible>` to false then by all means do so. (Please target the `PR` against `master`)

**Comment by amaitland** [comment] 2019-11-03 03:15
The `<None/>` entries are now set to `<Visible>false</Visible>`. There's still a stray `.` folder that contains `locales` and `swiftshader` folders. Someone should probably follow that up with `Microsoft` as that seems like an unexpected behaviour. The change is in `75.1.143` as is now on `Nuget.org`

I will look at creating a newer set of packages that better support `PackageReference` format, see
https://github.com/cefsharp/CefSharp/issues/2795

**Closed by amaitland** 2019-11-03 03:15 UTC
Labels: pr-rejected
