### ISSUE TITLE
CefSharp.Wpf Can‘t support other Input Method

### ISSUE THREAD

**Issue by willent** [cefsharp/CefSharp#583] opened 2014-11-10 10:45 UTC
cef version:33.0.1750 r1738 cefsharp version 33.0.2.0
CefSharp.Wpf it is unable to input any Chinese。

**Comment by ssdyz** [comment] 2015-03-30 10:58
Is this problem solved? Very worried, please do me a favor, thank you

**Comment by amaitland** [comment] 2015-03-30 11:21
Updating link to cef bitbucket site https://bitbucket.org/chromiumembedded/cef/issue/1019

Issue is still unsolved, you can try the workaround proposed above.

**Comment by ralphmayr** [comment] 2015-04-09 08:42
I created a PR that contains the fix proposed in this issue - as mentioned before, I'm confident that this fixed the issue for most cases.
We'd be very grateful if this would make it into the next CefSharp release ;)

**Comment by amaitland** [comment] 2015-07-27 03:36
So the upstream issue has been marked as closed
https://bitbucket.org/chromiumembedded/cef/issues/1019

Anyone care to take the current `master` for a spin and see how it goes? (Will of course have to comment out https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf.Example/Views/BrowserTabView.xaml.cs#L30)

**Comment by amaitland** [comment] 2015-08-26 21:35
I've removed the workaround from `master` see https://github.com/cefsharp/CefSharp/commit/c7c90581da7ed3dda80fd8304a856462d133d9a7

As the `upstream` issue has been resolved I'm closing this. (If someone can still reproduce the problem with latest `master` then this can be reopened).

**Comment by luciusli** [comment] 2015-09-04 04:36
I can still reproduce this problem. FYI cefclient build 2454 from cefbuilds.com works flawlessly.

**Comment by amaitland** [comment] 2015-09-04 04:40
> FYI cefclient build 2454 from cefbuilds.com works flawlessly.

Just confirming that you ran `cefclient` with the `--off-screen-rendering-enabled` command line argument?

**Comment by luciusli** [comment] 2015-09-04 04:45
I didn't but if run with that argument, the character selection box is misaligned.

**Comment by amaitland** [comment] 2015-09-04 04:50
`WPF` uses `off screen rendering`, without that argument it behaves like the `WinForms` version.

If the problem still persists then someone with a vested interest in `IME` will have to troubleshoot the issue.

**Comment by amaitland** [comment] 2015-09-20 11:56
Looks like the problem still exists, rather than multiple issues, closing this one in favor of  #1262

**Closed by amaitland** 2015-09-20 11:56 UTC
Labels: upstream
