### ISSUE TITLE
Hard Crash: FATAL:hwnd_util.cc(65)] : The parameter is incorrect. (0x57)

### ISSUE THREAD

**Issue by robertdeml** [cefsharp/CefSharp#2378] opened 2018-05-01 14:32 UTC
- **What version of the product are you using?**
NuGet: CefSharp.WinForms 63.0.3 and all dependencies

- **What architecture x86 or x64?**
x86

- **On what operating system?**
Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
WinForms

- **What steps will reproduce the problem?**
The program opens a winform panel with a ChromiumWebBrowser set to www.google.com.
The panel is cleared and the web browser is disposed.
The panel is populated with a new ChromiumWebBrowser set to www.google.com.
Repeat this and eventually the appliction crashes.

- **What is the expected output? What do you see instead?**
Expected: see the google page.
Actual: I see a Win10 dialog that the application has stopped working. "A problem caused the program to stop working correctly.  Windows will close the program and notify you if a solution is available."

- **Please provide any additional information below.**
The Output Panel in Visual Studio has this:
[0501/100214.314:FATAL:hwnd_util.cc(65)] : The parameter is incorrect. (0x57)
The program '[15972] Application.exe' has exited with code 1073741855 (0x4000001f).

The file Debug.log from the bin folder has this:
[0501/100209.058:WARNING:angle_platform_impl.cc(51)] rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(30,8-58): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(35,8-28): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

[0501/100212.560:WARNING:angle_platform_impl.cc(51)] rx::HLSLCompiler::compileToBinary(228): 
C:\fakepath(48,8-58): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
C:\fakepath(53,8-28): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them

[0501/100214.314:FATAL:hwnd_util.cc(65)] : The parameter is incorrect. (0x57)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
This application uses custom user controls that are disposed and created when the user clicks on different parts of the application.  My guess is that the ChromiumWebBrowser is not use to being disposed and created quickly.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
    - To compare with WinForms run cefclient --multi-threaded-message-loop
This error does not occur.
    - Please include the version you tested with e.g. cef_binary_3.3359.1769.gd0bfc4d_windows32_client.tar.bz2

**Comment by michaelkhalsa** [comment] 2018-05-01 22:56
Hi, on the recent release (from nuget without prerelease checked a few hours ago)
cef.redist.x64.3.3239.1723
it crashes as soon as touched,
 If Not CefSharp.Cef.IsInitialized …

Even touching it here first
CefSharp.Cef.EnableHighDPISupport()
will crash.

Previous versions work fine.
Windows 10 build 1803
win forms .net 4.6.1
Visual C++ 2013, 2015 installed
All dependcy files installed

**Comment by michaelkhalsa** [comment] 2018-05-02 00:17
Problem solved. The version of cef.redist.x64 on nuget v 3.3325.1758 (without prerelease checked) that shows up as updates available in nuget, is not compatible with 63.03 common/ I uninstalled all cefsharp packages, reinstalled to 3239.1723, Clean, Rebuild (necessary), and working again.

**Comment by amaitland** [comment] 2018-05-02 04:42
@robertdeml Can you test with `65.0.0-pre01` when you have a chance. If you can reproduce the problem with `65.0.0-pre01` can you fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an example that reproduces your problem. If you can use a `Timer`, or similar to automate the process that would be helpful. 

Have you tested with different hardware? `hwnd_util.cc` looks like it's part of the `GFX` lib, so could easily be related to the `GPU` you are using

> My guess is that the ChromiumWebBrowser is not use to being disposed and created quickly.

Typically the only problem with `Disposing` of a `ChromiumWebBrowser` instance quickly is occasionally the `BrowserSubProcess` doesn't close. 

> Please include the version you tested with e.g. cef_binary_3.3359.1769.gd0bfc4d_windows32_client.tar.bz2

You've tested with the same build that `65.0.0-pre01` is based, `63.0.3` is based on `3.3239.1723.g071d1c1`

My initial thoughts are this will need an updated version of `CEF/Chromium` to resolve, so marking as `upstream` for now. I've not seen any similar reports.

**Comment by amaitland** [comment] 2018-06-10 23:15
Closing due to lack of feedback

**Closed by amaitland** 2018-06-10 23:15 UTC
Labels: upstream

**Comment by medoni** [comment] 2020-06-30 08:11
I having the same issue with 75.1.143.0. 
32Bit, Visual Studio 2019 Debug.

> This application uses custom user controls that are disposed and created when the user clicks on different parts of the application. My guess is that the ChromiumWebBrowser is not use to being disposed and created quickly.

Same here. After closing a modal WinForm Window(CefSharp is used as HtmlEditor), the application crashes with `[0630/092217.734:FATAL:hwnd_util.cc(64)] : Falscher Parameter. (0x57)`On different computers with same hardware (eg. Graphics card).

**Comment by pjaffe** [comment] 2021-02-16 23:00
I am intermittently encountering this as well.

Standard out has the following (the application using CefSharp is called "Oasis"):
```[0216/175211.566:FATAL:hwnd_util.cc(62)] : The parameter is incorrect. (0x57)
The program '[28800] Oasis.exe' has exited with code -2147483645 (0x80000003).```

Using CefSharp.WinForms 83.4.20.0 inside a WPF application.  The WinForms component is used instead of CefSharp.Wpf, because of an unexpected Mouse event that was undermining behavior of a 3rd party web app being hosted inside the CefSharp browser.

This issue is definitely intermittent for me, and I haven't been able to pin down a reproducible case.  But it did seem to start occurring after an explicit `Dispose()` call was added to the CefSharp.WinForms ChromiumWebBrowser object.

I'll give some more thought to whether this issue should be Reopened, or a new issue created.  I'm not familiar with the preferred protocol on that.  And, unfortunately, I don't have an isolated repeatable test case.

**Comment by amaitland** [comment] 2021-02-16 23:55
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17814 has a related discussion. Perhaps this will give you some insight. The source is there if you wish to do some debugging. 

This issue can be reopened if the following two conditions are met:

- The problem reproduces with the current version, at time of writing that's version 87.
- An example that reliably reproduces the problem is provided. 
 
As it stands there isn't anything actionable without an example. 

Make sure you are calling Dispose on the UI thread.

**Comment by pjaffe** [comment] 2021-02-17 19:24
@amaitland - thanks for the quick acknowledgement of my comment on this old/closed issue.  I incremented to v87 and was still able to reproduce the intermittent issue.  I believe the following in our code ensures Dispose is called on the UI thread:

```
if (webBrowserForCPQ.Handle != IntPtr.Zero)
{
	webBrowserForCPQ.BeginInvoke(new Action(() => webBrowserForCPQ.Dispose()));
}
```

Due to competing priorities, I had to take the easiest path for now, which was to just avoid instantiating the `CefSharp.WinForms.ChromiumWebBrowser` in the only scenario we have been able to reproduce the problem under so far.  This is a situation where our logic path instantiated (via WPF xaml markup) an instance, but then ran some code paths without user interaction, and immediately disposed the control within 1-3 seconds.

Now, rather than always constructing the `ChromiumWebBrowser` via WPF xaml markup, we programmatically construct it via `new ChromiumWebBrowser(url)` only when there will actually be user interactions with it.  We are crossing our fingers that this intermittent crash won't manifest under this mode of use, and are hoping that is reinforced by the previously stated hunch:

> My guess is that the ChromiumWebBrowser is not use to being disposed and created quickly.

Thanks again!

**Comment by michaelkhalsa** [comment] 2021-02-18 04:26
Hi @pjaffe ,

I have a large mixed winforms and wpf application (mostly on winforms), however only use chromium within a winforms container. I use it in several dozen places for formatting interactive help, previews (rapidly reloaded), and to host third party processes with external javascript. I might have half a dozen instances open at any one time (with changing content) on various tabs, including a few that only stay open for a relatively short duration, and are fairly rapidly created and disposed. 

I had some difficult (impossible) to find occasional intermediate crashes, which I could not pin down, which I suspect were from chromium, as it is the only process left in my app that creates its own separate UI threads, along with the hallmark of vanishing UI, even without any user interaction for some time.

I solved it by carefully making sure that message buses, events, etc., (particularly in legacy code processes and rew2riting some of these) were all handled on correct threads in the UI, and making super sure that anything that was touched by a chromimum event (such as the various events loaded from chromium) were on the correct thread. I also defensively checked for IsDispose and handle creation both before invoking to the correct thread and after (wrapping in try catch as well) (taking care of any race conditions). Like you, I also standardized a few components for typical use cases, however not for all cases.

For me, this solved it.

Another area I suspected, was possible cross handling of events from different instances of chromium open at the same time (through their sub processes), including a chromium instance  being used by another program., or another instance of my program. I do not recall the steps I took, other than following best practices - and uploading to latter versions. I would not think that this would be possible, but their was some evidence for it. This was a couple years ago, and there is no longer any evidence of it.

Apologies that above is all a bit vague, however, by carefully examining my code base and updating legacy event handling in combination with careful use of chromium - I am happy to say that this is no longer an issue for me.

**Comment by pjaffe** [comment] 2021-02-18 14:48
@michaelkhalsa - thanks for taking the time to write up those additional thoughts and your encouraging statement of eventually reaching stability.  I do wonder if the `CefSharp.WPF` library is less susceptible to this, or if the same challenges would exist there too.  Regardless, that isn't an option for us at the moment, due to an issue with the 3rd party web app we are loading into it.
