### ISSUE TITLE
OffScreen - Downloadhandler methods not fired

### ISSUE THREAD

**Issue by Lenwe666** [cefsharp/CefSharp#3132] opened 2020-05-18 17:32 UTC
- **What version of the product are you using?**
    last stable (81.3.2)

- **What architecture x86 or x64?**
    both
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
     OffScreen
    
- **What steps will reproduce the problem?**
    Create a console app
    Initialise CEF with all necessary parameters
    Create downloadhandler class
    Create offscreen browser and set browser settings
    Attach download handler to browser
    Load url directly to zip to download
    (breakpoint on downloadhandler methods aren't reached)
    
    program.cs (https://pastebin.com/PpHyHQu8)
    DownloadHandler.cs (https://pastebin.com/4988zkzR)
    OffScreenBrowsering.cs (https://pastebin.com/R5vSctef)    

- **What is the expected output? What do you see instead?**
    that the methods of the downloadhander are reached and the file is downloaded

**Comment by amaitland** [comment] 2020-05-18 19:55
Did you check the log file?

**Comment by amaitland** [comment] 2020-05-18 21:29
> If code is required to reproduce your problem then please provide one of the following
> - Fork the MinimalExample and push your changes to GitHub (this is the preferred option).

As per the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) please fork the `MinimalExample` and provide an example, you can use the https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81 branch to test out the `v81.3.20-pre` release (there is no stable `81` release yet).

Please only include the **minimum** changes required to reproduce your problem.

Marking as `unable to reproduce` as `DownloadHandler` is working as expected using https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/81

**Comment by amaitland** [comment] 2020-05-18 21:37
Simply adding a download handler in https://github.com/cefsharp/CefSharp.MinimalExample/commit/0128ab860585b73726e4a5a90dc0b1b8ba1d3a30 to the https://github.com/cefsharp/CefSharp.MinimalExample/tree/demo/3132 branch and everything works as expected.

**Comment by Lenwe666** [comment] 2020-05-19 08:37
Hi,

I was able to reproducte the problem with the minimal example. I've then noticed that, when loading the URL with the zip-file, my request is forwarded to our loadmanager system (also our authentication). 
I've then tried with a zip-file on a simple webpage and there the downloadhandler is triggered (both in my application as the minimal example). 

So the problem doesn't exist in CefSharp. Thanks for the quick and clear response! you rock!

(below question maybe needs another issue post?)
I've also noticed that the ChromiumWebBrowser.LoadString(string html, string url) isn't available anymore in the version post 71.0.2. I use this for the following:

1) load url
2) get source
3) parse/modify DOM
4) load modified dom in webbrowser (<- so here)

Why is this function removed and is there another solution for what I'm trying?

**Comment by amaitland** [comment] 2020-05-21 05:56
For reference you can call [IBrowserHost.StartDownload](http://cefsharp.github.io/api/79.1.x/html/M_CefSharp_IBrowserHost_StartDownload.htm) to trigger a download of content types that normally would be displayed in the browser.

> I've also noticed that the ChromiumWebBrowser.LoadString(string html, string url) isn't available

It was removed `upstream` in https://bitbucket.org/chromiumembedded/cef/issues/2586/loadstring-results-in-terminating-renderer as `Chromium` changes left it practically unusable.

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream for a list of options for loading `Html` directly in the browser.

> * load url
> * get source
> * parse/modify DOM
> * load modified dom in webbrowser (<- so here)

This really isn't the approach I'd recommend. You'd be better off intercepting the request, getting the response, making the changes then continuing the response. 

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#loading-htmlcssjavascriptetc-from-diskdatabaseembedded-resourcestream

Alternatively you can rewrite the data using a `IResponseFilter` see https://github.com/cefsharp/CefSharp/wiki/General-Usage#response-filtering

Closing as this isn't a bug in `CefSharp`.

**Closed by amaitland** 2020-05-21 05:56 UTC
Labels: unable-to-reproduce

**Comment by Lenwe666** [comment] 2020-07-31 13:12
Hi Alex,

I like to come back to this. I’ve tried setting up a response filter by the example of https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Example/Filters/FindReplaceResponseFilter.cs
The problem now is that this filter is loading the data in chunks of 64kb. I need to make changes to the DOM, but that isn’t possible (the first chunk succeeds, but the second chunk doesn’t because there is no <html> tag, so I can’t traverse).  If is use the Reponse filter example on the page https://github.com/cefsharp/CefSharp/wiki/General-Usage#Response%20Filtering I get the full stream but can’t edit the reponse (readonly)

Is there an method/way where I can have the full response and edit that?

I looked for the other example you send me (for direcrly loading the HTML in browser) but that is only from disk/database or stream. Also I see now link for “This really isn't the approach I'd recommend. You'd be better off intercepting the request, getting the response, making the changes then continuing the response” is the same as above (loading html directly in browser). Can you provide me

Met vriendelijke groeten,
Joris Notterdaeme

[cid:image001.png@01D6674B.ABF470A0]<http://www.360it.be/>

Kortrijksesteenweg 205 bus 4 – 9830 Sint-Martens-Latem
T +32 (0) 9 283 06 90 – www.360it.be<http://www.360it.be/>
jn@360it.be<mailto:jn@360it.be> - support@360it.be<mailto:support@360it.be> - sales@360it.be<mailto:sales@360it.be>
The content of this email should be treated as confidential and is intended for the recipient(s) specified in message only.
If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by amaitland** [comment] 2020-07-31 20:46
https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Example/Filters/ExperimentalStreamResponseFilter.cs#L127
https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Example/FlashResourceHandler.cs

**Comment by Lenwe666** [comment] 2020-08-12 15:12
Hi Alex,

Thanks for the links. Unfortunatly the ExpirementalStreamResponseFilter also get the data in chunks so I can’t edit the DOM. I’ve modified the FlashResourceHandler example to my usage and there I can get the full response at once (yaay). But aside of editing the DOM, I also need to extract data from it and pass them to my ViewModel as object. This is not possible with the FlashResourceHandler as this is added before the Cef.initialize and thus acting for all requests of that scheme (unlike the filter, wich you attach at a ChromiumBrowser directly (from within the ViewModel)).

Kind regards,
Met vriendelijke groeten,
Joris Notterdaeme

[cid:image001.png@01D670CB.89D26F70]<http://www.360it.be/>

Kortrijksesteenweg 205 bus 4 – 9830 Sint-Martens-Latem
T +32 (0) 9 283 06 90 – www.360it.be<http://www.360it.be/>
jn@360it.be<mailto:jn@360it.be> - support@360it.be<mailto:support@360it.be> - sales@360it.be<mailto:sales@360it.be>
The content of this email should be treated as confidential and is intended for the recipient(s) specified in message only.
If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by amaitland** [comment] 2020-08-12 19:33
> Unfortunatly the ExpirementalStreamResponseFilter also get the data in chunks so I can’t edit the DOM

You can if look closer as it buffers all data then you can modify the response data as per the link I provided already https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Example/Filters/ExperimentalStreamResponseFilter.cs#L127

> thus acting for all requests of that scheme (unlike the filter, wich you attach at a ChromiumBrowser directly (from within the ViewModel)).

https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-interception

**Comment by Lenwe666** [comment] 2020-08-13 10:09
Hi Alex,

Thanks for the information. I’ve already tried you’re example and modified it in different ways but it always get the data in chunks for large pages (90% of the pages I need). No matter where I call the ReplaceTextInBufferedData, the data I get isn’t complete and the IResponseFilter.Filter get called a second time.

It also states in the comments above that it’s not production tested:

//The assumption here is dataIn is smaller than dataOut then this will be the last of the
//data to read and we can start processing, this is not a production tested assumption


For now if found a way to use the CefShar 75.1.143 (by using another method to post data than with a custom resource handler) so I can keep using the Browser.LoadString method untill I find a working solution.

I would like to thank you for your patience, the support and feedback given feedback!

Kind regards,
Met vriendelijke groeten,
Joris Notterdaeme

[cid:image004.png@01D22BA0.DDAA6860]<http://www.360it.be/>

Kortrijksesteenweg 205 bus 4 – 9830 Sint-Martens-Latem
T +32 (0) 9 283 06 90 – www.360it.be<http://www.360it.be/>
jn@360it.be<mailto:jn@360it.be> - support@360it.be<mailto:support@360it.be> - sales@360it.be<mailto:sales@360it.be>
The content of this email should be treated as confidential and is intended for the recipient(s) specified in message only.
If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.


Van: Alex Maitland <notifications@github.com>
Verzonden: woensdag 12 augustus 2020 21:34
Aan: cefsharp/CefSharp <CefSharp@noreply.github.com>
CC: Joris Notterdaeme | 360IT <jn@360it.be>; Author <author@noreply.github.com>
Onderwerp: Re: [cefsharp/CefSharp] OffScreen - Downloadhandler methods not fired (#3132)

Deze mail komt van buiten 360IT. Help onze organisatie en partners veilig te houden. Het is aan ons; denk vooraleer je klikt!


Unfortunatly the ExpirementalStreamResponseFilter also get the data in chunks so I can’t edit the DOM

You can if look closer as it buffers all data then you can modify the response data as per the link I provided already https://github.com/cefsharp/CefSharp/blob/cefsharp/83/CefSharp.Example/Filters/ExperimentalStreamResponseFilter.cs#L127

thus acting for all requests of that scheme (unlike the filter, wich you attach at a ChromiumBrowser directly (from within the ViewModel)).

https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-interception
