### ISSUE TITLE
Changing the browser url after the loaded url is successful cause the Cefsharp to freeze and goes into breakpoint

### ISSUE THREAD

**Issue by Daszbin** [cefsharp/CefSharp#2554] opened 2018-10-29 22:49 UTC
- I am using Cefsharp for Winforms x86 build running on Windows 10.
    - I am using Cefsharp build 70.0.0-CI2816 for Winforms.
- The issue is when I start up the process of the browser running Cefsharp after loading the homepage successfully if the user wants to go to a different website Cefsharp just freezes as well as visual studio 2017. When finally the breakpoint is shown it reveals it has something to do with libcef.pdb and also logging.cc be missing however this has only happened recently with the newest version on Myget. With using version 70.0.0-CI2811 and prior to that build there have been no issue that has occurred even with logging being configured. So after build 70.0.0-CI2811 that’s when issues started occurring.

- **What architecture x86 or x64?**
x86

- **On what operating system?**
    - Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
Winforms

- **What steps will reproduce the problem?**
I recommend looking into chrome_elf.dll and libcef.dll with user requested changes to the browser addresses changing.
    

- **What is the expected output? What do you see instead?**
My expected output is to prevent this from happening because it slows down the browser and eats a lot of cpu memory. Even with the browser preferences have the gpu disabled.
- A stack trace if available, any Exception information.
Breakpoint brings up logging.cc and also in another instance says libcef.pdb is missing I know why it’s missing because it’s to big to distribute through Nuget it’s about 1.25 GB in size when downloaded from debug and or release symbols from Cef files located at opensource.spotify.com

```
[1029/194651.049:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegin failed with: 8
[1029/194735.882:INFO:CONSOLE(1)] "[bugsnag]", source: https://d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js (1)
[1029/194740.399:WARNING:mediasession.cc(356)] Duplicate id found. Reassigning from 104 to 127
[1029/194740.406:WARNING:mediasession.cc(356)] Duplicate id found. Reassigning from 106 to 125
[1029/194740.406:WARNING:mediasession.cc(356)] Duplicate id found. Reassigning from 103 to 124
[1029/194740.406:WARNING:mediasession.cc(356)] Duplicate id found. Reassigning from 105 to 123
[1029/194745.010:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20181024/r20180604/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/194820.599:WARNING:url_request_job_manager.cc(90)] Failed to map: chrome-extension://invalid/
[1029/194820.645:WARNING:url_request_job_manager.cc(90)] Failed to map: chrome-extension://invalid/
[1029/194821.195:INFO:CONSOLE(95)] "Using native MSE as-is.", source: https://shaka-player-demo.appspot.com/lib/polyfill/mediasource.js (95)
[1029/194821.220:INFO:CONSOLE(36)] "Using native VTTCue.", source: https://shaka-player-demo.appspot.com/lib/polyfill/vttcue.js (36)
[1029/194821.226:INFO:CONSOLE(161)] "Registering service worker.", source: https://shaka-player-demo.appspot.com/demo/main.js (161)
[1029/194821.372:INFO:CONSOLE(1510)] "It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior.", source: https://shaka-player-demo.appspot.com/lib/media/drm_engine.js (1510)
[1029/194821.716:INFO:CONSOLE(164)] "Service worker registered!", source: https://shaka-player-demo.appspot.com/demo/main.js (164)
[1029/194847.626:WARNING:spdy_session.cc(3105)] Received HEADERS for invalid stream 1
[1029/200149.808:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:codernut

[1029/200149.855:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:codernut

[1029/200149.855:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:test

[1029/200150.748:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegin failed with: 8
[1029/200151.500:ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.
[1029/200153.028:ERROR:widevine_loader.cc(382)] Widevine CDM registration failed; Missing file C:\Users\Daszbin\Music\New folder\New folder\Programs\Codernut-master\CoderNut-master\src\bin\Coder Nut\WidevineCdm\widevinecdm.dll
[1029/200209.907:INFO:CONSOLE(1)] "safeframe test Jun 30 14:37", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200209.945:INFO:CONSOLE(1)] "MOB inview code", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.048:INFO:CONSOLE(7)] "https://o.cmp.advertising.com/v3/se?et=di&en=&crid=402600&cpid=1C&e.crid=402600&e.plid=4778311&e.dgid=10646019&a.pid=369865&a.fid=10646019&a.cid=10630065&a.nid=5431&a.sid=1013212&a.bid=1&a.plid=4778311&a.aid=923846&1540857731049", source: https://ads.pictela.net/rm/lib/richmedia/adtechRichMediaLib_3_0_6.js (7)
[1029/200211.049:INFO:CONSOLE(1)] "MOB preInit adConfig", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.050:INFO:CONSOLE(1)] "CHECKING adBlockContainer CLASS: outeradcontainer", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.051:INFO:CONSOLE(1)] "RENDERED***************", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.055:INFO:CONSOLE(1)] "+++ AK in resizeWrappers", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.158:INFO:CONSOLE(1)] "+++ AK in resizeWrappers", source: https://ads-us.pictela.net/addyn/3.0/5431/4778311/1013212/0/ADTECH;apid=1A0aa4950a-dbd7-11e8-9a4a-d89d671a67c8;cfp=1;rndc=1540857727;AdId=10646019;BnId=-1;loc=100;target=_blank;misc=857727153;kvu.3rd-plc=msnusen15;kvu.3rd-creative=26497646;rmvars=%7B%22placementId%22%3A%20%22msnusen15%22%2C%20%22creativeId%22%3A%20%2226497646%22%7D;gdpr=0;euconsent=;rdclick=https://at.atwola.com/adlink/5113.1/3762118/0/2466/AdId=10597205;BnId=2;guid=1A0aa017a0-dbd7-11e8-93da-a0d3c101f574;itime=857727153;gdpr=0;impref=1540857727293658328;imprefseq=178744457116525744;imprefts=1540857727;adclntid=1002;link= (1)
[1029/200211.896:INFO:CONSOLE(1)] "initSpecial", source: https://ads.pictela.net/rm/ads/402600/27/core.min.js (1)
[1029/200211.896:INFO:CONSOLE(1)] "initWindowShopper", source: https://ads.pictela.net/rm/ads/402600/27/core.min.js (1)
[1029/200214.664:INFO:CONSOLE(7)] "https://o.cmp.advertising.com/v3/se?et=vi&en=&crid=402600&cpid=1C&e.crid=402600&e.plid=4778311&e.dgid=10646019&a.pid=369865&a.fid=10646019&a.cid=10630065&a.nid=5431&a.sid=1013212&a.bid=1&a.plid=4778311&a.aid=923846&1540857734663", source: https://ads.pictela.net/rm/lib/richmedia/adtechRichMediaLib_3_0_6.js (7)
[1029/200214.727:INFO:CONSOLE(42)] "document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.", source: https://ads.pictela.net/rm/ads/402600/27/maincontent.html (42)
[1029/200214.827:INFO:CONSOLE(136)] " [  0.000s] [studio.sdk] ", source: https://s0.2mdn.net/ads/studio/Enabler.js (136)
[1029/200216.197:INFO:CONSOLE(136)] " [  1.289s] [studio.sdk] Using default ad parameters in test environment. Simulating local events.", source: https://s0.2mdn.net/ads/studio/Enabler.js (136)
[1029/200218.253:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
[1029/200218.278:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
[1029/200218.752:INFO:CONSOLE(136)] " [  3.473s] [studio.sdk] Video "gwd-video_1" dispatching "EVENT_VIDEO_PLAY" event.", source: https://s0.2mdn.net/ads/studio/Enabler.js (136)
[1029/200218.752:INFO:CONSOLE(136)] " [  3.473s] [studio.sdk] Video "gwd-video_1" dispatching "EVENT_VIDEO_VIEW_TIMER" event.", source: https://s0.2mdn.net/ads/studio/Enabler.js (136)
[1029/200218.752:INFO:CONSOLE(0)] "The resource https://scripts.host.bannerflow.com/1.0.0/widget.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/200218.752:INFO:CONSOLE(0)] "The resource https://cdn.flashtalking.com/71195/1890146/js/tinyroom.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/200218.752:INFO:CONSOLE(0)] "The resource https://static.doubleclick.net/instream/ad_status.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/200218.752:INFO:CONSOLE(0)] "The resource https://c.betrad.com/a/n/279/78175.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/200218.752:INFO:CONSOLE(0)] "The resource https://s0.2mdn.net/6955512/1499344193123/web/300x250_edge.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[1029/200241.948:INFO:CONSOLE(7)] "https://o.cmp.advertising.com/v3/se?et=imd&en=displayTimer&d=30903&crid=402600&cpid=1C&e.crid=402600&e.plid=4778311&e.dgid=10646019&a.pid=369865&a.fid=10646019&a.cid=10630065&a.nid=5431&a.sid=1013212&a.bid=1&a.plid=4778311&a.aid=923846&1540857761948", source: https://ads.pictela.net/rm/lib/richmedia/adtechRichMediaLib_3_0_6.js (7)
[1029/200241.948:INFO:CONSOLE(7)] "https://o.cmp.advertising.com/v3/se?et=imd&en=viewTimer&d=30901&crid=402600&cpid=1C&e.crid=402600&e.plid=4778311&e.dgid=10646019&a.pid=369865&a.fid=10646019&a.cid=10630065&a.nid=5431&a.sid=1013212&a.bid=1&a.plid=4778311&a.aid=923846&1540857761949", source: https://ads.pictela.net/rm/lib/richmedia/adtechRichMediaLib_3_0_6.js (7)
[1029/200742.764:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:codernut

[1029/200742.814:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:codernut

[1029/200742.814:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:test

[1029/200743.657:ERROR:network_change_notifier_win.cc(157)] WSALookupServiceBegin failed with: 8
[1029/200744.396:ERROR:gpu_process_transport_factory.cc(990)] Lost UI shared context.
[1029/200745.903:ERROR:widevine_loader.cc(382)] Widevine CDM registration failed; Missing file C:\Users\Daszbin\Music\New folder\New folder\Programs\Codernut-master\CoderNut-master\src\bin\Coder Nut\WidevineCdm\widevinecdm.dll
[1029/200915.007:INFO:CONSOLE(3)] "CMP: Received error response retrieving GDPR consent from GUCE", source: https://s.yimg.com/aaq/cmp/version/2.9.1/cmp.js (3)
[1029/200915.859:INFO:CONSOLE(3)] "DARLA notice: 405", source: https://s.yimg.com/rq/darla/3-4-0/js/g-r-min.js (3)
[1029/200915.871:INFO:CONSOLE(3)] "DARLA notice: 405", source: https://s.yimg.com/rq/darla/3-4-0/js/g-r-min.js (3)
[1029/200916.566:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200916.583:INFO:CONSOLE(21)] "darla csc writer, potential invalid html content", source: https://s.yimg.com/rq/darla/3-4-0/html/r-csc.html (21)
[1029/200916.648:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-vertical-video", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.648:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-client-templates-viewer-controls-atomic", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.685:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-vertical-video", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.685:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-vertical-video", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.686:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-client-templates-viewer-controls-atomic", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.686:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-client-templates-viewer-controls-atomic", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.686:INFO:CONSOLE(14)] "yui: NOT loaded: highlander-vertical-video", source: https://s.yimg.com/zz/combo?yui:/3.18.0/yui/yui-min.js (14)
[1029/200916.819:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200916.824:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200916.829:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200918.091:INFO:CONSOLE(2757)] "Uncaught ReferenceError: Notification is not defined", source: https://www.yahoo.com/ (2757)
[1029/200918.092:INFO:CONSOLE(2757)] "Uncaught ReferenceError: Notification is not defined", source: https://www.yahoo.com/ (2757)
[1029/200918.698:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200918.712:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200918.715:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200918.718:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200918.720:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.028:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.042:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.045:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.127:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.140:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.163:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.166:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.203:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.240:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.243:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.551:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.553:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.573:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.788:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200919.791:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.654:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.657:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.660:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.662:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.664:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.667:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.669:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.671:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.674:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.676:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.679:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.681:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

[1029/200922.684:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1
```
    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?
No usage of third party controls.
- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**
No issues have occurred from the sample application.

**Comment by amaitland** [comment] 2018-10-30 03:02
> * I am using Cefsharp build 70.0.0-CI2816 for Winforms.

`CI` builds are potentially unstable, I'd advise against using them. Is there are a reason you aren't using a release version or at least a `-pre` release?

For a history of changes see https://ci.appveyor.com/project/cefsharp/cefsharp/history

> * The issue is when I start up the process of the browser running Cefsharp after loading the homepage successfully if the user wants to go to a different website Cefsharp just freezes as well as visual studio 2017. When finally the breakpoint is shown it reveals it has something to do with libcef.pdb and also logging.cc be missing however this has only happened recently with the newest version on Myget

This should be part of your list of steps to reproduce. Please provide a set of dot points that list the steps required to reproduce.  For me I'm unable to reproduce the any crash using `CefSharp.WinForms.Example` at commit https://github.com/cefsharp/CefSharp/commit/a10a5ef897ce4c8aac5baf7bf024c6b2f82e3c2a

- Load `CefSharp.WinForms.Example`
- Wait for web page to load
- Load `github.com`

> [1029/200149.808:ERROR:CefSharpApp.h(164)] CefSchemeRegistrar::AddCustomScheme failed for schemeName:codernut

Your scheme registration fails, it's possible this has something to do with the problem, you should resolve this.

> [1029/200922.684:ERROR:CefAppUnmanagedWrapper.cpp(242)] Failed to identify BrowserWrapper in OnContextCreated BrowserId:1

#2373 maybe related, though I don't see these error message in my log using the steps above.

More details are required.

**Comment by amaitland** [comment] 2018-11-07 05:53
@Daszbin Any further update on this?

**Comment by amaitland** [comment] 2018-11-08 21:04
Closing as suspected duplicate of #2562

**Closed by amaitland** 2018-11-08 21:04 UTC
