### ISSUE TITLE
web flash problem after load url when using winform example

### ISSUE THREAD

**Issue by wearybird** [cefsharp/CefSharp#2226] opened 2018-01-08 10:23 UTC
- **What version of the product are you using?**
     v63.0.0-pre01
     
- **What architecture x86 or x64?**
    x64
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
   WinForms, i use the  v63.0.0-pre01's  WinForms.examples,but this problem does not exist in 
  wpf.examples
- **What steps will reproduce the problem?**
     just run  v63.0.0-pre01's  WinForms.examples,then input a web site such as "www.ifeng.com",scroll the web html ,then you will found  screen flash.
- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.

    - Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

    - Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

    i run cefclient of cef_binary_3.3239.1721.g86eb141_windows64_client with  --multi-threaded-message-loop ,but no flash problem.

**Comment by wearybird** [comment] 2018-01-08 10:25
why i compile with source can produce the problem but cefClient not

**Comment by amaitland** [comment] 2018-01-08 23:11
> web flash problem

What's exactly do you mean? Are you referring to `Flash Player`?

> i run cefclient of cef_binary_3.3239.1721.g86eb141_windows64_client with --multi-threaded-message-loop ,but no flash problem.

The `63.0.0-pre01` release is based on version `CEF 3.3239.1716.g735b746`, for an accurate comparison you need to test using that version.

Loading http://www.ifeng.com/ and it looks fine to me, also testing with https://www.google.com/doodles/ and https://www.cnet.com/news/ I'm not seeing any flickering issues. Please provide more details, ideally a video of what your seeing.

> just run v63.0.0-pre01's WinForms.examples

Do you mean the `MinimalExample`? Please use the full name of the project your testing with.

**Comment by wearybird** [comment] 2018-01-09 08:21
i  mean  after load the url , the screen flash .
v63.0.0-pre01's WinForms.examples  is  the CefSharp.WinForms.example  project  in 63.0.0-pre01 release version.the attach file  is  the recorder of issue.
[recorder_2018_01_09_16_16_16_813.zip](https://github.com/cefsharp/CefSharp/files/1614344/recorder_2018_01_09_16_16_16_813.zip)

**Comment by amaitland** [comment] 2018-01-09 09:06
Closing as duplicate of #1259

It's pepper flash that briefly opens a console window.

**Closed by amaitland** 2018-01-09 09:06 UTC

**Comment by wearybird** [comment] 2018-01-09 09:53
does the screen flash  because the html has falsh plugin?
