### ISSUE TITLE
BrowserSubProcess crashing with NRE in JavascriptObjectWrapper.GetProperty

### ISSUE THREAD

**Issue by drewnoakes** [cefsharp/CefSharp#2369] opened 2018-04-23 13:45 UTC
- **What version of the product are you using?**

63.0.3 via NuGet.

- **What architecture x86 or x64?**

x86 platform in build configuration.

- **On what operating system?**

Windows 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**

WinForms

- **What steps will reproduce the problem?**

I'm not sure what steps I need to take to reproduce this, though I can reproduce it 100% of the time in my (closed source) application.

I will include as much information as possible and am happy to answer any questions needed.

- **What is the expected output? What do you see instead?**

Expect process to not crash.

- **Please provide any additional information below.**

The eventlog shows a few relevant entries:

```
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at CefSharp.JavascriptObjectWrapper.GetProperty(System.String)
   at <Module>.CefSharp.JavascriptPropertyHandler.Get(CefSharp.JavascriptPropertyHandler*, CefStringBase<CefStringTraitsUTF16>*, scoped_refptr<CefV8Value>*, scoped_refptr<CefV8Value>*, CefStringBase<CefStringTraitsUTF16>*)
   at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```

```
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 63.0.3.0, time stamp: 0x5ab4a0d2
Faulting module name: KERNELBASE.dll, version: 10.0.16299.371, time stamp: 0xee297154
Exception code: 0xe0434352
Fault offset: 0x00103ef2
Faulting process ID: 0x32fc
Faulting application start time: 0x01d3dafe56359102
Faulting application path: C:\SomePath\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: fc6ac867-8ed1-4ca8-87b4-963c2a44dbab
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 1685641669926730192, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: CefSharp.BrowserSubprocess.exe
P2: 63.0.3.0
P3: 5ab4a0d2
P4: CefSharp.BrowserSubprocess.Core
P5: 63.0.3.0
P6: 5ab4a0cf
P7: 508
P8: 0
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2EFB.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER348A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER349C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER34CC.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CefSharp.Browser_6e951068e61dd60d43affb46d3e3b89a17af9ab_e09807e4_3d5c3db0

Analysis symbol: 
Rechecking for solution: 0
Report ID: fc6ac867-8ed1-4ca8-87b4-963c2a44dbab
Report Status: 268435456
Hashed bucket: 32ec86d05710399327649a2afa9439d0
```

Looking at [`GetProperty`](https://github.com/cefsharp/CefSharp/blob/9eb19756ac8791f3bc716629d9a01a0f8d6c5990/CefSharp.BrowserSubprocess.Core/JavascriptObjectWrapper.cpp#L46) it suggests `_browserProcess` is `null`.

The WER log file contents are [here](https://pastebin.com/tcygvHmk).

- Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

`debug.log` is empty.

- Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

I only recently updated to 63 from 59. As part of that upgrade I set `LegacyJavascriptBindingEnabled` to `true`.

- **Does this problem also occur in the `CEF` Sample Application from http://opensource.spotify.com/cefbuilds/index.html?**

No. Tested with cef_binary_3.3359.1768.g8e7c5d6_windows32_client.

**Comment by amaitland** [comment] 2018-04-25 04:11
Propagate the exception where exactly? Your in the render process, there's no easy way to report back to the browser process, at least not currently. Logging sounds sensible, a null check so the objects are only bound if a valid WCF connection was created also seems reasonable. 

Will look more in detail when I'm in front of a computer.

**Comment by drewnoakes** [comment] 2018-04-25 08:08
Understood.

I see two options, as a starting point.

1) Don't catch and swallow the exception. Just let it crash the process. This crash will be reported in the event log (on Windows at least) and will at least contain information about what the real problem is rather than a loosely correlated NRE.

2) Write to the event log directly (again, on Windows) with information about the failure.

I think the first option is better. If `Open` fails, the process isn't going to survive for long anyway. It's better to crash due to the root cause than some hard to correlate symptom.

**Comment by amaitland** [comment] 2018-04-27 13:08
Out of curiosity are you able to get the command line args for the process your seeing crash? Had a report that suggests some of the args including the parent process id are duplicated, which the current implementation uses SingleOrDefault which could be the root cause of the actual problem. May be unrelated, I have no way to test as I cannot reproduce.

**Comment by amaitland** [comment] 2018-05-01 03:14
The `65.0.0-pre01` packages are on `Nuget.org`, one report suggests the parent process id was being passed in multiple times and the parsing was failing due to the user of `SingleOrDefault`, so that's one additional problem that could be causing the a problem with the `WCF` service. https://github.com/cefsharp/CefSharp/commit/a8ff890433be5a5fb188a039ce0b79c4bb0cc105#diff-9c8e4ee5fa7f6a8fa3330d9ef3325c67R22

If you can easily reproduce the problem then I'd be curios to see if this helps.

**Comment by drewnoakes** [comment] 2018-05-14 19:49
I haven't seen this issue for a while, sorry. I'll report back if I do.

**Comment by amaitland** [comment] 2018-06-25 09:28
Commit https://github.com/cefsharp/CefSharp/commit/4854f4f45c87eb8492c56b95fda7996c74e1fd97#diff-e0936a04d33d63867c8e3d791b5dd605 adds a check when binding `sync` objects and logs an error.

Changes are included in the `65.0.0-pre02` release.

**Comment by drewnoakes** [comment] 2018-06-25 12:51
Thanks Alex.

**Comment by amaitland** [comment] 2018-07-13 00:58
Closing this as the process should no longer crash. If you can reproduce in `65.0.0-pre02` or greater then this can be reopened.

**Closed by amaitland** 2018-07-13 00:58 UTC

**Comment by drewnoakes** [comment] 2018-07-13 06:44
Thanks, I'll let you know if I see it again.

**Comment by bhagatus** [comment] 2021-04-08 14:46
Has this problem resolved. I can not see issue  Id #2369 in change logs at following URL
https://github.com/cefsharp/CefSharp/wiki/ChangeLog

**Comment by amaitland** [comment] 2021-04-08 19:46
> Commit 4854f4f#diff-e0936a04d33d63867c8e3d791b5dd605 adds a check when binding sync objects and logs an error.

The same check exists in the version 89 release 

https://github.com/cefsharp/CefSharp/blob/cefsharp/89/CefSharp.BrowserSubprocess.Core/JavascriptRootObjectWrapper.cpp#L33

If you can reproduce the problem in version 89 then please create a new issue making sure you complete the bug report temple.
