### ISSUE TITLE
WPF/OffScreen - Unable to render when height > 16384

### ISSUE THREAD

**Issue by MatthiasNistl** [cefsharp/CefSharp#3747] opened 2021-08-11 12:11 UTC
- **What version of the product are you using?**
    91.1.230 (via NuGet)

- **What architecture x86 or x64?**
    x64
	
- **What version of .Net?**
    .Net 4.7.2
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
    - Set `Height` of `ChromiumWebBrowser` to 17000. Can be reproduced in a new WPF project with `CefSharp.Wpf` by simply adding this line to the MainWindow: 
    `<cefSharp:ChromiumWebBrowser Address="https://google.com/" Height="17000"/>`

- **What is the expected output? What do you see instead?**
    - Expected: Rendered page
    - Instead: No content is rendered, memory usage will steadily climb up to 100%

- **Please provide any additional information below.**
    - Issue only occurs if the Controls `Height` exceeds 16384 (= 2^14)
    - Issue has been introduced in version 89. In Versions <= 88 heights exceeding 16384 did not cause that problem
    - `debug.log` repeats these lines: 
    ```
  [0811/082922.574:ERROR:skia_output_surface_impl.cc(867)] 
  surface_size=784x17000
  format=6
  color_type=4
  backend_format.isValid()=1
  backend_format.backend()=0
  backend_format.asGLFormat()=1
  backend_format.asVkFormat()=0
  backend_format.asVkFormat() vk_format=0
  surface_origin=0
  willGlFBO0=0
  isProtected=0
  [0811/082922.575:ERROR:skia_output_surface_impl_on_gpu.cc(1532)] Failed to make current.
  [0811/082922.576:ERROR:raster_decoder.cc(1065)]   RasterDecoderImpl: Context lost during MakeCurrent.
    ```

- **Does this problem also occur in the `CEF` Sample Application**
    Sorry, not sure how to test this correctly, since I am unable to size the window of the sample application accordingly :-(

**Comment by amaitland** [comment] 2021-08-11 20:05
> Issue has been introduced in version 89. In Versions <= 88 heights exceeding 16384 did not cause that problem

This is mostly likely a bug in Chromium as we've only made minor changes to the WPF implementation over the last few versions. 

It's unlikely this is something that can be fixed in CefSharp.

**Comment by amaitland** [comment] 2021-08-11 21:44
To provide a slightly nicer user experience we could set the default max height for the control. 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.maxheight?view=net-5.0

**Comment by jankurianski** [comment] 2021-08-11 23:13
This does not directly address your problem, but here is some additional info on CEF's offscreen size limitations I know of.

Marshall (CEF maintainer) says:
> Chromium is designed to operate with displayable resolution sizes. For larger sizes you will need to scroll the web content in a reasonably sized viewport and stitch the images together in your application.
https://magpcss.org/ceforum/viewtopic.php?f=6&t=15507

When I stumbled on this issue in 2018 I found at some point the image buffer will simply not get regenerated and so from the user's point of view the browser will "freeze" (not redraw).  It was not based on a specific width or height, but rather the combination of both (i.e. based on width * height - or the overall size of the image buffer).  I set a maximum size of 6000x6000 since then, and have not experienced any further issues.

**Comment by amaitland** [comment] 2021-08-12 00:35
Looking at the skia source and if the width/height exceed the maximum the method returns an empty structure 
- https://source.chromium.org/chromium/chromium/src/+/refs/tags/91.0.4472.109:third_party/skia/src/gpu/GrContextThreadSafeProxy.cpp;l=80;drc=9d1ccebc2fa67f5a624835e692f3f27c7e60acae

Which results in check failure and the fatal error in the log
- https://source.chromium.org/chromium/chromium/src/+/refs/tags/91.0.4472.109:components/viz/service/display_embedder/skia_output_surface_impl.cc;l=867

It looks like the max size is based on the maximum size of the gl texture, so probably differs based on hardware/software support.

If you feel like comparing this behaviour to the older versions you can use https://cs.chromium.org 

It's also likely the WinForms version also has the same fundamental limitation.

**Comment by amaitland** [comment] 2021-08-12 01:10
The Chromium main branch has a SKIA D3D implementation with a hardcoded size of 16384

https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/src/gpu/d3d/GrD3DCaps.cpp;l=52;bpv=1;bpt=0?q=fMaxRenderTargetSize%20%3D%2016384&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2F

No sign of this file in the 91/92 release tags, possibly the file structure has changed or this is new.

As it's not clear what the maximum size actually is I'm not sure if it makes sense to pick an arbitrary size. Thoughts?

**Comment by jankurianski** [comment] 2021-08-12 01:27
I agree, since the maximum size is not exposed in any API, and it isn't clear which value is used for the maximum so we cannot track it manually with each chromium version change.  The max size should be a choice made by the consumer of CefSharp in their code.

**Comment by amaitland** [comment] 2021-08-13 00:00
@jankurianski Thanks for the insight/feedback 👍 

I'm going to close this issue as this is not a bug in CefSharp. If more information comes to light about the maximum size we can potentially reopen and add a default maximum.

**Closed by amaitland** 2021-08-13 00:00 UTC
Labels: wpf, upstream, offscreen
