### ISSUE TITLE
Asynchronous JavaScript gives error when called by ExecuteScriptAsync

### ISSUE THREAD

**Issue by Pengii** [cefsharp/CefSharp#3095] opened 2020-04-12 16:08 UTC
#2881 # Bug Report

- **What version of the product are you using?**
v79.1.360

- **What architecture x86 or x64?**
    x64
    
- **On what operating system?**
    Win10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WinForms
    
- **What steps will reproduce the problem?**

C# Lines:
```
string lines = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + @"api-req.js");
                            browser.ExecuteScriptAsyncWhenPageLoaded(lines);
```

api-req.js
```
async function getData(url) {
    const data = await fetch(url)
    .then(
        function(response) {
            if (response.status !== 200) {
                console.log('Looks like there was a problem. Status Code: ' +
                response.status);
                return;
            }
            return response.json();
        }
    )
    .catch(function(err) {
        console.log('Fetch Error :-S', err);
    });
    return data;
}

let objects = await getData('/api/tasks/get/systemObjects') // Error
    .then((data) => {
        return data;
    });

objects.data.systemObjects.forEach(element => {
    console.log(element.name);
});
```

I get this error from Console:
`Uncaught SyntaxError: await is only valid in async function`

But when I manually copy/paste and run those lines, I don't get any errors. It is just happening when I call this JavaScript from C#.

**Comment by amaitland** [comment] 2020-04-12 20:21
Closing as `invalid` as this in not a bug in `CefSharp`.

> CefSharp is just a wrapper around the Chromium Embedded Project

As per the [Bug Report Template](https://github.com/cefsharp/CefSharp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) `CefSharp` is just a wrapper around the `Chromium Embedded Project`.

A call to `ExecuteScriptAsyncWhenPageLoaded` is equivalent to calling [ExecuteJavaScript](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html#ExecuteJavaScript(constCefString&,constCefString&,int)) in [CefLoadHandler::OnLoadingStateChange](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefLoadHandler.html#OnLoadingStateChange(CefRefPtr%3CCefBrowser%3E,bool,bool,bool))

The [ExecuteJavaScript](https://magpcss.org/ceforum/apidocs3/projects/(default)/CefFrame.html#ExecuteJavaScript(constCefString&,constCefString&,int)) isn't intended to Load blocks of javascript as you are using it, it's intended to execute a script block.

Personally I recommend wrapping anything more than a few lines in an `self executing anonymous function`. See http://markdalgleish.com/2011/03/self-executing-anonymous-functions. for some examples.

**Closed by amaitland** 2020-04-12 20:21 UTC
Labels: invalid
