### ISSUE TITLE
CefSharp and Asp.net MVC

### ISSUE THREAD

**Issue by twilly86** [cefsharp/CefSharp#1196] opened 2015-08-14 23:16 UTC
I'd like to run CefSharp.Offline in an Asp.net MVC app.  I have cefsharp.offline working in a console app so I know I have the VS Redistribute files installed correctly, but I get the file [FileNotFoundException: Could not load file or assembly 'CefSharp] error

I created this test project to see if anyone else can reproduce the issue or if it's specific to my machine.
https://github.com/twilly86/cefsharp.mvc

Any help would be appreciated.  

One thing I did notice was when building the app, the cefsharp dll's are not put in bin/x86/debug, they are just put in bin.  In the console app, all dlls are put in bin/x86/debug

Thanks,

Tom

**Comment by amaitland** [comment] 2015-08-14 23:20
Duplicate of #1127 

Please continue the conversation there.

**Closed by amaitland** 2015-08-14 23:20 UTC

**Comment by twilly86** [comment] 2015-08-14 23:24
Thanks for the quick response.  I swear I looked everywhere before posting.
