### ISSUE TITLE
Cefsharp can't display a PDF stream , shows blank grey background only instead

### ISSUE THREAD

**Issue by bradley-berthold** [cefsharp/CefSharp#4024] opened 2022-03-03 15:54 UTC
Hi, I cannot get newest versions of CefSharp to properly display a PDF that is received from a http stream. 

Versions affected: 96.0.180 and also 97.1.61
Windows version: Windows 10
CefSharp: WPF control, 64 bit
Language: C#
Server: C# HttpSelfHost server with ASP.Net controllers (ApiController)

Problem:  If I navigate to a URL on a server which returns  PDF as a stream, as shown in this code below:

```
HttpResponseMessage toreturn = new HttpResponseMessage(HttpStatusCode.OK);
toreturn.Content = new StreamContent(new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.ReadWrite));

if (filename.ToLower().EndsWith(@"pdf")) toreturn.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(@"application/pdf");

toreturn.Content.Headers.Expires = new DateTimeOffset(DateTime.Now);
toreturn.Headers.CacheControl = new System.Net.Http.Headers.CacheControlHeaderValue() { NoCache = true };
```

**The browser control will not display the PDF. It will display a blank dark grey colored background and that is all.**

When i look at CefSharp log, (I set log to verbose) I see these messages:

```
[0302/172604.014:VERBOSE1:dispatcher.cc(440)] Num tracked contexts: 1
[0302/172604.105:INFO:CONSOLE(2094)] "Uncaught TypeError: Cannot read properties of null (reading 'getItem')", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/pdf_viewer_wrapper.js (2094)
[0302/172604.125:INFO:CONSOLE(0)] "Unchecked runtime.lastError: Not implemented", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (0)
[0302/172604.128:INFO:CONSOLE(2099)] "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/pdf_viewer_wrapper.js (2099)
[0302/172607.682:VERBOSE1:document.cc(3701)] Document::DispatchUnloadEvents() URL = "chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html"
[0302/172607.682:VERBOSE1:document.cc(3701)] Document::DispatchUnloadEvents() URL = "http://localhost:9090/UserData/Test%20Descriptions.pdf"
[0302/172607.682:VERBOSE1:document.cc(3779)] Actually dispatching an UnloadEvent: URL = "http://localhost:9090/UserData/Test%20Descriptions.pdf"
[0302/172607.682:VERBOSE1:document.cc(3779)] Actually dispatching an UnloadEvent: URL = "chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html"
[0302/172607.683:VERBOSE1:dispatcher.cc(636)] Num tracked contexts: 1
[0302/172607.691:VERBOSE1:script_context.cc(202)] Destroyed context for extension
  extension id: 
  effective extension id: 
[0302/172607.692:VERBOSE1:script_context.cc(202)] Destroyed context for extension
  extension id: 
  effective extension id: 
```

Expected behavoir: The PDF should be displayed.

**I tested this with the CEF Sample Application and the PDF renders correctly from the exact same URL**. It also functions correctly in and old version of CefSharp version 73.1.130.

I do have some CEF Settings applied in my code, they are as follows:

```
if (!Cef.IsInitialized)
{
	var browserSettings = new CefSettings();
	// ReSharper disable once AssignNullToNotNullAttribute
	browserSettings.BrowserSubprocessPath = Path.Combine(
		Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), @"Cefsharp.browsersubprocess.exe");
	browserSettings.CefCommandLineArgs.Add(@"disable-gpu-shader-disk-cache",
		@"1"); // disables creating the GPUCache folder
	browserSettings.CefCommandLineArgs.Add(@"disable-local-storage", @"1"); // disables local storage
	browserSettings.LogFile = Path.Combine(RoutineFiles.RoutineDirectory, @"CefSharp.log");
	browserSettings.LogSeverity = LogSeverity.Verbose;

	Cef.Initialize(browserSettings);
}

```

**Comment by bradley-berthold** [comment] 2022-03-03 15:55
I tried doing searches in bugs, issues, community and Google in general for this problem and haven't found any information yet.

**Comment by bradley-berthold** [comment] 2022-03-03 16:05
Ugh...

I found that if I remove the line of code where I disable local storage, PDF's work again.

```
if (!Cef.IsInitialized)
{
	var browserSettings = new CefSettings();
	// ReSharper disable once AssignNullToNotNullAttribute
	browserSettings.BrowserSubprocessPath = Path.Combine(
		Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), @"Cefsharp.browsersubprocess.exe");
	browserSettings.CefCommandLineArgs.Add(@"disable-gpu-shader-disk-cache",
		@"1"); // disables creating the GPUCache folder
	---> COMMENT OUT THIS LINE ---browserSettings.CefCommandLineArgs.Add(@"disable-local-storage", @"1"); // disables local storage
	browserSettings.LogFile = Path.Combine(RoutineFiles.RoutineDirectory, @"CefSharp.log");
	browserSettings.LogSeverity = LogSeverity.Verbose;

	Cef.Initialize(browserSettings);
}
```

Apparently PDF needs local storage to be enabled?

**Comment by amaitland** [comment] 2022-03-03 19:11
Closing as this is not a bug in CefSharp. 

> Apparently PDF needs local storage to be enabled?

Based on your feedback it sounds likely that is the case. Disabling local storage is not a use case that I test.

**Closed by amaitland** 2022-03-03 19:11 UTC
Labels: invalid
