### ISSUE TITLE
pdf copy doesnt work

### ISSUE THREAD

**Issue by roybrand** [cefsharp/CefSharp#4235] opened 2022-09-06 09:17 UTC
Hi

right click on copy, in pdf file, doesn't work,

ctrl c works

details:

What version of the product are you using?
104.4.240 Nuget

What architecture x86 or x64?
x86

What version of .Net?
4.6.2

On what operating system?
Win10

Are you using WinForms, WPF or OffScreen?
WinForms && WPF

What steps will reproduce the problem?
Open any PDF file. Mark some text. Right click. Select 'Copy'
The issue is reproducible using the MinimalExample.

What is the expected output? What do you see instead?

I expect the selection to be copied to the clipboard. Nothing happens.

Please provide any additional information below.
No exceptions are thrown. Log shows nothing. Using the keyboard Ctrl+C does work.

Does the cef log provide any relevant information? (By default there should be a debug.log file in your bin directory)

Any other background information that's relevant? Are you doing something out of the ordinary? 3rd party controls?

Does this problem also occur in the CEF Sample Application
yes

**Comment by amaitland** [comment] 2022-09-06 09:53
Closing as duplicate of #4224

You'll need to report the issue as detailed at  https://github.com/cefsharp/CefSharp/issues/4224#issuecomment-1229540048

**Closed by amaitland** 2022-09-06 09:53 UTC
