### ISSUE TITLE
CefSharp.Offscreen 65.0.0-pre02 scroll in Browser by SendMouseWheelEvent work once

### ISSUE THREAD

**Issue by Spocher** [cefsharp/CefSharp#2450] opened 2018-07-11 08:05 UTC
Yesterday I found that if you refresh the page or load an address different from the initial, the scroll in the browser by SendMouseWheelEvent stops working. In General, the scroll works correctly only when the page is initially loaded. In version 63.0.3 scrolling works correctly.

**Comment by amaitland** [comment] 2018-07-11 08:10
> WPF/OffScreen Mouse wheel becomes unresponsive after reload, see #2408 for the workaround (hopefully in CEF shortly).

Please check the `Known Issues` section of the release notes before opening a new issue. https://github.com/cefsharp/CefSharp/releases/tag/v65.0.0-pre02

Closing as duplicate of #2408

**Closed by amaitland** 2018-07-11 08:10 UTC
