### ISSUE TITLE
Keyboard Input does not work as expected - only inputs capitals and numbers

### ISSUE THREAD

**Issue by BenWoodford** [cefsharp/CefSharp#2143] opened 2017-09-14 13:52 UTC
- **What version of the product are you using?**
57 from Nuget

- **What architecture x86 or x64?**
x64

- **On what operating system?**
Win 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
OffScreen

- **What steps will reproduce the problem?**
Example here, links to relevant code for this: https://github.com/BenWoodford/CefSharp.MinimalExample/blob/keyboard-bug-test/CefSharp.MinimalExample.OffScreen/Program.cs#L52

- **What is the expected output? What do you see instead?**
Expected: it should type "rR4$" in the input
What actually happens: "RR44"

- **Please provide any additional information below.**
Try as I must, I cannot get the appropriate characters to print. I can't just pass through keyboard events either as that's not my intended purpose here.

Given the examples work fine with the other form of key sending process (`wParam` and `lParam`) I'm lead to believe that this issue is specific to the `KeyEvent` version of the `SendKeyEvent` method.

**Comment by perlun** [comment] 2017-12-02 20:27
Thanks for the feedback! I haven't got any experience with the Offscreen control here so can't really help you for the time being. Anyone else? @cefsharp/team-cefsharp

**Comment by jankurianski** [comment] 2017-12-04 04:20
You need to generate the correct `WindowsKeyCode` value given the shift modifier.

Here is a gist that correctly types "rR4$":

https://gist.github.com/jankurianski/5b56b9e36526606bcf175747c592e1c8

Hopefully others trying to use `SendKeyEvent` with the `KeyEvent` structure can adapt this gist to their needs as the `GetCharsFromKeys` function has been written generically to handle all `Key` values (thanks to https://stackoverflow.com/a/6949520/450141).

Closing this issue as it is not a bug.

**Closed by jankurianski** 2017-12-04 04:20 UTC

**Comment by amaitland** [comment] 2017-12-04 09:23
https://msdn.microsoft.com/en-us/library/windows/desktop/gg153546(v=vs.85).aspx explains keyboard messages in detail.

**Comment by BenWoodford** [comment] 2017-12-04 13:18
Sorry, I completely forgot about this issue.

I did eventually resolve this, as ut turned out I actually wanted to:

1.) Use `VkKeyScan` on the character after running it through `Encoding.UTF8.GetString()` to get any modifiers
2.) Set the type to `Char` and only set the `WindowsKeyCode` to the character from `GetString()` (my mistake was using the `vkey` result here
3.) Apply any modifiers from `VkKeyScan`

I had been doing a variety of small things wrong.

**Comment by danielh1989** [comment] 2018-03-14 16:00
Do you have any sample code @BenWoodford ?
