### ISSUE TITLE
WPF - Page is loaded incompletely

### ISSUE THREAD

**Issue by TangWilson** [cefsharp/CefSharp#3814] opened 2021-09-15 08:35 UTC
---
### Bug Report
Delete this line and everything above, and then fill in the details below.

- **What version of the product are you using?**
    CEFSharp v 75.1.142 & v93.1.111 from Nuget
- **What architecture x86 or x64?**
    <x64>
	
- **What version of .Net?**
    <.Net 4.5.2>
    
- **On what operating system?**
    Win11 on NUC11PAHi5

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    WPF
    
- **What steps will reproduce the problem?**
  I want to use CefSharp library on WPF on Windows 11 on NUC. But the web page is loaded incompletely and just like it's freezing that I can't do any action. The same code I use on Windows 10/Windows 11 on normal PC works fine.
The web I browse is a google login page  which will access the OAuth process.

- **What is the expected output? What do you see instead?**
  What i see just like a freezing page -> [https://imgur.com/AIEiLNR](url)  

- **Please provide any additional information below.**
    The function works fine on normal asus PC(D700SA) on Window 10 /Windows 11.
    It will be freezing on NUC11PAHi5 on Windows 10. 
   Is it possible because of the PC influence?

**Comment by TangWilson** [comment] 2021-09-15 08:35
cefsharp problem on win11

**Comment by amaitland** [comment] 2021-09-15 09:05
Closing as duplicate of #3280

**Closed by amaitland** 2021-09-15 09:05 UTC
