### ISSUE TITLE
WPF - WritableBitmap Cannot call this method while the image is unlocked.

### ISSUE THREAD

**Issue by romqn1999** [cefsharp/CefSharp#4140] opened 2022-06-14 11:24 UTC
- **What version of the product are you using?**
    `101.0.180`

- **What architecture x86 or x64?**
    `x86`
	
- **What version of .Net?**
    `.Net Framework 4.7.2`
    
- **On what operating system?**
    `Win10`

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    `WPF`
    
- **What steps will reproduce the problem?**
    - I have a kiosk app run on a touch screen. It's a multi-page WPF application. And 1 of these pages has to work on a web page so I used the control `CefSharp.Wpf.Experimental.ChromiumWebBrowserWithTouchSupport` to display the web.
    - Users can do processes on the kiosk many times so the web browser has to reload many times.
    - After many times success to display the web page, sometime I got an error while loading the browser

- **What is the expected output? What do you see instead?**
    - I expected the browser can completely load but the exception was thrown.

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information:
```
EXCEPTION: System.InvalidOperationException: Cannot call this method while the image is unlocked.
   at System.Windows.Media.Imaging.WriteableBitmap.AddDirtyRect(Int32Rect dirtyRect)
   at System.Windows.Media.Imaging.WriteableBitmap.WritePixelsImpl(Int32Rect sourceRect, IntPtr sourceBuffer, Int32 sourceBufferSize, Int32 sourceBufferStride, Int32 destinationX, Int32 destinationY, Boolean backwardsCompat)
   at CefSharp.Wpf.Rendering.WritableBitmapRenderHandler.<>c__DisplayClass4_0.<CreateOrUpdateBitmap>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at KioskApp.App.Main()
```

- **Does this problem also occur in the `CEF` Sample Application**
    - I can't reproduce the problem with the `CEF` Sample Application.

**Comment by amaitland** [comment] 2022-06-14 20:02
Does the problem reproduce with the normal ChromiumWebBrowser instance? Touch support was merged into ChromiumWebBrowser some time ago, ChromiumWebBrowserWithTouchSupport only adds stylus support. 

Seems unlikely ChromiumWebBrowserWithTouchSupport is related here.

> What steps will reproduce the problem?

What I need is a clear list of steps to reproduce the problem. Enough information to reliably reproduce the problem. 

There is an alternative WPF implementation available that host a a native win32 browser, see https://github.com/cefsharp/CefSharp.Wpf.HwndHost (Airspace issues apply).

**Comment by amaitland** [comment] 2022-06-14 20:37
> Does the problem reproduce using the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample)?
If code is required to reproduce your problem then please provide one of the following
Fork the [MinimalExample](https://github.com/cefsharp/CefSharp.MinimalExample) and push your changes to GitHub (this is the preferred option).
Use a code sharing service list Gist or Pastebin
Paste your formatted code as part of this issue (only do this for small amounts of code and make sure you format the code so it's readable)
Please no binary attachments (zip, 7z, etc), code needs to be easily reviewed in a web browser.

As per the bug report temple, please confirm the issue reproduces with the minimal example. If code changes are required please **fork** the project and push the changes to GitHub. Please make sure the code is the minimal required to reproduce the problem.

**Comment by amaitland** [comment] 2022-08-08 04:22
So far this is the only report, if someone can provide a clear example that reproduces the problem this can be reopened.

Closing due to lack of feedback.

**Closed by amaitland** 2022-08-08 04:22 UTC
Labels: more-details-needed-from-op
