### ISSUE TITLE
No option to print without the dialog box popping up?

### ISSUE THREAD

**Issue by kendallb** [cefsharp/CefSharp#1821] opened 2016-09-28 23:02 UTC
I have tested the basic sample app and also played with the offscreen app to add printing and they both work. The HTML prints just fine. The problem is the print dialog box pops up and I can't find anything in the API to be able to print without the dialog popping up?

We are currently using the IE browser control for printing HTML but we always seem to run into problems with it so I am looking for other solutions and CefCsharp looks promising except there does not appear to be a way to do it without the dialog box.

I really think this is something many developers would find extremely useful so is there a way to expose some kind of API to allow for programmatic printing to the default printer?

**Comment by amaitland** [comment] 2016-09-28 23:12
> I really think this is something many developers would find extremely useful so is there a way to expose some kind of API to allow for programmatic printing to the default printer?

Needs to be fixed in `CEF`. It currently doesn't expose an `API` (This question has been asked before).

**Closed by amaitland** 2016-09-28 23:12 UTC
Labels: wontfix

**Comment by amaitland** [comment] 2016-09-28 23:35
Duplicate of #886

@kendallb Please search before opening a new `Issue` please.

**Comment by amaitland** [comment] 2016-09-28 23:39
For reference http://magpcss.org/ceforum/viewtopic.php?f=6&t=12567#p24126

**Comment by kendallb** [comment] 2016-09-28 23:45
Ok I was not aware of those forums so I will check it out. But from the looks like there is currently no support in CEF for it. Is it possible to do a custom build of CEF to use with CefSharp?

**Comment by amaitland** [comment] 2016-09-29 00:35
> Is it possible to do a custom build of CEF to use with CefSharp?

You could, lot of effort though.
