### ISSUE TITLE
CefSharp.BrowserSubprocess.exe crash

### ISSUE THREAD

**Issue by dem219** [cefsharp/CefSharp#1486] opened 2015-12-11 16:02 UTC
We have seen some users having frequent crashes which result in a dialog indicating an error in CefSharp.BrowserSubprocess.exe.

We are using CefSharp v41 on WinForms

There is no obvious pattern of what is causing the crash.  I was able to gather the following information after a crash from the windows event viewer:

Description:
```
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00000000
```

and

Description:
```
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 41.0.0.0, time stamp: 0x55e8a627
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x2a64
Faulting application start time: 0x01d1335fda1e79a8
Faulting application path: C:\Users\jmurphy1\data\IceConnectIDP\IdpCefSharp\CefSharp.BrowserSubprocess.exe
Faulting module path: unknown
Report Id: ea6a0924-9f5c-11e5-9024-b8ca3ab2a7f7
```

The following was at the end of the debug.log
```
[1209/150408:ERROR:backend_impl.cc(1990)] Corrupt Index file
[1209/150408:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[1209/150408:ERROR:cache_util.cc(132)] Unable to move cache folder C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\Cache to C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\old_Cache_000
[1209/150408:ERROR:cache_creator.cc(133)] Unable to create cache
[1210/094017:ERROR:renderer_main.cc(212)] Running without renderer sandbox
[1210/094017:ERROR:backend_impl.cc(1990)] Corrupt Index file
[1210/094017:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[1210/094017:ERROR:cache_util.cc(132)] Unable to move cache folder C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\Cache to C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\old_Cache_000
[1210/094017:ERROR:cache_creator.cc(133)] Unable to create cache
[1210/103134:ERROR:renderer_main.cc(212)] Running without renderer sandbox
[1210/103134:ERROR:backend_impl.cc(1990)] Corrupt Index file
[1210/103134:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[1210/103134:ERROR:cache_util.cc(132)] Unable to move cache folder C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\Cache to C:\Users\jmurphy1\AppData\Roaming\IceDesktopPlatform\old_Cache_000
[1210/103134:ERROR:cache_creator.cc(133)] Unable to create cache
```

(There was much more before this)

Any suggestions on what may be the cause?  Or how to gather more information?

I will try to upgrade to the latest version of CefSharp soon, but anything else that can be done in the meantime to identify or resolve the issue would be helpful.

**Comment by amaitland** [comment] 2015-12-14 01:10
> [1209/150408:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5

Typically that error occurs when you failed to `Shutdown` cleanly.

http://magpcss.org/ceforum/search.php?keywords=Unable+to+move+the+cache&sid=1aafe4a359a30eebbe87f22b629f7098

> Or how to gather more information?

If you compile the `cefsharp/41` branch from source you can generate the `pdb` files, they might yield some additional information. Typically you can download the release symbols from https://cefbuilds.com/, for the relevant version, extract them next to `libcef.dll` and get a little more information if the problem exists within `CEF` it's self. It looks like for `41` we used a custom build, so no symbols are available. 

> will try to upgrade to the latest version of CefSharp soon

Excellent place to start :+1: Version `41` is no longer being developed/supported.

**Comment by amaitland** [comment] 2016-01-11 02:26
We're moving towards using [Gitter Chat](https://gitter.im/cefsharp/CefSharp). Please ask follow up questions there. If there is a reproducible bug then we can reopen this issue.

**Closed by amaitland** 2016-01-11 02:26 UTC
