### ISSUE TITLE
JS binding causes memory leak in 65+

### ISSUE THREAD

**Issue by chylex** [cefsharp/CefSharp#2390] opened 2018-05-12 04:07 UTC
- **What version of the product are you using?**
    - Reproduced from c37dbcd06a978ac000fdee14ac64df5b802eb2df (commit after upgrade to CEF 65) to 22b299e3b5588f51e532ce60b80b3b93e1c5d748 (latest master w/ 66)

- **What architecture x86 or x64?**
    - Both x86 and x64

- **On what operating system?**
    - Tested on Win 7 & 10

- **Are you using `WinForms`, `WPF` or `OffScreen`?**
    - WinForms

- **What steps will reproduce the problem?**
    - Using `RegisterAsyncJsObject` on a browser and then reloading that browser keeps increasing memory usage and never releases it

- **Reproduction example**
    - Get https://github.com/chylex/CefSharp/commit/cd9dad63f6bb6555d54a6a7526820eb0c899688e and run `CefSharp.WinForms.Example`
    - Repeatedly click `Go` or reload the page, memory usage of the subprocess should keep rising forever

**Comment by amaitland** [comment] 2018-05-15 00:37
Appears to be a problem with the newer binding method also.

**Comment by amaitland** [comment] 2018-05-15 06:27
The `destructor` isn't being called in newer branches for the `CefV8Handler` implementations so the process is leaking memory 😦  

It appears to be related to how we're currently storing a `CefV8Value` reference to the promise creator function used by the `async` code. It's possible to obtain the promise on `Execute` so we don't need to hold the reference. The `destructor` seems to be called now, so memory is freed.

Relevant commit for `cefsharp/65` is https://github.com/cefsharp/CefSharp/commit/930846eb52c2fc4c8d4ccb6d4c0349ff921b658d and for `master` see https://github.com/cefsharp/CefSharp/commit/5f3dca4d960f6306c3a1b03e7312a8f6d5a0e961

**Comment by amaitland** [comment] 2018-05-15 06:27
> Reproduction example
> 
>     Get chylex/CefSharp@cd9dad6 and run CefSharp.WinForms.Example
>     Repeatedly click Go or reload the page, memory usage of the subprocess should keep rising forever

@chylex Thanks for taking the time to create a example, greatly appreciated 👍

**Comment by chylex** [comment] 2018-05-15 08:05
Tested with latest build, appears to be working fine now. Thanks!

**Comment by amaitland** [comment] 2018-05-16 01:05
Thanks for checking 👍 

Closing as appears the problem is resolved.

**Closed by amaitland** 2018-05-16 01:05 UTC
Labels: upstream
