### ISSUE TITLE
Second run of *.exe ends with crash

### ISSUE THREAD

**Issue by Nerver91** [cefsharp/CefSharp#4725] opened 2024-02-21 11:08 UTC
### Is there an existing issue for this?

- [X] I have searched both open/closed issues, no issue already exists.

### CefSharp Version

121.3.70.0

### Operating System

Windows 10

### Architecture

x64

### .Net Version

.NET Framework 4.8

### Implementation

WPF

### Reproduction Steps

Install from nuget 121.3.70.0 CesfSharp version. Add <wpf:ChromiumWebBrowser/> to XAML. Start application two times. Second start ends with crash.

[CefSharpCrash.zip](https://github.com/cefsharp/CefSharp/files/14358515/CefSharpCrash.zip)

### Expected behavior

Working without crash

### Actual behavior

Crash

### Regression?

In version 119.4.30 it is working properly.

### Does this problem also occur in the CEF Sample Application

No

**Comment by campersau** [comment] 2024-02-21 11:29
See https://github.com/cefsharp/CefSharp/issues/4668#issuecomment-1890241487 / https://github.com/cefsharp/CefSharp/issues/4668#issuecomment-1890331903

**Comment by amaitland** [comment] 2024-02-23 21:14
Closing as duplicate of https://github.com/cefsharp/CefSharp/issues/4668

> Expected behavior
> Working without crash

Starting in version `120` a crash is expected as `CEF` now implements the `Process Singleton` which means `Cef.Initialzie` will return false for second process launch with the same cache path.

https://github.com/cefsharp/CefSharp/blob/cefsharp/121/CefSharp.Wpf/ChromiumWebBrowser.cs#L554

**Closed by amaitland** 2024-02-23 21:14 UTC
