### ISSUE TITLE
RegisterJsObject works indeterminately when larger amount of tab opened in short time

### ISSUE THREAD

**Issue by attilarickert** [cefsharp/CefSharp#1675] opened 2016-05-02 15:29 UTC
Hi,

I'm using v47.0.3 from Nuget in a WPF project, under Windows 10.
I try to open larger amount of tabs (>10) in short time (few seconds max), and each tab should register an object. Some of the tabs register the object well, but some don't, and I don't get any Exception when a tab fails registering. 
RegisterJsObject funcion is called right after usercontrol's InitializeComponent().  If more time passes between opening tabs, it works as expected on every tab.

Thanks in advance for any help.

**Comment by amaitland** [comment] 2016-05-02 21:25
One workaround (not a very pretty one) is to initialize `ChromiumWebBrowser` in code, then register your objects immediately. This is necessary for the `WinForms` control, should give you a guaranteed result

https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L25

My initial though is without a major rewrite (which I personally don't have time for) it's will be very difficult to provide a fix for this. 

In general it's helpful if you could provide an example that reproduces your problem otherwise it's very hard to verify it's been fixed.

**Comment by amaitland** [comment] 2016-05-03 00:09
In the next version (`49.0.0`) you'll be able to defer the underlying browser creation.

https://github.com/cefsharp/CefSharp/blob/cefsharp/49/CefSharp.Wpf/ChromiumWebBrowser.cs#L893

This is probably the cleanest option, subclass `ChromiumWebBrowser` and `return false` until your ready.

**Comment by tamasmonus-cas** [comment] 2016-05-03 08:56
Hi!

I'm writing on behalf of attilarickert.

We've tried to create and initialize the ChromiumWebBrowser in code, but it didn't help. However we realized, that if we're creating only one browser per control then it's working. (We have a control where we have to create 4-6 browser instance, but if we create only one then it looks ok).

For some further informations, for me it looks like a problem with asyncs/thread handling. Because if we put a breakpoint right after the RegisterJSObject, or if I block the thread completly with a Task.Delay after the method call, then it works OK. But this could not be a workaround for us, because its blocking the UI as well.

**Comment by amaitland** [comment] 2016-05-03 09:29
> We've tried to create and initialize the ChromiumWebBrowser in code, but it didn't help.

What does that code look like? 

> For some further informations, for me it looks like a problem with asyncs/thread handling. Because if we put a breakpoint right after the RegisterJSObject, or if I block the thread completly with a Task.Delay after the method call, then it works OK. But this could not be a workaround for us, because its blocking the UI as well.

The source code is there, by all means download and debug :+1: It would likely be a couple of weeks before I have time to look into this (and that's assuming you provide a working example that demos your problem).

**Comment by tamasmonus-cas** [comment] 2016-05-03 09:38
Unfortunately, I don't have the actual code now. I've done a revert after I found out, that it didn't helped. But simply I created a new instance of the ChromiumWebBrowser and right after that call I called the RegisterJsObject method.

It should have been similar to this:
 `public Browser(object webObject)
  {
            DefaultStyleKey = typeof (Browser);
            Unloaded += OnUnloaded;

            _webView = new ChromiumWebBrowser
            {
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Stretch,
                Background = new SolidColorBrush(Colors.Transparent),
                BorderThickness = new Thickness(2),
                BorderBrush = new SolidColorBrush(Colors.Blue)
            };

           _webView.RegisterJsObject("ObjectName", webObject);

            _webView.LoadingStateChanged += WebViewOnLoadingStateChanged;
            ScrollViewer.SetHorizontalScrollBarVisibility(_webView, ScrollBarVisibility.Disabled);
  }
  // ...
  public override void OnApplyTemplate()
  {
            base.OnApplyTemplate();
            _root = GetTemplateChild("_root") as Grid;
            _root.Children.Add(_webView);
  }
`

I tried to create the browser instance in the OnApplyTemplate as well, but that doesn't helped me either.

**Comment by amaitland** [comment] 2016-05-03 09:52
@tamasmonus-cas I've reformatted your code as it was hard to read. 

It looks fine in theory, though `CefSharp` doesn't play particularly nice when hosted in a ` ScrollViewer` from memory (If you search, I think you'd find some old issues).

It does sound like a timing issue, probably need to add some debugger writelines to see whats happening under the hood.

**Comment by tamasmonus-cas** [comment] 2016-05-03 11:47
Does the ScrollViewer a problem even if we don't put the browser directly into a ScrollViewer? I mean, we put the Browser instances inside of a Border with constant size, this Border is added to a Grid and that Grid is added to a ContentPresenter which is contained by a ScrollViewer. I hope it is understandable.

Also, (Altough I think this should be putted into an other issue) we found that in some cases CefSharp throws an OutOfMemory exception. to be more precise, at CefSharp.Wpf.Rendering.WritableBitmapInfo.CreateBitmap() even tough our application doesn't use more than 400Mb memory, so there should be plenty of memory left. I looked around but didn't find anything about this in google.

**Comment by amaitland** [comment] 2016-05-03 11:55
> Does the ScrollViewer a problem even if we don't put the browser directly into a ScrollViewer? I mean, we put the Browser instances inside of a Border with constant size, this Border is added to a Grid and that Grid is added to a ContentPresenter which is contained by a ScrollViewer. I hope it is understandable.

I don't remember what the specific issue was, you'd have to search for it.

> Also, (Altough I think this should be putted into an other issue) we found that in some cases CefSharp throws an OutOfMemory exception. to be more precise,

Open a new issue, please follow the issue template. `WritableBitmapInfo` is typically only used when `DPI > 1`, so make sure to include all relevant information.

**Comment by tamasmonus-cas** [comment] 2016-05-03 12:59
I looked after the ScrollViewer issue. The issues I found were about focus losting, we applied the workaround for that.

I'll look into this Register problem if I'll have time and post my experiences or solution (if I found one) here.

Also, I still didn't find anything related to that WriteableBitmapInfo problem, so I'll create a new issue about that.

**Comment by tamasmonus-cas** [comment] 2016-05-11 11:14
Hi!

I'm just curious, so I updated to the new 49.0.0 version and modified my code, so that I only create one browser at a time, I wait till it's loaded, then create and load the other one. It helped a little, but there were still cases when the .NET object wasn't exposed.

However, I discussed this problem with my collegues and we could use the window.postMessage method as well. Unfortunately, I couldn't find how to handle that in CefSharp. Is there a support for catching/listening/handling postMessage in CefSharp?

**Comment by amaitland** [comment] 2016-05-11 21:20
> I wait till it's loaded, then create and load the other one. It helped a little, but there were still cases when the .NET object wasn't exposed.

Can you fork the `MinimalExample` and provide a working demo? Your the first, and only person to report this problem and the code hasn't changed in quite some time, so what exactly are you doing differently to everyone else?

> I couldn't find how to handle that in CefSharp. Is there a support for catching/listening/handling postMessage in CefSharp?

Not that I'm aware of. Remembering that `CefSharp` is just a wrapper around `CEF`. I see someone else asked a similar question with no response. http://magpcss.org/ceforum/viewtopic.php?f=6&t=13883&p=29622

**Comment by ta-stott-oe** [comment] 2016-05-12 08:17
I think I have the same problem: the registered object is occasionally `undefined` in JS, unless I add an artificial delay between registering the object and loading the page. I realise you don't have much to go on here so I will try to reproduce this on a fork of `MinimalExample` if I get a chance.

**Comment by tamasmonus-cas** [comment] 2016-05-12 10:43
I'm sorry to say this, but I'm releived, I'm not the only one with this problem. Today afternon, I think I will have time to make an example app to you to reproduce this bug.

Until then, some further information what I noticed now. A few times, it happened, that I exposed the object to the browser succesfully, then time passed and I reloaded the page, and the newly loaded page didn't find the object. Maybe the object got deleted from the memory? It happened really rarely, like 2-3 times all, but sometimes it happens and I'm certain that I don't release the object myself, I have a reference to it in the container control, so the GC shouldn't remove it from the memory, but still.

**Comment by tamasmonus-cas** [comment] 2016-05-12 14:30
I created a demo, which is loading a simple, static html page from the project folder, but I couldn't reproduce the bug for now. I look into it deeper tomorrow.

**Comment by tamasmonus-cas** [comment] 2016-05-13 08:46
Ok, I'm really confused here. I started to build up the demo step by step, until I reached a point where it is generally the same as the production program. I checked it a few times and under the hood it works the same. The only difference which I can see is that in the demo I just load a static html file, which checks if the .NET object is defined on the window or not. And I cannot reproduce the issue. I even putted in our custom TabControl to check if that causes the issue, but it still isn't reproduced, the problem.

Could it be that it behaves differently when loading an html page which is contructed with JavaScript dynamically (it's a ReactJS page to be precise)?

Any kind of help would be much appreciated!

I attach the demo here:
https://drive.google.com/file/d/0BxH-QjFtOlgwTFlzLWp5UjY4dTg/view?usp=sharing

Or attached to this comment here:
[CefNetObjectExposingBug.zip](https://github.com/cefsharp/CefSharp/files/262838/CefNetObjectExposingBug.zip)

**Comment by amaitland** [comment] 2016-05-13 09:33
Please no zip or binary files. If you modified the MinimalExample then please push your changes to GitHub.

**Comment by tamasmonus-cas** [comment] 2016-05-13 09:45
I didn't modified the minimal example because I wanted to follow the structure what we use in our program, in order to avoid structure caused bugs, or anything related to that.

How should I share the example with you? Should I create a GitHub repository or something else?

**Comment by amaitland** [comment] 2016-05-13 09:49
GitHub is fine :+1:

**Comment by tamasmonus-cas** [comment] 2016-05-13 09:59
I created a public repository for the project.

You can find it here:
[https://github.com/tamasmonus-cas/CefNetObjectExposingBug](https://github.com/tamasmonus-cas/CefNetObjectExposingBug)

Thank you for the help in advance!

**Comment by amaitland** [comment] 2016-05-16 11:34
> And I cannot reproduce the issue

Were you able to reproduce the problem with your example?

> Could it be that it behaves differently when loading an html page which is contructed with JavaScript dynamically (it's a ReactJS page to be precise)?

It's possible. Is there a public `ReactJS` demo you can use for testing purposes?

**Comment by tamasmonus-cas** [comment] 2016-05-16 14:45
I tried my example with our ReactJS pages, but I couldn't reproduce the bug. And I have no idea why it isn't coming out in the example. The real program works exactly the same. I just simplified on the structure, because I didn't need some features and I don't have to have that clean code. I was on holiday today, but tomorrow I'll try to construct the example step by step to the actual program, so hopefully, I'll find that little thing which is causing this issue. Any advice is welcomed to hunt down this bug.

Thank you in advance!

----- Eredeti üzenet -----
Feladó: "Alex Maitland" <notifications@github.com>
Feladva: ‎2016.‎05.‎16. 13:34
Címzett: "cefsharp/CefSharp" <CefSharp@noreply.github.com>
Másolat: "tamasmonus-cas" <tamas.monus@casrd.net>; "Mention" <mention@noreply.github.com>
Tárgy: Re: [cefsharp/CefSharp] RegisterJsObject works indeterminately whenlarger amount of tab opened in short time (#1675)

And I cannot reproduce the issue
Were you able to reproduce the problem with your example?
Could it be that it behaves differently when loading an html page which is contructed with JavaScript dynamically (it's a ReactJS page to be precise)?
It's possible. Is there a public ReactJS demo you can use for testing purposes?

**Comment by tamasmonus-cas** [comment] 2016-05-17 09:16
I may have found the problem. I had to call JavaScript on the browser. And it seems this JavaScript call sometimes happened too soon. And apparently this caused some kind of error in object exposing. Now, before I call JavaScript on the browser I check if our page is initialized, the page sends us a ready status when it is ready. But it could be that this bug just isn't appeared while I tested. So I pushed the changes and I'll try to reproduce the bug today, but I hope I can't.

However, I wanted to ask, is there any property which is indicating that it is safe to run JavaScript on the browser? Maybe a property which is true when the DOM is loaded? Because I didn't find anything like that. There is an IsLoading property, but that changes every time a page loads something, while it is safe to run JavaScript after the DOM is loaded.

**Comment by amaitland** [comment] 2016-05-17 09:46
> However, I wanted to ask, is there any property which is indicating that it is safe to run JavaScript on the browser?

Not currently. Sounds like a reasonable idea though :+1: If you have time then please submit a `PR`.

If you haven't already read over https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#when-can-i-start-executing-javascript

**Comment by amaitland** [comment] 2016-05-17 09:48
> Maybe a property which is true when the DOM is loaded?

For clarity, it's safe to execute javascript after the `CefV8Context` has been loaded.

http://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefRenderProcessHandler.html#OnContextCreated%28CefRefPtr%3CCefBrowser%3E,CefRefPtr%3CCefFrame%3E,CefRefPtr%3CCefV8Context%3E%29

Which maps to `IRenderProcessMessageHandler.OnContextCreated`

**Comment by ta-stott-oe** [comment] 2016-05-17 12:20
Thanks @tamasmonus-cas , I think you've got it. I temporarily removed some calls to `ExecuteScriptAsync()` and it fixed the problem (the .NET object is registered successfully every time).

@amaitland , thanks for pointing us to `OnContextCreated`, I'll give it a try. If the problem is calling `ExecuteScriptAsync()` before the V8 context is loaded, would it make sense for CefSharp to throw an exception or defer the script execution in that case?

Thanks both for your help.

**Comment by tamasmonus-cas** [comment] 2016-05-17 13:49
I'll tried to create a worst case scenario and modified my AddTab method, so that I create 3 tabs at once with 4 different Browsers on every tab, and the WebObject were exposed fine in every one of them. But I let my bug ticket open for a few days, because this bug gived me some hard times. I tought it's fixed but then it appeared again.

After that I think I'll try to create a property in my CefSharp wrapper control which is indicating whether it is ready to run JS or not. And defer the script executions which are arriving too soon.

@amaitland Can you give me a link or address where I can submit a PR? Sorry but I'm unfamiliar with github.

**Comment by amaitland** [comment] 2016-05-17 22:18
> would it make sense for CefSharp to throw an exception or defer the script execution in that case?

It does, though I think you'll find that implementing this would be quite difficult. By all means look into it further and come back with some questions

> @amaitland Can you give me a link or address where I can submit a PR? Sorry but I'm unfamiliar with github.

Start with https://github.com/cefsharp/CefSharp/wiki/Forking-and-Pull-Requests

**Comment by amaitland** [comment] 2016-05-31 22:32
Any further follow up on this?

**Comment by tamasmonus-cas** [comment] 2016-06-02 07:47
There isn't any from my side. But thanks again for all the help. : )

**Comment by amaitland** [comment] 2016-06-02 08:01
@tamasmonus-cas Was there a `PR` you were planning on submitting?

**Closed** 2016-06-02 08:39 UTC
Labels: wpf

**Comment by amaitland** [comment] 2016-06-02 08:47
> I didn't have time to do any changes.

I'd also encourage you to make time, the project will only continue if more people contribute :+1:
